### ISSUE TITLE
BigQuery: support for BIGNUMERIC data type

### ISSUE THREAD

**Issue by shollyman** [googleapis/google-cloud-ruby#10094]
This issues tracks support of [BIGNUMERIC](https://cloud.google.com/bigquery/docs/reference/standard-sql/data-types#numeric_types) data type support in BigQuery client library.

Implementation guidance has previously been shared out of band with implementors.

**Comment by quartzmo** [comment]
The existing Numeric type has precision 38, scale 9. User-provided values that exceed these parameters should be coerced to the new` BIGNUMERIC` data type.
