### ISSUE TITLE
Project objects returned with create_project have @gapi initialized to Operation instead of Project.

### ISSUE THREAD

**Issue by JustinMyers** [googleapis/google-cloud-ruby#10837]
Hello,

When you create a new project using resource manager, it creates a Google::Cloud::ResourceManager::Project but the @gapi object is initialized to a Google::Apis::CloudresourcemanagerV1::Operation instead of a Google::Apis::CloudresourcemanagerV1::Project which means calling its methods to learn about the created project errors out. You cannot even call reload! on the returned Project.

Perhaps there is a more-clever way to use the returned object? Apologies if my expectations are incorrect here. Thank you.

This is the manager call that creates the google cloud project and returns a Project object with the @gapi set to an Operation:
https://github.com/googleapis/google-cloud-ruby/blob/master/google-cloud-resource_manager/lib/google/cloud/resource_manager/manager.rb#L203

Here is the API method returning the Operation:
https://github.com/googleapis/google-api-ruby-client/blob/master/generated/google-apis-cloudresourcemanager_v1/lib/google/apis/cloudresourcemanager_v1/service.rb#L879

Here is where the the Project object calls an non-existing method on its @gapi object:
https://github.com/googleapis/google-cloud-ruby/blob/master/google-cloud-resource_manager/lib/google/cloud/resource_manager/project.rb#L63

#### Environment details

  - OS: Linux
  - Ruby version: ruby 2.5.8p224 (2020-03-31 revision 67882) [x86_64-linux]
  - Gem name and version: google-cloud-resource_manager (~> 0.29)

#### Steps to reproduce / Code example

```ruby
resource_manager = Google::Cloud::ResourceManager.new
project = resource_manager.create_project([project_id],
                                      name: [project_name],
                                      labels: { env: :development },
                                      parent: [resource])
project.project_number
```

#### Full backtrace

```sh
NoMethodError (undefined method `project_number' for #<Google::Apis::CloudresourcemanagerV1::Operation:0x00002a0c8943abd8>):
```

**Comment by JustinMyers** [comment]
An additional effect of this issue is that project creation fails silently if the account creating the projects has exceeded its project quota. The call returns immediately with no issue but no project is created. I think checking quotas must take longer than value validation.

This differs from supplying bad values, for example, as the error is returned immediately.

**Comment by dazuma** [comment]
This client is being reworked using the gRPC backend and code generator. Please try the [google-cloud-resource_manager-v3 gem](https://rubygems.org/gems/google-cloud-resource_manager-v3) which will have a different but more up to date interface and shouldn't have the issue described here. The google-cloud-resource_manager gem will shortly be relaunched as a thin wrapper around the v3 gem.
