### ISSUE TITLE
Several libraries have lingering rubocop issues after the Ruby 3 migration

### ISSUE THREAD

**Issue by dazuma** [googleapis/google-cloud-ruby#10867]
It seems to affect handwritten parts (samples, acceptance tests) of generated libraries. I know google-cloud-vision is affected, and there was at least one other.

**Comment by quartzmo** [comment]
Please let me know if there's anything for me to do here.

**Comment by dazuma** [comment]
@trambui09 is working on this.

**Comment by danoscarmike** [comment]
@dazuma how should this one be labelled? Process?

**Comment by dazuma** [comment]
@danoscarmike Uh, yeah, process is probably reasonable for this.
