### ISSUE TITLE
BigQuery: table.time_partitioning_expiration can not be unset

### ISSUE THREAD

**Issue by tamayika** [googleapis/google-cloud-ruby#10889]
It's impossible to unset table's time_partitioning_expiration. (https://github.com/googleapis/google-cloud-ruby/blob/master/google-cloud-bigquery/lib/google/cloud/bigquery/table.rb#L417-L422)
If `nil` specified as argument, `nil * 1000` raises an error.
I confirmed if null is applied to time_partitioning.expiration_ms it was unset via GCP REST API Explorer.

**Comment by quartzmo** [comment]
@tamayika Thank you for opening this issue. I'll try to reproduce it soon, then look into possible solutions.

**Comment by quartzmo** [comment]
@tamayika I reproduced this and will issue a patch soon. Thanks again.
