### ISSUE TITLE
undefined method `new' for Google::Cloud::Language:Module 

### ISSUE THREAD

**Issue by Skezey** [googleapis/google-cloud-ruby#11048]
#### Environment details

  - OS: MacOS Big Sur
  - Ruby version: 2.7.0p0
  - Gem name and version: google-cloud-language 1.3.0

#### Steps to reproduce

  1. Install gem
  2. Enter IRB
  3. Require gem (require "google/cloud/language")
  2. Try to instantiate a new client with Google::Cloud::Language.new
  3. Run code

#### Code example

```ruby
require "google/cloud/language"
language = Google::Cloud::Language.new
```

#### Full backtrace

```sh
   Traceback (most recent call last):
        4: from /Users/syoung/.rbenv/versions/2.7.0/bin/irb:23:in `<main>'
        3: from /Users/syoung/.rbenv/versions/2.7.0/bin/irb:23:in `load'
        2: from /Users/syoung/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/irb-1.2.1/exe/irb:11:in `<top (required)>'
        1: from (irb):2
NoMethodError (undefined method `new' for Google::Cloud::Language:Module)
```

**Comment by dazuma** [comment]
`Google::Cloud::Language` is a module, not a class. It does not have a `new` method.

To instantiate a new client, use the module method `Google::Cloud::Language.language_service`.

See https://googleapis.dev/ruby/google-cloud-language/latest/Google/Cloud/Language.html for the reference documentation.

If you were using a pre-1.0 version of google-cloud-language, this is a change in the interface. See https://googleapis.dev/ruby/google-cloud-language/latest/file.MIGRATING.html for info on other changes to be aware of.
