### ISSUE TITLE
PubSub: support ordering keys in synchronous mode

### ISSUE THREAD

**Issue by FooBarWidget** [googleapis/google-cloud-ruby#11041]
Thanks for stopping by to let us know something could be better!

**PLEASE READ**: If you have a support contract with Google, please create an issue in the [support console](https://cloud.google.com/support/) instead of filing on GitHub. This will ensure a timely response.

 **Is your feature request related to a problem? Please describe.**
No.

 **Describe the solution you'd like**
Please add the `ordering_key` option to `Google::PubSub::Topic#publish`.

 **Describe alternatives you've considered**
I've tried using the async publishing API instead, which does support ordering keys. However, my use case is synchronous: I don't want to acknowledge my caller until I know that my message has been received by PubSub. The async API doesn't seem to provide a way to "flush *and* wait until flushed".

**Additional context**
Only `publish_async` supports `ordering_key`. I don't know why `publish` doesn't support it.

**Comment by quartzmo** [comment]
@FooBarWidget Thanks for opening this issue!

I see two requests here, and will look into adding both of them:

1. Add the `ordering_key` option to `Google::PubSub::Topic#publish`.
2. A way to "flush and wait until flushed" when using `AsyncPublisher`.
