### ISSUE TITLE
bigquery: support GEOGRAPHY type

### ISSUE THREAD

**Issue by shollyman** [googleapis/google-cloud-ruby#11124]
This issue tracks support for the GEOGRAPHY data type in the bigquery library.  It seems this didn't get formally introduced during initial launch.

**Comment by quartzmo** [comment]
@shollyman Is there a reference implementation for this feature in another language that you prefer?

**Comment by shollyman** [comment]
I'm most familiar with the go version.  https://github.com/googleapis/google-cloud-go/pull/4225 was an update that improved geography support in query params (initially geography wasn't supported), and has reasonable roundtrip testing.
