### ISSUE TITLE
FR(bigquery): support mutable clustering configuration

### ISSUE THREAD

**Issue by shollyman** [googleapis/google-cloud-ruby#11155]
BigQuery service released support [mutable clustering configuration](https://cloud.google.com/bigquery/docs/creating-clustered-tables#modifying-cluster-spec) some time ago, but this hasn't propagated to all clients.

I see for example the stale commentary reflecting clustering fields:

> One or more fields on which data should be clustered. Must be specified with time partitioning, data in the table will be first partitioned and subsequently clustered. The order of the returned fields determines the sort order of the data.

Library should ensure:

* Clustering configuration can be modified on a managed table via a table update call
* Documentation reflects this capability, and possibly links to the cloud.google.com content above to describe the behavior when clustering is added/changed.
* Stale comments indicating that clustering requires a partitioning config are removed (you can cluster a table without partitioning it)

**Comment by quartzmo** [comment]
Todo:

- [ ] Add `Table#clustering_fields=`
- [ ] Support removing/clearing `Table#clustering_fields`.
- [ ] Remove stale docs.
- [ ] Add new docs with link.
