### ISSUE TITLE
docs(stackdriver): Need to remove the Debugger description from the stackdriver gem?

### ISSUE THREAD

**Issue by hypermkt** [googleapis/google-cloud-ruby#11223]
Now that the stackdriver gem no longer depends on Debugger(google-cloud-debugger), it looks like we can remove the description of Debugger from the documentation.

- Here are the commits related to the removal of the Debugger: 
  - googleapis@bf17920#diff-ae0c347001fcba09f798bd5e12b1e6041afca5ce18fe1187a86f213a687fdb0e
  - googleapis@00c40db#diff-ae0c347001fcba09f798bd5e12b1e6041afca5ce18fe1187a86f213a687fdb0e
- stackdriver document:
  - https://github.com/googleapis/google-cloud-ruby/blob/master/stackdriver/README.md
  - https://github.com/googleapis/google-cloud-ruby/blob/master/stackdriver/INSTRUMENTATION_CONFIGURATION.md 

Do I need to remove the description of Debugger (google-cloud-debugger) from the stackdriver gem documentation? 

If for some reason you need to keep the description of the Debugger in the stackdriver documentation, please close this issue. If you don't mind removing it, send a pull request. I am ready by the way. 😃 : https://github.com/hypermkt/google-cloud-ruby/commit/e7200c6dd407b6a18da7e8da413407e3ccd787fb

**Comment by danoscarmike** [comment]
@hypermkt thanks for reaching out! I imagine a PR would be welcomed :)

cc/ @dazuma

**Comment by hypermkt** [comment]
@danoscarmike  Thanks for responding! Okay, I will send a PR soon!
