### ISSUE TITLE
Please support if_(meta)generation_match in Google::Cloud::Storage::Bucket#create_file

### ISSUE THREAD

**Issue by FooBarWidget** [googleapis/google-cloud-ruby#11259]
Thanks for stopping by to let us know something could be better!

**PLEASE READ**: If you have a support contract with Google, please create an issue in the [support console](https://cloud.google.com/support/) instead of filing on GitHub. This will ensure a timely response.

 **Is your feature request related to a problem? Please describe.**
No.

 **Describe the solution you'd like**
I would like Google::Cloud::Storage::Bucket#create_file to add support for [precondition headers](https://cloud.google.com/storage/docs/generations-preconditions):
- if_generation_match
- if_metageneration_match

 **Describe alternatives you've considered**
The alternative is shelling out to `gsutil`.

 **Additional context**
None.

**Comment by quartzmo** [comment]
@frankyn Is there any reason we can't expose support for these precondition headers?

**Comment by frankyn** [comment]
Nope, if there's spare cycles, I think Ruby is the last remaining language without if_(meta)generation support.

**Comment by quartzmo** [comment]
@frankyn Great! I'll start work on it soon.

Based on the generated client `Google::Apis::StorageV1::StorageService`, It looks like some or all of the 4 parameters (`if_generation_match`, `if_generation_not_match`, `if_metageneration_match` and `if_metageneration_not_match`) should be added to the following internal `Service` methods, then similarly exposed in the public methods that use them:

* `Google::Cloud::Storage::Service#compose_file` (`if_generation_match` and `if_metageneration_match` only)
* `Google::Cloud::Storage::Service#delete_file`
* `Google::Cloud::Storage::Service#get_file`
* `Google::Cloud::Storage::Service#insert_file`
* `Google::Cloud::Storage::Service#patch_file`
* `Google::Cloud::Storage::Service#rewrite_file`
