### ISSUE TITLE
When running specs against the emulator: Ability to reset entire datastore set between tests

### ISSUE THREAD

**Issue by NielsKSchjoedt** [googleapis/google-cloud-ruby#11256]
Hi, it would be really convenient to have a `teardown` or `reset` command which could be run around each tests case when running specs against the emulator. I know the emulator has a `reset` capability (as per: https://github.com/googleapis/google-cloud-java/issues/1292#issuecomment-250391120%7C) It would be really great to have that option instead of having to query and delete all objects in the DB one by one to ensure no leaks happen between test cases.

**Comment by quartzmo** [comment]
Hi @NielsKSchjoedt,

Thanks for this suggestion. Can you provide more context about where you would use this feature? Are you referring to tests in this project or your own tests? Where would you expect the command to be?

**Comment by NielsKSchjoedt** [comment]
Hi @quartzmo This would most likely be for peoples own projects where they use the `google-cloud-datastore` gem. A typical ruby example would be that you e.g. have `rspec` as your test library, but it could essentially be any library. If we take the spec example people will always have a `spec_helper.rb` for the spec config. It would normally look something like this: https://github.com/rspec/rspec/wiki#specspec_helperrb

Now what most people do (e.g. in a rails project) is that they will have some strategy implemented for clearning the db (or whatever persistence layer they have) between the tests to avoid inserted test data leaking between requests. For datastore it could look something like this inside the spec_helper.rb:

```ruby
RSpec.configure do |config|
  config.after :example do
    Google::Cloud.datastore("my-todo-project").reset!
  end
end
```

So `reset!` or `clear!` or `delete_all!` or `teardown!` or whatever :-)

**Comment by quartzmo** [comment]
Thank you, now I understand. I don't think this feature is something that should be included in the google-cloud-datastore library, since it is outside the scope of the Datastore API, and exists only in the emulator. Users of google-cloud-datastore might get confused and think that `reset` executes an RPC to the Datastore service.

Instead, can you implement your own simple ``POST` request to `http://<host>:<port>/reset` in Ruby inside your RSpec helper?
