### ISSUE TITLE
pubsub: GetSchema doesn't retrieve schema definition

### ISSUE THREAD

**Issue by hongalex** [googleapis/google-cloud-ruby#11419]
#### Steps to reproduce

  1. Run `pubsub.schema` to retrieve a schema without a view (`view: :full`)

#### More info

This is analogous to https://github.com/googleapis/java-pubsub/issues/669. By default, get/list schemas should default to the `FULL` view.

**Comment by quartzmo** [comment]
@hongalex Since this was opened as a `bug`, the change should be published as a semver `patch`, correct?

**Comment by hongalex** [comment]
Yeah patch sounds right to me.
