### ISSUE TITLE
Undocumented Pub/Sub dependency for error reporting in google-cloud-trace

### ISSUE THREAD

**Issue by grobie** [googleapis/google-cloud-ruby#11668]
The google-cloud-trace library has a [hidden pub/sub dependency for internal exception reporting](https://github.com/googleapis/google-cloud-ruby/blob/0c5ca6071773495ddbeec906bd6a47c42e516f5b/google-cloud-trace/lib/google/cloud/trace/async_reporter.rb#L285) which is *not documented anywhere*.

Our service account doesn't have any pub/sub permissions (as pub/sub isn't otherwise used), so all exceptions were silently ignored without any indication besides 4xx errors in the pub/sub metrics https://console.cloud.google.com/apis/api/pubsub.googleapis.com/metrics (which is really not that obvious).

Please document this dependency clearly in the Cloud Trace documentation or provide an easier way to see errors caused by the trace library. (@dazuma this would have made it a lot easier to debug #11666).

**Comment by dazuma** [comment]
Oh, that's totally broken. It should be using Trace's own config classes, not pubsub's. Lemme get that fixed.
