### ISSUE TITLE
ArtifactRegistry Credentials Hash not correctly scoped

### ISSUE THREAD

**Issue by watsonjon** [googleapis/google-cloud-ruby#11665]
ArtifactRegsitry defines a `Hash` for its own purposes and that is being used when checking if the given credentials `is_a?(Hash)` instead of a normal ruby `Hash`.

#### Environment details

  - OS: macOS BigSur 11.4
  - Ruby version: 2.6.6
  - Gem name and version: google-cloud-artifact_registry-v1beta2 (0.3.0)

#### Steps to reproduce

  1. Create a new instance of the artifact registry client and supply your service credentials as a hash.

#### Code example

```ruby
require 'google/cloud/artifact_registry/v1beta2'

Google::Cloud::ArtifactRegistry::V1beta2::ArtifactRegistry::Client.new do |config|
  config.credentials = {....} # your credentials as a Hash
end
```

#### Full backtrace

```sh
[4] pry(main)> require 'google/cloud/artifact_registry/v1beta2'
=> true
[5] pry(main)> Google::Cloud::ArtifactRegistry::V1beta2::ArtifactRegistry::Client.new do |config|
[5] pry(main)*   if creds.is_a?(Hash)  
[5] pry(main)*     config.credentials = creds    
[5] pry(main)*   end  
[5] pry(main)* end  
ArgumentError: invalid credentials (Hash)
from /Users/me/.rvm/gems/ruby-2.6.6@spacedust/gems/gapic-common-0.4.1/lib/gapic/grpc/service_stub.rb:71:in `initialize'
[6] pry(main)> 
```

Need to instead check for `credentials.is_a?(::Hash)` here:
 https://github.com/googleapis/google-cloud-ruby/blob/master/google-cloud-artifact_registry-v1beta2/lib/google/cloud/artifact_registry/v1beta2/artifact_registry/client.rb#L278

**Comment by dazuma** [comment]
Fixed in the latest release: https://rubygems.org/gems/google-cloud-artifact_registry-v1beta2/versions/0.3.2
