### ISSUE TITLE
Add preconditions for source files to Bucket#compose

### ISSUE THREAD

**Issue by quartzmo** [googleapis/google-cloud-ruby#11690]
`Google::Apis::StorageV1::ComposeRequest::SourceObject::ObjectPreconditions` need to be exposed for `sources` in `Bucket#compose`.

This work has been started in https://github.com/quartzmo/google-cloud-ruby/tree/storage-compose-source-preconditions, but the design needs to be re-considered.

**Comment by frankyn** [comment]
Please consider Python implementation, https://github.com/googleapis/python-storage/blob/master/google/cloud/storage/blob.py#L3194-L3252
