### ISSUE TITLE
OpenTelemetry exporter for Cloud Trace

### ISSUE THREAD

**Issue by bouk** [googleapis/google-cloud-ruby#12169]
Hello,

I'm trying to adopt OpenTelemetry for my Rails app, but there's no OpenTelemetry exporter available. Right now there's just the `google-cloud-trace` gem which doesn't integrate nicely with the rest of the OpenTelemetry ecosystem. It would be really useful to get a well-supported exporter gem!

**Comment by dazuma** [comment]
This is being worked on here: https://github.com/GoogleCloudPlatform/opentelemetry-operations-ruby. We don't have a solid ETA yet, but we have an engineer actively on it now, so likely this quarter.
