### ISSUE TITLE
cloudrad: add readme and other *.md files to docs

### ISSUE THREAD

**Issue by TheRoyalTnetennba** [googleapis/google-cloud-ruby#13173]
@tbpg

**Comment by tbpg** [comment]
Note: you can publish a package named `help` with a minimal TOC and it will show up like this: https://cloud.google.com/dotnet/docs/reference/help/getting-started

See https://github.com/googleapis/google-cloud-dotnet/blob/master/docs/devsite-help/toc.yml.

That can be useful for product-neutral guides.
