### ISSUE TITLE
Google Cloud Debugger Gem does not support Ruby 3

### ISSUE THREAD

**Issue by terracatta** [googleapis/google-cloud-ruby#13668]
> The google-cloud-debugger agent has dependencies on libraries that are not compatible with Ruby 3, and thus is itself not supported on Ruby 3. There are no immediate plans to update it with Ruby 3 support. If you are using the agent and require support for Ruby 3, please open an issue at https://github.com/googleapis/google-cloud-ruby/issues.

We use the Google Cloud Debugger for a Rails app we wish to upgrade to Ruby 3.0. We will not be able to use the debugger if the Gem is not upgraded. I don't see any duplicate issues, so I wanted to add my voice in case others need this too.

**Comment by znorris** [comment]
My organization would also like to use Ruby 3.0 with cloud debugger.

**Comment by dazuma** [comment]
Unfortunately, the Google Cloud Debugger product is deprecated and due to be shut down. See https://cloud.google.com/debugger/docs/deprecations. So we're not going to be updating the gem any further.
