### ISSUE TITLE
fix(pubsub): Add retry options and expanded retry logic

### ISSUE THREAD

**Issue by quartzmo** [googleapis/google-cloud-ruby#13953]
The [google-cloud-pubsub](https://github.com/googleapis/google-cloud-ruby/blob/master/google-cloud-pubsub) library is required to support the following RPC retry policy, provided by the Pub/Sub team:

| property | default value |
| ---------------------- | ------ |
| init RPC timeout | 5s |
| max RPC timeout | 60s |
| rpc timeout multiplier | 1.3 |
| total timeout | 600s |
| initial retry delay | 100ms |
| retry delay multiplier | 1.3 |
| max retry delay | 60s |

This configuration is similar to the old [google/cloud/pubsub/v1/publisher_client_config.json](https://github.com/googleapis/google-cloud-ruby/blob/0015ad9859ad901d7ee6f595b3665cf6164b70a1/google-cloud-pubsub/lib/google/cloud/pubsub/v1/publisher_client_config.json#L31-L37) that was used prior to the introduction of this generator and gapic-common, except that in the table above "init RPC timeout" is `5s` and in the older config `initial_rpc_timeout_millis` was `60000` (60s).

The preference of the Ruby clients team is to address this issue entirely in the veneer layer as follows:

1. Override the [default retry behavior for the RPC](https://github.com/googleapis/google-cloud-ruby/blob/master/google-cloud-pubsub-v1/lib/google/cloud/pubsub/v1/publisher/client.rb#L78-L81) in the configuration block [here](https://github.com/googleapis/google-cloud-ruby/blob/master/google-cloud-pubsub/lib/google/cloud/pubsub/service.rb#L65-L72).
2. Implement the timeout and delay behavior specified above entirely in the veneer layer (google-cloud-pubsub). See [gax-nodejs/src/normalCalls/retries.ts](https://github.com/googleapis/gax-nodejs/blob/main/src/normalCalls/retries.ts) for how this is done in nodejs-pubsub.
3. Close googleapis/gapic-generator-ruby#672 without making any changes to `gapic-common`.

**Comment by quartzmo** [comment]
Changing to `p3` as this issue may be addressed by "hedging" (a differing solution), pending investigation.

**Comment by meredithslota** [comment]
@quartzmo Would you be willing to add the outcome of the aforementioned investigation?

**Comment by quartzmo** [comment]
@kamalaboulhosn Any updates on this request? Has it been determined that the need for the desired retry behavior can be addressed by "hedging"?

**Comment by NivedhaSenthil** [comment]
Closing the issue as this will be addressed by hedging sooner as mentioned.
