### ISSUE TITLE
PubSub: Add an option to reduce logging volume when no messages can be pulled

### ISSUE THREAD

**Issue by sriedel** [googleapis/google-cloud-ruby#13965]
**Is your feature request related to a problem? Please describe.**
We are pulling messages from a pubsub subscription via #listen. Since we have bursty traffic on pubsub, a lot of times there is nothing to fetch. Every polling-loop we get the following output into our logs:

    DEBUG: bidi-read-loop: starting
    DEBUG: bidi-read-loop: 0
    DEBUG: bidi-write-loop: starting
    DEBUG: bidi-write-loop: 0
    DEBUG: bidi-read-loop: null batch <struct Struct::BatchResult send_message=nil, send_metadata=nil, send_close=nil, send_status=nil, message=nil, metadata={"date"=>"Tue, 14 Sep 2021 09:42:58 GMT"}, status=nil, cancelled=nil>
     DEBUG: bidi-read-loop: done status <struct Struct::Status code=14, details="The service was unable to fulfill your request. Please try again. [code=8a75]", metadata={}, debug_error_string="{\"created\":\"@1631612578.548498110\",\"description\":\"Error received from peer ipv4:142.251.5.95:443\",\"file\":\"src/core/lib/surface/call.cc\",\"file_line\":1066,\"grpc_message\":\"The service was unable to fulfill your request. Please try again. [code=8a75]\",\"grpc_status\":14}">
    DEBUG: Failing with status <struct Struct::Status code=14, details="The service was unable to fulfill your request. Please try again. [code=8a75]", metadata={}, debug_error_string="{\"created\":\"@1631612578.548498110\",\"description\":\"Error received from peer ipv4:142.251.5.95:443\",\"file\":\"src/core/lib/surface/call.cc\",\"file_line\":1066,\"grpc_message\":\"The service was unable to fulfill your request. Please try again. [code=8a75]\",\"grpc_status\":14}">
    WARN: bidi: read-loop failed
    WARN: 14:The service was unable to fulfill your request. Please try again. [code=8a75]. debug_error_string:{\"created\":\"@1631612578.548498110\",\"description\":\"Error received from peer ipv4:142.251.5.95:443\",\"file\":\"src/core/lib/surface/call.cc\",\"file_line\":1066,\"grpc_message\":\"The service was unable to fulfill your request. Please try again. [code=8a75]\",\"grpc_status\":14}
    DEBUG: calling pubsub.googleapis.com:/google.pubsub.v1.Subscriber/StreamingPull
    DEBUG: bidi-write-loop: 1 writes done 
    DEBUG: bidi-write-loop: client sent 1, waiting
    DEBUG: bidi-write-loop: done
    DEBUG: bidi-write-loop: finished

I don't know who bidi is, but they certainly want us to know that they're reading and writing a lot ;)

Of course this adds up quickly over time, filling up the logs and making it more difficult than needed to find "real", relevant log entries.

 **Describe the solution you'd like**
An option to display a single terse "No messages available" log line would be appreciated.

 **Describe alternatives you've considered**
Increasing the log level beyond DEBUG would filter out most of the messages, however, this leaves the WARN messages (which in the context of my application I don't really consider to be worthy of that high a log level, having no messages to receive isn't necessarily a warning condition for us). Also, we do use the DEBUG log level internally to output debug information for our own application. So filtering out pubsub messages becomes more complex in order to not inadvertently filter out our own log messages.

 **Additional context**
Currently running gem version 2.7.1, but these messages have been with us since the 0.x days of the gem, and the amount of log output in these no-message read-loops has been slowing increasing over the past two years.

**Comment by quartzmo** [comment]
These logging statements originate in the logging for the underlying [gRPC](https://github.com/grpc/grpc/tree/master/src/ruby) client library.

> I don't know who bidi is, but they certainly want us to know that they're reading and writing a lot ;)

😄 Search for `GRPC.logger` in [grpc/generic/bidi_call.rb](https://github.com/grpc/grpc/blob/master/src/ruby/lib/grpc/generic/bidi_call.rb) and you will see where all that noise comes from.

> we do use the DEBUG log level internally to output debug information for our own application. So filtering out pubsub messages becomes more complex in order to not inadvertently filter out our own log messages.

Are you configuring the gRPC client logging as described in [Logging.md](https://github.com/googleapis/google-cloud-ruby/blob/master/google-cloud-pubsub/LOGGING.md)? If so, and you remove the "gRPC module-level logger method", does that stop the gRPC logging?

> An option to display a single terse "No messages available" log line would be appreciated.

This library, google-cloud-pubsub, currently has no logging. (Issue #1216 raised the idea of adding logging in 2017.) Although it would be a big change for this library, we might be able to add what you want here in google-cloud-pubsub. I'm not sure how feasible it would be to add the logging statement you want to the gRPC library.

**Comment by sriedel** [comment]
Ah, grpc... we meet again... :)

Thanks for the pointers I'll have a look at what I can do. I'd hate to disable the loop logging completely, since a sporadic "Yep, I'm still alive, just idleing right now, everything is fine" log message does serve a purpose. But maybe I can get away with it in the application level logs and just silence grpc completely.

Either way as google-cloud-pubsub is not the source of the log messages I'll close the ticket as nothing is really to be done here, unless the read-loop-logging is lifted a layer of abstraction from grpc to the google-cloud-pubsub  gem.

**Comment by quartzmo** [comment]
@sriedel The gRPC client exposes the stream as an enumerator in Ruby. You can see where it is repeatedly called inside a loop in google-cloud-pubsub on [google/cloud/pubsub/subscriber/stream.rb#L244](https://github.com/googleapis/google-cloud-ruby/blob/master/google-cloud-pubsub/lib/google/cloud/pubsub/subscriber/stream.rb#L244). I believe this would be an appropriate location for the logging statement you want.
