### ISSUE TITLE
[Contributor docs] Document development and testing processes for google-cloud-bigquery

### ISSUE THREAD

**Issue by dazuma** [googleapis/google-cloud-ruby#14164]
Enumerate topics and write an initial document for contributors to google-cloud-bigquery. At a high level, this should include at least:
* How to run local unit tests
* How to set up and run integration/acceptance/samples tests, including remote project setup, fixtures, and connections to other services
* How to write tests for new features
* Other things we check during CI (e.g. rubocop, yard tests, etc.)
* What is expected when opening a pull request (e.g. conventional commits, CLA)
* Anything else you can think of

**Comment by quartzmo** [comment]
Updated docs should be adapted from [google-cloud-firestore/CONTRIBUTING.MD](https://github.com/googleapis/google-cloud-ruby/blob/main/google-cloud-firestore/CONTRIBUTING.md) and [google-cloud-firestore/samples/CONTRIBUTING.MD](https://github.com/googleapis/google-cloud-ruby/blob/main/google-cloud-firestore/samples/CONTRIBUTING.md).
