### ISSUE TITLE
Broken links in AUTHENTICATION.md

### ISSUE THREAD

**Issue by quartzmo** [googleapis/google-cloud-ruby#14475]
The following links in `AUTHENTICATION.md` files produce 404s:

* `https://raw.githubusercontent.com/GoogleCloudPlatform/gcloud-common/master/authentication/enable-apis.png`
* `https://raw.githubusercontent.com/GoogleCloudPlatform/gcloud-common/master/authentication/create-new-service-account.png`
* `https://raw.githubusercontent.com/GoogleCloudPlatform/gcloud-common/master/authentication/create-new-service-account-existing-keys.png`
* `https://raw.githubusercontent.com/GoogleCloudPlatform/gcloud-common/master/authentication/reuse-service-account.png`

I'm not sure if these images are needed in the document, or if there might be a better way to communicate the information.

For generated clients, the fix depends on googleapis/gapic-generator-ruby#688.
For hand-written clients, the fixes must be made manually in this repo, but should copy the solution from googleapis/gapic-generator-ruby#688.

**Comment by meredithslota** [comment]
https://github.com/googleapis/gapic-generator-ruby/issues/688 is now fixed.
