### ISSUE TITLE
How to authorize requests in Google::Apis clients using OAuth 2.0 flow?

### ISSUE THREAD

**Issue by timoffex** [googleapis/google-cloud-ruby#14484]
How can I make my App Engine service make requests to GCS on behalf of a logged-in Google user that is using my web app?

I want my service account NOT to have permission to access a storage bucket to reduce the risk of it acting as a [confused deputy](https://en.wikipedia.org/wiki/Confused_deputy_problem) (and to reduce the risk of me writing buggy authz code). Instead, I want to use the permissions of the logged-in user.

NOTE: I haven't used the API in other languages, so I don't know if this is something that's just missing from the Ruby implementation, or if I am thinking about this wrong. Does IAM even support credential forwarding?

I see that I can pass a `Credentials` instance to `Google::Cloud::Storage.new`. Am I supposed to create a new `Project` instance on every HTTP request just to pass different credentials? I tried this and felt it was slower than when I just used a single instance. The documentation says that "every instance creates a new connection". How do I close the connection? Will I run out of connections?

Next, how do I get `Credentials`? [This page](https://developers.google.com/identity/protocols/oauth2/web-server#ruby_2) gives an example for a `Google::Apis`-style library, so it's not applicable. The `google-auth-library-ruby` library has a [get_credentials](https://www.rubydoc.info/github/google/google-auth-library-ruby/Google/Auth/WebUserAuthorizer#get_credentials-instance_method) method that [its README uses](https://github.com/googleapis/google-auth-library-ruby), but this doesn't return a `Credentials` instance. I also see an [IAMCredentials class](https://www.rubydoc.info/github/google/google-auth-library-ruby/Google/Auth/IAMCredentials) in the auth library, which sounds closer to what I need, but to use this I need an "IAM token", which I don't know how to get.

Any pointers appreciated. Thanks!

**Comment by quartzmo** [comment]
| how do I get Credentials?

I think you can do it just by creating a new instance of [Signet::OAuth2::Client](https://github.com/googleapis/signet/blob/main/lib/signet/oauth_2/client.rb). `Signet::OAuth2::Client` is not a documented type for the `credentials` param in `Google::Cloud::Storage.new`, but it works and it probably should be. We can look into getting it added. You will need the user's Google Cloud project ID to call the GCS API.

```rb
require "google/cloud/storage"

token = "ya29.a0ARrd..."
project_id = "my-project-id"

auth_client = Signet::OAuth2::Client.new
auth_client.access_token = token

storage = Google::Cloud::Storage.new project_id: project_id, credentials: auth_client
buckets = storage.buckets
```

In the example above, I used a short-lived OAuth2 token that I obtained  from IAM using "Try this API" at [`projects.serviceAccounts.generateAccessToken`](https://cloud.google.com/iam/docs/reference/credentials/rest/v1/projects.serviceAccounts/generateAccessToken). This is called impersonating the service account. I think it should also work with an OAuth token that you obtain as shown in [Step 5: Exchange authorization code for refresh and access tokens](https://developers.google.com/identity/protocols/oauth2/web-server#exchange-authorization-code):

```rb
auth_client = Signet::OAuth2::Client.new
auth_client.code = auth_code
auth_client.fetch_access_token!
```

Can you try this?

**Comment by quartzmo** [comment]
> This page gives an example for a Google::Apis-style library, so it's not applicable.

Both `google-cloud-storage` and `google-cloud-bigquery` use the generated `Google::Apis` clients under the hood. The `Google::Apis::StorageV1::StorageService` is initialized with the auth client [here](https://github.com/googleapis/google-cloud-ruby/blob/main/google-cloud-storage/lib/google/cloud/storage/service.rb#L46-L60):

```rb
@service = API::StorageService.new
...
@service.authorization = @credentials.client if @credentials
```

**Comment by timoffex** [comment]
Thank you for such a thorough response!

> The relationship with the datastore is 100% owned by your application or service, which uses it to store data

This explanation is helpful. I'm used to having another service that keeps track of fine-grained ACLs (i.e. [Zanzibar](https://research.google/pubs/pub48190/)) when storing user data in a database. Out of curiosity, is there an API like this in GCP? Or is this what per-file ACLs are for (and if so, is there a way to say "allow ONLY service A to read file X from this bucket if user Z gives permission, and don't allow user Z to touch X directly")?

> Normally, an application that uses Google accounts for authn would not expect those Google accounts to have a relationship with GCS, they would only be used to manage identity. Is there some special reason why users of your app would have access to GCS? [...] I imagine each of your users could implement finer-grained access for your app via IAM (bucket-level) or ACLs (bucket- and object-level), but is that realistic?

I think you are right, a different approach is better. For context, I am writing an admin app for modifying configuration files for a different app. The admin app reads and modifies data in a "staging" bucket, and eventually the user requests to push this data to a "prod" bucket. I wanted the staging bucket's IAM permissions to list the admins, not the service. However, I now realize that I probably don't want the users to be able to touch GCS directly. Instead, I am now considering putting the admin app into a separate project behind [IAP](https://cloud.google.com/iap/docs/app-engine-quickstart), and then allowing the users access to the admin service rather than to GCS directly.

> Signet::OAuth2::Client is not a documented type for the credentials param in Google::Cloud::Storage.new, but it works and it probably should be.

Yes, please! If this is true, then it is exactly the connection between the OAuth 2.0 flow and the client libraries that I was looking for. I spent a lot of time trying to figure this out; it should definitely be in the documentation. I will try it and post an update here if I run into any more trouble.
