### ISSUE TITLE
storage: error in sample test

### ISSUE THREAD

**Issue by bajajneha27** [googleapis/google-cloud-ruby#16029]
There are [sample test failures](https://source.cloud.google.com/results/invocations/6f7d2e57-41b3-46eb-b42b-230875c38009/log) in google-cloud-storage. This was noticed in PR [16028](https://github.com/googleapis/google-cloud-ruby/pull/16028)

**Comment by quartzmo** [comment]
I don't know why this is failing now, but I suppose it must be improved validation in the service. I tried using [the email that is used in the top-level acceptance tests](https://github.com/googleapis/google-cloud-ruby/blob/main/google-cloud-storage/acceptance/storage/bucket_acl_test.rb#L23) and it fixed the problem for me.

**Comment by bajajneha27** [comment]
Thank you, that worked.
