### ISSUE TITLE
Question: google-cloud-storage service firebase emulator support

### ISSUE THREAD

**Issue by appex-development** [googleapis/google-cloud-ruby#16068]
I am querying whether there is support to hook the storage service up to the storage firebase emulator.
I know in other languages you can set something like this:
 
 ENV['FIRESTORE_STORAGE_EMULATOR_HOST'] = 'http://localhost:9199'
 
 or
 
 ENV['STORAGE_EMULATOR_HOST'] = 'http://localhost:9199'
 
 But it doesnt seem to be supported or documented so guessing this feature does not exist yet.
 Any support would be greatly appreciated.

**Comment by quartzmo** [comment]
Hi @appex-development,

Thanks for opening this issue! Is the [Firebase Local Emulator Suite - Cloud Storage emulator](https://firebase.google.com/docs/emulator-suite/connect_storage) the emulator you mean? In these docs, I only see mention of the `FIREBASE_STORAGE_EMULATOR_HOST` environment variable. I couldn't find `FIRESTORE_STORAGE_EMULATOR_HOST` in any Google documentation. I'm not sure how libraries in this repo (`google-cloud-firestore` or `google-cloud-storage`) would interact with this emulator, but I don't know much about the emulator. At first glance it looks to be tightly coupled with Firebase. If you can provide any more information, I'm happy to keep investigating.

**Comment by appex-development** [comment]
Hi @quartzmo,

Thanks for the reply. Yes thats is the emulator. Yes my bad I think I just copied it incorrectly. In other available service gems there is either an environment variable you can set or pass in an argument when creating a client instance, for example in the google-cloud-firebase gem (see the readme below).

https://github.com/googleapis/google-cloud-ruby/blob/main/google-cloud-firestore/EMULATOR.md

**Comment by quartzmo** [comment]
It sounds like you are asking if it is possible to use the [Firebase Local Emulator Suite - Cloud Storage emulator](https://firebase.google.com/docs/emulator-suite/connect_storage) with the `google-cloud-storage` gem in this repo, is that correct?

**Comment by quartzmo** [comment]
If so, my impression from reading [How the Cloud Storage emulator differs from production](https://firebase.google.com/docs/emulator-suite/connect_storage#how_the_emulator_differs_from_production) is that the feature set of this emulator is narrowly focused on the Firebase client:

> For testing of client apps, the Cloud Storage emulator aligns to production almost perfectly in regards to the Firebase API surface area. All Firebase commands are expected to work between the regular Firebase SDKs (Web, Android, and Apple platforms). For testing of server-side apps, limitations exist.

Because the `google-cloud-storage` gem is a general-purpose client that aims to support all features available in Google Cloud Storage, it sounds to me like the Firebase Local Emulator Suite - Cloud Storage emulator is likely not to support all of its features.

**Comment by appex-development** [comment]
Ah ok thats not a problem. As I am only using the sdk for end to end test scripts I have got around it by just implementing a node script using the firebase admin sdk to do what I need and just exectuted where I need it in my ruby scripts.

Thanks very much for looking into it 👍

**Comment by quartzmo** [comment]
Sounds good! If you change your mind in the future and believe that the google-cloud-storage gem should support this Firebase emulator, please reopen this issue.
