### ISSUE TITLE
Google Cloud Storage Bucket#file does not return latest generation of file

### ISSUE THREAD

**Issue by tinco** [googleapis/google-cloud-ruby#16099]
#### Environment details

  - OS: Linux container
  - Ruby version: 2.7.1
  - Gem name and version:  google-cloud-storage (1.31.0)

#### Steps to reproduce

  1. Create a file like so:

```
bucket.create_file(StringIO.new(index_json), file_prefix + 'index.json', content_type: "text/plain")
```

  2. Note the generation, then create it again:
```
bucket.create_file(StringIO.new(index_json), file_prefix + 'index.json', content_type: "text/plain")
```

  3. Note the generation again. Then download the file

```
bucket.file(file_prefix + 'index.json').download
```

   4. Note that in the logs you will see a get request that looks like this:

```
   #<HTTP::Message::Body:0x0000558ec8c05b50
    @body=nil,
    @chunk_size=nil,
    @positions=nil,
    @size=nil>,
  @http_header=
   #<HTTP::Message::Headers:0x0000558ec8c05bf0
    @body_charset=nil,
    @body_date=nil,
    @body_encoding=#<Encoding:UTF-8>,
    @body_size=0,
    @body_type=nil,
    @chunked=false,
    @dumped=false,
    @header_item=
     [["X-GUploader-UploadID",
       "**secret?**"],
      ["ETag", "COKg7LLfsfQCEAE="],
      ["X-Goog-Hash", "crc32c=81yxQQ==,md5=C6207gR1emDU6C/GrIJWXg=="],
      ["Content-Type", "text/plain"],
      ["X-Goog-Generation", "1637782537310306"],
      ["X-Goog-Metageneration", "1"],
      ["X-Goog-Storage-Class", "REGIONAL"],
      ["Expires", "Mon, 29 Nov 2021 23:14:04 GMT"],
      ["Content-Disposition", "attachment"],
      ["Date", "Mon, 29 Nov 2021 23:14:04 GMT"],
      ["Vary", "Origin"],
      ["Vary", "X-Origin"],
      ["Content-Length", "77551"],
      ["Server", "UploadServer"],
      ["Age", "3088"],
      ["Cache-Control", "public, max-age=3600, must-revalidate"]],
```

Note especially the Cache-Control being set to max-age=3600, and in my case note that you got the old generation instead of the new one.

This directly contradicts the documentation which states that it's always the latest generation that is returned.

I also don't see a way of overriding the cache control header that the library sends.

**Comment by SandeepTuniki** [comment]
Hi @tinco, thanks for raising this issue and apologies for the delay in addressing this. I attempted to reproduce this issue with the same environment, and this is what I got:

**Step 1**: Create a file
```sh
bucket.create_file(StringIO.new(index_json), file_prefix + 'index.json', content_type: "text/plain")

# ...  @generation=1654423624185119 ...
```

**Step 2**: Create it again
```sh
bucket.create_file(StringIO.new(index_json), file_prefix + 'index.json', content_type: "text/plain")

# ... @generation=1654423673779816 ...
```

**Step 3**: Download it
```sh
bucket.file(file_prefix + 'index.json').download

# ... ["X-Goog-Generation", "1654423673779816"] ...
```

It appears like the `.download` method returns the latest generation of file, which is its expected behaviour.

Can you check if you're still facing this issue?

**Comment by tinco** [comment]
Hi @SandeepTuniki I have just tested this and I can confirm this bug has been fixed, the cache headers in `1.36` are now correctly set to ` ["Cache-Control", "private, max-age=0, must-revalidate, no-transform"]`

I also see that debug logging is now much more reasonable.

Thanks!

**Comment by tinco** [comment]
I've been diving into the code, but I haven't pinned it down yet.  When I use `make_simple_command` from `<Google::Apis::Core::ApiCommand` it sets `no-cache` but when I use `make_storage_download_command` it sets the cache. But I don't see it in the code anywhere on the main branch.

**Comment by tinco** [comment]
I was mistaken, the cache control header is on the response, not on the request. I think what is going on is that there's no cache control sent at all, and this causes Google to return with the default cache control setting for the object, which is `public, max-age=3600, must-revalidate`, so I'm getting outdated responses.
