### ISSUE TITLE
PubSub subscription.push_config set_oidc_token returning 403 

### ISSUE THREAD

**Issue by jpaulgs** [googleapis/google-cloud-ruby#16096]
#### Environment details

  - OS: debian:buster-slim (docker running on GKE)
  - Ruby version: 2.7.0
  - Gem name and version: google-cloud-pubsub (2.8.1)

#### Steps to reproduce

  1. Create a subscription
  2. Set push configuration 
 	- Set the endpoint
 	- `set_oidc_token` Boom!

Normally I would accept that this is a permissions issue on my end but we haven't been able to make progress from the documentation and error messages.

Our Application is running on GKE with workload identity in a project called 'greensync-clusters'. In this case the pubsub topics and subscriptions exist in another project 'dex-nonprod'.  We currently have the following roles associated to the service account:

```sh
gcloud projects get-iam-policy dex-nonprod  \
--flatten="bindings[].members" \
--format='table(bindings.role)' \
--filter="bindings.members:app-dex-sandbox@greensync-clusters.iam.gserviceaccount.com"
ROLE
roles/bigquery.user
roles/cloudsql.client
roles/iam.serviceAccountTokenCreator
roles/iam.serviceAccountUser
roles/pubsub.editor
```

```
gcloud projects get-iam-policy greensync-clusters  \
--flatten="bindings[].members" \
--format='table(bindings.role)' \
--filter="bindings.members:app-dex-sandbox@greensync-clusters.iam.gserviceaccount.com"
ROLE
roles/iam.serviceAccountTokenCreator
```

What roles are required to set the OIDC token?

#### Code example

```ruby
      subscription.push_config do |push_config|
        push_config.endpoint = request_output.fetch(:endpoint)
        push_config.set_oidc_token(pubsub_config.service_account_email, audience) if audience
      end
```

#### Full backtrace

message 

```
"7:User not authorized to perform this action.. debug_error_string:{"created":"@1637897816.315033265","description":"Error received from peer ipv4:142.250.66.202:443","file":"src/core/lib/surface/call.cc","file_line":1069,"grpc_message":"User not authorized to perform this action.","grpc_status":7}
```

```sh
0: "/usr/local/bundle/ruby/2.7.0/gems/google-cloud-pubsub-v1-0.6.0/lib/google/cloud/pubsub/v1/subscriber/client.rb:537:in `rescue in update_subscription'"
1: "/usr/local/bundle/ruby/2.7.0/gems/google-cloud-pubsub-v1-0.6.0/lib/google/cloud/pubsub/v1/subscriber/client.rb:501:in `update_subscription'"
2: "/usr/local/bundle/ruby/2.7.0/gems/google-cloud-pubsub-2.8.1/lib/google/cloud/pubsub/service.rb:223:in `update_subscription'"
3: "/usr/local/bundle/ruby/2.7.0/gems/google-cloud-pubsub-2.8.1/lib/google/cloud/pubsub/subscription.rb:299:in `push_config'"
4: "/app/lib/dex/core/api/v2_beta/participants/telemetry_subscription/configure/transaction.rb:63:in `configure_subscription_endpoint'"
[snip]
```

**Comment by jpaulgs** [comment]
After going back and forth with Google technical support on this.  It would appear that the service account used to set the OIDC token must exist in the same project as the PubSub subscription.

I'll post back and close this issue once I get final confirmation

**Comment by quartzmo** [comment]
@jpaulgs Were you able to confirm this?

**Comment by jpaulgs** [comment]
@quartzmo I'm still waiting for final confirmation from google support.  However local testing confirms that I can associate an OIDC token if the associated signing service account in is the same project as the subscription being clear all other roles on my test service accounts are the same.

**Comment by quartzmo** [comment]
@jpaulgs Sounds good. Please ping me to close this issue when you feel it is appropriate.

**Comment by quartzmo** [comment]
@jpaulgs I'm going to close this issue now per your comment above with the explanation from support. Please re-open if you still have any trouble.
