### ISSUE TITLE
ALTER TABLE statement fails sometimes with a dataset not found error in google-cloud-bigquery

### ISSUE THREAD

**Issue by ZimbiX** [googleapis/google-cloud-ruby#16097]
Semi-related to comments on https://github.com/googleapis/google-cloud-ruby/issues/9617#issuecomment-784501338.

We found that re-running our schema migrations (after deleting the dataset) (using [sequel-bigquery](https://github.com/ZimbiX/sequel-bigquery)) _sometimes_ results in an error inexplicably complaining that the dataset could not be found.

The dataset definitely did exist (due to previous migration files succeeding), so this was quite a confusing error. Drilling into the backtrace, we discovered that `QueryJob#data` has a special return path for DDL statements; yet the `#ddl?` method did not categorise an `ALTER TABLE` statement as DDL!

We have no idea why `service.list_tabledata` fails inconsistently.

Although we discovered this issue in google-cloud-bigquery 1.37.0, the applicable code is unchanged in the latest version, 1.38.0.

We have a patch we're submitting as a PR now.

#### Environment details

  - OS: `Linux ZimbiX-GreenSync 5.15.4-arch1-1 #1 SMP PREEMPT Sun, 21 Nov 2021 21:34:33 +0000 x86_64 GNU/Linux`
  - Ruby version: `ruby 2.7.3p183 (2021-04-05 revision 6847ee089d) [x86_64-linux]`
  - Gem name and version: `google-cloud-bigquery`, `1.38.0`

#### Steps to reproduce

  1. Run our Sequel migrations in a loop:
    - drop dataset
    - migrate

#### Code example

It tends to fail at one of the `ALTER TABLE` migration steps.

sequel-bigquery is effectively executing `Google::Cloud::Bigquery::Dataset#query` with, e.g.:

```ruby
ALTER TABLE `der_dimensions` ADD COLUMN `provider_agent_id` string(28), ADD COLUMN `provider_authority_id` string(28), ADD COLUMN `site_id` string(28), ADD COLUMN `external_reference` string, ADD COLUMN `maximum_stored_energy_wh` integer, ADD COLUMN `maximum_continuous_real_load_w` integer, ADD COLUMN `minimum_continuous_real_load_w` integer
```

#### Full backtrace

```sh
Google::Cloud::NotFoundError: notFound: Not found: Dataset greensync-dex-dev:local_dev_ZimbiX
/home/brendan/.rbenv/versions/2.7.4/lib/ruby/gems/2.7.0/gems/google-cloud-bigquery-1.37.0/lib/google/cloud/bigquery/service.rb:572:in `rescue in execute'
/home/brendan/.rbenv/versions/2.7.4/lib/ruby/gems/2.7.0/gems/google-cloud-bigquery-1.37.0/lib/google/cloud/bigquery/service.rb:565:in `execute'
/home/brendan/.rbenv/versions/2.7.4/lib/ruby/gems/2.7.0/gems/google-cloud-bigquery-1.37.0/lib/google/cloud/bigquery/service.rb:224:in `list_tabledata'
/home/brendan/.rbenv/versions/2.7.4/lib/ruby/gems/2.7.0/gems/google-cloud-bigquery-1.37.0/lib/google/cloud/bigquery/query_job.rb:735:in `data'
/home/brendan/.rbenv/versions/2.7.4/lib/ruby/gems/2.7.0/gems/google-cloud-bigquery-1.37.0/lib/google/cloud/bigquery/dataset.rb:1709:in `query'
/home/brendan/.rbenv/versions/2.7.4/lib/ruby/gems/2.7.0/gems/sequel-bigquery-0.6.0/lib/sequel-bigquery.rb:85:in `block (2 levels) in execute'
[...]
```

**Comment by quartzmo** [comment]
@ZimbiX Thank you so much for finding and reporting this bug!

> yet the `#ddl?` method did not categorise an `ALTER TABLE` statement as DDL!

YIKES! The fix in the associated PR makes perfect sense, but to be on the safe side I'll first try to reproduce the error myself before reviewing the PR. Again, thank you!

> We have no idea why service.list_tabledata fails inconsistently.

Do you think this problem needs a separate issue? If so and you can provide steps to reproduce and a code example, feel free to open one.

**Comment by quartzmo** [comment]
@shollyman 

I did some exploratory testing and noticed that [`QueryJob#ddl_operation_performed`](https://github.com/googleapis/google-cloud-ruby/blob/main/google-cloud-bigquery/lib/google/cloud/bigquery/query_job.rb#L325-L343) is `nil` for an `ALTER TABLE` operation:

```rb
    create_job = dataset.query_job "CREATE TABLE #{table_id} (x INT64)"
    create_job.wait_until_done!
    _(create_job.statement_type).must_equal "CREATE_TABLE"
    _(create_job.ddl_operation_performed).must_equal "CREATE"

    alter_job = dataset.query_job "ALTER TABLE #{table_id} ADD COLUMN y STRING"
    alter_job.wait_until_done!
    _(alter_job.statement_type).must_equal "ALTER_TABLE"
    _(alter_job.ddl_operation_performed).must_equal "ALTER" # Fails! Value is nil.
```

Similarly, our inline docs description for [`QueryJob#ddl_operation_performed`](https://github.com/googleapis/google-cloud-ruby/blob/main/google-cloud-bigquery/lib/google/cloud/bigquery/query_job.rb#L325-L343) doesn't mention `ALTER` as a possible value, which seems strange. I noticed that the current API description for [JobStatistics2](https://cloud.google.com/bigquery/docs/reference/rest/v2/Job#jobstatistics2) (below) has a shorter, more general description that does not mention possible values.

>  The DDL operation performed, possibly dependent on the pre-existence of the DDL target.

**Comment by shollyman** [comment]
Spent time looking at this.  Seems like we're not propagating `ddlOperationPerformed` from the metadata layer as expected here.  I've opened internal issue 212472444 to address this.  My expectation is that `ALTER` should be the value returned.
