### ISSUE TITLE
Missing symbol called crashes 

### ISSUE THREAD

**Issue by ViaJables** [googleapis/google-cloud-ruby#16157]
Hi,

Any call I make on a snapshot results in a dyld[38102]: missing symbol called. It happens on both a get and a set.

  - OS: macOS Monterey (command line tools installed)
  - Ruby version: 2.6.6
  -  google-cloud-firestore (2.6.5)
        concurrent-ruby (~> 1.0)
        google-cloud-core (~> 1.5)
        google-cloud-firestore-v1 (~> 0.0)
        rbtree (~> 0.4.2)

Example:
ref = firestore.collection "lists"

ref.doc("test1").set(
    {
      title:       "test",
      list_type:   "test",
      profile_image:    "test",
      profile_bio:    "test",
      begins: "test",
      ends: "test"
    })
    
    Result:
    Crashes ruby with:
    dyld[38102]: missing symbol called

**Comment by dazuma** [comment]
There's a known issue in the latest version (1.42.0) of the grpc gem. Update your Gemfile to use grpc 1.41.1 instead of 1.42.0. grpc should be releasing a patched version of 1.42 shortly. See https://github.com/grpc/grpc/issues/28271.

**Comment by makuchaku** [comment]
I had the same issue on Mac, ruby (ruby 2.6.3p62 (2019-04-16 revision 67580) [universal.x86_64-darwin20])
I downgraded grpc gem to 1.41.1 and it worked.

Thanks

**Comment by ViaJables** [comment]
Thank you!

**Comment by dazuma** [comment]
If you have any other question, feel free to reopen.

**Comment by yuichiu416** [comment]
A note to that, if you installed a later version of grpc, such as 1.42.0, you may want to uninstall it then bundle install again.
