### ISSUE TITLE
Adding instrumentation via interceptors in Google PubSub

### ISSUE THREAD

**Issue by Linuus** [googleapis/google-cloud-ruby#16184]
I'm trying to add some instrumentation for PubSub calls and it looks like the way to go about this is to use GRPC interceptors.

I can see that the Ruby grpc gem has some experimental support for interceptors: https://github.com/grpc/grpc/blob/fd3bd70939fb4239639fbd26143ec416366e4157/src/ruby/lib/grpc/generic/interceptors.rb

Is it possible to add interceptors for the PubSub grpc client somehow?

**Comment by quartzmo** [comment]
@Linuus Here is the [proposal for Ruby interceptors](https://github.com/grpc/proposal/blob/master/L11-ruby-interceptors.md), which shows usage examples. Based on the client example, it appears that a modification would be needed in google-cloud-pubsub to allow interceptors to be set on the generated client stub. I'll try to test it out today and post what I learn.

**Comment by Linuus** [comment]
> @Linuus Here is the [proposal for Ruby interceptors](https://github.com/grpc/proposal/blob/master/L11-ruby-interceptors.md), which shows usage examples. Based on the client example, it appears that a modification would be needed in google-cloud-pubsub to allow interceptors to be set on the generated client stub. I'll try to test it out today and post what I learn.

Ah nice, I hadn't seen that proposal 👍  But yeah, I guess the other libraries need to be updated to be able to pass in the interceptors somehow. Looking forward hearing about what you learn :) Thanks!

**Comment by quartzmo** [comment]
Good news: I successfully added the proposal example to the library and am seeing the logging output:

```
quartzmo@Chriss-iMac google-cloud-pubsub % bundle exec rake acceptance
Run options: --seed 57187

# Running:

I, [2021-12-14T13:06:00.722750 #11131]  INFO -- : [MyPublisherInterceptor] Sending unary request/response to /google.pubsub.v1.Publisher/GetTopic
I, [2021-12-14T13:06:00.997903 #11131]  INFO -- : [MyPublisherInterceptor] Sending unary request/response to /google.pubsub.v1.Publisher/CreateTopic
I, [2021-12-14T13:06:03.735120 #11131]  INFO -- : [MySubscriberInterceptor] Sending unary request/response to /google.pubsub.v1.Subscriber/GetSubscription
I, [2021-12-14T13:06:04.054440 #11131]  INFO -- : [MySubscriberInterceptor] Sending unary request/response to /google.pubsub.v1.Subscriber/CreateSubscription
I, [2021-12-14T13:06:07.243746 #11131]  INFO -- : [MySubscriberInterceptor] Sending unary request/response to /google.pubsub.v1.Subscriber/Pull
I, [2021-12-14T13:06:09.906272 #11131]  INFO -- : [MyPublisherInterceptor] Sending unary request/response to /google.pubsub.v1.Publisher/Publish
I, [2021-12-14T13:06:10.897548 #11131]  INFO -- : [MySubscriberInterceptor] Sending bidi streamer to /google.pubsub.v1.Subscriber/StreamingPull
I, [2021-12-14T13:06:10.898036 #11131]  INFO -- : [MySubscriberInterceptor] Sending bidi streamer to /google.pubsub.v1.Subscriber/StreamingPull
I, [2021-12-14T13:06:12.898116 #11131]  INFO -- : [MySubscriberInterceptor] Sending unary request/response to /google.pubsub.v1.Subscriber/Acknowledge
I, [2021-12-14T13:06:13.902864 #11131]  INFO -- : [MySubscriberInterceptor] Sending unary request/response to /google.pubsub.v1.Subscriber/DeleteSubscription
.

Finished in 14.883877s, 0.0672 runs/s, 0.4703 assertions/s.

1 runs, 7 assertions, 0 failures, 0 errors, 0 skips
Cleaning up pubsub topics after tests.
I, [2021-12-14T13:06:15.596816 #11131]  INFO -- : [MyPublisherInterceptor] Sending unary request/response to /google.pubsub.v1.Publisher/ListTopics
I, [2021-12-14T13:06:15.803028 #11131]  INFO -- : [MyPublisherInterceptor] Sending unary request/response to /google.pubsub.v1.Publisher/ListTopicSubscriptions
I, [2021-12-14T13:06:16.211527 #11131]  INFO -- : [MyPublisherInterceptor] Sending unary request/response to /google.pubsub.v1.Publisher/DeleteTopic
Cleaning up pubsub schemas after tests.
Cleaning up pubsub snapshots after tests.
I, [2021-12-14T13:06:18.449892 #11131]  INFO -- : [MySubscriberInterceptor] Sending unary request/response to /google.pubsub.v1.Subscriber/ListSnapshots
```

Bad news: The handwritten client library does not expose the `interceptors` property that is present in the underlying generated client config. It will need to be modified to accept this field, similar to how `endpoint` is set on the underlying client config.

Meanwhile, feel free to try out the demo I just pushed to a branch on my fork. I opened a draft PR to show the change: #16186

**Comment by Linuus** [comment]
Oh, very nice 👍 

> Bad news: The handwritten client library does not expose the interceptors property that is present in the underlying generated client config. It will need to be modified to accept this field, similar to how endpoint is set on the underlying client config.

How bad is that? :) I mean, how easy would it be to get that change done?
You are talking about adding something similar to [this](https://github.com/googleapis/google-cloud-ruby/blob/main/google-cloud-pubsub/lib/google-cloud-pubsub.rb#L139), right?

**Comment by quartzmo** [comment]
Not very bad. It is technically easy. There is a release freeze in place for the holidays, however.

**Comment by quartzmo** [comment]
> You are talking about adding something similar to this, right?

Yes, exactly. There is also an `endpoint` param on the client factory method(s) [here](https://github.com/googleapis/google-cloud-ruby/blob/main/google-cloud-pubsub/lib/google/cloud/pubsub.rb#L80) that is passed down. If you follow both to `service.rb`, you will see how one or the other `endpoint` value is set on the underlying client configs, for example [here](https://github.com/googleapis/google-cloud-ruby/blob/main/google-cloud-pubsub/lib/google/cloud/pubsub/service.rb#L55) for the subscriber client. 

I should have time to get this done at the end of this week.

**Comment by quartzmo** [comment]
@Linuus Can you try an alternate method of configuring interceptors that should work without requiring a new version of this library? 

You simply configure them using class methods of the underlying generated [gapic](https://github.com/googleapis/gapic-generator-ruby) client library [`google-cloud-pubsub-v1`](https://github.com/googleapis/google-cloud-ruby/tree/main/google-cloud-pubsub-v1) (see `Google::Cloud::PubSub::V1::Publisher::Client` and `Google::Cloud::PubSub::V1::Subscriber::Client`, below.) You must do this configuration before instantiating the client from this library. The configuration will be scoped to all instances of the underlying clients. Please let me know if this works for you:

```ruby
require "grpc"
require "google/cloud/pubsub"

class MyInterceptor < GRPC::ClientInterceptor
  attr_reader :name

  def initialize name
    @name = name
  end

  def request_response(request:, call:, method:, metadata:)
    logger.info "[#{name}] Sending unary request/response to #{method}"
    metadata['request_id'] = generate_request_id
    yield
  end

  def client_streamer(requests:, call:, method:, metadata:)
    logger.info "[#{name}] Sending client streamer to #{method}"
    metadata['request_id'] = generate_request_id
    yield
  end

  def server_streamer(request:, call:, method:, metadata:)
    logger.info "[#{name}] Sending server streamer to #{method}"
    metadata['request_id'] = generate_request_id
    yield
  end

  def bidi_streamer(requests:, call:, method:, metadata:)
    logger.info "[#{name}] Sending bidi streamer to #{method}"
    metadata['request_id'] = generate_request_id
    yield
  end

  private

  def logger
    @logger ||= Logger.new(STDOUT)
  end

  def generate_request_id
    SecureRandom.uuid
  end
end

Google::Cloud::PubSub::V1::Publisher::Client.configure do |config|
  config.interceptors = [MyInterceptor.new("MyPublisherInterceptor")]
end

Google::Cloud::PubSub::V1::Subscriber::Client.configure do |config|
  config.interceptors = [MyInterceptor.new("MySubscriberInterceptor")]
end

pubsub = Google::Cloud::PubSub.new
```

**Comment by Linuus** [comment]
Oh, interesting! I missed those config methods when looking around. I will try it out and report back. Thanks!

**Comment by Linuus** [comment]
Seems to work great so far! I guess we can close this one :)

Thank you very much for the help!
