### ISSUE TITLE
spanner: Failure in acceptance test case

### ISSUE THREAD

**Issue by bajajneha27** [googleapis/google-cloud-ruby#16643]
There's an acceptance test case [failure](https://source.cloud.google.com/results/invocations/4917ec18-77a6-4ea4-9292-22f01dda5b2c/log) in spanner for listing backup operations.

**Comment by bajajneha27** [comment]
The issue is caused by a backend change where you need to specify the type along with the field name now. i.e. the code at [#L63](https://github.com/googleapis/google-cloud-ruby/blob/main/google-cloud-spanner/acceptance/spanner/backup_operations_test.rb#L63) will now become 
```
filter = "metadata.@type=type.googleapis.com/google.spanner.admin.database.v1.CreateBackupMetadata AND metadata.database:#{database_id}"

```

The issue is being tracked here b/211362831 and we already have a fix for it but it'll take another 3-4 weeks for it to release. Do we want to fix it for now or wait for the fix?

**Comment by NivedhaSenthil** [comment]
@bajajneha27 do we know if the fix is available now ?

**Comment by bajajneha27** [comment]
Looks like it. The bug is fixed and the previous spanner acceptance tests are passing.

**Comment by dazuma** [comment]
Confirmed the referenced error is no longer happening. Closing.
