### ISSUE TITLE
google protobuf Denial of Service (DoS) prompt.

### ISSUE THREAD

**Issue by digitaldrk** [googleapis/google-cloud-ruby#17226]
Hello! Thank you for taking the time to look at this issue. I've searched through issues for 'proto' but did not see anything related.

## Request/Issue
Our security tool has alerted us to a [DOS vulnerability with the google-protobuf gem](https://security.snyk.io/vuln/SNYK-RUBY-GOOGLEPROTOBUF-2331705).

We have ran `gem dependency google-protobuf --reverse-dependencies` and get the following (among other output):
```
 Used by
    gapic-common-0.7.0 (google-protobuf (~> 3.14))
    gapic-common-0.3.4 (google-protobuf (~> 3.12, >= 3.12.2))
    gapic-common-0.2.0 (google-protobuf (~> 3.2))
    google-gax-1.8.1 (google-protobuf (~> 3.9))
    googleapis-common-protos-1.3.12 (google-protobuf (~> 3.14))
    googleapis-common-protos-1.3.11 (google-protobuf (~> 3.14))
    googleapis-common-protos-types-1.3.0 (google-protobuf (~> 3.14))
    googleapis-common-protos-types-1.0.6 (google-protobuf (~> 3.14))
    grpc-1.37.0-universal-darwin (google-protobuf (~> 3.15))
    grpc-google-iam-v1-1.0.0 (google-protobuf (~> 3.14))
    grpc-google-iam-v1-0.6.10 (google-protobuf (~> 3.11))
```

Is this by chance on the team's radar?

## Describe the solution you'd like
It'd be great to get protobuf upgraded to `3.19.2` or higher for the above dependencies.

## Describe alternatives you've considered
I've considered forking, updating those forks and running with that but I wanted to be sure this wasn't a work in progress before taking that on.

**Comment by dazuma** [comment]
The linked vulnerability appears to be specific to the Java implementation of protobuf. The Ruby protobuf implementation is based on the C core and does not include the Java code, so this issue likely does not affect the Ruby libraries.

Furthermore, none of the above usages precludes the new protobuf version (for example, the gapic-common-0.7.0 dependency is `google-protobuf ~> 3.14` which translates to `>= 3.14 and < 4.0`). So even if this issue did affect the Ruby libraries, I don't think there's anything to be done directly.

**Comment by digitaldrk** [comment]
Thank you very much for the response and explanation!
