### ISSUE TITLE
Sample request: setting endpoint on storage client

### ISSUE THREAD

**Issue by WildSunLove** [googleapis/google-cloud-ruby#17587]
We need samples added that describe how to set the endpoint for our storage clients.
Such as setting for localhost/emulator, or private/vpc, or for the soon to be added locational endpoints feature.

Sample tracker & Request:

https://docs.google.com/document/d/1aeL7jgs789s7xg9khTxGzGWkb4k-t6LUk-uqhhs1Vuw/edit#

**Comment by meredithslota** [comment]
Based on the doc, it looks like this was addressed in https://github.com/googleapis/google-cloud-ruby/pull/17680 I'm assuming this is ok to close out, but please let me know if I've understood this incorrectly. Thanks!
