### ISSUE TITLE
Missing tables

### ISSUE THREAD

**Issue by choxi** [googleapis/google-cloud-ruby#17863]
#### Environment details

  - OS: Linux
  - Ruby version: 2.7.4
  - Gem name and version: `google-cloud-bigquery`

#### Steps to reproduce

  1. Calling `project.dataset.tables` with the Ruby client returns 0 tables
  2. cURL request to the REST API also returns 0 tables
  2. Querying `INFORMATION_SCHEMA` directly returns 4 tables

Unfortunately I'm not really sure what conditions with our BigQuery configuration are causing this discrepancy and I can't reproduce it with a fresh BigQuery instance. 

#### Code Example

The Ruby client returns 0 tables:
```ruby
bigquery = Google::Cloud::Bigquery.new(credentials)
dataset = bigquery.projects.first.datasets.first
dataset.tables.count # => 0
```

So does the REST API:
```
curl --location --request GET 'https://bigquery.googleapis.com/bigquery/v2/projects/<project-id>/datasets/<dataset-id>/tables' \
--header 'Authorization: Bearer <oauth token>'
```

SQL returns 4 tables:
```
SELECT tables.table_schema, tables.table_name, options.option_value as description
FROM #{dataset_id}.INFORMATION_SCHEMA.TABLES as tables
LEFT JOIN #{dataset_id}.INFORMATION_SCHEMA.TABLE_OPTIONS as options
ON tables.table_name = options.table_name AND options.option_name = 'description'
WHERE tables.table_type <> 'VIEW'
```

I couldn't find any information in the REST API docs about why the API returns 0 tables when there are actually more, I'm authenticating as the same user in all instances (fetching the tables via the REST API vs querying INFORMATION_SCHEMA directly). Could you please point me in a direction I could look into or the appropriate place to submit this bug report?

**Comment by shollyman** [comment]
Certainly an unusual behavior, and it's not clear why it's manifesting at first glance.

A couple of followup questions:

* In what location does the dataset exist?
* Any chance these tables were recently deleted (explicitly or via table expiration)?
* For one of the 4 tables/views that's missing from the API list, can you fetch the table/view metadata directly using the ruby library?

**Comment by choxi** [comment]
> In what location does the dataset exist?

`'EU'`

> Any chance these tables were recently deleted (explicitly or via table expiration)?

It looks like none of them have been deleted or have an expiration

> For one of the 4 tables/views that's missing from the API list, can you fetch the table/view metadata directly using the ruby library?

How would I go about that in Ruby? I'm not sure how to get a handle on a table without calling `dataset.tables`. I tried to do it via API request (assuming this is what the Ruby client does):

```
curl --location --request GET 'https://bigquery.googleapis.com/bigquery/v2/projects/<project ID>/datasets/<datasetID>/tables/<missing table ID>' \
--header 'Authorization: Bearer <token>'
```

But I get a `404 Not Found` response.

**Comment by shollyman** [comment]
Following up out of band.

**Comment by choxi** [comment]
After inspecting the `INFORMATION_SCHEMA` further, it looks like there were multiple datasets with the same name and my INFORMATION_SCHEMA query was not fully qualified so it was returning tables for a dataset in a different project. We also had permissions to view table schemas but not dataset schemas on this project which added to some confusion.

I'll close out this ticket now, thanks for your help!
