### ISSUE TITLE
Unable to configure ignore classes

### ISSUE THREAD

**Issue by frenkel** [googleapis/google-cloud-ruby#17902]
#### Environment details

  - OS: Debian Linux based Dockerfile: ruby-2.7
  - Ruby version: 2.7
  - Gem name and version: stackdriver (0.21.1), google-cloud-error_reporting (0.42.2)

#### Steps to reproduce

  1. I'm trying to configure ignore classes for ActiveRecord::RecordNotFound and ActionController::RoutingError.
  2. The following two code examples were put in initializers with different effects, but none did what was expected.

#### Code example

As I'm using Rails I expected the following to work:
```ruby
Rails.application.configure do |config|
  config.google_cloud.error_reporting.ignore_classes = [ActiveRecord::RecordNotFound, ActionController::RoutingError]
end
```
This results in the following error when starting a console or server: `config/initializers/google_cloud.rb:2:in 'block in <main>': undefined method 'google_cloud' for `.

So I tried to configure it without the Rails integration:
```ruby
require 'google/cloud/error_reporting'

Google::Cloud::ErrorReporting.configure do |config|
  config.ignore_classes = [ActiveRecord::RecordNotFound, ActionController::RoutingError]
end
```
This seems to fail silently, the project can be started, but the errors are still showing up and not ignored.

What am I doing wrong?

**Comment by NivedhaSenthil** [comment]
This issue has some context for this https://github.com/googleapis/google-cloud-ruby/issues/2605. I tried replicating this myself but no luck getting the error. Will be really helpful if you can provide a sample project or docker image to replicate the error you are facing.

**Comment by frenkel** [comment]
I'll try to setup a sample project within a week.

**Comment by frenkel** [comment]
When I deploy the following project to my acceptance environment, the error tracking does not get enabled, so it's related to the above errors (configuration seems to take place after the project has already been initialized/started?)

https://github.com/frenkel/sampleproject

**Comment by NivedhaSenthil** [comment]
Sorry for coming back late here, I do not see the sample now in the link. Can you please provide the right link if the issue still persists ?

**Comment by frenkel** [comment]
The issue still persists, but we've given up on fixing it and are marking these invalid errors to be ignored in the interface. Sorry, but I don't want to sink any effort into this anymore.
