### ISSUE TITLE
Fetching an individual project

### ISSUE THREAD

**Issue by choxi** [googleapis/google-cloud-ruby#17914]
**Is your feature request related to a problem? Please describe.**
It looks like there isn't a way to fetch an individual project, i.e. `bigquery.projects.find(project_id)`. We have some accounts that have thousands of bigquery projects so we have to fetch them all to get a handle on the two or three projects we actually need. 

 **Describe the solution you'd like**
As a workaround, we've been doing:

```ruby
project_service = Google::Cloud::Bigquery::Service.new(project_id, bigquery.service.credentials, retries: bigquery.service.retries, timeout: bigquery.service.timeout)
project = Google::Cloud::Bigquery::Project.new(project_service)
```

But this isn't perfect since it doesn't load the actual project or its name, but `project.datasets` will work. It would be nice if there was a public API like `Google::Cloud::Bigquery::Project.find(project_id)` or `bigquery.projects.find(project_id)`

**Comment by dazuma** [comment]
Does

```ruby
Google::Cloud::Bigquery.new(project_id)
```

do what you're looking for? (If not, can you elaborate on what you're looking for that the above doesn't give you?)
