### ISSUE TITLE
Google Cloud Pub/Sub PermissionDenied errors should return clear information

### ISSUE THREAD

**Issue by jpaulgs** [googleapis/google-cloud-ruby#17944]
Thanks for stopping by to let us know something could be better!

I do have a Google Support Account but I can't find Pub/Sub in the product selection! 

Problem:
I have a pre-existing topic and a subscription to this topic
and a service account with the role `roles/pubsub.subscriber` 
When I attempt to run the example https://github.com/googleapis/google-cloud-ruby/tree/main/google-cloud-pubsub#example 
Then I get the following error:
> Exception: GRPC::PermissionDenied 7:User not authorized to perform this action.. debug_error_string:{"created":"@1648687386.976710200","description":"Error received from peer ipv4:142.250.70.234:443","file":"src/core/lib/surface/call.cc","file_line":1063,"grpc_message":"User not authorized to perform this action.","grpc_status":7}

This error is also returned when I use the role `roles/pubsub.viewer`

However I do not get this error when I assign the service account `roles/pubsub.editor`

I definitely do not want to assign `roles/pubsub.editor` to this account but I cannot figure out the magical set of permissions required.

 **Describe the solution you'd like**
The errors returned by AWS services in my experience indicate that a permissions issue has occurred __AND__ indicate what permission is required.

**Comment by pradn** [comment]
[The sample](https://github.com/googleapis/google-cloud-ruby/tree/main/google-cloud-pubsub#example) both publishes and subscribes. For that, the service account needs to be granted two roles: roles/pubsub.publisher and roles/pubsub.subscriber.

**Comment by pradn** [comment]
You do make a good point that permissions errors need to be clearer. I don't know if this is an explicit choice we've made, or if it's a security concern or just an oversight.

**Comment by russellkgw** [comment]
Hi, I am experiencing a similar issue, but even with the full `Pub/Sub Admin` role on the service account, the error: `Exception: GRPC::PermissionDenied 7:User not authorized to perform this action` is still being raised.

This is an unexpected result.

I am attempting to create a subscription on an existing topic:

``` ruby
subscription = topic.subscribe(subscription_name,
  push_config: push_config,
  message_ordering: true,
  retain_acked: true,
  filter: type_filter(filter_string),
  dead_letter_topic: dead_letter_topic,
  dead_letter_max_delivery_attempts: 100)

subscription.policy { |p| p.add "roles/pubsub.subscriber", gcp_pubsub_service_account }
```

Any insight as to why this would be the case even though the PubSub Admin role has been granted?

**Comment by NivedhaSenthil** [comment]
@jpaulgs Hope the details provided on roles helped. Closing this issue for now, please feel free to reopen if you still feel its important to update the error message. We can discuss further on the options.
