### ISSUE TITLE
Using BigQuery on AWS: Got "RuntimeError: Could not load the default credentials" even if I have configured BIGQUERY_CREDENTIALS

### ISSUE THREAD

**Issue by sg-xdl** [googleapis/google-cloud-ruby#18070]
**Context**
I am using `BIGQUERY_CREDENTIALS` and `BIGQUERY_PROJECT` ENV following the gem authentication [guide](https://googleapis.dev/ruby/google-cloud-bigquery/latest/file.AUTHENTICATION.html). I'd like to avoid configuring file on a server, so I am directly setting  `BIGQUERY_CREDENTIALS` with the content of my service account json file content.

This works fine in my local as well as QA environment which is hosted on Heroku. But when I deploy the code to a staging environment hosted on AWS, I got authentication error as follows:

```
RuntimeError: Could not load the default credentials. Browse to https://developers.google.com/accounts/docs/application-default-credentials for more information
```

I read the link in the error message but it's unclear to me how I can configure the authentication directly with the service account json instead of having to set `GOOGLE_APPLICATION_CREDENTIALS` ENV which points to the credential file path.

I don't understand why the behaviors are different between Heroku and AWS. My understanding is Heroku underneath is on AWS. And according to the gem authentication guide, setting `BIGQUERY_CREDENTIALS` as the json content should work.

I also tried other ENV such as `GOOGLE_CLOUD_KEYFILE_JSON`, or `GOOGLE_CLOUD_CREDENTIALS` but nothing works.

**Comment by NivedhaSenthil** [comment]
This looks more of an issue with how the env variable is configured with AWS environment rather than a issue with authentication in Bigquery gem. Closing it for now, please feel free to reopen if you are still facing the issue.
