### ISSUE TITLE
Fix the failing nightly tests on github actions and kokoro

### ISSUE THREAD

**Issue by NivedhaSenthil** [googleapis/google-cloud-ruby#18289]
There are quite a few test which had been failing in the nightly tests that are run in github actions and kokoro. Fix them so that the test runs becomes actionable providing valuable feedback.

Sample failed runs:
Github actions - https://github.com/googleapis/google-cloud-ruby/actions/runs/2344227366
Kokoro - https://fusion2.corp.google.com/invocations?q=cloud-devrel%2Fclient-libraries%2Fgoogle-cloud-ruby%2Fnightly%2F

**Comment by dazuma** [comment]
GitHub Actions nightlies are now passing, and we have a mechanism in place to open issues automatically if we get new failures. I'm currently going through the current Kokoro failures and opening separate issues for each. (They are each prefixed with `[Test failures]`.) Accordingly, I'm going to close this issue.
