### ISSUE TITLE
Error in storage acceptance tests

### ISSUE THREAD

**Issue by bajajneha27** [googleapis/google-cloud-ruby#18342]
There is an acceptance test case [failure](https://github.com/googleapis/google-cloud-ruby/pull/18332)  in google-cloud-storage.

**Comment by SandeepTuniki** [comment]
Logging the failing test case for when we come back to fix it:

```
  1) Failure:
Storage::buckets::storage#test_0001_gets pages of buckets [/workspace/google-cloud-storage/acceptance/storage/buckets_test.rb:35]:
Expected: "multi-region"
  Actual: "region"

```

**Comment by SandeepTuniki** [comment]
This issue is fixed. The problem turned out be a residual bucket from a previous build that didn't get deleted after the test run. I deleted the bucket manually from the project and the error disappeared.
