### ISSUE TITLE
feature request: Pub/Sub Lite support

### ISSUE THREAD

**Issue by ahayworth** [googleapis/google-cloud-ruby#18355]
**Is your feature request related to a problem? Please describe.**

Problem: we cannot use the Ruby client library to publish to Pub/Sub Lite topics, and we would like to do so.

 **Describe the solution you'd like**

Solution: The Ruby client should have support for Pub/Sub Lite.

 **Describe alternatives you've considered**

Alternative 1: Use regular Pub/Sub - possible, but the pricing considerations make it an unsuitable option.
Alternative 2: Use a different language. This is the current plan, but it's not because we've evaluated Ruby on the merits and chosen another language - it's simply the only realistic option.

 **Additional context**

Using other languages at a ruby shop introduces unnecessary friction and frustration. 😢 Of course, that is not Google's problem, but it is additional context as to why I am making the feature request.

**Comment by shivgautam** [comment]
Thank you @ahayworth for the request. We'll triage this request and update here.

**Comment by ahayworth** [comment]
Thank you @kamalaboulhosn ❤️
