### ISSUE TITLE
[PubSub] Async options ignored when `skip_lookup` is true

### ISSUE THREAD

**Issue by matthieuprat** [googleapis/google-cloud-ruby#18428]
When retrieving a topic by name with `skip_lookup: true`, async options are not passed to the underlying async publisher.

#### Environment details

  - Ruby version: 3.1.2
  - Gem name and version: google-cloud-pubsub@2.10.0

#### Steps to reproduce

Setup:

```rb
pubsub = Google::Cloud::PubSub.new(project_id: "dummy-project")
pubsub.create_topic("dummy-topic")
```

❌ When `skip_lookup` is true, async options are _not_ passed as expected:

```rb
topic = pubsub.topic("dummy-topic", skip_lookup: true, async: { interval: 1 })
topic.publish_async("{}") # initialize the async publisher
topic.async_publisher.instance_variable_get("@interval")
#=> 0.01
```

✅ When `skip_lookup` is false, async options are passed as expected:

```rb
topic = pubsub.topic("dummy-topic", async: { interval: 1 })
topic.publish_async("{}") # initialize the async publisher
topic.async_publisher.instance_variable_get("@interval")
#=> 1
```

#### Additional details

It seems the cause of the issue is that unlike the [`Topic.from_grpc`](https://github.com/googleapis/google-cloud-ruby/blob/fe4de7b49ce74d561b291a9ad0802fb025625842/google-cloud-pubsub/lib/google/cloud/pubsub/topic.rb#L1073) method, the [`Topic.from_name`](https://github.com/googleapis/google-cloud-ruby/blob/fe4de7b49ce74d561b291a9ad0802fb025625842/google-cloud-pubsub/lib/google/cloud/pubsub/topic.rb#L1077-L1084) method doesn't set the topic's `@async_opts` instance variable.

**Comment by NivedhaSenthil** [comment]
Thanks for reporting 👍
