### ISSUE TITLE
[Storage] Add invocation-id to x-goog-api-client header for Ruby storage

### ISSUE THREAD

**Issue by danielduhh** [googleapis/google-cloud-ruby#18827]
Tracking ticket to add a unique invocation-id to the x-goog-api-client header for all Storage API requests.
See [nodejs  example](https://github.com/googleapis/nodejs-storage/pull/1920)

**Comment by bajajneha27** [comment]
This was fixed in [PR#19161](https://github.com/googleapis/google-cloud-ruby/pull/19161)
