### ISSUE TITLE
Google::Cloud::Firestore::DocumentSnapshot#fields returns data in wrong format

### ISSUE THREAD

**Issue by psyho** [googleapis/google-cloud-ruby#18832]
#### Environment details

  - OS: Ubuntu 20.04 LTS
  - Ruby version: 3.1.2p20
  - Gem name and version: google-cloud-firestore (2.7.0)

#### Steps to reproduce

1. Get a document from firestore run the fields method on it.
2. The result is a hash, that is a JSON representation of the underlying GRPC structure, instead of simple ("raw") values.

#### Code example

```ruby
firestore = Google::Cloud::Firestore.new
doc = firestore.doc("test/test")
doc.set(foo: 123)
doc.get.fields
# => {"foo"=>{:null_value=>:NULL_VALUE, :boolean_value=>false, :integer_value=>123, :double_value=>0.0, :timestamp_value=>nil, :string_value=>"", :bytes_value=>"", :reference_value=>"", :geo_point_value=>nil, :array_value=>nil, :map_value=>nil}}
```

**Comment by alexpapworth** [comment]
Seeing this issue as well. Firestore is not returning *which* value is stored against the structure.

Equally, `doc.get["foo"]` no longer works, possibly due to the same underlying changes from the 2.7.0 release.

Rolling back to `2.6.6` fixes these issues.

**Comment by github0013** [comment]
I also encountered this issue.

I was working on v2.7.0 last night, and it was as expected.

```rb
document.data[:createdAt] # => Time object
``` 

Then only after like 10 hours later, when I woke up and tried the same code, and now it returns

```rb
document.data[:createdAt] # => Hash object

# a hash like this big
# {"createdAt"=>
#   {:null_value=>:NULL_VALUE,
#    :boolean_value=>false,
#    :integer_value=>0,
#    :double_value=>0.0,
#    :timestamp_value=>{:seconds=>1653610742, :nanos=>259896000},
#    :string_value=>"",
#    :bytes_value=>"",
#    :reference_value=>"",
#    :geo_point_value=>nil,
#    :array_value=>nil,
#    :map_value=>nil}
``` 

I kinda think the values are changed on their server side?? not the gems?

The only major difference I see between 2.6.6 and 2.7.0 is [Updated minimum Ruby version to 2.6](https://github.com/googleapis/google-cloud-ruby/blob/9a49c80ea46d63e49c9681342141f95cb7bf3eab/google-cloud-firestore/CHANGELOG.md#features), so I guess we can safely downgrade it back to 2.6.6 for now?

**Comment by psyho** [comment]
@github0013 yes, locking the gem version to `2.6.6` is the workaround.

**Comment by dazuma** [comment]
I'll get 2.7.1 out shortly with the fix. Thanks for tracking this down.
