### ISSUE TITLE
[Test failures] google-cloud-storage acceptance and samples tests (flaky)

### ISSUE THREAD

**Issue by bajajneha27** [googleapis/google-cloud-ruby#18854]
There are failures in [acceptance tests](https://source.cloud.google.com/results/invocations/c33b2960-c46c-43d0-9860-665276c589fd/targets) and [samples tests](https://source.cloud.google.com/results/invocations/0fcb8909-7a01-46b6-bec3-baeaae4f650f/log). This issue is created to track those.

**Comment by dazuma** [comment]
These failures are not consistent.

On the 2022-08-04 nightly run, the samples test passed, although there was a lot of noise in the output, a bunch of error logs that probably should be suppressed, possibly because they were from cleanup?

However, in some earlier runs there were errors (that were possibly resolved in the 1.38.0 release?) They included:

in the 2022-07-30 and 2022-07-31 runs:
```
1) Error:
Buckets Snippets::storage_create_bucket_dual_region#test_0001_creates dual region bucket:
ArgumentError: unknown keyword: :custom_placement_config
    /[h/.gem/gems/google-cloud-storage-1.37.0/lib/google/cloud/storage/project.rb:366](https://cs.corp.google.com/piper///depot/google3/h/.gem/gems/google-cloud-storage-1.37.0/lib/google/cloud/storage/project.rb?l=366):in `create_bucket'
    /[workspace/google-cloud-storage/samples/storage_create_bucket_dual_region.rb:31](https://cs.corp.google.com/piper///depot/google3/workspace/google-cloud-storage/samples/storage_create_bucket_dual_region.rb?l=31):in `storage_create_bucket_dual_region'
    /[workspace/google-cloud-storage/samples/acceptance/buckets_test.rb:124](https://cs.corp.google.com/piper///depot/google3/workspace/google-cloud-storage/samples/acceptance/buckets_test.rb?l=124):in `block (5 levels) in <top (required)>'
```

in the 2022-08-01 run:
```
1) Error:
Files Snippets#test_0012_download_file_requester_pays:
Google::Cloud::PermissionDeniedError: forbidden: kokoro@helical-zone-771.iam.gserviceaccount.com does not have storage.objects.create access to the Google Cloud Storage bucket.
    /[h/.gem/gems/google-cloud-storage-1.38.0/lib/google/cloud/storage/service.rb:772](https://cs.corp.google.com/piper///depot/google3/h/.gem/gems/google-cloud-storage-1.38.0/lib/google/cloud/storage/service.rb?l=772):in `rescue in execute'
    /[h/.gem/gems/google-cloud-storage-1.38.0/lib/google/cloud/storage/service.rb:769](https://cs.corp.google.com/piper///depot/google3/h/.gem/gems/google-cloud-storage-1.38.0/lib/google/cloud/storage/service.rb?l=769):in `execute'
    /[h/.gem/gems/google-cloud-storage-1.38.0/lib/google/cloud/storage/service.rb:359](https://cs.corp.google.com/piper///depot/google3/h/.gem/gems/google-cloud-storage-1.38.0/lib/google/cloud/storage/service.rb?l=359):in `insert_file'
    /[h/.gem/gems/google-cloud-storage-1.38.0/lib/google/cloud/storage/bucket.rb:1587](https://cs.corp.google.com/piper///depot/google3/h/.gem/gems/google-cloud-storage-1.38.0/lib/google/cloud/storage/bucket.rb?l=1587):in `create_file'
    /[workspace/google-cloud-storage/samples/acceptance/files_test.rb:223](https://cs.corp.google.com/piper///depot/google3/workspace/google-cloud-storage/samples/acceptance/files_test.rb?l=223):in `block (2 levels) in <top (required)>'
```

The acceptance test runs are similarly inconsistent.

Failure in the 2022-08-04 nightly run:
```
1) Failure:
Google::Cloud::Storage::Bucket::uniform_bucket_level_access::storage#test_0001_sets uniform_bucket_level_access true and is unable to modify file ACL rules [/[workspace/google-cloud-storage/acceptance/storage/bucket_uniform_bucket_level_access_test.rb:50](https://cs.corp.google.com/piper///depot/google3/workspace/google-cloud-storage/acceptance/storage/bucket_uniform_bucket_level_access_test.rb?l=50)]:
Google::Cloud::PermissionDeniedError expected but nothing was raised.
```

Failures in the 2022-08-03 nightly run:
```
1) Failure:
Google::Cloud::Storage::File::storage#test_0026_should copy an existing file, with updates [/[workspace/google-cloud-storage/acceptance/storage/file_test.rb:622](https://cs.corp.google.com/piper///depot/google3/workspace/google-cloud-storage/acceptance/storage/file_test.rb?l=622)]:
Expected ["allUsers"] to not include "allUsers".

  2) Failure:
Google::Cloud::Storage::File::storage#test_0027_should copy an existing file, with force_copy_metadata set to true [/[workspace/google-cloud-storage/acceptance/storage/file_test.rb:660](https://cs.corp.google.com/piper///depot/google3/workspace/google-cloud-storage/acceptance/storage/file_test.rb?l=660)]:
Expected ["allUsers"] to not include "allUsers".

  3) Failure:
Google::Cloud::Storage::File::storage#test_0025_should copy an existing file [/[workspace/google-cloud-storage/acceptance/storage/file_test.rb:590](https://cs.corp.google.com/piper///depot/google3/workspace/google-cloud-storage/acceptance/storage/file_test.rb?l=590)]:
Expected ["allUsers"] to not include "allUsers".
```

However, the 2022-08-02 and 2022-08-01 nightlies seem to have passed (albeit with a bunch of log noise).

**Comment by bajajneha27** [comment]
We've also been seeing some rate limit errors:

```E, [2022-09-06T22:48:10.181076 #37957] ERROR -- : Error - #<Google::Apis::RateLimitError: rateLimitExceeded: The rate of change requests to the object gcloud-ruby-acceptance-2022-09-06t17-18-00z-c3111d54/PredefinedTest.png exceeds the rate limit. Please reduce the rate of create, update, and delete requests. status_code: 429 header: #<HTTP::Message::Headers:0x00007fb632973070 @http_version="1.1", @body_size=0, @chunked=false, @request_method="PATCH", @request_uri=#<Addressable::URI:0x4394 URI:https://storage.googleapis.com/storage/v1/b/gcloud-ruby-acceptance-2022-09-06t17-18-00z-c3111d54/o/PredefinedTest.png?predefinedAcl=projectPrivate>, @request_query=nil, @request_absolute_uri=nil, @status_code=429, @reason_phrase="Too Many Requests", @body_type=nil, @body_charset=nil, @body_date=nil, @body_encoding=#<Encoding:UTF-8>, @is_request=false, @header_item=[["X-GUploader-UploadID", "ADPycduSRkZd1hEDffg-7-QSsOPYMR7QVHUyg_N_iFv8W4mP5j6miLesp6osVOFwITtZn_sgDtCQJ8lZ6pj12PX_BqYUDg"], ["Content-Type", "application/json; charset=UTF-8"], ["Date", "Tue, 06 Sep 2022 17:18:10 GMT"], ["Vary", "Origin"], ["Vary", "X-Origin"], ["Cache-Control", "no-cache, no-store, max-age=0, must-revalidate"], ["Expires", "Mon, 01 Jan 1990 00:00:00 GMT"], ["Pragma", "no-cache"], ["Content-Length", "589"], ["Server", "UploadServer"], ["Alt-Svc", "h3=\":443\"; ma=2592000,h3-29=\":443\"; ma=2592000,h3-Q050=\":443\"; ma=2592000,h3-Q046=\":443\"; ma=2592000,h3-Q043=\":443\"; ma=2592000,quic=\":443\"; ma=2592000; v=\"46,43\""]], @dumped=false> body: "{\n  \"error\": {\n    \"code\": 429,\n    \"message\": \"The rate of change requests to the object gcloud-ruby-acceptance-2022-09-06t17-18-00z-c3111d54/PredefinedTest.png exceeds the rate limit. Please reduce the rate of create, update, and delete requests.\",\n    \"errors\": [\n      {\n        \"message\": \"The rate of change requests to the object gcloud-ruby-acceptance-2022-09-06t17-18-00z-c3111d54/PredefinedTest.png exceeds the rate limit. Please reduce the rate of create, update, and delete requests.\",\n        \"domain\": \"usageLimits\",\n        \"reason\": \"rateLimitExceeded\"\n      }\n    ]\n  }\n}\n">```

**Comment by dazuma** [comment]
I haven't seen any recent failures. It looks like previous remediation seems to have addressed most of this. I'm going to close this to reduce noise. Will open new targeted issues if we see additional failures in the future.
