### ISSUE TITLE
Unit test case failure in google cloud trace

### ISSUE THREAD

**Issue by bajajneha27** [googleapis/google-cloud-ruby#18863]
Unit tests for certain ruby version i.e. [2.6](https://github.com/googleapis/google-cloud-ruby/runs/7445031023?check_suite_focus=true) and [2.7](https://github.com/googleapis/google-cloud-ruby/runs/7445031117?check_suite_focus=true) have been failing for a while now. This issue is created to track the same.

**Comment by dazuma** [comment]
This should have been fixed by #18865
