### ISSUE TITLE
Out of date SDK auth documentation 

### ISSUE THREAD

**Issue by asabourin** [googleapis/google-cloud-ruby#18901]
Hi team, just a heads up the documentation at https://googleapis.dev/ruby/google-cloud-storage/latest/file.AUTHENTICATION.html (and equivalent for other products) seems to be out of date regarding authentication via Cloud SDK credentials. We found thanks to the Python SDK docs at https://googleapis.dev/python/google-api-core/latest/auth.html that one needs to run `gcloud auth application-default login` instead of `gcloud auth login` to make local SDK credentials work.

This took us a little while to figure out so hopefully that can be updated easily for everyone else benefit!

Cheers,
Antoine

**Comment by inspire22** [comment]
The Google::Cloud::Translate docs are also horribly out of date.  Looks like the new format (I also had to go read the python docs) is:

> 
> translate = Google::Cloud::Translate.translation_service
> res = translate.translate_text parent:'projects/project_number/locations/global', contents: ['hello, world'], target_language_code: 'la'
> result_text = res.translations.first.translated_text
> from = res.translations.firstdetected_language_code
> 

Kinda frustrating this keeps changing and it's so hard to find any up to date info.

**Comment by NivedhaSenthil** [comment]
@inspire22 Please open a new issue with details for the documentation issue you are facing, so that it can be tracked. Feel free to create a PR with updates. 

Closing this issue as the auth documentation is updated now.
