### ISSUE TITLE
storage: add support for Autoclass

### ISSUE THREAD

**Issue by cojenco** [googleapis/google-cloud-ruby#19091]
Autoclass feature at the bucket level, allows for the automatic selection of the best storage class based on object metadata and access patterns. Currently, Autoclass supports  **new buckets** only - a bucket can be enabled for Autoclass only at creation, once disabled it cannot be enabled again

**System tests are only required in languages with code changes other than documentation:**
- Autoclass can be enabled via Bucket `Create`
- Autoclass can be disabled via Bucket `Patch` and `Update` operations
- Bucket `Get` operations should return the correct state of Autoclass on the bucket which includes the enabled boolean field and toggleTime timestamp field

**Samples demonstrating getting and setting Autoclass feature for a bucket:**
- region tags: `storage_get_autoclass` and `storage_set_autoclass`

canonical samples (internal): [go/gcs-autoclass-canonical-sample](http://go/gcs-autoclass-canonical-sample)
details and coordination (internal): [go/gcs-dpe-autoclass](http://go/gcs-dpe-autoclass)
python-storage example: https://github.com/googleapis/python-storage/pull/791

Please wait for approval from myself before merging/releasing so we can coordinate around release dates.

**Comment by NivedhaSenthil** [comment]
Support for autoclass is released https://github.com/googleapis/google-cloud-ruby/pull/19327
