### ISSUE TITLE
REGAPIC error breaking change

### ISSUE THREAD

**Issue by dazuma** [googleapis/google-cloud-ruby#19219]
The latest generator change for REGAPIC changed the error handling from

```ruby
rescue ::Faraday::Error => e
  gapic_error = ::Gapic::Rest::Error.wrap_faraday_error e
  raise ::Google::Cloud::Error.from_error(gapic_error)
```

to

```ruby
rescue ::Faraday::Error => e
  begin
    raise ::Gapic::Rest::Error.wrap_faraday_error e
  rescue ::Gapic::Rest::Error => gapic_err
    raise ::Google::Cloud::Error.from_error gapic_err.cause
  end
```

The old code passes a `Gapic::Rest::Error` to `Google::Cloud::Error.from_error`. The new code passes a `Faraday::Error` (i.e. the _cause_ of the `Gapic::Rest::Error`) to `Google::Cloud::Error.from_error`. It looks like `Google::Cloud::Error.from_error` knows how to deal with the former but not the latter.

I suspect that the new code is supposed to include

```ruby
raise ::Google::Cloud::Error.from_error gapic_err
```

rather than

```ruby
raise ::Google::Cloud::Error.from_error gapic_err.cause
```

@viacheslav-rostovtsev Can you confirm?

ref: #19218
See https://source.cloud.google.com/results/invocations/c68dbbae-7661-4068-9017-0b9e553230d5/log for the failing test.

**Comment by viacheslav-rostovtsev** [comment]
Yes, this was a mistake.
https://github.com/googleapis/gapic-generator-ruby/pull/829 to fix

**Comment by dazuma** [comment]
Fixed.
