### ISSUE TITLE
Google::Cloud::InvalidArgumentError on `create_file`

### ISSUE THREAD

**Issue by kevinrobayna** [googleapis/google-cloud-ruby#19246]
#### Environment details

  - OS: `Linux`
  - Ruby version: `3.1.0`
  - Gem name and version: `google-cloud-storage-1.43.0`

#### Steps to reproduce

Upgrade to 1.43.0
Create GCS file in bucket
Fail.

Revert to 1.42.0
Create GCS file in bucket
Works

#### Full backtrace

```ruby
Invalid request
/srv/app/vendor/bundle/ruby/3.1.0/gems/google-cloud-storage-1.43.0/lib/google/cloud/storage/service.rb:913:in `rescue in execute'
/srv/app/vendor/bundle/ruby/3.1.0/gems/google-cloud-storage-1.43.0/lib/google/cloud/storage/service.rb:910:in `execute'
/srv/app/vendor/bundle/ruby/3.1.0/gems/google-cloud-storage-1.43.0/lib/google/cloud/storage/service.rb:412:in `insert_file'
/srv/app/vendor/bundle/ruby/3.1.0/gems/google-cloud-storage-1.43.0/lib/google/cloud/storage/bucket.rb:1587:in `create_file'
/srv/app/vendor/bundle/ruby/3.1.0/Our Service
```

**Comment by asabourin** [comment]
Same happening here, reverting to 1.42 resolves it.

**Comment by bajajneha27** [comment]
Hi @kevinrobayna 
I just tried creating a file with version `1.43.0` and it worked. Can you please post the code snippet here so that I can reproduce it?

**Comment by timflapper** [comment]
It appears to be happening when uploading a StringIO with an empty string e.g.: `StringIO.new("")`.

**Comment by bajajneha27** [comment]
The fix is now released. Please let me know if you still face any issues.
