### ISSUE TITLE
Cannot create 0-length files in Google Cloud Storage

### ISSUE THREAD

**Issue by davebenson** [googleapis/google-cloud-ruby#19280]
```require 'google/cloud/storage'
storage = Google::Cloud::Storage.new
bucket = storage.bucket(bucket_name)
bucket.create_file (StringIO.new ''), 'empty'
```

With appropriate log levels:
`D, [2022-10-11T08:21:16.380611 #92504] DEBUG -- : Error - #<Google::Apis::ClientError: Invalid request status_code: 400 header: #<HTTP::Message::Headers:0x00007fda2754ae08 @http_version="1.1", @body_size=0, @chunked=false, @request_method="PUT", @request_uri=#<Addressable::URI:0x13934 URI:https://storage.googleapis.com/upload/storage/v1/b/...>, @request_query=nil, @request_absolute_uri=nil, @status_code=400, @reason_phrase="Bad Request", @body_type=nil, @body_charset=nil, @body_date=nil, @body_encoding=#<Encoding:UTF-8>, @is_request=false, @header_item=[["Content-Type", "text/plain; charset=utf-8"], ["X-GUploader-UploadID", "..."], ["Content-Length", "37"], ["Date", "Tue, 11 Oct 2022 15:21:16 GMT"], ["Server", "UploadServer"], ["Alt-Svc", "h3=\":443\"; ma=2592000,h3-29=\":443\"; ma=2592000,h3-Q050=\":443\"; ma=2592000,h3-Q046=\":443\"; ma=2592000,h3-Q043=\":443\"; ma=2592000,quic=\":443\"; ma=2592000; v=\"46,43\""]], @dumped=false> body: "Failed to parse Content-Range header.">`

**Comment by NivedhaSenthil** [comment]
Thanks for bringing this up, this is already fixed as part of https://github.com/googleapis/google-cloud-ruby/issues/19246. We can expect a release soon.

**Comment by bajajneha27** [comment]
The fix is now released. Please let me know if you still face any issues.
