### ISSUE TITLE
RuntimeError: can't add a new key into hash during iteration

### ISSUE THREAD

**Issue by stevenbarragan** [googleapis/google-cloud-ruby#1987]
```RuntimeError: can't add a new key into hash during iteration```
I added the gem into one on my rails app and I'm getting this error consistently.

I'm using ruby 2.5.0 and I'm running puma with a couple of workers and threads I'm not sure if it's related, I can share more details if need it.

```
…cloud-logging-1.5.0/lib/google/cloud/logging/logger.rb:  456:in `add_request_info'
…d-logging-1.5.0/lib/google/cloud/logging/middleware.rb:   88:in `call'
…/new_relic/agent/instrumentation/middleware_tracing.rb:   92:in `call'
…pack-5.1.4/lib/action_dispatch/middleware/remote_ip.rb:   79:in `call'
…/new_relic/agent/instrumentation/middleware_tracing.rb:   92:in `call'
…ack-5.1.4/lib/action_dispatch/middleware/request_id.rb:   25:in `call'
…/new_relic/agent/instrumentation/middleware_tracing.rb:   92:in `call'
…cal/bundle/gems/rack-2.0.3/lib/rack/method_override.rb:   22:in `call'
…/new_relic/agent/instrumentation/middleware_tracing.rb:   92:in `call'
  /usr/local/bundle/gems/rack-2.0.3/lib/rack/runtime.rb:   22:in `call'
…/new_relic/agent/instrumentation/middleware_tracing.rb:   92:in `call'
…loud-trace-0.31.0/lib/google/cloud/trace/middleware.rb:  156:in `block in call'
…ms/google-cloud-trace-0.31.0/lib/google/cloud/trace.rb:  408:in `block in in_span'
…ud-trace-0.31.0/lib/google/cloud/trace/trace_record.rb:  232:in `in_span'
…ms/google-cloud-trace-0.31.0/lib/google/cloud/trace.rb:  405:in `in_span'
…loud-trace-0.31.0/lib/google/cloud/trace/middleware.rb:  154:in `call'
…/new_relic/agent/instrumentation/middleware_tracing.rb:   92:in `call'
…ctive_support/cache/strategy/local_cache_middleware.rb:   27:in `call'
…/new_relic/agent/instrumentation/middleware_tracing.rb:   92:in `call'
…npack-5.1.4/lib/action_dispatch/middleware/executor.rb:   12:in `call'
…/new_relic/agent/instrumentation/middleware_tracing.rb:   92:in `call'
 /usr/local/bundle/gems/rack-2.0.3/lib/rack/sendfile.rb:  111:in `call'
…/new_relic/agent/instrumentation/middleware_tracing.rb:   92:in `call'
/usr/local/bundle/gems/rack-cors-1.0.1/lib/rack/cors.rb:   93:in `call'
…/new_relic/agent/instrumentation/middleware_tracing.rb:   92:in `call'
…r/local/bundle/gems/railties-5.1.4/lib/rails/engine.rb:  522:in `call'
…/new_relic/agent/instrumentation/middleware_tracing.rb:   92:in `call'
…ocal/bundle/gems/puma-3.10.0/lib/puma/configuration.rb:  225:in `call'
  /usr/local/bundle/gems/puma-3.10.0/lib/puma/server.rb:  605:in `handle_request'
  /usr/local/bundle/gems/puma-3.10.0/lib/puma/server.rb:  437:in `process_client'
  /usr/local/bundle/gems/puma-3.10.0/lib/puma/server.rb:  301:in `block in run'
…/local/bundle/gems/puma-3.10.0/lib/puma/thread_pool.rb:  120:in `block in spawn_thread'
```

**Comment by blowmage** [comment]
@dazuma Are you aware of anything that iterates `request_info`?

**Comment by dazuma** [comment]
`Logger#trace_ids` does iterate `@request_info` but I don't think we have anything that calls it directly.

**Comment by stevenbarragan** [comment]
I am not, maybe newrelic? I can see it in the logs

**Comment by blowmage** [comment]
I was looking for a call to `trace_ids` as well but didn’t see it in the backtrace. Can you share more information?

**Comment by blowmage** [comment]
Do we need to consider making Logger threadsafe?

**Comment by blowmage** [comment]
@stevenbarragan Can you add the following code to your application and see if this helps?

```ruby
require "google/cloud/logging/logger"

class Google::Cloud::Logging::Logger
  def trace_ids
    @request_info.dup.inject({}) { |r, (k, v)| r[k] = v.trace_id }
  end
end
```

**Comment by stevenbarragan** [comment]
Isn't threadsafe? if it's not that's probably it.

**Comment by stevenbarragan** [comment]
@blowmage I added your code to a rails initializer, it didn't work.

**Comment by blowmage** [comment]
Okay, that means this isn’t because of `trace_ids` then. We need more information to diagnose the cause.

**Comment by blowmage** [comment]
@stevenbarragan We need the additional detail you offered in order to resolve this.

**Comment by blowmage** [comment]
@stevenbarragan Can you give us that additional detail you offered?

**Comment by blowmage** [comment]
We are blocked until we can get more information about this.

**Comment by Goku-San** [comment]
RuntimeError: can't add a new key into hash during iteration

Hello, I hope you solve this bug quickly, I am very new to rails and I had this bug yesterday and today and when I restart the server the error is gone,

I am on windows 7 x64, rails 5.2, ruby 2.3.3-p222, puma 3.11.4

Sorry I can't give more information I don't know how to...
All I can see from the server log is when visiting root page(not rails stubbed welcome page) for the 1st time, it makes several requests GET 127.0.0.1 and loads everything(duplicates views, assets), the request time is different for each, and the error occurs

**Comment by blowmage** [comment]
@stevenbarragan I have not been able to reproduce this behavior, but we made some changes to the most recent version of the gem that may help. Can you upgrade to `google-cloud-logging` version 1.5.5 and let us know if you still experience this behavior?

**Comment by blowmage** [comment]
Closing as we haven't heard back. If anyone runs into this please open a new issue and reference this issue.
