### ISSUE TITLE
ArgumentError (wrong number of arguments (given 1, expected 0)) When try to add data to firestore

### ISSUE THREAD

**Issue by ricophie03** [googleapis/google-cloud-ruby#20132]
Thanks for stopping by to let us know something could be better!

**PLEASE READ**: If you have a support contract with Google, please create an issue in the [support console](https://cloud.google.com/support/) instead of filing on GitHub. This will ensure a timely response.

Please run down the following list and make sure you've tried the usual "quick fixes":

  - Search the issues already opened: https://github.com/googleapis/google-cloud-ruby/issues
  - Search StackOverflow: http://stackoverflow.com/questions/tagged/google-cloud-platform+ruby

If you are still having issues, please be sure to include as much information as possible:

#### Environment details

  - OS: Windows
  - Ruby version: ruby 3.1.3p185 (2022-11-24 revision 1a6b16756e) [x64-mingw-ucrt]
  - Gem name and version: ruby version 3.3.26

#### Steps to reproduce

  1. installing this package and  'require "google/cloud/firestore"
  2. copying the example code for add data from documentation (https://cloud.google.com/ruby/docs/reference/google-cloud-firestore/latest/index.html)
  3. run the api for add data

#### Code example

```ruby
firestore = Google::Cloud::Firestore.new(
                    project_id: <my project id>,
                    credentials: <path file to json credential>
                )

                # Get a collection reference
                messages_col = firestore.col "messages"

                # Get a document reference with data
                random_ref = messages_col.add({ 
                    message_text: params[:message_text],
                    username: params[:username],
                    time: params[:time]
                })
```

#### Full backtrace

```sh
app/controllers/api/v1/chats_controller.rb:29:in `create'
Started POST "/api/v1/chats" for 127.0.0.1 at 2023-02-07 01:24:24 +0800
Processing by Api::V1::ChatsController#create as HTML
  Parameters: {"message_text"=>"sfasdaf", "username"=>"sadf", "time"=>"2023-02-06T17:24:24.449Z", "chat"=>{"message_text"=>"sfasdaf", "username"=>"sadf", 
"time"=>"2023-02-06T17:24:24.449Z"}}
Completed 500 Internal Server Error in 130ms (Allocations: 2394)


  
ArgumentError (wrong number of arguments (given 1, expected 0)):
```

Making sure to follow these steps will guarantee the quickest resolution possible.

Thanks!

**Comment by SandeepTuniki** [comment]
Hi @ricophie03, thanks for raising this issue. Can you help us narrow down the issue further by locating the exact line of code it is failing at?

I see this line of log:
```
app/controllers/api/v1/chats_controller.rb:29:in `create'
```

I assume your code snippets is part of a larger controller code. So which line of code is in line 29?

**Comment by rajnish-jarvis** [comment]
Same issue I am facing when ruby upgraded from 2 to 3 while creating a new file  **wrong number of arguments (given 4, expected 2..3)**

require 'google/cloud/storage'

storage = Google::Cloud::Storage.new(project_id: ENV['G_CLOUD_PROJECT_ID'], credentials: ENV['G_CLOUD_KEYFILE'])

bucket = storage.bucket ENV['G_CLOUD_BUCKET_PUBLIC_DOCUMENTS']

file = params[;file]

upload_file = bucket.create_file data, "path/to/gzipped.txt",content_encoding: "gzip"

**Comment by SandeepTuniki** [comment]
Hi @ricophie03, I'm closing this issue due to a lack of response. If you still need assistance with this, please re-open & provide the info requested in my previous comment.
