### ISSUE TITLE
Storage downloads only half of a CSV and then fails the integrity check

### ISSUE THREAD

**Issue by gildo** [googleapis/google-cloud-ruby#20389]
Hi, I'm trying to download a file that was previously uploaded using this library.
The file is a small CSV (around 1.5k). My application is trying to download that file in the /tmp directory but the operation fails with:

```
/usr/local/bundle/gems/google-cloud-storage-1.44.0/lib/google/cloud/storage/file/verifier.rb:34:in `verify_md5!': The downloaded file failed MD5 verification. (Google::Cloud::Storage::FileVerificationError)
```

Looking at the downloaded file in the directory I see only half of the CSV like it was cut in half keeping the second half.

I've manually removed the file from the storage and manually re-uploaded it through the Console interface but the problem persists (the only thing that changes is where the "cut" is made).

Thank you for your time,
Gildo

---

#### Environment details

  - OS: ruby:3.1.3-alpine3.17
  - Ruby version: 3.1.3
  - Gem name and version: 1.44.0

#### Steps to reproduce

  1. Upload a CSV to Google Cloud Storage
  2. Download through the library
  
#### Code example

I'm using this small utility method to download the file, 

```ruby
      storage = Google::Cloud::Storage.new
      @bucket = storage.bucket ENV["GOOGLE_CLOUD_BUCKET_NAME"]

      def download(remote_path, local_path)
        file = bucket.file(remote_path)
        file.blank? ? false : file.download(local_path)
      end
```

#### Full backtrace

```sh
/usr/local/bundle/gems/google-cloud-storage-1.44.0/lib/google/cloud/storage/file/verifier.rb:34:in `verify_md5!': The downloaded file failed MD5 verification. (Google::Cloud::Storage::FileVerificationError)
```

**Comment by bajajneha27** [comment]
Hi @gildo 

I just tried downloading a CSV and it worked fine for me. I didn't receive any error and the full file was downloaded. 
Can you confirm that you face this issue with all the CSV files? Or only a particular one?

**Comment by gildo** [comment]
Hi, @bajajneha27, thanks for your response.

Apparently, the problem was using `Pathname` instead of `String` for the `local_path` parameter.
I don't know if this problem can be traceable to `google-cloud-ruby` or an internal problem since I'm expecting that using the wrong class would lead to an error instead of a partially downloaded resource.

**Comment by meredithslota** [comment]
Reclassifying as a bug based on the above comment. :)
