### ISSUE TITLE
Secret manager: access_secret_version received: 8:to-be-sent initial metadata size exceeds peer limit.

### ISSUE THREAD

**Issue by khanhnd0408** [googleapis/google-cloud-ruby#20391]
I attempted to obtain GCP credentials from the GCP secret manager, but it failed.

#### Environment details

  - OS: linux/amd64 (docker image ruby:2.6.7)
  - Ruby version: 2.6.7
  - Gem name and version: google-cloud-secret_manager 1.1.0

#### Steps to reproduce

  1. Run script.

#### Code example

```ruby
require 'google/cloud/secret_manager'

...

def get_key(project_id, secret_key_name):
  client = Google::Cloud::SecretManager.secret_manager_service
  key_path = client.secret_version_path(
    project: project_id,
    secret: secret_key_name,
    secret_version: 'latest'
  )
  response = client.access_secret_version name: key_path 
  secret = response.payload.data
```

#### Full backtrace

```sh
8:to-be-sent initial metadata size exceeds peer limit
/usr/local/bundle/gems/google-cloud-secret_manager-v1-0.2.1/lib/google/cloud/secret_manager/v1/secret_manager_service/client.rb:777:in `rescue in access_secret_version'
/usr/local/bundle/gems/google-cloud-secret_manager-v1-0.2.1/lib/google/cloud/secret_manager/v1/secret_manager_service/client.rb:743:in `access_secret_version'
/app/lib/utils/secret_key.rb:20:in `get_key'
```

The script above works normally in staging environment, but it failed in production environment. Is there any way to fix it?

It looks like this script is running an older version of Secret Manager instead of 1.1.0; is this right?

Thanks!

**Comment by NivedhaSenthil** [comment]
Yes this seems to be using older version of the gem, can you please try updating to use the latest version ?
Also if you can provide some details on your staging and production environment it will help us find if there is any potential difference that is causing this issue.

**Comment by SandeepTuniki** [comment]
I'm closing this issue due to lack of response. If the issue persists, feel free to re-open it by providing more info.
