### ISSUE TITLE
Blank docs pages for lower-level API links

### ISSUE THREAD

**Issue by quartzmo** [googleapis/google-cloud-ruby#2072]
Blank pages:

- [ ] [Google::Cloud::Datastore::V1](https://googlecloudplatform.github.io/google-cloud-ruby/#/docs/google-cloud/v0.52.0/google/cloud/datastore/v1)
- [ ] [Google::Cloud::ErrorReporting::V1beta1](https://googlecloudplatform.github.io/google-cloud-ruby/#/docs/google-cloud/v0.52.0/google/cloud/errorreporting/v1beta1)
- [ ] [Google::Cloud::Logging::V2](https://googlecloudplatform.github.io/google-cloud-ruby/#/docs/google-cloud/v0.52.0/google/cloud/logging/v2) 
- [ ] [Google::Cloud::Monitoring::V3](https://googlecloudplatform.github.io/google-cloud-ruby/#/docs/google-cloud/v0.52.0/google/cloud/monitoring/v3)
- [ ] [Google::Cloud::Pubsub::V1](https://googlecloudplatform.github.io/google-cloud-ruby/#/docs/google-cloud/v0.52.0/google/cloud/pubsub/v1)
- [ ] [Google::Cloud::Spanner::V1](https://googlecloudplatform.github.io/google-cloud-ruby/#/docs/google-cloud/v0.52.0/google/cloud/spanner/v1)
- [ ] [Google::Cloud::Trace::V1](https://googlecloudplatform.github.io/google-cloud-ruby/#/docs/google-cloud/v0.52.0/google/cloud/trace/v1)

Broken links:

- [ ] [DLP V2beta1](https://googlecloudplatform.github.io/google-cloud-ruby/#/docs/google-cloud/v0.52.0/google/cloud/dlp/v2beta1)

Incorrect content (lower-level content - see #2075):

- [ ] [Google::Cloud::Datastore](https://googlecloudplatform.github.io/google-cloud-ruby/#/docs/google-cloud/v0.52.0/google/cloud/datastore)
- [ ] [Google::Cloud::Debugger](https://googlecloudplatform.github.io/google-cloud-ruby/#/docs/google-cloud-debugger/v0.32.0/google/cloud/debugger)
- [ ] [Google::Cloud::Firestore](https://googlecloudplatform.github.io/google-cloud-ruby/#/docs/google-cloud/v0.52.0/google/cloud/firestore)
- [ ] [Google::Cloud::Logging](https://googlecloudplatform.github.io/google-cloud-ruby/#/docs/google-cloud/v0.52.0/google/cloud/logging)
- [ ] [Google::Cloud::Pubsub](https://googlecloudplatform.github.io/google-cloud-ruby/#/docs/google-cloud/v0.52.0/google/cloud/pubsub)
- [ ] [Google::Cloud::Spanner](https://googlecloudplatform.github.io/google-cloud-ruby/#/docs/google-cloud/v0.52.0/google/cloud/spanner)
- [x] Google::Cloud::Speech (Do not fix: will be changed to GAPIC-only.)
- [x] Google::Cloud::Vision (Do not fix: will be changed to GAPIC-only.)

Issue from discussion on PR #2065.

Blank page when clicking on the version [(V3) on the left hand menu bar](https://googlecloudplatform.github.io/google-cloud-ruby/#/docs/google-cloud-monitoring/v0.28.0/google/cloud/monitoring/v3) for both `google-cloud` and `google-cloud-monitoring` docs.

If you run `rake jsondoc` and look at the resulting `V3` output:

```sh
$ cat jsondoc/google/monitoring/v3.json 
{"id":"google/monitoring/v3","name":"V3","title":["Google","Monitoring","V3"],"description":"","source":"google-cloud-monitoring/lib/google/cloud/monitoring/v3/doc/google/monitoring/v3/alert.rb#L17","resources":[],"examples":[],"methods":[]}
```

You can see it's from `/google/monitoring/v3/alert.rb`, which has no docs for `V3`. So it seems to be a problem we've seen before in which the correct output is shadowed by blank output. **However, I've looked at all the declarations of `module V3` in `google-cloud-monitoring/lib/google/cloud/monitoring/v3/doc` and I can't find any with docs comments.**

**Comment by blowmage** [comment]
I believe this can be closed now that JSONDOC has been retired and we are on YARD produced documentation.
