### ISSUE TITLE
Spanner Guide page shows V1 docs, while V1 page is blank 

### ISSUE THREAD

**Issue by quartzmo** [googleapis/google-cloud-ruby#2075]
The [Spanner docs landing page](https://googlecloudplatform.github.io/google-cloud-ruby/#/docs/google-cloud-spanner/v1.4.0/google/cloud/spanner) shows the content from [google/cloud/spanner/v1/doc/overview.rb](https://github.com/GoogleCloudPlatform/google-cloud-ruby/blob/master/google-cloud-spanner/lib/google/cloud/spanner/v1/doc/overview.rb#L17-L49) rather than the desired "guide" content from [google/cloud/spanner.rb](https://github.com/GoogleCloudPlatform/google-cloud-ruby/blob/master/google-cloud-spanner/lib/google/cloud/spanner.rb#L23-L345).

In addition, the [V1 landing page](https://googlecloudplatform.github.io/google-cloud-ruby/#/docs/google-cloud-spanner/v1.4.0/google/cloud/spanner/v1) is blank, when it should have the content from [google/cloud/spanner/v1/doc/overview.rb](https://github.com/GoogleCloudPlatform/google-cloud-ruby/blob/master/google-cloud-spanner/lib/google/cloud/spanner/v1/doc/overview.rb#L17-L49).

Moving the docs comment in `google/cloud/spanner/v1/doc/overview.rb` from the `Spanner` module to the `V1` module fixes both issues.

I'm guessing this might be related to #2072.

@jbolinger @landrito Should I open a PR that manually makes this fix?

**Comment by jbolinger** [comment]
@quartzmo yes, that's a perfectly fine workaround. 

If doing the same move for monitoring will also give us a quick fix to #2072 let's just do them both manually I'll open a new issue for fixing the underlying bug in the generator and link it here.

**Comment by quartzmo** [comment]
This appears to be a duplicate of #1859, which documents this issue for other packages in addition to Spanner.

**Comment by quartzmo** [comment]
Closing this issue, since it is a duplicate of #2072, which is more comprehensive and breaks down the two issues (incorrect content and blank content) by package.
