### ISSUE TITLE
better cloud monitoring example (current is wrong for v3)

### ISSUE THREAD

**Issue by kryali** [googleapis/google-cloud-ruby#2080]
The documentation around publishing metrics via ruby is sparse and inaccurate at best. Can we get a refresher here? Something along the lines of publishing a time series via ruby would be very helpful here. 

java example is great here: https://cloud.google.com/monitoring/docs/reference/libraries#client-libraries-usage-java

This is the document I'm referring to: https://github.com/GoogleCloudPlatform/google-cloud-ruby/blob/master/google-cloud-monitoring/README.md

At the very least, the require line should be updated to the latest 
```
require "google/cloud/monitoring/v3"
```

**Comment by kryali** [comment]
maybe a suggestion

```ruby
class MetricClient
  @@service_client = Google::Cloud::Monitoring::V3::MetricServiceClient.new

  # @metric_type e.g "sidekiq/enqueued_count"
  def self.gauge(metric_type, value, labels = {})
    metric = Google::Api::Metric.new
    metric.type = "custom.googleapis.com/#{metric_type}"
    metric.labels["instance_id"] = dyno_name
    metric.labels["environment"] = Rails.env.to_s

    time_series = Google::Monitoring::V3::TimeSeries.new(metric: metric, resource: monitored_resource, metric_kind: :GAUGE)
    timestamp = Google::Protobuf::Timestamp.new(seconds: Time.now.utc.to_i)
    time_interval = Google::Monitoring::V3::TimeInterval.new(end_time: timestamp)
    typed_value = Google::Monitoring::V3::TypedValue.new(int64_value: value)
    time_series.points << Google::Monitoring::V3::Point.new(interval: time_interval, value: typed_value)

    @@service_client.create_time_series(project_name, [time_series])
  end

  def self.dyno_name
    @@dyno_name ||= ENV['PS'] || ENV['DYNO'] || (defined?(Rails::Console) ? "console" : "unknown")
  end

  private
  def self.project_name
    @@project_name ||= @@service_client.class.project_path(PROJECT_ID)
  end

  def self.monitored_resource
    @@monitored_resource ||= Google::Api::MonitoredResource.new(type: "global")
    @@monitored_resource.labels["project_id"] = PROJECT_ID
    @@monitored_resource
  end
end
```

**Comment by blowmage** [comment]
@jbolinger These code examples all come from the generated files. What is the process for updating the code examples on these files?

/cc @frankyn

**Comment by jbolinger** [comment]
@blowmage I think it's fine to override the generated example with a better example provided that it's reasonably short and standalone (i.e. no Rails references, etc.). Complex examples probably shouldn't live in the `README` since we have other places to put them. 

Process wise, we should just have someone like @frankyn or a member of his team review any samples and decide where to put them before updating.

This particular example is great (thanks @kryali) but it's probably not a good fit for the `README`. We should definitely update https://cloud.google.com/monitoring/docs/reference/libraries with a Ruby example though. All the other languages have one. I asked Frank to take a look.

**Comment by frankyn** [comment]
@jbolinger I was under the impression that during a client library generation samples were also generated in the client library documentation. Is that no longer the case?

**Comment by frankyn** [comment]
A sample for monitoring/docs/reference/libraries: I can help write a quickstart sample for that page specifically during Q3. I'm out of bandwidth this quarter.

**Comment by quartzmo** [comment]
@dazuma I self-assigned this to comply with SLO, but I also labeled it `good first issue`, for Graham or anyone else.

**Comment by quartzmo** [comment]
The deliverables for GoogleCloudPlatform/ruby-docs-samples#359, or the Python examples that it links, may be useful here.

**Comment by blowmage** [comment]
@quartzmo FWIW, I think this issue should be closed in favor of GoogleCloudPlatform/ruby-docs-samples#359.

**Comment by quartzmo** [comment]
OK, I will close on the assumption that the deliverables for GoogleCloudPlatform/ruby-docs-samples#359 will be published at  https://cloud.google.com/monitoring/docs/reference/libraries. If this is incorrect, please reopen.
