### ISSUE TITLE
Consider moving AsyncWriter classes to use concurrent-ruby

### ISSUE THREAD

**Issue by dazuma** [googleapis/google-cloud-ruby#2084]
Currently `Google::Cloud::Logging::AsyncWriter`, `Google::Cloud::ErrorReporting::AsyncErrorReporter`, `Google::Cloud::Trace::AsyncReporter`, and `Google::Cloud::Debugger::Agent` are all based on a custom actor-like class `Stackdriver::Core::AsyncActor`. We might consider changing this to use tools in the concurrent-ruby gem. (An example where this has been done is https://github.com/census-ecosystem/opencensus-ruby-exporter-stackdriver/blob/master/lib/opencensus/trace/exporters/stackdriver.rb). Note that combining batches would still need to be implemented separately. We should investigate how feasible and desirable this is.

**Comment by blowmage** [comment]
I've started working on this, and I think one of the biggest improvements we can make is to add buffering to these classes that are currently using `Stackdriver::Core::AsyncActor`. I think we will see a large improvement in performance by buffereing items into larger batches that can trigger API calls by either the age of the buffer, number of items in the buffer, or byte size of the buffer.

**Comment by blowmage** [comment]
Here is the status for this change:

- [x] Google::Cloud::Logging::AsyncWriter
- [x] Google::Cloud::ErrorReporting::AsyncErrorReporter
- [x] Google::Cloud::Trace::AsyncReporter
- [ ] Google::Cloud::Debugger::Agent
- [x] Google::Cloud::Debugger::Transmitter

All have been converted to use concurrent except for Debugger's Agent.

**Comment by fhinkel** [comment]
Greetings, we're closing this. Looks like the issue got resolved. Please let us know if the issue needs to be reopened.
