### ISSUE TITLE
Invalid request header x-goog-request-params 

### ISSUE THREAD

**Issue by diptanshumittal** [googleapis/google-cloud-ruby#20926]
`x-goog-request-params` request header is assigned invalid value. Results in failure of presubmit acceptance tests.

**Comment by diptanshumittal** [comment]
`x-goog-request-params` is assigned `parent=projects/{project_id}/databases/{dataabse_id}` instead of  `projects={project_id}&databases={dataabse_id}`

**Comment by viacheslav-rostovtsev** [comment]
What RPC are you calling? Can you provide more details.

**Comment by diptanshumittal** [comment]
> What RPC are you calling? Can you provide more details.

Using the Commit RPC - https://github.com/googleapis/google-cloud-ruby/blob/main/google-cloud-firestore-v1/lib/google/cloud/firestore/v1/firestore/client.rb#L927
But the issue is not releated this specific RPC. Might be releated to this - https://github.com/googleapis/gapic-generator-ruby/blob/main/gapic-generator/templates/default/service/client/method/def/_routing_params.erb#L34
