### ISSUE TITLE
[Feature request] Support Stackdriver Profiler

### ISSUE THREAD

**Issue by premist** [googleapis/google-cloud-ruby#2116]
Currently [Stackdriver Profiler](https://cloud.google.com/profiler/docs/) only supports Go, Java, and Node.js, and it'll be nice if Ruby is also supported.

There were many cases where I had to ad-hoc debug OOMs and unintended high CPU usage, and Stackdriver Profiler can greatly increase application performance visibility alongside other Stackdriver tools like Trace. It can make debug much easier on the GCP console instead of debugging inside production machine manually.

**Comment by dazuma** [comment]
Hi. Yes, this is on our radar. Stay tuned.

**Comment by suprememoocow** [comment]
Any news on this? We've recently rolled our [continuous profiling for our Go services](https://gitlab.com/gitlab-com/gl-infra/scalability/issues/101) using Google Cloud Profiling, and would love to be able to do the same for our Ruby services.

**Comment by bitglue** [comment]
I was able to implement Cloud Profiler support separately: https://github.com/remind101/ruby-cloud-profiler

This was just merged today, and hasn't been tested in production yet. Feedback would be highly appreciated!

After some testing and refinement, it would be nice to get this incorporated into the Google libraries and officially supported.

**Comment by dazuma** [comment]
The plan of record is to lean on [OpenTelemetry profiling](https://github.com/open-telemetry/oteps/blob/main/text/profiles/0212-profiling-vision.md). There is a SIG working on it, and while the specification and SDK are probably still a ways off, we don't think it's prudent to create something bespoke that we'll just have to deprecate later in favor of OpenTelemetry. As noted above, there is a client for the Cloud Profiling service if you just need a way to upload profiling data.
