### ISSUE TITLE
Stackdriver logging not... logging

### ISSUE THREAD

**Issue by CraigCottingham** [googleapis/google-cloud-ruby#2117]
Ruby 2.3.6, Rails 4.2.6, Stackdriver gem 0.15.0

I've followed the directions at https://cloud.google.com/logging/docs/setup/ruby, adding the gem to Gemfile and enabled it in my environment config file with `config.google_cloud.use_logging = true
`. I've also set `GKE_NAMESPACE_ID` to make sure that the namespace is set correctly.

After deploying the container, I can exec a shell in it, run `bundle exec rails c`, and inspect the default logger:

```
irb(main):001:0> pp Rails.logger
#<Google::Cloud::Logging::Logger:0x000055560664bde0
...
```

However, I'm not seeing any logging from the app, only what's written to `stderr`. Even when I explicitly create a log message (like `Rails.logger.error "this is an error message"`) it doesn't show up in the Stackdriver logging viewer. (I expect there to be a delay until it shows up, but I've waited 30+ minutes so far and nothing.)

The confusing (and frustrating) part is that I swear earlier today an explicit log message I created _did_ show up in the logging viewer, but when I reloaded the log view it disappeared, and I haven't been able to recreate it.

**Comment by dazuma** [comment]
Some things to check:
* Make sure the logging API is enabled (go to https://console.cloud.google.com/apis/dashboard to check). It generally gets enabled automatically when you deploy, but best to make sure and rule this out.
* See if there's an exception being thrown by the background thread:

```ruby
Rails.logger.error "this is an error message"
# Wait a few seconds...
pp Rails.logger.writer.last_exception
```

**Comment by CraigCottingham** [comment]
```irb(main):002:0> Rails.logger.error "this is an error message"
this is an error message
=> true
irb(main):003:0> pp Rails.logger.writer.last_exception
nil
=> nil
```

The API is enabled. I have noticed that when I drill down into the Stackdriver Logging API from https://console.cloud.google.com/apis/dashboard it's showing errors on the method `google.logging.v2.LoggingServiceV2.WriteLogEntries`:

* 400: 2 errors
* 403: 8 errors
* 499: 3 errors

I don't see any way to see which one the latest error is. I'm going to try an explicit log again and see which count goes up.

**Comment by CraigCottingham** [comment]
I _think_ the error code corresponding to the explicit log is 499.

**Comment by blowmage** [comment]
I've been looking into this. Some upcoming changes will hopefully make errors easier to deal with.

**Comment by awinograd** [comment]
I'm having a similar issue here. 

```
this is an error message
=> true
irb(main):003:0> pp Rails.logger.writer.last_exception
nil
=> nil
```

These manual logs through rails console do show up in the stackdriver UI, but none of the Rails logs from the server process are showing up

**Comment by blowmage** [comment]
@awinograd We recently updated the gem. What version are you using?

**Comment by awinograd** [comment]
@blowmage, my Gemfile.lock says `1.6.0`

` google-cloud-logging (1.6.0)                                                                                  `

Please let me know if there's any other info I can provide

**Comment by awinograd** [comment]
Logging appears to be working for me now

**Comment by blowmage** [comment]
@CraigCottingham Are you still using google-cloud-logging? We have introduced new error semantics that will make it easier to track errors raised while writing log entries, as well as making the logging client more resilient when errors are raised. With these changes it should be much easier to diagnose the issue you are having.

**Comment by CraigCottingham** [comment]
@blowmage No, I am not.

**Comment by blowmage** [comment]
Okay, I am going to close this specific issue then. If someone reads this issue and has a similar problem, please open a new issue providing all the requested information about your environment.

There have been several changes to the ruby libraries since this issue was first opened. The grpc gem now raises a RuntimeError instead of hanging when being use both pre and post fork. This will help those running into that issue using a forking server like Puma. The Google Cloud gems also added `on_error` callbacks to many objects. This callback can be used log all errors raised when writing log entries asynchronously, which will help us diagnose problems. We have also added buffering and batching to many of the Stackdriver libraries, which should reduce the demand for networking resources.
