### ISSUE TITLE
Enable frozen_string_literal magic comment in all manual packages

### ISSUE THREAD

**Issue by quartzmo** [googleapis/google-cloud-ruby#2138]
Add the comment `# frozen_string_literal: true` to the top (first line) of non-generated source files in all manual packages.

This update should probably wait until after #2130 ("Ruby 2.3 and later") has been merged.

See #2122 for implementation example.

**Comment by blowmage** [comment]
Man, I am really, really nervous about this change. I fear the unintended consequences of how the String objects that are created in the gem are used outside of the gem. For example, consider a user uses a Google Cloud gem to retrieve a record from a data store. Whether it is Datastore or Spanner or Firestore. The user mutates the `title` value on the record, which is a string, and saves the record back to the data store. This change would raise `FrozenError (can't modify frozen String)` for every string mutation in their code.

I think we should continue to profile the performance of the gems, and make safe changes where possible. But I do not think we should make this change.

**Comment by quartzmo** [comment]
I think I have to agree. I'll close this issue now. Please create new issues for performance problems related to strings, and we will address them in a narrower scope.
