### ISSUE TITLE
Don't return query results from BigQuery DML/DDL statements

### ISSUE THREAD

**Issue by nfallen** [googleapis/google-cloud-ruby#2141]
This client library uses tabledata.list to fetch query results, and so even for a DML/DDL statement it fetches rows. Instead, you could use the jobs.getQueryResults API, which correctly does not return any rows for DML/DDL.

**Comment by quartzmo** [comment]
@nfallen Thank you for bringing up this issue. This library originally used `getQueryResults`, but was changed last year to use `tabledata.list` for better performance. I'm not sure if the performance difference still exists, however. I'll see what I can find out.

How many rows are you seeing?

**Comment by quartzmo** [comment]
Thanks @nfallen, this is very helpful!
