### ISSUE TITLE
Api for Google Sheets

### ISSUE THREAD

**Issue by honzasterba** [googleapis/google-cloud-ruby#21558]
**Describe the solution you'd like**
Generate gRPC wrappers for google sheets api V4

 **Describe alternatives you've considered**
google-api-client is outdated and relies on Faraday 1.x

**Comment by dazuma** [comment]
Agreed that a modern gRPC-based client for sheets would be ideal.

In the meantime, I recommend https://rubygems.org/gems/google-apis-sheets_v4 which is much more up to date than https://rubygems.org/gems/google-api-client.

**Comment by dazuma** [comment]
Thanks for opening this request. I created internal request b/305286695 to track this, and will close this issue from GitHub. Unfortunately, this is dependent on the Sheets service team publishing a gRPC endpoint and protobuf descriptor for their service. I'm not sure what their plans are around this, but will notify them that it's being requested.
