### ISSUE TITLE
Owlbot postprocessor fails rubocop checks when using string interpolation

### ISSUE THREAD

**Issue by SandeepTuniki** [googleapis/google-cloud-ruby#21669]
This issue is a corner case discovered while working on #21668.

### Problem
The owlbot postprocessor had below code in `.owlbot.rb` to replace interpolated strings:
```rb
OwlBot.modifier path: paths do |content|
  content&.gsub '#{case}', '#{binding.local_variable_get :case}'
end
```

Due to the above, the generated code is [failing rubocop check](https://github.com/googleapis/google-cloud-ruby/actions/runs/5066984623/jobs/9097457780#step:6:207):
```
lib/google/cloud/support/v2/case_attachment_service/paths.rb:73:1: C: [Correctable] Layout/TrailingEmptyLines: 1 trailing blank lines detected.
```

The postprocessor modifier is somehow adding an extra line at the end of the file due to the above change. I'm not sure how they're related, but the rubocop error goes away when I remove the interpolated code (i.e; `#{...}`). I suspect the source of this error is [this code](https://github.com/googleapis/ruby-common-tools/blob/88d8acfbdce0b26a4b70df22b781720eeb627bc3/owlbot-postprocessor/lib/owlbot/ruby_content.rb#L259-L263).

As a temporary fix, I manually ran the `rubocop -A` command, but this issue will recur when the library gets proto changes. So we need to find a permanent fix for this issue

### Solutions

Potential solutions:

1. Fix the [owlbot posprocessor](https://github.com/googleapis/ruby-common-tools/blob/88d8acfbdce0b26a4b70df22b781720eeb627bc3/owlbot-postprocessor/lib/owlbot/ruby_content.rb#L259-L263) to handle this case.
2. Run `rubocop -A` in the [toys script](https://github.com/googleapis/google-cloud-ruby/blob/c1e320bc049b28426785843f6700885d7789d261/.toys/owlbot.rb#L204) as part of code generation.

Since this issue is a rare corner case, I'm leaning towards solution 2. It requires less effort & is simpler than changing the regex in postprocessor code.

**Comment by dazuma** [comment]
Did some digging here. It looks like it has nothing to do with the preprocessor. The original generated `paths.rb` files in google-cloud-support-v2 (i.e. in the googleapis-gen repo) have the extra newline at the end. Just so happens that we also are preprocessing those files, but that was a red herring. I'm looking into why the generator is producing the extra newline.

**Comment by dazuma** [comment]
Okay, here's what happened.

The generator runs `rubocop -a` internally in order to format generated code. Normally, that should remove these extra trailing newlines. However, for these particular files, due to the use of the Ruby keyword `case` as a variable name, the generator's internal rubocop run fails to parse the file, and thus fails to remove the newline.

For now, since we already have an `.owlbot.rb` script to fix the `case` issue, we should also modify that script to remove the extra newline. I'll open a quick PR.
