### ISSUE TITLE
GAPIC documentation missing types

### ISSUE THREAD

**Issue by blowmage** [googleapis/google-cloud-ruby#2233]
The GAPIC documentation for common protobuf types is missing the following:

* `Google::Protobuf::NullValue`
* `Google::Protobuf::Timestamp`
* `Google::Type::LatLng`

The GAPIC client documentation also documents the `Google::Cloud::Datastore::V1::DatastoreClient#datastore_stub` attribute returning a `Google::Datastore::V1::Datastore::Stub` object, but `Google::Datastore::V1::Datastore::Stub` is not contained in the protobuf documentation. Perhaps the `datastore_stub` should be marked private?

**Comment by blowmage** [comment]
@jbolinger @dazuma Thoughts on this?

**Comment by blowmage** [comment]
I just realized that Datastore doesn't have a `synth.py` file, so the GAPIC generated files may be out of data. it is possible the missing types have already been added to the generated documentation and the GAPIC files are regenerated these types will show up in the documentation.

**Comment by jbolinger** [comment]
I believe at least one of those missing types should be generated. So, it's probably best to regenerate first and then I can add if we find anything is still missing.

I'm not sure about the `stub` part. I suspect using it is rare but I'm not sure if it's a good idea to make it private.

**Comment by blowmage** [comment]
@dazuma Is there a timeline for adding `synth.py` to the hand coded gems?

**Comment by dazuma** [comment]
I'm working on them now (actually first the gapic-only and partial gapics, then the hand-coded). I was hoping to have it done this week, but it's going slowly and will be well into next week.

**Comment by dazuma** [comment]
I'll frontload synth for datastore (probably Monday) and see if it fixes it.

**Comment by blowmage** [comment]
FYI, I still don't see these types being documented in Datastore.

http://googlecloudplatform.github.io/google-cloud-ruby/docs/google-cloud-datastore/master/

**Comment by dazuma** [comment]
Hmm, those docs files aren't getting generated. There might be a config missing. I'll investigate.

**Comment by quartzmo** [comment]
This issue was fixed by #2428. If a new Datastore version is generated and is missing these files, please re-open or reference in a new issue.
