### ISSUE TITLE
Document GAPIC generated Credentials classes

### ISSUE THREAD

**Issue by blowmage** [googleapis/google-cloud-ruby#2234]
Currently the GAPIC generated Credentials class does not have any documentation on how to use it. Most of the behavior is inherited from `Google::Auth::Credentials`, but it would be good to document these classes, including come code examples, so users can better understand how they are to be used if they choose to use them.

**Comment by blowmage** [comment]
@jbolinger @dazuma Thoughts on this?

**Comment by quartzmo** [comment]
Moved to backlog, opened googleapis/gapic-generator-ruby#5.
