### ISSUE TITLE
YARD Parsing Warnings & Errors

### ISSUE THREAD

**Issue by blowmage** [googleapis/google-cloud-ruby#2265]
There are many gems that print warnings and errors while YARD is parsing the documentation. We should go through each gem and correct all the warnings and errors.

- [x] BigQuery #2293
- [x] BigQuery DataTransfer #2294
- [ ] Bigtable #2295
- [x] google-cloud-core #2296
- [ ] Dataproc #2297
- [ ] Datastore #2417
- [ ] Debugger #2299 and #2301
- [ ] Dialogflow #2302
- [ ] DLP #2303
- [ ] Error Reporting #2304
- [ ] Firestore #2305
- [ ] KMS #2306
- [ ] Language #2307
- [ ] Logging #2308
- [ ] Monitoring #2312
- [x] OSLogin #2313
- [x] Pub/Sub #2314
- [ ] Redis #2315
- [ ] Spanner #2316
- [ ] Speech #2318
- [x] Storage #2324
- [ ] Tasks #2325
- [ ] Trace #2326
- [ ] Video Intelligence #2327
- [x] Vision #2328
- [x] stackdriver-core #2329

**Comment by blowmage** [comment]
There are several gems that are unable to clear all the YARD warnings because of the documentation that GAPIC generates. The current path to resolve these warnings is to replace GAPIC with a new code generator that we can have more control over.

@googleapis/yoshi-ruby, do you think these issues should remain open? Or should we close them all now and revisit this when the new generator is ready?

**Comment by dazuma** [comment]
This is a good point; there are a lot of open issues covered by this. I hesitate to close them since you've already done a lot of analysis work on what the issues are and what direction the new generator might need to go to solve them, analysis that will still be really useful and that we shouldn't throw away. Could we consolidate that data into one issue, or maybe throw it into a wiki on the new generator repo?

**Comment by blowmage** [comment]
Yes, we could move this issue to the backlog wiki.

**Comment by quartzmo** [comment]
I vote to close these issues here, and open an issue for YARD compliance on the new generator repo. Fwiw, the example output for the new generator has no YARD warnings.

**Comment by blowmage** [comment]
> Fwiw, the example output for the new generator has no YARD warnings.

That is because the example proto input/output doesn't have long running operations, and the current GAPIC generated docs for long running operations references classes that do not exist in Ruby.

**Comment by quartzmo** [comment]
There were a couple warnings that I fixed.

**Comment by blowmage** [comment]
This issue has been moved to the [backlog wiki](https://github.com/googleapis/google-cloud-ruby/wiki/Feature-backlog). All of the remaining warnings are from generated files, and outside of our direct control in this repo.
