### ISSUE TITLE
Turn down google-cloud-iot clients

### ISSUE THREAD

**Issue by dazuma** [googleapis/google-cloud-ruby#22821]
The IOT service is turned down and obsolete. Need to remove the relevant GAPIC and wrapper. See the playbook in the internal go/ruby-cloud site.

**Comment by dazuma** [comment]
Reserving for @aandreassa

**Comment by aandreassa** [comment]
Done in #24778 & #24779

Published gems at https://rubygems.org/search?query=google-cloud-iot
