### ISSUE TITLE
Turn down google-cloud-beyond_corp-client_connector_services

### ISSUE THREAD

**Issue by dazuma** [googleapis/google-cloud-ruby#22820]
The BeyondCorp.ClientConnectorServices service is being turned down. Need to remove the relevant GAPIC, and update the wrapper to remove the dependency. See the playbook in the internal go/ruby-cloud site.

**Comment by dazuma** [comment]
Reserving for @aandreassa

**Comment by aandreassa** [comment]
Deleted in #24811
