### ISSUE TITLE
Enable `BIGQUERY_EMULATOR_HOST` in bigquery 

### ISSUE THREAD

**Issue by kromiii** [googleapis/google-cloud-ruby#22861]
### Problem
I was wondering why we cannot use `BIGQUERY_EMULATOR_HOST` in this google-cloud-bigquery gem. 

For example, Python bigquery clinent allows us to set `BIGQUERY_EMULATOR_HOST` for using local bigquery emulator.
https://github.com/googleapis/python-bigquery/blob/3645e32aeebefe9d5a4bc71a6513942741f0f196/google/cloud/bigquery/_helpers.py#L64

Also, the package in nodejs has.
https://github.com/googleapis/nodejs-bigquery/blob/71dbed2140893677f7af254f5a7713a7f50bae92/src/bigquery.ts#L336

### Example Solution
I want to add `BIGQUERY_EMULATOR_HOST` to the configuration file in google-cloud-bigquery. The implementation would be something like this. 

https://github.com/googleapis/google-cloud-ruby/compare/main...kromiii:google-cloud-ruby:main

I would be happy if you are considering this issue.

**Comment by NivedhaSenthil** [comment]
@kromiii Please feel free to create a PR.. will be happy to review 👍
