### ISSUE TITLE
Google Cloud Gem does not build on FreeBSD

### ISSUE THREAD

**Issue by LennyHenrydoesGitHub** [googleapis/google-cloud-ruby#22876]
**Bug Description:**

I encountered an issue while trying to merge a branch into the master of my Ruby on Rails application. The problem arises from the Google Cloud Translate gem failing to build on the FreeBSD environment used by the master branch. I'm submitting this bug report to bring attention to the issue and provide relevant details for resolution.

**Reproduction Steps:**

Clone the Ruby on Rails application.
Checkout the master branch.
Attempt to merge a feature branch into the master.
Observe the gem build failure related to the Google Cloud Translate gem on the FreeBSD environment.

**Expected Behavior:**

The Google Cloud Translate gem should build successfully on the FreeBSD environment when merging a branch into the master.

**Actual Behavior:**

The gem build process fails with error messages related to the Google Cloud Translate gem on the FreeBSD environment.

**Error Messages:**

Please see the error messages below:

https://gist.github.com/faraquet/2f240448f883500dd5e7d87a053a0593

**Environment:**

Rails version:             6.1.7.3
Ruby version:            ruby 3.1.2p20 (2022-04-12 revision 4491bb740a) [x86_64-linux]
RubyGems version:   3.3.7
Rack version:             2.2.7
Google Cloud Translate Gem Version: 0.8.0, 0.7.1
Operating System: FreeBSD: 13.2-RELEASE-p2

Best regards

**Comment by SandeepTuniki** [comment]
@LennyHenrydoesGitHub I'm closing this issue. As mentioned previously, feel free to re-open it in the repo https://github.com/grpc/grpc
