### ISSUE TITLE
BigTable: Add configurable connection pooling to Ruby client

### ISSUE THREAD

**Issue by T-Humphrey** [googleapis/google-cloud-ruby#22879]
**Is your feature request related to a problem? Please describe.**
We are seeing issues when using BigTable which we believe could be due to the lack of configurable connection pooling in the Ruby client. A very small subset of our traffic has a very high latency compared with the typical latency (p50 ~ 10ms, p99 ~ 400ms), this is both on reads and writes.

We cannot say for certain but this seems like it could be related to our connection pooling which we have had to do in app as the Ruby client does not support it. We believe that some of our BigTable connections are going cold due to lack of traffic and the tail latencies are due to BigTable having to reestablish a connection.

 **Describe the solution you'd like**
We would like it if the Ruby client supported configurable connection pooling, similar to the Go, C++, or Java clients as mentioned [here](https://cloud.google.com/bigtable/docs/connection-pools).

 **Additional context**
Ruby version: 3.2.0
Google-cloud-ruby version: 2.8.0

**Comment by shivgautam** [comment]
This feature is already in the works and should be released shortly.
