### ISSUE TITLE
Add the feature to filter by regular expression

### ISSUE THREAD

**Issue by obregonia1** [googleapis/google-cloud-ruby#22894]
I use filter by regular expression with [google\-api\-ruby\-client](https://github.com/googleapis/google-api-ruby-client). This gem allows me to filter by string or regular expression. 
https://googleapis.dev/ruby/google-api-client/v0.27.1/Google/Apis/AnalyticsreportingV4/DimensionFilter.html#expressions-instance_method

But, [google\-analytics\-data\-v1beta](https://github.com/googleapis/google-cloud-ruby/tree/main/google-analytics-data-v1beta) allows me to filter by only string.
https://rubydoc.info/gems/google-analytics-data-v1beta/Google%2FAnalytics%2FData%2FV1beta%2FFilter%2FStringFilter:value

It would be very nice to be able to filter by regular expression, and I think there are many use cases for that.

**Comment by dazuma** [comment]
The functionality is there. Set [StringFilter#match_type](https://rubydoc.info/gems/google-analytics-data-v1beta/Google/Analytics/Data/V1beta/Filter/StringFilter#match_type-instance_method) to FULL_REGEXP or PARTIAL_REGEXP.

**Comment by obregonia1** [comment]
@dazuma 
I've missed it. Thanks!!
