### ISSUE TITLE
QueryJob: Ruby Query Job doesn't support append true option for the destination table

### ISSUE THREAD

**Issue by megha492** [googleapis/google-cloud-ruby#23324]
**PLEASE READ**: If you have a support contract with Google, please create an issue in the [support console](https://cloud.google.com/support/) instead of filing on GitHub. This will ensure a timely response.

**Comment by NivedhaSenthil** [comment]
Can you please elaborate what the issue is?

**Comment by SandeepTuniki** [comment]
@megha492 Gentle ping.

**Comment by SandeepTuniki** [comment]
Closing this due to lack of response. If you're still looking for assistance, you can re-open the issue with more info.
