### ISSUE TITLE
Google Text-To-Speech client: unable to authenticate per documentation

### ISSUE THREAD

**Issue by cstavitsky** [googleapis/google-cloud-ruby#23361]
#### Environment details

  - OS: `MacOS Ventura 13.2.1`
  - Ruby version: `3.2.2` (rails 7.0.8)
  - Gem name and version: Shows in Gemfile.lock as `google-cloud-text_to_speech (1.5.0)`, installed in Gemfile via `gem "google-cloud-text_to_speech"` with no version explicitly specified

#### Steps to reproduce

  1. ensured I have working service account and credentials by [testing via command line](https://cloud.google.com/text-to-speech/docs/create-audio-text-command-line). Successfully received a response and generated mp3 file per documentation.
  2. attempted to follow the text-to-speech [authentication documentation](https://cloud.google.com/ruby/docs/reference/google-cloud-text_to_speech/latest/AUTHENTICATION) for Ruby client library. I tried the following two ways of authenticating described in the docs, code examples below.

#### Code example & backtraces

```ruby
client = Google::Cloud::TextToSpeech.text_to_speech do |config|
  config.credentials = Rails.root.join("google-credentials.json")
end

=> /Users/cstavitsky/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/gapic-common-0.20.0/lib/gapic/config.rb:94:in `block in create_setter': ArgumentError (ArgumentError)

        raise ArgumentError unless valid_value
              ^^^^^^^^^^^^^
```

```ruby
ENV["TEXTTOSPEECH_CREDENTIALS"] = "/Users/cstavitsky/flashcard_rails/google-credentials.json"
client = Google::Cloud::TextToSpeech.text_to_speech

An error occurred when inspecting the object: #<NoMethodError: undefined method `is_a?' for <Config: endpoint="texttospeech.googleapis.com" credentials=nil scope=nil lib_name=nil lib_version=nil interceptors=nil timeout=nil metadata=nil retry_policy=nil quota_project=nil>:Google::Cloud::Config>
Result of Kernel#inspect: #<Google::Cloud::TextToSpeech::V1::TextToSpeech::Client:0x000000011057a0d8 @config=#<Google::Cloud::TextToSpeech::V1::TextToSpeech::Client::Configuration:0x000000011067f7f8 @parent_config=#<Google::Cloud::TextToSpeech::V1::TextToSpeech::Client::Configuration:0x000000011067f9d8 @parent_config=<Config: endpoint="texttospeech.googleapis.com" credentials=nil scope=nil lib_name=nil lib_version=nil interceptors=nil timeout=nil metadata=nil retry_policy=nil quota_project=nil>, @timeout=300.0, @retry_policy={:initial_delay=>0.1, :max_delay=>60.0, :multiplier=>1.3, :retry_codes=>[14, 4]}>, @channel_pool=#<Gapic::ServiceStub::ChannelPool::Configuration:0x0000000110779348>>, @quota_project_id=nil, @text_to_speech_stub=#<Gapic::ServiceStub:0x00000001107792a8 @channel_pool=nil, @grpc_stub=#<Google::Cloud::TextToSpeech::V1::TextToSpeech::Stub:0x0000000110612040 @ch=#<GRPC::Core::Channel:0x00000001107789e8>, @host="texttospeech.googleapis.com", @propagate_mask=nil, @timeout=1969-12-31 15:59:59 -0800, @interceptors=#<GRPC::InterceptorRegistry:0x0000000110778880 @interceptors=[]>>>>
```

Backtraces seem very limited. I'm not sure if this is because of a setting on my side, in which case please let me know and I will try to address that. 

Please let me know if you can help point me in the right direction, would love to get this working. Thanks!

**Comment by DanielNill** [comment]
I'm running into the same issue. Also verified that I am able to authenticate via the CLI and on gem version 3.4.6

**Comment by jasonshah** [comment]
Also seeing this same issue. I've verified my credentials work via the Python library as well.

My error looks nearly identical to @cstavitsky 's error message.

**Comment by aandreassa** [comment]
Can anyone verify if this still an issue? I tried with the setup below and it works as expected. I obtained fresh credentials following [this doc](https://cloud.google.com/ruby/docs/reference/google-cloud-text_to_speech/latest/AUTHENTICATION#creating-a-service-account). Perhaps could be that some required keys are missing from the json config being used?

```ruby
# frozen_string_literal: true
require 'google/cloud/text_to_speech'

tts = Google::Cloud::TextToSpeech.text_to_speech do |config|
  config.credentials = "/tmp/credentials.json"
end

input = {
  text: 'Hello, this is a test for text to speech.',
}
voice = {
  language_code: 'en-US',
}
audio_config = {
  audio_encoding: 'MP3',
}

response = tts.synthesize_speech(input: input, voice: voice, audio_config: audio_config)

File.open 'output.mp3', 'wb' do |file|
  file.write response.audio_content
end
```

**Comment by tbrammar** [comment]
Hey, I tracked this down to a bug in IRB, not this Gem. You can see the details here: #24836

**Comment by aandreassa** [comment]
Thanks for the update! I will close this one out for now then.
