### ISSUE TITLE
Provide an example of using the WebRisk API in Ruby

### ISSUE THREAD

**Issue by collimarco** [googleapis/google-cloud-ruby#23742]
I have spent a few hours trying to figure out how to use the WebRisk API from Ruby.

I can't find any examples.

This is the only resource that I found and there isn't any full example of using the library:
https://github.com/googleapis/google-cloud-ruby/tree/main/google-cloud-web_risk-v1

I simply need to make a query to Google WebRisk to see if one/some URLs are safe or not.

Something like this:

```
client.is_url_safe? 'https://example.com'
# => true
```

Can you please provide a complete example on how to achieve that?

**Comment by NivedhaSenthil** [comment]
Hope this gives some insight into the api https://github.com/googleapis/google-cloud-ruby/blob/main/google-cloud-web_risk-v1/snippets/web_risk_service/search_uris.rb

**Comment by collimarco** [comment]
@NivedhaSenthil That is not a real example, it seems some meaningless code generated automatically. It's a call without any params...

**Comment by NivedhaSenthil** [comment]
Please refer https://cloud.google.com/ruby/docs/reference/google-cloud-web_risk-v1/latest/Google-Cloud-WebRisk-V1-WebRiskService-Client#Google__Cloud__WebRisk__V1__WebRiskService__Client_search_uris_instance_

The api either takes [request object](https://cloud.google.com/ruby/docs/reference/google-cloud-web_risk-v1/latest/Google-Cloud-WebRisk-V1-SearchUrisRequest) or the request parameter as named parameters.  
```ruby
require 'google/cloud/web_risk/v1'
client = Google::Cloud::WebRisk::V1::WebRiskService::Client.new
response = client.search_uris uri: "example.com", threat_types: [1,2,3]
```

**Comment by shivgautam** [comment]
@collimarco 
> `[1, 2, 3]`... definitely not Ruby-style. Google documentation is really bad :(

This is not official documentation. This is something we were trying while investigating this issue. 
`threat_types` array contains values of type Google::Cloud::WebRisk::V1::ThreatType which is found here: 
https://github.com/googleapis/google-cloud-ruby/blob/main/google-cloud-web_risk-v1/proto_docs/google/cloud/webrisk/v1/webrisk.rb#L494-L510

The accepted values for threat_type are: :MALWARE, :SOCIAL_ENGINEERING, :UNWANTED_SOFTWARE, :SOCIAL_ENGINEERING_EXTENDED_COVERAGE
and not `1,2,3`
😄

**Comment by NivedhaSenthil** [comment]
Closing the issue, feel free to reopen if you have more question on the topic.
