### ISSUE TITLE
Spanner: Session not found error

### ISSUE THREAD

**Issue by kryali** [googleapis/google-cloud-ruby#2405]
```
error=5:Session not found: projects/xxxx/AJTWoU5tVv_XKB0peOVcz7sZcaoUSwne6sv0SqxHWBYjgUaWihT8W35rGgcN 
error_class=Google::Cloud::NotFoundError
```

Our spanner client started throwing these errors yesterday for around 12 hours. Is there something with session management here that needs to be configured? More insight into this error would be helpful as well.

We're using  `google-cloud-spanner (1.6.1)`

**Comment by blowmage** [comment]
Hi @kryali, thanks for the issue. When were these error occurring? The Spanner client maintains a pool of sessions, and that pool is supposed to ensure that the session resource is valid, and when it isn't it is supposed to replace it with a session resource that is valid.

**Comment by kryali** [comment]
The session not found errors were occurring pretty frequently between 9/3 11PM and 9/4 11AM PST (~200K errors).  After that, we had a blip on 9/4 8:30PM - 8:45PM PST.

**Comment by blowmage** [comment]
I apologize, I meant what operation was being performed when these errors occurred? Do you have any logging information you can share? A backtrace would be very helpful.

**Comment by kryali** [comment]
We were doing both row reads via key and row upserts to the same table. It looks like we dropped the backtrace, but I'll capture it the next time it happens.

**Comment by blowmage** [comment]
Was this within a transaction or outside of a transaction?

**Comment by kryali** [comment]
Outside of a transaction. Here are the api calls we're making with the ruby client

```
client.upsert(TABLE_NAME, row)
client.read(TABLE_NAME, [:primary_key], keys: keys).rows
```

**Comment by quartzmo** [comment]
@kryali Have you continued to have this issue with the Spanner: Session not found error?

**Comment by kryali** [comment]
This hasn't popped up in a while as far as I can tell, didn't change
anything.

**Comment by blowmage** [comment]
K, I haven't been able to reproduce. If you are not seeing this then I will close this issue. If you see this again, please open a new issue with all the relevant information (gem version, ruby version, platform, backtrace, etc.), and reference this issue. If you can cleanly reproduce outside of your app that would also be very helpful.
