### ISSUE TITLE
Segmentation fault on stackdriver + ruby 2.5 + rails

### ISSUE THREAD

**Issue by uiureo** [googleapis/google-cloud-ruby#2453]
I got segmentation fault when using stackdriver gem with rails application

ruby 2.5.1p57 (2018-03-29 revision 63029) [x86_64-linux]
rails 5.2.1

The app is deployed on unicorn

```
/home/admin/.rbenv/versions/2.5.1/lib/ruby/2.5.0/monitor.rb:147: [BUG] Segmentation fault at 0x000000000000003c
ruby 2.5.1p57 (2018-03-29 revision 63029) [x86_64-linux]

-- Control frame information -----------------------------------------------
c:0077 p:---- s:0537 e:000536 CFUNC  :broadcast
c:0076 p:0015 s:0533 e:000532 METHOD /home/admin/.rbenv/versions/2.5.1/lib/ruby/2.5.0/monitor.rb:147
c:0075 p:0007 s:0529 e:000528 BLOCK  /home/admin/rails_app/shared/bundle/ruby/2.5.0/gems/google-cloud-logging-1.5.4/lib/google/cloud/logging/async_writer.rb
c:0074 p:0007 s:0526 e:000525 METHOD /home/admin/.rbenv/versions/2.5.1/lib/ruby/2.5.0/monitor.rb:226
c:0073 p:0005 s:0522 e:000521 METHOD /home/admin/rails_app/shared/bundle/ruby/2.5.0/gems/google-cloud-logging-1.5.4/lib/google/cloud/logging/async_writer.rb
c:0072 p:0004 s:0518 e:000517 METHOD /home/admin/rails_app/shared/bundle/ruby/2.5.0/gems/stackdriver-core-1.3.2/lib/stackdriver/core/async_actor.rb:344
c:0071 p:0060 s:0514 e:000513 BLOCK  /home/admin/rails_app/shared/bundle/ruby/2.5.0/gems/stackdriver-core-1.3.2/lib/stackdriver/core/async_actor.rb:312 [FINISH]
c:0070 p:---- s:0511 e:000510 CFUNC  :synchronize
c:0069 p:0022 s:0507 e:000506 METHOD /home/admin/rails_app/shared/bundle/ruby/2.5.0/gems/stackdriver-core-1.3.2/lib/stackdriver/core/async_actor.rb:306
c:0068 p:0004 s:0503 e:000502 METHOD /home/admin/rails_app/shared/bundle/ruby/2.5.0/gems/google-cloud-logging-1.5.4/lib/google/cloud/logging/async_writer.rb
c:0067 p:0120 s:0494 e:000493 METHOD /home/admin/rails_app/shared/bundle/ruby/2.5.0/gems/google-cloud-logging-1.5.4/lib/google/cloud/logging/logger.rb:553
c:0066 p:0079 s:0485 e:000484 METHOD /home/admin/rails_app/shared/bundle/ruby/2.5.0/gems/google-cloud-logging-1.5.4/lib/google/cloud/logging/logger.rb:317
c:0065 p:0031 s:0478 e:000477 METHOD /home/admin/rails_app/shared/bundle/ruby/2.5.0/gems/google-cloud-logging-1.5.4/lib/google/cloud/logging/logger.rb:211
c:0064 p:0032 s:0472 e:000471 METHOD /home/admin/rails_app/shared/bundle/ruby/2.5.0/gems/railties-5.2.1/lib/rails/rack/logger.rb:37
c:0063 p:0009 s:0462 e:000461 BLOCK  /home/admin/rails_app/shared/bundle/ruby/2.5.0/gems/railties-5.2.1/lib/rails/rack/logger.rb:26
c:0062 p:0004 s:0459 e:000458 BLOCK  /home/admin/rails_app/shared/bundle/ruby/2.5.0/gems/activesupport-5.2.1/lib/active_support/tagged_logging.rb:71
c:0061 p:0013 s:0456 e:000455 METHOD /home/admin/rails_app/shared/bundle/ruby/2.5.0/gems/activesupport-5.2.1/lib/active_support/tagged_logging.rb:28
c:0060 p:0012 s:0450 e:000449 METHOD /home/admin/rails_app/shared/bundle/ruby/2.5.0/gems/activesupport-5.2.1/lib/active_support/tagged_logging.rb:71
c:0059 p:0041 s:0445 e:000444 METHOD /home/admin/rails_app/shared/bundle/ruby/2.5.0/gems/railties-5.2.1/lib/rails/rack/logger.rb:26
c:0058 p:0092 s:0439 e:000438 METHOD /home/admin/rails_app/shared/bundle/ruby/2.5.0/gems/newrelic_rpm-5.4.0.347/lib/new_relic/agent/instrumentation/middlewa
c:0057 p:0049 s:0430 e:000429 METHOD /home/admin/rails_app/shared/bundle/ruby/2.5.0/gems/google-cloud-logging-1.5.4/lib/google/cloud/logging/middleware.rb:9
```

full log:  https://gist.github.com/uiureo/ba3cd795134dfec41410d92f801323d4

**Comment by blowmage** [comment]
@uiureo Thank you for the detailed information. We will look into this.

**Comment by lucaong** [comment]
I have the same Segmentation fault error. It only occurs when I add the `stackdriver`. Our app is running on Puma, with Ruby 2.5.1 on GKE.

Full log here: https://gist.github.com/lucaong/63e815c05b0db59618baebed56b4616b

Interestingly, we run two different kubernetes deployments of the same app, one is the web application and the other is the background job workers. Only the latter seem to be affected by this.

Also, but possibly unrelated, close to the segfault we observe often multiple times these errors too:

```
E  ruby: ../nptl/pthread_mutex_lock.c:352: __pthread_mutex_lock_full: Assertion `INTERNAL_SYSCALL_ERRNO (e, __err) != ESRCH || !robust' failed.
```

**Comment by lucaong** [comment]
Possibly related to https://github.com/protocolbuffers/protobuf/issues/4460

There is no mention of `protobuf` in the stacktrace, but the chain of methods that get called when `/google-cloud-logging-1.5.4/lib/google/cloud/logging/async_writer.rb:322` calls `MonitorMixin::ConditionVariable#broadcast` and wakes up awaiting threads ends up calling this: `https://github.com/googleapis/google-cloud-ruby/blob/master/google-cloud-logging/lib/google/cloud/logging/v2/logging_service_v2_client.rb#L395`, which uses protobuf from `Google::Gax`

**Comment by fruwe** [comment]
same here, on puma with the same ruby and rails versions

**Comment by blowmage** [comment]
@uiureo @lucaong @fruwe I've been asked to look into this more and am wondering if we can get more information about when you see this. Is this segfault happening immediately on app start? Or does it happen after the app has been running? How often do you see this segfault? How heavy is your app being run when you see this? How many threads/workers are you running when you see this?

Any information you can provide is very much appreciated. I haven't reproduced this myself, so providing a small app/docker image that does repro would also help immensely.

**Comment by fruwe** [comment]
@blowmage Thanks a lot. I already removed the gem until it is fixed, but as far as I can remember, the segfault happened on startup and without any load (staging environment). We were using 2 threads and 2 workers

**Comment by lucaong** [comment]
Same here, the segfault was happening both on staging and in production (staging with no load). In our case though, only the background job workers were affected.

The workers are Rails ActiveJob running with Sneakers (RabbitMQ job queues for Ruby) on 4 workers per machine, 10 maximum threads per worker.

We removed the gem and instead wrote a log formatter and exception logger for the Stackdriver JSON format. Removing the gem, the issue is gone, and we simply log to stdout, with logs being collected correctly into Stackdriver by the GKE infrastructure.

**Comment by blowmage** [comment]
Was this using docker? If so, was it using a common or custom image?

**Comment by lucaong** [comment]
In our case, it runs on Docker, on an image derived from the official `ruby:2.5.1` image. On top of it, we basically just install NodeJS and build our Rails 5.2 app.

**Comment by dirkjonker** [comment]
I am also getting random segfaults, cannot always reproduce
Ubuntu 18.04, ruby 2.5.1 using rbenv, Rails 5.2.1, stackdriver gem latest
`require 'stackdriver'` in config/application.rb
opening the Rails console `rails c`
running an arbitrary command such as `Rails.logger` to see that it uses the Google::Cloud::Logging::Logger
exiting with `CTRL+D` -> causes segfault

**Comment by blowmage** [comment]
Thanks @dirkjonker, does the following workaround fix this for you?

https://github.com/protocolbuffers/protobuf/issues/4460#issuecomment-434631296

**Comment by paulpyrb** [comment]
Hi, I'm facing the same segmentation issue on GAE, I'm able to deploy and run my migrations (via the appengine gem) without any issues, but it responds with a 503 when trying to access it. 

The app is running on Ruby 2.5.3 and Rails 5.2.0, appengine 0.4.6

Logs and Gemfile.lock are available in this gist: https://gist.github.com/paulpyrb/1161a24ba970391a2f8a94f85207a494

@blowmage I tried the workaround you've linked above by adding `BUNDLE_FORCE_RUBY_PLATFORM` as a variable in my app.yaml file, but it didn't fix my issue. 

```
entrypoint: bundle exec rackup --port $PORT
env: flex
runtime: ruby

env_variables:
  BUNDLE_FORCE_RUBY_PLATFORM: 1 # segmentation fix

beta_settings:
  cloud_sql_instances:
```

**Comment by axalix** [comment]
Same issue here and the workaround didn't for me either.

**Comment by blowmage** [comment]
@axalix, unfortunately yours looks like a separate issue. The segfault is from a different method, and the backtrace shows you are using a pre-compiled gem. You need to install the pure-ruby gem which will compile the C-code.

**Comment by dirkjonker** [comment]
@blowmage I'm having some issues trying the "fix" as I cannot seem to build V8 from scratch without some effort

**Comment by jarv** [comment]
@axalix this works for me:
```
apk add build-base
gem install google-cloud-logging --platform ruby
```

**Comment by dirkjonker** [comment]
@blowmage I have some issues related to the grpc forking issues. I am loading the stackdriver gem conditionally and it seems to load some grpc component before forking. I'll have to investigate a bit further, I might open a new ticket for it.

**Comment by blowmage** [comment]
@Viktor-Ivliev Can you open a new issue with all the relevant details?

**Comment by dirkjonker** [comment]
@blowmage thanks, the fix seems to work, just submitted #2742 to fix one issue I have with it

**Comment by blowmage** [comment]
@dirkjonker Glad to hear it.

@uiureo I have been unable to reproduce the exact segfault you have reported. I see that you are using Unicorn. Are you seeing the segfault pre or post-fork? Can you try updating to use the code in the repo and see if that helps?

**Comment by uiureo** [comment]
I've tried the latest version of the gem, and it works perfectly in our environment with ruby 2.5.3 + rails 5.2.2.
I don't run into this problem anymore.

Thanks!
