### ISSUE TITLE
Expose MetricDescriptor and MetricDescriptorMetadata

### ISSUE THREAD

**Issue by blowmage** [googleapis/google-cloud-ruby#2463]
The PR #2455 added `MetricDescriptorMetadata`, which is not currently exposed in the Ruby API. (Not the low-level protobuf layer, the top-level hand-written layer.) Should this data be exposed? If so, how?

Monitoring also had this added, but it is a purely generated gem and there is no hand-written layer for it.

**Comment by quartzmo** [comment]
I can't see any reason *not* to expose `Google::Api::MetricDescriptor` in the `Metric` class, other than demand/priority, so I think this issue is a feature request rather than a question.

**Comment by blowmage** [comment]
K, I'll start on this while I'm doing the other Stackdriver stuff.

**Comment by blowmage** [comment]
I am releasing this issue as I am not going to work on it.
