### ISSUE TITLE
Add Vision helper method for Object Localization

### ISSUE THREAD

**Issue by beccasaurus** [googleapis/google-cloud-ruby#2482]
Please add helper method (partial) to Vision for [Feature.Type `OBJECT_LOCALIZATION`](https://cloud.google.com/vision/docs/reference/rpc/google.cloud.vision.v1p3beta1#google.cloud.vision.v1p3beta1.Feature.Type)

See related PHP issue: https://github.com/googleapis/google-cloud-php/issues/1303
And related C# change: https://github.com/googleapis/google-cloud-dotnet/commit/367420a1602950bdf3271294ffec873c2b76d114
And related comment on ruby-docs-samples for sample demonstrating ObjectLocalization: https://github.com/GoogleCloudPlatform/ruby-docs-samples/pull/346/commits/963d75f833d46400dafd03c0b33a7839319cd0ac#r217499831

/cc @dizcology

**Comment by beccasaurus** [comment]
🤞 _no more additions to this hand-written after this_ 😕😁

**Comment by beccasaurus** [comment]
Removed the v1p3beta1 – this Feature.Type should be available on V1 /cc @dizcology

**Comment by beccasaurus** [comment]
Thank you so much @blowmage! 🙏

**Comment by blowmage** [comment]
This is released in [google-cloud-vision 0.31.0](https://github.com/googleapis/google-cloud-ruby/releases/tag/google-cloud-vision%2Fv0.31.0).

**Comment by beccasaurus** [comment]
Thank you kindly!
