### ISSUE TITLE
Add path helpers to ServiceClients (as instance methods)

### ISSUE THREAD

**Issue by beccasaurus** [googleapis/google-cloud-ruby#2515]
**REQUEST:** please add path helpers as instance methods on ServiceClients! 🙏

### What I want

I _keep_ trying to call these path helpers on the client, like some other languages support...

```rb
require "google/cloud/kms"

kms = Google::Cloud::KMS.new

key_ring_id = "123"
key_ring = { name: "my-key-ring" }

kms.create_key_ring(
  kms.location_path("my-project", "us-central-1"),
  key_ring_id,
  key_ring
)
```

### Currently supported

But that doesn't work. Here is what works today:

```rb
require "google/cloud/kms"

kms = Google::Cloud::KMS.new

key_ring_id = "123"
key_ring = { name: "my-key-ring" }

kms.create_key_ring(
  Google::Cloud::Kms::V1::KeyManagementServiceClient.location_path("my-project", "us-central-1")
  key_ring_id,
  key_ring
)
```

**Note:** _trying `Google::Cloud::Kms.location_path()` also blows up (which makes sense to us, knowing the implementation, but isn't obvious to the user). If we wanted to force class methods on people to avoid instance methods (as class methods are truly more "correct"), it would at least be nice if this worked. Which we could support by adding the self.methods to the `Google::Cloud::[XXX]` module. But I think instance methods are the most usable and 'guessable'.

### But, really, I do this instead...

Because the supported syntax for getting the path is... inconvenient, I avoid the path helpers altogether in my own, real code. Which is a data point unto itself. And a bummer because I want to use the helpers.

```rb
require "google/cloud/kms"

kms = Google::Cloud::KMS.new

key_ring_id = "123"
key_ring = { name: "my-key-ring" }

kms.create_key_ring(
  "projects/#{project_id}/locations/#{location_name}"
  key_ring_id,
  key_ring
)
```

#### What do y'all think about `include`'ing the `_path` helpers of each `*ServiceClient` as instance methods?

_For backwards compatibility, keep the class versions. But have instance version aliases to delegate to the class methods._

**Comment by quartzmo** [comment]
Makes sense to me.

**Comment by quartzmo** [comment]
@beccasaurus Which APIs/services would benefit most from the addition of such helpers? All?

**Comment by jbolinger** [comment]
We plan to add this as part of the generator refresh. @frankyn has requested this multiple times as well: https://github.com/googleapis/gax-ruby/issues/125

Unless we plan to add these manually, or need them ASAP on a particular API, let's move the discussion to the new generator repo once it is live: https://github.com/googleapis/gapic-generator-ruby.  I'll open the issue there when ready but feel free to suggest other things there too... we'll prioritize on the number of 🙏's

**Comment by blowmage** [comment]
I would very much like to see this change on all GAPIC-generated clients. We could add them via the synth.py files, but I would be okay waiting for the new generator.

**Comment by beccasaurus** [comment]
> let's move the discussion to the new generator repo once it is live

Love it  👍

Might also allow for further usability discussions of resource paths? 🙂
Various other ways to think about improving the developer experience.

Like... maybe path helpers isn't the right approach.
e.g. Can haz resource name parts flattened as method params? 😇

Regardless of what the pattern is that gets implemented in the new generator:

> I would very much like to see this change on all GAPIC-generated clients

+💯

**Comment by blowmage** [comment]
> e.g. Can haz resource name parts flattened as method params? 😇

There are some instances where the path value is retrieved from some other resource object, and it would be painful to pass in every value as a separate argument instead of the single path string argument. I'm thinking Spanner and Firestore. But I can see allowing users to pass in a Hash instead of a String, and passing values from the hash to the path helper.

```ruby
require "google/cloud/kms"

kms = Google::Cloud::KMS.new

key_ring_id = "123"
key_ring = { name: "my-key-ring" }

kms.create_key_ring(
  { project: project_id, location: location_name }
  key_ring_id,
  key_ring
)
```

Of course the class helper has positional arguments, and a syntax like this would be better if it used named arguments.

```ruby
##
# Returns a fully-qualified location resource name string.
# @param project [String]
# @param location [String]
# @return [String]
def location_path project:, location:
  LOCATION_PATH_TEMPLATE.render(
  :"project" => project,
  :"location" => location
)
end

# Using named arguments instead of positional arguments
resource_path = kms.location_path project: project_id, location: location_name
```

**Comment by blowmage** [comment]
Moving this issue to googleapis/gapic-generator-ruby#6 and closing.
