### ISSUE TITLE
safe_search does not include racy

### ISSUE THREAD

**Issue by rickthomasjr** [googleapis/google-cloud-ruby#2526]
When using the gem to perform a safe search detection, the results contain everything but whether the image is racy.  Is this intentional, or is the gem missing a feature?

![image](https://user-images.githubusercontent.com/516470/47047012-7edabf80-d164-11e8-9392-1c48046cdc7d.png)

**Comment by quartzmo** [comment]
@rickthomasjr Thanks for bringing this omission to our attention. 

Would you like to see `racy` added to the top-level API? If so, I'll re-label this issue as a feature request.

It is already [present and available for use](https://github.com/googleapis/google-cloud-ruby/blob/master/google-cloud-vision/lib/google/cloud/vision/v1/doc/google/cloud/vision/v1/image_annotator.rb#L412-L417) in the lower-level API contained in the same gem. Documentation for the lower-level API is here: [Google::Cloud::Vision::V1](http://googleapis.github.io/google-cloud-ruby/docs/google-cloud-vision/v0.31.0/Google/Cloud/Vision/V1.html).

**Comment by quartzmo** [comment]
Closing, since Vision is likely to be migrated to a GAPIC-only library. If you have an urgent need for this feature, please use the lower-level API linked above.
