### ISSUE TITLE
Dependency Conflict with faraday in `google-cloud-translate-v2`

### ISSUE THREAD

**Issue by Keulsss** [googleapis/google-cloud-ruby#25287]
### Description
There is a dependency conflict between `google-cloud-translate-v2` due to differing requirements for the `faraday` gem.

### Issue Details
- gem which requires `faraday` version `~> 2.0`.
- `google-cloud-translate-v2` (all current versions) requires `faraday` version `>= 0.17.3, < 2.0`.

This creates a situation where it's impossible to satisfy both dependencies in the same project.
Thank you for looking into this issue. Your assistance would greatly help many developers facing the same challenge.

**Comment by dazuma** [comment]
google-cloud-translate-v2 0.5.1 (released a few weeks ago) expands the compatibility to include 2.x
