### ISSUE TITLE
bigquery: please don't authenticate on require

### ISSUE THREAD

**Issue by brauliobo** [googleapis/google-cloud-ruby#2535]
On `require 'google/cloud/bigquery'` it is doing a network request and authenticating with the server.

This is contrary to (almost) all ruby libraries that authenticate later on initialization or usage call. For instance, AWS SDK, pg (for postgresql), Rails, etc.

Because of this behaviour I cannot require bigquery in rake tasks, specs or environments that don't have authentication keys, so I need some bad conditions like:
```ruby
$rake_task = defined?(Rake) && Rake.application.top_level_tasks.first&.include?('db')                                                                                                        
unless $rake_task or ENV['DAEMON_ENV'] == 'test'
```

Instead of that, I think the authentication can be done on the first request/usage.

**Comment by quartzmo** [comment]
@brauliobo I'm sorry, but I can't reproduce this issue. I have executed the `require` statement without a network connection, but there is no network call. I only see a network call when I initialize the `BigQuery` client.

```sh
$ irb
irb(main):001:0> require "google/cloud/bigquery"
=> true
irb(main):002:0> bigquery = Google::Cloud::Bigquery.new
Faraday::ConnectionFailed: Failed to open TCP connection to oauth2.googleapis.com:443 (getaddrinfo: nodename nor servname provided, or not known)
```

Can you please provide detailed steps to reproduce this issue in a simple environment? Thanks!

**Comment by brauliobo** [comment]
@quartzmo checking in an isolated scenario

**Comment by brauliobo** [comment]
sorry for the wrong report @quartzmo, I can reproduce your test case and indeed I was using `Bigquery.new` at class level. Although I have the feeling that this used was true before, good that it is fine now :smile:
