### ISSUE TITLE
Bigdecimal won't be part of standard library from Ruby 3.4.0 #97

### ISSUE THREAD

**Issue by SandeepTuniki** [googleapis/google-cloud-ruby#25461]
(Duplicating this issue from https://github.com/googleapis/ruby-spanner/issues/97, since we have multiple gems in this repo using bigdecimal)

Saw this warning log message during a CI run:

```
/[workspace/google-cloud-spanner/lib/google/cloud/spanner/convert.rb:20]
warning: bigdecimal was loaded from the standard library,
but will no longer be part of the default gems since Ruby 3.4.0.
Add bigdecimal to your Gemfile or gemspec.
```

A quick project-wide search shows the following gems are using bigdecimal:
- bigquery
- firestore
- datastore
- pubsub

Creating this bug to keep track of the warning before it becomes an error in the future.

**Comment by blowmage** [comment]
Datastore checks if the `BigDecimal` constant exists, but it does not require the library. This results in the warning never being raised when running it's CI, therefore my PR does not add an explicit dependency to it's gemspec.
