### ISSUE TITLE
Bigquery: limit amount of bytes queried

### ISSUE THREAD

**Issue by brauliobo** [googleapis/google-cloud-ruby#2562]
I can't find a way to prevent big queries to run

**Comment by quartzmo** [comment]
@brauliobo Thank you for this question!

Both [`Project#query_job`]() and [`Dataset#query_job`]() have a `maximum_bytes_billed` option which is described as follows:

> Limits the bytes billed for this  job. Queries that will have bytes billed beyond this limit will fail (without incurring a charge). Optional. If unspecified, this will be set to your project default.

You can read more at [BigQuery Best Practices: Controlling Costs - Limit query costs by restricting the number of bytes billed](https://cloud.google.com/bigquery/docs/best-practices-costs#limit_query_costs_by_restricting_the_number_of_bytes_billed).

A good way to determine the number of bytes that a query will process is to set the `dry_run` flag to `true` as shown in this [acceptance test](https://github.com/googleapis/google-cloud-ruby/blob/f8d23acb212aad27080decb2fba5bea620d5ddc0/google-cloud-bigquery/acceptance/bigquery/bigquery_test.rb#L152-L168). (Please note that this feature is pending merge and release but should be available as soon as later today or tomorrow.)
