### ISSUE TITLE
Upgrade Rubocop to 0.60.x

### ISSUE THREAD

**Issue by quartzmo** [googleapis/google-cloud-ruby#2574]
Rubocop [0.60.0](https://rubygems.org/gems/rubocop/versions/0.60.0) was released. The google-cloud-ruby gems currently declare `~> 0.59.2`.

**Comment by blowmage** [comment]
The release cadence seems to be a minor release every month or so. Do we intend on performing an upgrade on all gems every month?

**Comment by quartzmo** [comment]
Maybe not forever, but I think it might be smart to do so while we work on the generator.
