### ISSUE TITLE
Add tracking tags to Spanner acceptance tests

### ISSUE THREAD

**Issue by quartzmo** [googleapis/google-cloud-ruby#2579]
Example 'tags' are:

`spanner_write_read_bool_array`
`spanner_write_read_empty_int64_array`
`spanner_write_read_null_int64_array`
`spanner_write_read_int64_array`
`spanner_write_read_empty_float64_array`
`spanner_write_read_null_float64_array`
`spanner_write_read_float64_array`

These tags should surround applicable tests in comments. For combined tests multiple tags may be nested.
```
# [START require_library]
CODE HERE
# [END require_library]
```

**Comment by quartzmo** [comment]
@crwilcox Is this still actionable? If so, how should it be prioritized?

**Comment by quartzmo** [comment]
Unassigned myself per @crwilcox instructions, opening this for Spanner team.

**Comment by jiren-wal** [comment]
@skuruppu above examples are available in acceptance test but I think we should add these examples to [ruby-docs-sample](https://github.com/GoogleCloudPlatform/ruby-docs-samples/) https://github.com/GoogleCloudPlatform/ruby-docs-samples/blob/master/spanner/spanner_samples.rb

**Comment by jiren** [comment]
@skuruppu above examples are available in acceptance tests but I think we should add these examples to [ruby-docs-sample](https://github.com/GoogleCloudPlatform/ruby-docs-samples/) https://github.com/GoogleCloudPlatform/ruby-docs-samples/blob/master/spanner/spanner_samples.rb

**Comment by skuruppu** [comment]
> @skuruppu above examples are available in acceptance tests but I think we should add these examples to [ruby-docs-sample](https://github.com/GoogleCloudPlatform/ruby-docs-samples/) https://github.com/GoogleCloudPlatform/ruby-docs-samples/blob/master/spanner/spanner_samples.rb

Ah ok, I missed that these were in the acceptance tests. Yes, you're right. The docs won't pick these up unless it's in the samples repo. Would you be able to make the change?

**Comment by jiren** [comment]
Yes, I am working on it.

**Comment by jiren-wal** [comment]
@skuruppu created [PR#485](https://github.com/GoogleCloudPlatform/ruby-docs-samples/pull/485) for the listed examples in this issue.

**Comment by jiren** [comment]
@skuruppu created [PR#485](https://github.com/GoogleCloudPlatform/ruby-docs-samples/pull/485)  in ruby-docs-samples for the listed examples in this issue.

**Comment by skuruppu** [comment]
Updated PR [#488](https://github.com/GoogleCloudPlatform/ruby-docs-samples/pull/488) has been merged in.

This work is complete so closing the issue.
