### ISSUE TITLE
Missing Ruby Clients for Shopping Merchant APIs

### ISSUE THREAD

**Issue by blowmage** [googleapis/google-cloud-ruby#26042]
Last week four new Google Merchant APIs were released. The [protos are published](https://github.com/googleapis/googleapis/tree/master/google/shopping/merchant), but look to be missing some configuration for the Ruby clients. And the Ruby clients have not yet been generated. What is the ETA for generating and releasing these clients?

I understand the process of defining, generating, and releasing these clients is internal to Google. Is there anything folks outside of Google can do to aid this process along?

**Comment by dazuma** [comment]
@blowmage Additional merchant APIs are in progress and should, barring any issues, be published in the next couple days. (I just saw the internal configuration change for accounts, products, and promotions [go through](https://github.com/googleapis/googleapis/commit/d664abd91cf7a1ea3b2d4434fa664d2e555d687a) a couple hours ago.)

If there are specific APIs you are interested in, let me know and I can check if they're in the pipeline.

**Comment by aandreassa** [comment]
I just published three of them to Rubygems.

The only missing one is `google-shopping-merchant-accounts`, which is still blocked internally. I will keep this open until then.

**Comment by aandreassa** [comment]
`google-shopping-merchant-accounts` is now published: https://rubygems.org/gems/google-shopping-merchant-accounts

**Comment by blowmage** [comment]
Thank you @aandreassa!
