### ISSUE TITLE
storage: Samples for managed folders 

### ISSUE THREAD

**Issue by sydney-munro** [googleapis/google-cloud-ruby#26072]
We would like to have samples for the following managed folders operations:
Create
Get
List
Delete

See the java samples as the canonical sample [here](https://github.com/googleapis/java-storage/pull/2562)

**Comment by sydney-munro** [comment]
@bajajneha27 do we have an eta on when this will be completed?

**Comment by bajajneha27** [comment]
> @bajajneha27 do we have an eta on when this will be completed?

I can take it up in July sprint.

**Comment by sydney-munro** [comment]
> > @bajajneha27 do we have an eta on when this will be completed?
> 
> I can take it up in July sprint.

thanks!
