### ISSUE TITLE
BigQuery: dataset.exists? acts in unexpected ways

### ISSUE THREAD

**Issue by alixhami** [googleapis/google-cloud-ruby#2610]
Why doesn't [dataset.exists?](http://googleapis.github.io/google-cloud-ruby/docs/google-cloud-bigquery/v1.9.0/Google/Cloud/Bigquery/Dataset.html#exists%3F-instance_method) call the API? I see that it is a cached property of a dataset, but it does not update when a dataset is deleted. I would expect this method to call the API to determine if the dataset exists, or at minimum the delete method should set the property to false. (Note that this likely also applies to `table.exists?` as well but I haven't looked into it)

#### Environment details

Gem name and version: 
  - OS: macOS High Sierra
  - Ruby version: 2.4.4
  - Gem name and version: google-cloud-bigquery 1.8.0

#### Code example

Here is the output from irb. I removed the output from lines 1-3 for readability.
```ruby
irb(main):001:0> require "google/cloud/bigquery"
irb(main):002:0> bigquery = Google::Cloud::Bigquery.new
irb(main):003:0> dataset = bigquery.create_dataset "sandwich"
irb(main):004:0> dataset.delete
=> true
irb(main):005:0> dataset.exists?
=> true
```
I think line 5 should return `false`, whether that's due to an API call or the local object updating its property when the delete method is called.

**Comment by quartzmo** [comment]
@alixhami I agree. Thanks for catching this.

**Comment by alixhami** [comment]
FWIW, [we got rid of the exists method](https://cloud.google.com/bigquery/docs/python-client-migration#dataset-exists) in the python client library because it was somewhat of a wasted API call. We recommend wrapping whatever table/dataset fetching operation with error handling if there's a risk it doesn't exist. It seems that would be the current recommendation in ruby now anyway, since `exists?` doesn't always give an accurate result.

**Comment by quartzmo** [comment]
Removing `#exists?` would require a `2.0.0` release, which seems a bit drastic at this point. I think first we should attempt to fix it.

**Comment by quartzmo** [comment]
@alixhami PTAL at #2612.

>  We recommend wrapping whatever table/dataset fetching operation with error handling if there's a risk it doesn't exist.

If you can point me to this recommendation in the python client documentation, I can try to adapt it and include it in #2612.

**Comment by alixhami** [comment]
The only documentation we have of it is in the [python migration guide](https://cloud.google.com/bigquery/docs/python-client-migration#dataset-exists). Other than that, we don't have anything docs explaining why we don't have an exists method because it's not part of the API so there isn't an expectation to have the method.

**Comment by quartzmo** [comment]
Sorry, I meant documentation recommending wrapping the fetch operation with error handling to avoid unnecessary API calls.
