### ISSUE TITLE
Support the LogEntry "trace_sampled" field in GoogleCloudPlatform/fluent-plugin-google-cloud

### ISSUE THREAD

**Issue by sebright** [googleapis/google-cloud-ruby#2690]
https://github.com/googleapis/googleapis/commit/7b34e5a3ed10775fe14d15ffa842870dc3b5400e added the `trace_sampled` field to the Stackdriver `LogEntry` proto.  It would be nice if the Stackdriver Logging agent handled `trace_sampled` similarly to the `trace` and `span_id` fields and used a special field in the Fluentd log event to set `LogEntry.trace_sampled` (See https://cloud.google.com/logging/docs/agent/configuration#special_fields_in_structured_payloads).  This feature could be used in combination with OpenCensus log correlation to allow Stackdriver to interpret the sampling decision from OpenCensus.

This change would be very similar to https://github.com/GoogleCloudPlatform/fluent-plugin-google-cloud/pull/180.

**Comment by sduskis** [comment]
It looks like #2611 is tackling `trace_sampled`

**Comment by sebright** [comment]
@blowmage Thanks for working on this feature!

Is #2611 the correct link?  It looks like it's related to buffering log entries, not transforming entries in the logging agent.

**Comment by blowmage** [comment]
That is not the correct link. I have just started this, and 2611 is for a different change.

**Comment by sebright** [comment]
Thanks for the fix!
