### ISSUE TITLE
Error when using KEYFILE_JSON env var with Storage and Shrine

### ISSUE THREAD

**Issue by mikesaltsman** [googleapis/google-cloud-ruby#2693]
I'm using [Shrine's google cloud storage](https://github.com/renchap/shrine-google_cloud_storage) for uploads and when using the Keyfile location as a path it works just fine in dev, but I'm needing to have the JSON key in an environment variable for production. As per the [Google Cloud docs](https://github.com/googleapis/google-cloud-ruby/blob/master/AUTHENTICATION.md) I've created the environment variable as **GOOGLE_CLOUD_KEYFILE_JSON** containing the contents of the keyfile.json but I'm still getting a runtime error when running on Heroku. 

Stacktrace can be found [here](https://gist.github.com/mikesaltsman/07e7f183fff12202c2c319047f0f66f9)

It seems as if it's still expecting a file, but being handed the JSON. 

#### Environment details

  - OS: MacOS / Heroku
  - Ruby version: 2.2.10
  - Gem name and version: google-cloud-storage

#### Code example

```ruby
Google::Cloud.configure do |config|
    config.project_id = ENV['GOOGLE_CLOUD_PROJECT']
    config.keyfile = ENV['GOOGLE_CLOUD_KEYFILE_JSON']
end
```

**Comment by quartzmo** [comment]
It appears that [shrine-google_cloud_storage is calling](https://github.com/renchap/shrine-google_cloud_storage/blob/v1.0.1/lib/shrine/storage/google_cloud_storage.rb#L146) `Google::Cloud::Storage.new` with no args. Then, given the configuration you provided, [`storage.rb`](https://github.com/googleapis/google-cloud-ruby/blob/master/google-cloud-storage/lib/google/cloud/storage.rb#L163) is loading `Google::Cloud.configure.credentials` (your JSON string) and passing that to `Credentials.new` [here](https://github.com/googleapis/google-cloud-ruby/blob/master/google-cloud-storage/lib/google/cloud/storage.rb#L87).

I'm not sure if this is the proper solution, but can you try parsing your JSON?

```rb
Google::Cloud.configure do |config|
    config.project_id = ENV['GOOGLE_CLOUD_PROJECT']
    config.keyfile = JSON.parse(ENV['GOOGLE_CLOUD_KEYFILE_JSON'])
end
```

**Comment by quartzmo** [comment]
I did a quick test of `Google::Cloud.configure` and it does NOT appear to automatically convert a JSON string to a hash:

```sh
irb(main):012:0> Google::Cloud.configure do |config|
irb(main):013:1* config.credentials = "{ \"a\": \"b\" }"
irb(main):014:1> end
Key :inspect does not exist. Returning nil. at /Users/quartzmo/.rbenv/versions/2.4.2/lib/ruby/2.4.0/irb/inspector.rb:109:in `block in <module:IRB>'
=> 
irb(main):015:0> Google::Cloud.configure.credentials
=> "{ \"a\": \"b\" }"
```

**Comment by blowmage** [comment]
I concur with @quartzmo, the issue here is that you are not using the environment variable, you are shortcutting it by specifying the value in `Google::Cloud.configure`. If you do not specify the configuration value, the environment variable will be checked and used. Or, you can do as @quartzmo suggests and parse the JSON string.

**Comment by quartzmo** [comment]
Yes, the best solution (if it works) would be to remove your `Google::Cloud.configure` block and set just the `GOOGLE_CLOUD_KEYFILE_JSON` env var. The no-args construction (`Google::Cloud::Storage.new`) in the Shrine plugin should then work correctly.

**Comment by mikesaltsman** [comment]
That did it. Removing the configuration from production worked... Thank you for the help!
