### ISSUE TITLE
Cloud trace slows down the app apparently making synchronous call to other region

### ISSUE THREAD

**Issue by giovannibonetti** [googleapis/google-cloud-ruby#2696]
Thank you for the hard work on the Ruby gems for integrating with Google Cloud!
I created the issue here since I thought it could benefit from an open discussion on Github.

--------------------------------------------
Thanks for stopping by to let us know something could be better!

**PLEASE READ**: If you have a support contract with Google, please create an issue in the [support console](https://cloud.google.com/support/) instead of filing on GitHub. This will ensure a timely response.

Please run down the following list and make sure you've tried the usual "quick fixes":

  - [x] Search the issues already opened: https://github.com/googleapis/google-cloud-ruby/issues
  - [x] Search StackOverflow: http://stackoverflow.com/questions/tagged/google-cloud-platform+ruby

If you are still having issues, please be sure to include as much information as possible:

#### Environment details

  - OS: App Engine Flex with [Custom Dockerfile](https://hub.docker.com/r/hoteltonight/ruby-jemalloc/tags/) running Debian Stretch
  - Ruby version: 2.5.1
  - Gem name and version:  google-cloud-trace (0.33.6), stackdriver (0.15.3)

#### Steps to reproduce

  1. Add `stackdriver` gem to Gemfile
  2. Run `bundle install`
  3. Deploy the app in App Engine in South America
  4. Check out the app performance metrics and see that about 200ms of latency have been added to the requests. I have used New Relic since Cloud Trace has not recorded anything in my project despite of that.

![screenshot 2018-11-28 11 51 13](https://user-images.githubusercontent.com/3451581/49156264-130f7900-f304-11e8-8224-4a87cf75fe84.png)

#### Comments

The endpoint in question used to be very quick (about 20 ms) and now with this added latency it got almost 10x slower, which made the app go down until we disabled Cloud Trace.

One thing that has called my attention is that this delay matches very well the **round-trip latency from South America to North America region**. Maybe the app is making a synchronous call to a webserver in North America? 🤔

**Comment by quartzmo** [comment]
@giovannibonetti Thank you for opening this issue. I'm not sure if there is anything we can do to fix it in the client library, but as you say, hopefully it will benefit from an open discussion on GitHub.

**Comment by giovannibonetti** [comment]
Hi, @quartzmo, thanks for the quick reply!

Is there a way to pass an option for the client library to make an async request, like [Sentry](https://github.com/getsentry/raven-ruby#async)?

Another option is make usage of background jobs with ActiveJob - when running Rails - like [Airbrake](https://github.com/airbrake/airbrake/blob/master/lib/airbrake/rails.rb#L63-L69).

**Comment by blowmage** [comment]
Trace should already be making API calls asynchronously, but I am not as familiar with the middleware. I am starting some work on Trace shortly, and will dive deeper into the middleware. Thank you for opening this issue.

**Comment by blowmage** [comment]
@giovannibonetti Are you using a custom configuration for `Google::Cloud::Trace::Middleware`? Or does your call look like this?

```ruby
use Google::Cloud::Trace::Middleware
```

**Comment by blowmage** [comment]
Is this slow down immediate? Or does it run for a while before slowing down? How many RPM does this endpoint get?

**Comment by giovannibonetti** [comment]
Hi, @blowmage, thanks for the help!
> Are you using a custom configuration for Google::Cloud::Trace::Middleware? Or does your call look like this?

I'm using the stackdriver gem, which uses the middleware approach. All of the middleware running in production are listed [here](https://gist.github.com/giovannibonetti/99d03f873fdf0452e2a47ad4aa67996c).

> Is this slow down immediate? Or does it run for a while before slowing down? 

I can't answer that with the metrics I have.

> How many RPM does this endpoint get?

This is a very low traffic application, which gets about 10 rpm on this endpoint and about 60 rpm total.

The metrics I do have are this. The chart is flat because the data has been undersampled, since the free plan only keeps the last 24 hours and this incident happened about 24 hours ago. I have since disabled Cloud Trace since it increased considerably the load (10x increase in this endpoint from 20ms to 200ms) and the app didn't scale up fast enough to prevent it from going down.

<p align="center">
<img style="max-width: 100%" src="https://user-images.githubusercontent.com/3451581/49224134-c5f4db00-f3c7-11e8-805f-3355a849ae46.png">
</p>

It is also possible that this measurement isn't accurate when new threads are called (which I guess is the case). By the way, if it helps, our production server is Puma v3.12 in clustered mode, with 2 workers [as recommended for 1 core](https://github.com/puma/puma/blob/master/docs/deployment.md#single-vs-cluster-mode) and 5 threads. Maybe the _thread_ limit is the problem?

**Comment by giovannibonetti** [comment]
Thank you, @blowmage! That is awesome! 
I will give it another try soon! 🙂

**Comment by blowmage** [comment]
If you want to try this before it is released, you can tell your `Gemfile` to use the code in the GitHub repo:

```ruby
gem "google-cloud-trace", github: "googleapis/google-cloud-ruby"
```

**Comment by giovannibonetti** [comment]
Yeah, I will do that! Thanks! 👍🏻
