### ISSUE TITLE
Permission Denied Error - Pub/Sub - Subscriber Role - Bug

### ISSUE THREAD

**Issue by theSociableme** [googleapis/google-cloud-ruby#2723]
#### Environment details

  - OS:  OSX  10.13.6
  - Ruby version: 2.4.1
  - Gem name and version:  'google-cloud-pubsub'

#### Steps to reproduce

  1. Create a Service Account with only Pub/Sub Subscriber Role
  2. Run code below

#### Code example

```ruby
require "google/cloud/pubsub"

pubsub = Google::Cloud::Pubsub.new(
  project_id: "my-project",
  credentials: "/path/to/keyfile.json"
)

# Retrieve a subscription
sub = pubsub.subscription "my-topic-sub"
# ^^^ this line will Error with Permission Denied
```

Stack Trace
```
Google::Cloud::PermissionDeniedError: 7:User not authorized to perform this action.
  /Users/markwagner/.rvm/gems/ruby-2.4.1/gems/google-cloud-pubsub-0.33.2/lib/google/cloud/pubsub/service.rb:480:in `rescue in execute'
  /Users/markwagner/.rvm/gems/ruby-2.4.1/gems/google-cloud-pubsub-0.33.2/lib/google/cloud/pubsub/service.rb:477:in `execute'
  /Users/markwagner/.rvm/gems/ruby-2.4.1/gems/google-cloud-pubsub-0.33.2/lib/google/cloud/pubsub/service.rb:170:in `get_subscription'
  /Users/markwagner/.rvm/gems/ruby-2.4.1/gems/google-cloud-pubsub-0.33.2/lib/google/cloud/pubsub/project.rb:287:in `subscription'
```

This Error does not happen with the same SA Role using the GO library

There seems to be a difference in the permissions needed between the two libraries.

**Comment by blowmage** [comment]
@theSociableme Can you try with specifying the `skip_lookup` option?

```ruby
require "google/cloud/pubsub"

pubsub = Google::Cloud::Pubsub.new(
  project_id: "my-project",
  credentials: "/path/to/keyfile.json"
)

# Retrieve a subscription
sub = pubsub.subscription "my-topic-sub", skip_lookup: true
```

**Comment by blowmage** [comment]
Here is the method [documentation](http://googleapis.github.io/google-cloud-ruby/docs/google-cloud-pubsub/latest/Google/Cloud/Pubsub/Project.html#subscription-instance_method).

> **`skip_lookup`** (`Boolean`) — Optionally create a Subscription object without verifying the subscription resource exists on the Pub/Sub service. Calls made on this object will raise errors if the service resource does not exist. Default is `false`.

**Comment by quartzmo** [comment]
Using `skip_lookup` might well work (since it won't make the `subscriber.get_subscription` API call), but shouldn't this work without `skip_lookup`? I quickly looked over the code and I can't see anything that involves Publisher, so it seems like it should work.

**Comment by blowmage** [comment]
When `skip_lookup` is not specified, the subscription resource is retrieved form the API. If the authenticated user does not have view permissions they will see the permission denied error shown in this issue.

**Comment by quartzmo** [comment]
Ah, gotcha. Role `roles/pubsub.subscriber` does not have permission `pubsub.subscriptions.get`.

https://cloud.google.com/pubsub/docs/access-control#tbl_roles

**Comment by quartzmo** [comment]
That's not exactly intuitive, but I'll change the issue type back to `question`.

**Comment by theSociableme** [comment]
Skip Lookup does not work as it fails further downstream, where it tries to get the subscription name again.

**Comment by blowmage** [comment]
What method is pulling the name? Can you send an error backtrace?

**Comment by blowmage** [comment]
Still waiting for a response, _but_ if you are creating a `Subscriber` object by calling `Subscription#listen`, then you will need to pass the optional `deadline` argument to avoid a `projects.subscriptions.get` call.

```ruby
require "google/cloud/pubsub"

pubsub = Google::Cloud::Pubsub.new

topic = pubsub.topic "my-topic"

# No API call is made to retrieve the subscription resource.
sub = topic.subscription "my-topic-sub", skip_lookup: true

# No API call is made to retrieve the subscription deadline.
subscriber = sub.listen deadline: 60 do |received_message|
  # process message
  received_message.acknowledge!
end

# Start background threads that will call block passed to listen.
subscriber.start

# Shut down the subscriber when ready to stop receiving messages.
subscriber.stop.wait!
```

**Comment by theSociableme** [comment]
It fails on this line 
```
sub = topic.subscription "my-topic-sub", skip_lookup: true
```
If it only has the Pub/Sub Subscriber Role,  I will see If I can locate the other call and update this ticket.

**Comment by theSociableme** [comment]
Actually scratch that....   You are getting the topic. I don't believe Pub/Sub Subscriber Role has access to the topic.  See my original example:
```
require "google/cloud/pubsub"

pubsub = Google::Cloud::Pubsub.new(
  project_id: "my-project",
  credentials: "/path/to/keyfile.json"
)

# Retrieve a subscription
sub = pubsub.subscription "my-topic-sub", skip_lookup: true

```
This line still fails 
```
sub = pubsub.subscription "my-topic-sub", skip_lookup: true
```

**Comment by blowmage** [comment]
It probably fails on the line previous. My apologies. The code I posted was wrong. You should not create a `topic` object. the line should be:

```ruby
sub = pubsub.subscription "my-topic-sub", skip_lookup: true
```

**Comment by blowmage** [comment]
You actually can create a topic object as long as you also pass the `skip_lookup` argument to that as well.

```ruby
# No API call is made to retrieve the subscription resource.
topic = pubsub.subscription "my-topic", skip_lookup: true

# No API call is made to retrieve the subscription resource.
sub = topic.subscription "my-topic-sub", skip_lookup: true
```

**Comment by blowmage** [comment]
> This line still fails
>
> `sub = pubsub.subscription "my-topic-sub", skip_lookup: true`

I don't see how it could. That call does not make any API calls. Can you post a backtrace of the error you are seeing, please?

**Comment by blowmage** [comment]
@theSociableme Ping.

My tests show that providing the `skip_lookup` and `deadline` arguments on these methods avoid the API calls that you client is not authorized to make.

**Comment by blowmage** [comment]
@theSociableme Can you post a backtrace of the error you get when you call:

```ruby
sub = pubsub.subscription "my-topic-sub", skip_lookup: true
```

**Comment by blowmage** [comment]
Closing for lack of response. If you follow the instructions above and still get errors, please open a new issue and reference this one.

**Comment by Nakilon** [comment]
I wonder how do I see the "No API call is made to" to debug it myself.
