### ISSUE TITLE
Run Load Job in a project that loads data in a table in a different project 

### ISSUE THREAD

**Issue by oblivione81** [googleapis/google-cloud-ruby#27368]
This is related to [this](https://github.com/googleapis/google-cloud-ruby/issues/2609) closed issue. 

The problem has been resolved for the #extract, #extract_job, #copy and #copy_job methods, but it's still not possible to create a load job on project A that writes to a table in project B, since the #load_job method of the Client class operates through a Table object that is obtained from the project specified in the client object itself. 

Now, I'm not totally sure the Google BigQuery API actually allows this (which would explain why the problem has not been fixed for the #load_job method). In that case, please let me know and close this ticket.

**Comment by oblivione81** [comment]
Thanks for this change, I tested it and it's working fine for the load_job case. 
I've noticed though that it's still not working for the streaming inserts case. 
This code tries to write from project_A to a table with path "project_B.my_dataset.my_table"

```
client = Google::Cloud::Bigquery.new(project_id: 'project_A')
dataset = client.dataset(dataset: 'my_dataset', project_id: 'project_B', skip_lookup: true)
table = dataset.table('my_table', skip_lookup: true)
result = table.insert(rows, skip_invalid: skip_invalid)
```
This code fails with
`Google::Cloud::NotFoundError: notFound: Not found: Dataset project_A:my_dataset`

Is it the case that this feature is not supported for streaming inserts?

**Comment by alvarowolfx** [comment]
it is supported for streaming inserts, but more changes are needed on the Ruby SDK to support that. On the PR I foresaw more work to be done to support all operations in different projects. 

For your use case @oblivione81, what other operations are you planning to use ?

**Comment by oblivione81** [comment]
> it is supported for streaming inserts, but more changes are needed on the Ruby SDK to support that. On the PR #27681 I foresaw more work to be done to support all operations in different projects.
> 
> For your use case @oblivione81, what other operations are you planning to use across different projects ?

Thanks @alvarowolfx . I don't foresee any other usage at the moment. I can confirm load jobs are working both when providing data directly through the client or when passing the uri of a GCS file. Streaming inserts are what is currently missing.

Do you have an idea of when this could be fixed, limited to streaming inserts?

**Comment by alvarowolfx** [comment]
@oblivione81 I've opened PR https://github.com/googleapis/google-cloud-ruby/pull/28097, but still missing unit tests. I'm not the core maintainer on Ruby (I maintain the Go and Node SDKs for BigQuery) and I'm doing my best to solve this issue for you. Unfortunately I'm gonna be on leave for the next two weeks, so best estimate that I can give you is for early January.

**Comment by alvarowolfx** [comment]
@oblivione81 PR https://github.com/googleapis/google-cloud-ruby/pull/28097 got merged, will be available when https://github.com/googleapis/google-cloud-ruby/pull/28111 is released

**Comment by oblivione81** [comment]
Wow, that was fast :-) Thanks a lot, very helpful.
