### ISSUE TITLE
Pub/Sub: remove delay!

### ISSUE THREAD

**Issue by jadekler** [googleapis/google-cloud-ruby#2785]
AFAIK, the [delay! alias](https://github.com/googleapis/google-cloud-ruby/blob/d6ec4d8ff336db553e3b171962e60324ea6d580d/google-cloud-pubsub/lib/google/cloud/pubsub/received_message.rb#L163) is misleading users into a use case that Pub/Sub does not outright support. Can we remove this method?

/cc @kolea2 @kamalaboulhosn

**Comment by blowmage** [comment]
Removing it would be a breaking change. Users that currently use it would break when upgrading.

**Comment by jadekler** [comment]
This library appears to be beta, so that seems doable despite being unfortunate. @kamalaboulhosn is the authority, but I believe this change will cause the ruby library to be inline with other library's API surfaces, which is AFAIK a blocker towards it being considered GA. Let me know if you know otherwise, though!

**Comment by kamalaboulhosn** [comment]
Yes, I would consider this a GA blocker. The delay! API (or something similar) is something we'd consider adding in the future, but we need to make sure it is built in a way that matches our intended use and is consistent across all 7 client libraries.
