### ISSUE TITLE
Firestore V1

### ISSUE THREAD

**Issue by blowmage** [googleapis/google-cloud-ruby#2789]
[Firestore V1 protos](https://github.com/googleapis/googleapis/tree/master/google/firestore/v1) have been released. Should google-cloud-firestore be updated to use v1 instead of v1beta1?

**Comment by quartzmo** [comment]
Yes, I think this is what we are supposed to do right now.

**Comment by blowmage** [comment]
@dazuma @TheRoyalTnetennba can one of you take this issue?

**Comment by dazuma** [comment]
Verified internal issue 122732041. Fixed by #2852.
