### ISSUE TITLE
Sidekiq Middleware

### ISSUE THREAD

**Issue by danielmbarlow** [googleapis/google-cloud-ruby#2836]
**Is your feature request related to a problem?**
Yes. The google-cloud-trace gem doesn't send any metrics for Sidekiq jobs

 **Describe the solution you'd like**
I would like to offer some code to add a Sidekiq Middleware to trace Sidekiq jobs (much as you have Rack and Faraday middleware already in the project.) 

 **Describe alternatives you've considered**
We could keep the code in our own project, but everyone benefits if we share it. I don't see any other gems that add this functionality, but if you know of any, I would be keen to hear of it.

 **Additional context**
Let me know whether or not you think this will be useful because I have a window of opportunity to work on it now.

**Comment by danielmbarlow** [comment]
Hi @dazuma I have been given approval to offer this code as a PR, but I would first like to know if you would like to include Sidekiq middleware in the gem.

**Comment by dazuma** [comment]
I would recommend instead adding such middleware to the [opencensus](https://github.com/census-instrumentation/opencensus-ruby) gem. We will shortly be separating out the instrumentation code (e.g. middleware) out of google-cloud-trace, and delegating it to opencensus.

**Comment by danielmbarlow** [comment]
Thanks. I'll have a look into it and if necessary open a PR there.
