### ISSUE TITLE
Different API between Transaction and ReadOnlyTransaction for Datastore

### ISSUE THREAD

**Issue by BenWhitehead** [googleapis/google-cloud-ruby#2854]
#### Environment details

  - OS: Linux 64-Bit Debian base kernel 4.18.10
  - Ruby version: `ruby 2.5.3p105 (2018-10-18 revision 65156) [x86_64-linux]`
  - Gem name and version: `google-cloud-datastore 1.4.0`

#### Steps to reproduce
When attempting to update some code to use a `read_only_transaction` I encountered the following error:
```
NoMethodError:
  undefined method `query' for #<Google::Cloud::Datastore::ReadOnlyTransaction:0x000055f1c7f9bc80>
```

It appears that this is due to the fact that `ReadOnlyTransaction` does not extend `Dataset` where as `Transaction` does.

Would it be possible to update `ReadOnlyTransaction` to extend `Dataset`?

#### Code example

Old Code
```ruby
  task_list_key = datastore.key "TaskList", "default"
  datastore.transaction do |tx|
    task_list = tx.find task_list_key
    query = tx.query("Task").ancestor(task_list)
    tasks_in_list = tx.run query
  end
```

Attempted new code
```ruby
  task_list_key = datastore.key "TaskList", "default"
  datastore.read_only_transaction do |tx|
    task_list = tx.find task_list_key
    query = tx.query("Task").ancestor(task_list)
    tasks_in_list = tx.run query
  end
```

Working new code
```ruby
  task_list_key = datastore.key "TaskList", "default"
  datastore.read_only_transaction do |tx|
    task_list = tx.find task_list_key
    query = datastore.query("Task").ancestor(task_list)
    tasks_in_list = tx.run query
  end
```

/cc: @frankyn

**Comment by blowmage** [comment]
@quartzmo I agree with your assessment.

**Comment by quartzmo** [comment]
Ping @BenWhitehead

**Comment by BenWhitehead** [comment]
Thanks for the pointers, I'll look at duplicating the `query` helper method on `ReadOnlyTransaction` and try to get a PR.
