### ISSUE TITLE
Update release branch naming convention

### ISSUE THREAD

**Issue by blowmage** [googleapis/google-cloud-ruby#2883]
Currently we are using the naming convention `release-<gem>-v<version>` for the branch used to create a release, and `<gem>/v<version>` for tag that is created once the release is completed. I suggest changing the release branch to use the convention `release/<gem>/v<version>` instead, as we don't allow `/` in gem names, but we do allow (and use) `-` in them. This should help extracting the `<gem>` and `<version>` values from the branch name, as well as help in navigating branches using clients that support nested display of branch names.

**Comment by quartzmo** [comment]
Out of consideration for the level of automation that has been built up around the current naming convention, I believe we should keep it. Please feel free to reopen this issue however if you feel you have a compelling reason for changing it that outweighs the costs.
