### ISSUE TITLE
undefined method `new` for Google::Cloud::Vision:Module

### ISSUE THREAD

**Issue by melihalan** [googleapis/google-cloud-ruby#2884]
Hi, I`m trying to run following tutorial to actually start building something but to no avail!

[https://codelabs.developers.google.com/codelabs/cloud-vision-api-ruby/index.html?index=..%2F..io2018#7]

My setup is ruby 2.6.0 on a windows machine. Gem versions updated so shouldn't be a copy of existing thread.

google-api-client (0.28.3, 0.10.1)
google-cloud-core (1.3.0, 0.21.1)
google-cloud-env (1.0.5)
google-cloud-storage (1.16.0, 0.24.0)
google-cloud-vision (0.32.2, 0.27.0)
google-gax (1.5.0)
google-protobuf (3.6.1 ruby x64-mingw32)
googleapis-common-protos (1.3.7)
googleapis-common-protos-types (1.0.2)
googleauth (0.8.0, 0.5.1)
grpc (1.18.0 x64-mingw32)

I've followed exactly same as tutorial, created a service account, have .json file set to env. variables, downloaded project and bundle installed.

1) There is this `rmagick` gem, that`s not working on windows, tried to download ImageMagick along with libraries in multiple versions, still not working so I gave up and deleted the gem from project file. Run bundle update and everything OK! (Not so easy but I skipped the other parts, as it probably relates to me not experienced at all)

2) I run irb, and require  "google/cloud/vision" good, than I put Google::Cloud::Vision.new and it gives no method error.

I appreciate all the support, but should things really be so hard and frustrating ?

**Comment by quartzmo** [comment]
> I put Google::Cloud::Vision.new and it gives no method error.

Hi @melihalan, thanks for opening this issue and reporting the trouble you've been having. Can you please paste in the full backtrace for this error?

**Comment by melihalan** [comment]
Thanks for so quick reply Chris ! There you go;

`irb(main):001:0> require "google/cloud/vision"`
`irb(main):002:0> vision = Google::Cloud::Vision.new`
`Traceback (most recent call last):`
        `4: from C:/Ruby26-x64/bin/irb.cmd:31:in '<main>'`
        `3: from C:/Ruby26-x64/bin/irb.cmd:31:in 'load'`
       ` 2: from C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/irb-1.0.0/exe/irb:11:in '<top (required)>'`
        `1: from (irb):2`
`NoMethodError (undefined method 'new' for Google::Cloud::Vision:Module)`
`irb(main):003:0>`

**Comment by quartzmo** [comment]
Thanks, I reproduced on OS X with ` google-cloud-vision-0.32.2`:

```sh
$ gem install google-cloud-vision
Fetching: google-cloud-vision-0.32.2.gem (100%)
The 0.32.0 release introduced breaking changes relative to the previous release, 0.31.0. For more details and instructions to migrate your code, please visit the migration guide: https://cloud.google.com/vision/docs/ruby-client-migration.
Successfully installed google-cloud-vision-0.32.2
Parsing documentation for google-cloud-vision-0.32.2
Installing ri documentation for google-cloud-vision-0.32.2
Done installing documentation for google-cloud-vision after 1 seconds
1 gem installed
$ irb
irb(main):001:0> require "google/cloud/vision"
=> true
irb(main):002:0> vision = Google::Cloud::Vision.new
NoMethodError: undefined method `new' for Google::Cloud::Vision:Module
	from (irb):2
	from /Users/quartzmo/.rbenv/versions/2.4.5/bin/irb:11:in `<main>'
irb(main):003:0> 
```

**Comment by quartzmo** [comment]
@melihalan I think the tutorial you used is out of date, and I'll see if I can find a way to report that.

Meanwhile, please try out the Preview in the API docs for the gem: http://googleapis.github.io/google-cloud-ruby/docs/google-cloud-vision/v0.32.2/

**Comment by quartzmo** [comment]
Or, if you would rather continue with the tutorial you linked, try using the older version of the gem, which the tutorial specifies in this step](https://codelabs.developers.google.com/codelabs/cloud-vision-api-ruby/index.html#4):

```sh
gem install google-cloud-vision -v 0.27.0
```

**Comment by quartzmo** [comment]
I made an attempt to notify the author of the tutorial that it needs to be updated.

Please note that the `0.32.0` release introduced breaking changes relative to the previous release, `0.31.0`. For more details and instructions to migrate your code, please visit the [migration guide]: (https://cloud.google.com/vision/docs/ruby-client-migration).
