### ISSUE TITLE
ResourceManager does not support Folders or specifying Parents for Projects

### ISSUE THREAD

**Issue by wfarr** [googleapis/google-cloud-ruby#2885]
**Is your feature request related to a problem? Please describe.**

Our GCP organization makes use of IAM on a folder basis. Some of these libraries (eg. ResourceManager) do not appear to be parent-aware at the moment, which means we're best off digging into lower-level abstractions.

 **Describe the solution you'd like**

I'd like for ResourceManager to be both support CRUD operations on Folders, as well as allow specifying a parent when creating projects (and I suppose for moving projects between folders too).

 **Describe alternatives you've considered**

While there are definitely alternatives available (such as not using folders), it's not a design choice I have control over in my organization.

 **Additional context**

I'm certainly happy to contribute towards making this better. I've got monkey-patches we're using locally for the moment, but I'd like to understand how I can best work with upstream on getting this support mainline.

If the answer is simply "sign the CLA and send a Pull Request", I'd like to suss out any design concerns the team might have about adding `parent` as an optional parameters to things like `create_project`, etc.

**Comment by wfarr** [comment]
Sure thing!

``` ruby
resource_manager = Google::Cloud::ResourceManager.new

# this works today
resource_manager.create_project("tokyo-rain-123", name: "test project")

# this does not work because parent is not passed down to the underlying `Google::Apis::CloudresourcemanagerV1::CloudResourceManagerService`
resource_manager.create_project("tokyo-rain-123", name: "test project", parent: { "type": "folder", "id": "12345"})

# this does not work today, because Folders are not implemented in the ResourceManager here yet
resource_manager.create_folder("this is a display_name")

# this similarly does not work
resource_manager.create_folder("this is a display_name", parent: { "type": "folder", "id": "12345" })

# this also does not work yet
resource_manager.create_folder("this is a display_name", parent: { "type": "organization", "id": "12345" })
```

Happy to answer any further questions!

**Comment by blowmage** [comment]
Because you say you have monkey-patches in place already, do you have a preference for remaining on the V1 API? Or would you prefer to use the V2 API?

**Comment by wfarr** [comment]
> Because you say you have monkey-patches in place already, do you have a preference for remaining on the V1 API? Or would you prefer to use the V2 API?

A brief glance seems to indicate V2 has the Folder support we'd hope for, but does not contain Projects. V1 contains projects, but lacks Folder support for CRUD operations (as best I can tell with a quick glance through the auto generated code).

Seems like we'll probably end up needing to use both in this case.

This aligns with the experience monkeypatching `Google::Cloud::ResourceManager::Manager#create_project` and `Google::Cloud::ResourceManager::Service#create_project` to support specifying a parent (folder that already existed in this case), and using `Google::Apis::CloudresourcemanagerV2::CloudResourceManagerService` to create and delete folders.

**Comment by blowmage** [comment]
I am going to close this issue. The feature was partially implemented. The Resource Manager team has not given us a greenlight to implement the rest.
