### ISSUE TITLE
Forking related Runtime error when using Stackdriver gems with multiple Puma workers

### ISSUE THREAD

**Issue by RSpace** [googleapis/google-cloud-ruby#2888]
As described in https://github.com/googleapis/google-cloud-ruby/issues/1860, I too am unable to use the Stackdriver ruby gem when using Puma with multiple workers.

Attempting to do so results in a "RuntimeError: grpc cannot be used before and after forking" error, and neither debugger, error reporting, logging or trace works, as they all seem to encounter the same error when they try to use GRPC.

Setting the number of Puma workers to 0, so no forking happens, immediately resolves the error and Stackdriver debugger, error reporting, logging and trace starts to work as expected.

I have been in communication with Google Cloud Support over the past few weeks to attempt to resolve this, and we arrived at the conclusion that it is indeed a problem with forking in the Stackdriver gems. Support has filed an issue with the Client Library team, but has asked me to also raise an issue here.

I also see that https://github.com/googleapis/google-cloud-ruby/issues/1860 has been closed asking for concrete examples, and this is one. Following the steps below, this is very easy to reproduce.

#### Environment details

  - OS: Google Cloud AppEngine Flex Ruby (standard ruby image)
  - Ruby version: 2.5.3
  - Gem name and version: stackdriver (0.15.3), google-cloud-debugger (0.32.6), google-cloud-error_reporting (0.30.5), google-cloud-logging (1.5.7), google-cloud-trace (0.33.6)

#### Steps to reproduce

  1. Create a new Rails 5 app
  3. Add the `stackdriver` and `puma` gems to the `Gemfile`
  3. Add a `puma.rb` configuration file to the `config` directory as seen below
  4. Start the server with `RAILS_ENV=production rails s` (stackdriver is not activated by default in the development environment)
  5. Open the autogenerated frontpage in a browser
  6. Observe the "RuntimeError: grpc cannot be used before and after forking" error in the console

#### Code example

```ruby
# Gemfile
gem "puma"
gem "stackdriver"

# config/puma.rb
workers 2 # Will work with 0, will also fail with 1 or any other number above 0.
```

Hope this help you guys to get this long-standing issue resolved.

**Comment by blowmage** [comment]
Can you post the backtrace of the error?

**Comment by blowmage** [comment]
Three of the Stackdriver gems have recent releases that include fixes for running in forking environments. Can you upgrade to the following gems are see if you still see this?

* google-cloud-logging 1.6.0
* google-cloud-debugger 0.33.0
* google-cloud-error_reporting 0.31.0

**Comment by RSpace** [comment]
I stand corrected. I thought I had the newest gem versions, but after upgrading to the newest version everything started to fine with multiple Puma workers. So the fixes for running in forking environments seems to be working!
