### ISSUE TITLE
Prepare for google-protobuf 3.7

### ISSUE THREAD

**Issue by blowmage** [googleapis/google-cloud-ruby#2900]
The upcoming release of google-protobuf 3.7.0 will change how Protobuf resources are serialized to/from JSON. It looks like both `Debuggee#to_grpc` and `ErrorEvent#to_grpc` are relying on the current behavior, and will break when using the upcoming release.

There are also many test fixtures that rely on the current behavior, and those tests will need to be updated when new gem is released.

**Comment by dazuma** [comment]
@blowmage Is this complete now?

**Comment by blowmage** [comment]
Yes.
