### ISSUE TITLE
`Assertion failed ` protobuf error on Windows 10 

### ISSUE THREAD

**Issue by haitte** [googleapis/google-cloud-ruby#2908]
#### Environment details

  - OS: Windows 10 Home
  - Ruby version: ruby 2.5.3p105 (2018-10-18 revision 65156) [x64-mingw32]
  - Gem name and version: google-cloud-firestore (0.25.0)

#### Steps to reproduce
1)
```
require "google/cloud/firestore"

project_id= "xxxxxxx"

firestore = Google::Cloud::Firestore.new project_id: project_id

puts "Created Cloud Firestore client with given project ID."

restuarants_ref = firestore.col "restuarants"
restuarants_ref.get do |restuarant|
  puts "#{restuarant.document_id} data: #{restuarant.data}."
end
```
2) ruby example.rb
#### Full backtrace

```sh
Created Cloud Firestore client with given project ID.
Assertion failed!

Program: C:\Ruby25-x64\bin\ruby.exe
File: ../../../../ext/google/protobuf_c/upb.c, Line 6331

Expression: val.ctype == t->ctype
```

**Comment by blowmage** [comment]
Hi @haitte, thanks for opening the issue. We need more information from you. We need the full error details. The error object has an attribute, `backtrace`, that includes the call stack when the error happened. Or, you can send the "Traceback" generated when the error is printed. For example, here is the error information printed while using IRB:

```
$ irb
irb(main):001:0> 1 / 0
Traceback (most recent call last):
        3: from /Users/blowmage/.rubies/ruby-2.5.3/bin/irb:11:in `<main>'
        2: from (irb):1
        1: from (irb):1:in `/'
ZeroDivisionError (divided by 0)
```

And, here is the same error printed by an unhandled error outside of IRB:

```
$ ruby -e "1 / 0"
Traceback (most recent call last):
	1: from -e:1:in `<main>'
-e:1:in `/': divided by 0 (ZeroDivisionError)
```

**Comment by igorpeshansky** [comment]
Is this https://github.com/protocolbuffers/protobuf/issues/5025?

**Comment by blowmage** [comment]
Does using google-protobuf 3.7.0.rc.3 make this error go away?

**Comment by quartzmo** [comment]
Closing due to lack of response from original poster.
