### ISSUE TITLE
Access Scopes Documentation

### ISSUE THREAD

**Issue by LandonSchropp** [googleapis/google-cloud-ruby#2911]
#### Environment details

  - OS: macOS 10.14.2
  - Ruby version: 2.6.1
  - Gem name and version: stackdriver 0.15.3

#### Steps to reproduce

The [Stackdriver gem readme](https://github.com/googleapis/google-cloud-ruby/blob/master/stackdriver/README.md) states:

> If you are running on Google Kubernetes Engine, you must explicitly add https://www.googleapis.com/auth/cloud-platform to the API access scopes when creating the cluster. Authentication will then happen automatically.

My team is trying to install Stackdriver into a Rails app running in GKI and having a difficult time with this. [This link](https://cloud.google.com/kubernetes-engine/docs/how-to/access-scopes) makes it look like access scopes have been deprecated, and we're having a lot of trouble finding any reference to them in our cluster.

Is this documentation out of date? Is there a better way to do this?

#### Code example

N/A

#### Full backtrace

N/A

**Comment by LandonSchropp** [comment]
Sorry in advance if this isn't a documentation bug.

**Comment by blowmage** [comment]
> [This link](https://cloud.google.com/kubernetes-engine/docs/how-to/access-scopes) makes it look like access scopes have been deprecated

Hi, thanks for the issue. I believe that the guide you link to is stating that previously there were specific access scopes that were granted automatically, and with Google Kubernetes Engine version 1.10 those specific scopes are no longer granted automatically. But access scopes as a concept remain in Google Kubernetes Engine. So yes, automatically granting those specific scopes (`compute-rw`, `storage-ro`) is deprecated, but the ability to set access scopes is not deprecated.

Did I understand you question correctly? If not, can you restate it?

**Comment by DanielJoyce** [comment]
So we have to rebuild the cluster with those scopes for stackdriver logging to work?

**Comment by LandonSchropp** [comment]
Thanks for the quick reply @blowmage. And thanks for being patient with me. I'm new to GKE and its permissions.

We're trying to understand the steps we need to take to enable communication with the error reporting API. After digging around a bit more, I found [this documentation](https://cloud.google.com/compute/docs/access/service-accounts#accesscopesiam) on access scopes.

> Access scopes are the legacy method of specifying permissions for your instance. Before the existence of IAM roles, access scopes were the only mechanism for granting permissions to service accounts. Although they are not the primary way of granting permissions now, you must still set up access scopes when configuring an instance to run as a service account.

My impression after reading that is that access scopes are a legacy method of adding permissions. You're right that the documentation doesn't state that they'll be removed, but it does seem like Google is pushing us towards service accounts and IAM.

I think after digging into this some more, we have a few more questions that aren't answered by the documentation we've been able to find:

* Do the access scopes above have any corresponding roles to IAM? 
* What IAM roles or permissions should we be adding? 
* How do we determine which service account corresponds with our current cluster?
* Would it be helpful to update the documentation to include more information on this topic?

One other thing to mention: we're having trouble finding consistent documentation for setting up Stackdriver. We're happy to link to documents that seem to slightly conflict.

**Comment by LandonSchropp** [comment]
It looks some somebody else ran into the same issue we're experiencing and posted it on StackOverflow: https://stackoverflow.com/questions/54019706/stackdriver-error-reporting-for-ruby-running-on-gke.

**Comment by blowmage** [comment]
It sounds like these are all questions about GKE, and not specific to the Ruby clients. Unfortunately, we don't have the expertise in GKE to provide in-depth support for it. I would suggest asking questions on StackOverflow, or creating an issue in the Google Cloud Support console if you have a support contract with Google.

**Comment by LandonSchropp** [comment]
I completely see what you mean about how this may be a support issue. However, I do think the current documentation is either incomplete or does not reflect the current state of GKE. After following the instructions, we're still unable to send errors from GKI. Is there a way to update the documentation?

**Comment by DanielJoyce** [comment]
https://cloud.google.com/kubernetes-engine/docs/how-to/access-scopes

This says they're basically deprecated.

**Comment by quartzmo** [comment]
@LandonSchropp Yes, if we can make a case that this statement is out of date and should be removed:

> If you are running on Google Kubernetes Engine, you must explicitly add https://www.googleapis.com/auth/cloud-platform to the API access scopes when creating the cluster. Authentication will then happen automatically.

We can certainly submit a PR in this repo to update the documentation. It may take a little time to figure out exactly what replacement content to add to the README. In fact, if you are interested in contributing, feel free to open the PR yourself; otherwise we will try to get to it as quickly as we can.

**Comment by LandonSchropp** [comment]
@quartzmo Thanks for the reply! That would be really helpful. I'm always happy to contribute to open source, but I still don't feel like I have a good grasp on what that section should say. My team has just managed to get this working locally with the help of @blowmage but we haven't had a chance to push that up to GKE yet.

**Comment by quartzmo** [comment]
> I still don't feel like I have a good grasp on what that section should say.

@LandonSchropp No problem. After you've reached the goal that you stated above:

> We're trying to understand the steps we need to take to enable communication with the error reporting API.

Please let us know if you see an opportunity to improve the documentation.

**Comment by quartzmo** [comment]
@LandonSchropp Do you still feel like the Stackdriver gem README needs to be changed?

**Comment by LandonSchropp** [comment]
@quartzmo Maybe it's just a knowledge gap on my part or my team's part, but we were never able to get Stackdriver working in GKE with authentication happening automatically. We eventually gave up, created a service account and injected the credentials directly into the gem's configuration. At least from our perspective, what was provided wasn't enough information to actually get it working.

I recognize it's a challenge from your perspective because you can't support every setup or every team running into issues. GKE is also outside of your direct area of control. However, this was also a difficult process on our part and we struggled for a few days before we got it working in production.=

I wish that I could give you a more concrete answer to how the documentation could be improved, but we honestly don't know what we missed in the process.

**Comment by quartzmo** [comment]
@LandonSchropp Thank you, we'll keep this issue open and try to improve the documentation. Appreciate all your help!

**Comment by LandonSchropp** [comment]
Thank you!

**Comment by laurawadden** [comment]
> @quartzmo Maybe it's just a knowledge gap on my part or my team's part, but we were never able to get Stackdriver working in GKE with authentication happening automatically. We eventually gave up, created a service account and injected the credentials directly into the gem's configuration. At least from our perspective, what was provided wasn't enough information to actually get it working.
> 
> I recognize it's a challenge from your perspective because you can't support every setup or every team running into issues. GKE is also outside of your direct area of control. However, this was also a difficult process on our part and we struggled for a few days before we got it working in production.
> 
> I wish that I could give you a more concrete answer to how the documentation could be improved, but we honestly don't know what we missed in the process. However, I do feel that something is missing.

I have also been struggling with setting this up - wasting about 2 days because of unclear documentation.

I'm running a Rails App in GKE and trying to get the Error Reporting API to show errors. The documentation "it should just work" when it's not working is quite frustrating. 

I'm now going to try to inject service account json into my app, but don't know where/how I went wrong. And debugging this issue is also not easy. Any tips appreciated!

**Comment by LandonSchropp** [comment]
@laurawadden We've given up and have switched to different services. Honeybadger was easy to set up for logging, and we're looking at LogicMonitoring for some of the infrastructure work.

**Comment by fhinkel** [comment]
Greetings, we're closing this. Looks like the issue got resolved. Please let us know if the issue needs to be reopened.
