### ISSUE TITLE
Storage: batch operations

### ISSUE THREAD

**Issue by renchap** [googleapis/google-cloud-ruby#2914]
Thanks for stopping by to let us know something could be better!

 **Is your feature request related to a problem? Please describe.**
I want to delete a lot of files in GCS at the same time, and I can't use batched requests to do it

 **Describe the solution you'd like**
A way to batch calls to GCS, similar to what the underlying lib does: https://github.com/googleapis/google-api-ruby-client#batches

 **Describe alternatives you've considered**
I am currently deleting every file in a loop, which is not efficient

 **Additional context**
I am the maintainer of https://github.com/renchap/shrine-google_cloud_storage/ and it would be much more efficient to be able to batch our delete requests.

Example use case: cleaning up our test bucket after a test run.

We previously used `google-api-client` but we have been forced to switch to a less-optimized way when we switched to the `google-cloud-storage` gem.

**Comment by quartzmo** [comment]
@renchap Thank you for your work with [shrine-google_cloud_storage](https://github.com/renchap/shrine-google_cloud_storage/)! We really appreciate this integration. In October I helped a Google Cloud Storage user with some authentication problems. I believe he attempted to contribute some helpful documentation but it seems he made a mistake and [the PR](https://github.com/renchap/shrine-google_cloud_storage/pull/30) is stalled.

We will look into this within the next two days.

See: renchap/shrine-google_cloud_storage/pull/31

**Comment by quartzmo** [comment]
@frankyn Does this generally sound OK to you?

**Comment by frankyn** [comment]
Thanks for the ping @quartzmo, I'm still gathering context on this feature and if it should be supported in google-cloud-ruby. There's future feature expectations that aren't aligned with batch operations. I'll follow-up soon. I appreciate your patience!

**Comment by renchap** [comment]
Maybe some new methods for batched base operations could be an alternative? Like `Bucket#delete_files("object1", "object2")` which does a single batched request?

**Comment by frankyn** [comment]
Clarified future expectations with the GCS team. @quartzmo could you mark this as a FR to surface the batch API in google-cloud-ruby? Batch operations should be available in the library.

**Comment by quartzmo** [comment]
@frankyn Can you please specify what can be surfaced, and when? Thanks!

**Comment by quartzmo** [comment]
Ping @frankyn: Just want to be clear about what batch feature(s) to surface and when is OK to release them?

**Comment by blowmage** [comment]
Is this feature affected by the [discontinuation of global HTTP Batch endpoints](
https://developers.googleblog.com/2018/03/discontinuing-support-for-json-rpc-and.html)?

**Comment by frankyn** [comment]
Apologies @quartzmo, I think it's best to file this request across languages to have a consistent experience. That will en-queue it for some time under other priorities.

The feature is GA and the FR can be marked as help wanted until it's prioritized. 

HTH for now.

**Comment by frankyn** [comment]
@blowmage I missed your question. No, last I checked Cloud Storage isn't part of that deprecation. I'll double check next week if that's still the case.

**Comment by frankyn** [comment]
Hi @renchap, I have a few clarifying questions.

1. Are you attempting to delete an entire bucket or are there special conditions for deletion?
2. There's a limitation of 100 files per batch request, and it would require you to list all objects in a bucket then adding them to a delete batch request. Does this still meet your expectation for batch requests? Source: https://cloud.google.com/storage/docs/json_api/v1/how-tos/batch#overview

**Comment by renchap** [comment]
> 1. Are you attempting to delete an entire bucket or are there special conditions for deletion?

I guess you mean deleting an entire bucket *contents*. If there is a way to do this with 1 call, then it would cover some use-cases. For example in `shrine-google_cloud_storage` we want to clear the bucket's content after each test in the test suite (but not create a new bucket for each one).
Users requested to be able to provide a condition to only delete some files (see https://github.com/renchap/shrine-google_cloud_storage/pull/31). We can fallback to manually deleting files if such a condition is provided, but batches would help in this case.

> 2. There's a limitation of 100 files per batch request, and it would require you to list all objects in a bucket then adding them to a delete batch request. Does this still meet your expectation for batch requests? Source: https://cloud.google.com/storage/docs/json_api/v1/how-tos/batch#overview

This would be fine, the previous implementation (that used `google-api-client` directly) did this. This allowed to make 1 request to get objects, then `objects_count / 100` requests to delete them, not `1 + objects_count`, which is a nice improvement (and I guest GCS has some optimisation on the backend for mass-deletions)

**Comment by quartzmo** [comment]
Ping @frankyn

**Comment by frankyn** [comment]
Apologies for the delay.

We need to queue this request as I'm not sure how the feature should be surfaced. Other libraries are also experiencing a similar issue from not supporting this feature. I'll need to define a plan for support, it will take time to support. 

An alternative to clearing test bucket using the Batch API or individual requests is to set an [Object Lifecycle Management policy](https://cloud.google.com/storage/docs/lifecycle) on a Bucket. The policy can be used to delete files that live longer than a day. If it's a test bucket then this feature will help clean up the bucket daily as a background batch job.

```ruby
require "google/cloud/storage"

storage = Google::Cloud::Storage.new

bucket = storage.create_bucket "my-bucket" do |b|
  b.lifecycle.add_delete_rule age: 1
end
```

**Comment by frankyn** [comment]
For future updates please review tracking bug: https://issuetracker.google.com/issues/142641783.
@quartzmo could you close this issue?

**Comment by taman9333** [comment]
@frankyn Any update on this ?
