### ISSUE TITLE
Datastore requests hang with 4:Deadline Exceeded when run using RSpec in test env

### ISSUE THREAD

**Issue by nburt** [googleapis/google-cloud-ruby#2916]
We've been having some issues while testing an API endpoint where the backend hits Datastore. The test is hitting the endpoint and expecting JSON to be returned, some of the JSON body is pulled from our PostgresQL db, the rest is from Datastore.

I've wrapped the test in a `VCR.use_cassette` block to capture the Datastore requests and play them back for future test runs.

Whenever I run the test the request hangs in `google-gax-1.5.0/lib/google/gax/api_callable.rb:373`. When printing out the exception in that rescue, I get `4:Deadline Exceeded` over and over again.

Requests all work correctly when running the app in development. I haven't deployed to other environments yet.

I've tried a bunch of different workarounds found in github issues. I was wondering if it had something to do with gRPC/Puma thread issues as in https://github.com/googleapis/google-cloud-ruby/issues/691 but that has not worked either.

#### Environment details

  - OS: OSX 10.13.6
  - Ruby version: 2.6.1 (also tried 2.5.1)
  - Gem name and version: google-cloud-ruby 1.5.0

#### Steps to reproduce

1. Setup Rails app with initializer/class that performs query to datastore
1. Write RSpec test that runs the initializer code and then performs the query. This has hung with and without wrapping the test code in a VCR block

#### Code example

```ruby
# initializer
require 'google/cloud/datastore'

::Google::Cloud::Datastore.configure do |config|
  config.project_id = '<project id>'
  config.credentials = '<path to creds>'
end

# class
datastore = ::Google::Cloud::Datastore.new
key = @datastore.key('Query', 'uid')
query = @datastore.query('Query').ancestor(key).order('timestamp', :desc).limit(1)
result = datastore.run(query).first
```

#### Full backtrace

```sh
4:Deadline Exceeded

================================================================================
Received USR1 signal; printing all 4 thread backtraces.

Main thread backtrace:
/Users/nateburt/workspace/app/spec/spec_helper.rb:19:in `backtrace'
/Users/nateburt/workspace/app/spec/spec_helper.rb:19:in `block (2 levels) in <top (required)>'
/Users/nateburt/workspace/app/spec/spec_helper.rb:15:in `each'
/Users/nateburt/workspace/app/spec/spec_helper.rb:15:in `block in <top (required)>'
/Users/nateburt/.rvm/gems/ruby-2.6.1/gems/google-gax-1.5.0/lib/google/gax/api_callable.rb:373:in `sleep'
/Users/nateburt/.rvm/gems/ruby-2.6.1/gems/google-gax-1.5.0/lib/google/gax/api_callable.rb:373:in `rescue in block in retryable'
/Users/nateburt/.rvm/gems/ruby-2.6.1/gems/google-gax-1.5.0/lib/google/gax/api_callable.rb:358:in `block in retryable'
/Users/nateburt/.rvm/gems/ruby-2.6.1/gems/google-gax-1.5.0/lib/google/gax/api_callable.rb:230:in `block in create_api_call'
/Users/nateburt/.rvm/gems/ruby-2.6.1/gems/google-gax-1.5.0/lib/google/gax/api_callable.rb:260:in `block in create_api_call'
/Users/nateburt/.rvm/gems/ruby-2.6.1/gems/google-cloud-datastore-1.5.0/lib/google/cloud/datastore/v1/datastore_client.rb:314:in `run_query'
/Users/nateburt/.rvm/gems/ruby-2.6.1/gems/google-cloud-datastore-1.5.0/lib/google/cloud/datastore/service.rb:106:in `block in run_query'
/Users/nateburt/.rvm/gems/ruby-2.6.1/gems/google-cloud-datastore-1.5.0/lib/google/cloud/datastore/service.rb:188:in `execute'
/Users/nateburt/.rvm/gems/ruby-2.6.1/gems/google-cloud-datastore-1.5.0/lib/google/cloud/datastore/service.rb:105:in `run_query'
/Users/nateburt/.rvm/gems/ruby-2.6.1/gems/google-cloud-datastore-1.5.0/lib/google/cloud/datastore/dataset.rb:449:in `run'
```

Thanks for your help!

**Comment by blowmage** [comment]
The google-cloud-datastore gem depends on the grpc gem to connect to the Datastore API. And it communicates to the Datastore API via gRPC, which is based on HTTP/2, not HTTP/1.1. I don't know that the VCR gem supports HTTP/2, gRPC, or the grpc gem, and I don't see the grpc gem listed on its [README](https://github.com/vcr/vcr). My guess here is VCR is not the right tool to use to mock the Datastore API calls.

**Comment by nburt** [comment]
That's fair in regards to VCR, I can look into other options there. Do you have recommendations outside of the emulator or stubbing?

I experience the same problems without VCR, do you know of issues related to RSpec or test environments?

**Comment by nburt** [comment]
I was curious about whether VCR would work or not and it at least works for the authentication request (`POST https://oauth2.googleapis.com/token`) and the yml file recording the request does get written correctly. The request just hangs on `datastore.run(query)`.

**Comment by blowmage** [comment]
> it at least works for the authentication request

That makes sense as the Oauth request for a token is an HTTP/1.1 request, while the Datastore requests are HTTP/2 request using gRPC.

> Do you have recommendations outside of the emulator or stubbing?

I do not. In our tests we mock the requests and responses using the client object, not at the network level.

> do you know of issues related to RSpec or test environments?

I am not aware of any issues.

**Comment by dinshaw** [comment]
Just ran into this problem. Anyone have suggestion as to an alternative or workaround?

**Comment by nburt** [comment]
I don't use datastore anymore but at the time we ended up stubbing the object directly with RSpec: https://relishapp.com/rspec/rspec-mocks/docs/configuring-responses/returning-a-value

**Comment by quartzmo** [comment]
> we ended up stubbing the object directly 

This is what I would recommend as well for unit testing. Full mocks or stubs above the network level.
