### ISSUE TITLE
Unable to log in locally via a service account credentials file.

### ISSUE THREAD

**Issue by LandonSchropp** [googleapis/google-cloud-ruby#2917]
#### Environment details

  - OS: macOS 10.14
  - Ruby version: 2.6.1
  - Gem name and version: 0.15.3

#### Steps to reproduce

1. Create a service account and add the project owner role. (I know this is overkill, but we haven't been able to get this to work at any role level.)
2. Download the credentials and copy them into a file named `service-account.json`.
3. In the `config/application.rb` file in a Rails app, add the following:

```
config.project_id = "<PROJECT_ID>"
config.credentials = "service-account.json"
config.google_cloud.use_error_reporting = true
```

#### Code example

Open up the Rails console. When the console starts up, it spits out the following errors:

```
Note: Google::Cloud::Logging is disabled because it failed to authorize with the service. (Could not load the default credentials. Browse to
https://developers.google.com/accounts/docs/application-default-credentials
for more information
) Falling back to the default Rails logger.
Note: Google::Cloud::Debugger is disabled because it failed to authorize with the service. (Could not load the default credentials. Browse to
https://developers.google.com/accounts/docs/application-default-credentials
for more information
)
Note: Google::Cloud::ErrorReporting is disabled because it failed to authorize with the service. (Could not load the default credentials. Browse to
https://developers.google.com/accounts/docs/application-default-credentials
for more information
)
Note: Google::Cloud::Trace is disabled because it failed to authorize with the service. (Could not load the default credentials. Browse to
https://developers.google.com/accounts/docs/application-default-credentials
for more information
)
```

If we try setting this via the `GOOGLE_APPLICATION_CREDENTIALS` environment variable, the error goes away.

```
export GOOGLE_APPLICATION_CREDENTIALS="service-account.json"
export GOOGLE_CLOUD_PROJECT="<project-id>"
```

However, if we try to actually create an error, our promise is rejected.

```
irb(main):057:0> promise = Google::Cloud::ErrorReporting.report Exception.new "Oh no!"
=> #<Concurrent::Promises::Future:0x00007fdf5ba08470 pending>
irb(main):058:0> promise.state
=> :rejected
```

If we try to determine what went wrong, we find an error that looks like it might be an internal gem error:

```
irb(main):059:0> promise.reason
=> #<NoMethodError: undefined method `configuration' for Google::Cloud::ErrorReporting:Module
Did you mean?  configure>
```

**Comment by LandonSchropp** [comment]
After digging into this for a while, we think the problem might be here: https://github.com/googleapis/google-cloud-ruby/blob/master/google-cloud-error_reporting/lib/google/cloud/error_reporting/async_error_reporter.rb#L187

When we commented out that line, our promise was fufilled.

**Comment by LandonSchropp** [comment]
We were able to get the promise to be fufilled by monkey patching the `ErrorReporing` module.

```
module Google::Cloud::ErrorReporting
  module_function def configuration
    OpenStruct.new
  end
end
```

This isn't something we want to keep in our code base, but it might be a quick workaround.

**Comment by LandonSchropp** [comment]
Even with this monkey patch, we don't see any errors showing up in Stackdriver. The only way we've been able to get errors to show up is by using `gcloud auth application-default login`.

**Comment by blowmage** [comment]
> 3\. In the `config/application.rb` file in a Rails app, add the following:
> 
> ```
> config.project_id = "<PROJECT_ID>"
> config.credentials = "service-account.json"
> config.google_cloud.use_error_reporting = true
> ```

I believe you should be using `config.google_cloud.project_id`, not `config.project_id`.

**Comment by blowmage** [comment]
> #<NoMethodError: undefined method `configuration' for Google::Cloud::ErrorReporting:Module

Ugh, that's unfortunate. I'm pushing a fix right now. We will investigate how this was not caught in the test coverage.

**Comment by LandonSchropp** [comment]
Thanks for the quick reply and the continued help @blowmage!

Good call on #3. That fixed that problem.

With the monkey patch, we were able to get a fulfilled state in our promise. However, the errors never did show up in `Stack Driver Error Monitoring`. I double checked the credentials inside of the gem and they're definitely for the service account we created.

Currently, we've still only seen errors show up in Stackdriver when we've been logged in locally via the `gcloud auth application-default` command.

**Comment by LandonSchropp** [comment]
Are there different configuration objects for the different authentication methods? Maybe that error wasn't caught in test coverage because one of the other approach, such as `gcloud`, creates a different configuration object that includes the `configuration` method. The tests would then be able to exercise that code path.

Just speculating.

**Comment by LandonSchropp** [comment]
Also, if you guys are curious about what the process of integrating the Stackdriver gem has looked like from an outside perspective, we've be happy to hop on a call and show you. 😃

**Comment by blowmage** [comment]
Can you try adding something like the following to your monkey-patch to see what errors are being raised by ErrorReporting as it tries to call the API?

```ruby
module Google::Cloud::ErrorReporting
  module_function def configuration
    on_error = -> (err) { puts err.inspect; puts err.backtrace.inspect }
    OpenStruct.new on_error: on_error
  end
end
```

**Comment by LandonSchropp** [comment]
Ah ha! The error was being masked by the promise, and my old monkey patch discarded it.

```
#<Google::Cloud::ErrorReporting::ErrorReporterError: Error reporting error_event: 7:Stackdriver Error Reporting API has not been used in project <ID> before or it is disabled. Enable it by visiting https://console.developers.google.com/apis/api/clouderrorreporting.googleapis.com/overview?project=<ID> then retry.
```

So after all that, the real issue was we hadn't turned on the API. 😟

Is that the normal level of error reporting from the `stackdriver` gem? It would be really helpful if it printed that out by default while trying to set up the gem for the first time. Barring that, a debugging section in the readme might be helpful.

Thanks again for the help.

**Comment by blowmage** [comment]
Awesome! I'm glad that you can get it to work. We will get the fix released ASAP.

> Is that the normal level of error reporting from the `stackdriver` gem?

We have a problem with clients based on gRPC. The grpc gem can't be used both before and after a fork, because of how resources are acquired. Because of this we delay instantiating a gRPC connection until it is needed, hopefully post-fork. This means we can't make an API call on app boot to make this check. So unfortunately this is what we are stuck for this behavior for now.

**Comment by jorge0136** [comment]
> > 3. In the `config/application.rb` file in a Rails app, add the following:
> > ```
> > config.project_id = "<PROJECT_ID>"
> > config.credentials = "service-account.json"
> > config.google_cloud.use_error_reporting = true
> > ```
> 
> I believe you should be using `config.google_cloud.project_id`, not `config.project_id`.

Regarding `config.project_ID` vs. `config.google_cloud.project_id`: 

I know this documentation is well outside of this repo but as an FYI please search for "You can also set shared configuration for all Stackdriver gems using:" on the following [google documentation page](https://cloud.google.com/logging/docs/setup/ruby).

**Comment by blowmage** [comment]
I see the following code example for “You can also set shared configuration for all Stackdriver gems using”:

```ruby
# Add this to config/environments/*.rb
Rails.application.configure do |config|
  # Stackdriver Shared parameters
  config.google_cloud.project_id = "YOUR-PROJECT-ID"
  config.google_cloud.keyfile    = "/path/to/service-account.json"
end
```

**Comment by blowmage** [comment]
There is a second code example that also uses "You can also set shared configuration for all Stackdriver gems using", but it shows using `Google::Cloud.configure`, not `Rails.application.configure`:

```ruby
require "stackdriver"

Google::Cloud.configure do |config|
  # Stackdriver Shared parameters
  config.project_id = "YOUR-PROJECT-ID"
  config.keyfile    = "/path/to/service-account.json"
end
```

**Comment by blowmage** [comment]
Oops, I didn't mean to close this issue last night.

**Comment by blowmage** [comment]
Oh wait, I did mean to close this one with the PR. Re-closing.
