### ISSUE TITLE
[Documentation Issue] 

### ISSUE THREAD

**Issue by Avemark** [googleapis/google-cloud-ruby#2933]
"[Setup Authentication](http://googleapis.github.io/google-cloud-ruby/docs/google-cloud-dialogflow/v0.2.3/)" link does not actually link to Authentication information. Further links on the following page leads to an "[authentication guide](https://googleapis.github.io/google-cloud-ruby/docs/google-cloud/latest/file.AUTHENTICATION)" that does not as much explain authentication as inform you that you should be running the code on a machine where authentication is already available.

A mention on where to get credentials, and an example or description of a credential json would be very helpful here.  Also, I'd suggest a direct link to the authentication guide from the first page.

**Comment by quartzmo** [comment]
@Avemark Thank you for reporting the broken link at "Setup Authentication". And I agree that the top-level authentication guide for google-cloud-ruby that you link seems incomplete.

What do you think of the [authentication guide for google-cloud-datastore](http://googleapis.github.io/google-cloud-ruby/docs/google-cloud-datastore/v1.5.1/file.AUTHENTICATION.html)? Is it adequate?

**Comment by quartzmo** [comment]
> A mention on where to get credentials, and an example or description of a credential json would be very helpful here.

@Avemark If we fix the "Setup Authentication" to link to an authentication guide that is similar to the [authentication guide for google-cloud-datastore](http://googleapis.github.io/google-cloud-ruby/docs/google-cloud-datastore/v1.5.1/file.AUTHENTICATION.html) (but adapted to google-cloud-dialogflow), will that work for you?

**Comment by quartzmo** [comment]
Should the scope of this issue be expanded to all generated packages that currently lack an authentication guide?

**Comment by Avemark** [comment]
@quartzmo The linked authentication guide seems a lot more thorough, and a direct link to something similar would have cut down on the time needed for my discovery process a lot.

**Comment by quartzmo** [comment]
@blowmage @dazuma @TheRoyalTnetennba Is there any reason why the generated packages do not have an `AUTHENTICATION.md` file? (See [datastore/AUTHENTICATION.md](https://github.com/googleapis/google-cloud-ruby/blob/master/google-cloud-datastore/AUTHENTICATION.md) for example.)

If not, do we want one? If so, should I add them manually, or can I update the generation somehow?

**Comment by blowmage** [comment]
It is not part of the generation process. We would have to add them manually, or configure each gem's `synth.py` script to generate one.

**Comment by quartzmo** [comment]
I'll start work on a PR to add this to `synth.py`.
