### ISSUE TITLE
[KMS] Acceptance/smoke test

### ISSUE THREAD

**Issue by dazuma** [googleapis/google-cloud-ruby#2980]
KMS is a gapic-generated library (and gapic doesn't generate any smoke test itself), but the team is asking for a basic smoke test for it. It should be sufficient to make a simple call to `list_key_rings`.

**Comment by quartzmo** [comment]
> gapic doesn't generate any smoke test itself

Do you know why some generated packages appear to have been generated with smoke tests?

For example, `google-cloud-ruby/google-cloud-bigquery-data_transfer/acceptance/google/cloud/bigquery/data_transfer/v1/data_transfer_service_smoke_test.rb`, which was added with the following commit message?

```
Generate Bigquery Data Transfer

Command Log:


set DEST ~/workspace/google-cloud-ruby
git clone https://github.com/googleapis/googleapis.git
cd googleapis
artman --config google/cloud/bigquery/datatransfer/artman_bigquerydatatransfer.yaml generate ruby_gapic
cp -rv ./artman-genfiles/ruby/google-cloud-ruby/google-cloud-bigquerydatatransfer $DEST
```

**Comment by dazuma** [comment]
As far as I can tell, some of the gapic configs include a smoke test specification, which the current gapic generator (for Ruby) turns into both an acceptance test and a "preview" in the library readme. For BigQuery Data Transfer, [this is the config](https://github.com/googleapis/googleapis/blob/master/google/cloud/bigquery/datatransfer/v1/bigquerydatatransfer_gapic.yaml#L79). KMS doesn't include such a config, and I'm not sure we want to add one on behalf of the team since it may affect other languages as well. (As far as I can tell, other languages are hand-writing these smoke tests and examples—see [nodejs smoke test](https://github.com/googleapis/nodejs-kms/pull/111) and [nodejs sample](https://github.com/googleapis/nodejs-kms/pull/88))

**Comment by jbolinger** [comment]
@dazuma you are correct - the Ruby gapic has a known issue where the smoke test and example config values are mixed up (https://github.com/googleapis/gapic-generator/issues/2106). 

I can fix it if you'd like to alter the config and try to go that route (if the values actually need to be different) However, I'm pretty sure that your other suspicion is correct (i.e. this feature is not working correctly in other language generators, hence the manual samples).

**Comment by dazuma** [comment]
@jbolinger I'd rather not muck with the config at this point, since the libraries are trying to go GA. In addition:
* The current sample generation isn't great as-is. I'd rather hand-write a simple sample if it's going on the README.
* The current smoke test generation doesn't seem to be able to generate actual assertions—for other libraries where it is configured, it just makes a call and drops the result on the floor. Again, I'd rather hand-write a smoke test at this point.

**Comment by jbolinger** [comment]
@dazuma that's exactly what I wanted to hear. Just wanted to let you know the door was open if you needed it.
