### ISSUE TITLE
[KMS] Getting-started example in the readme

### ISSUE THREAD

**Issue by dazuma** [googleapis/google-cloud-ruby#2981]
KMS team is asking for a getting-started example in the readme. Note that `README.md` for this library is generated by gapic, so we'd have to figure out how to inject a getting-started section (maybe using synth).

**Comment by quartzmo** [comment]
Where should the getting-started example live? `synth.metadata`, or some other configuration file?

**Comment by blowmage** [comment]
Speech has the README changes in the [`synth.py` file](https://github.com/googleapis/google-cloud-ruby/blob/master/google-cloud-speech/synth.py#L79-L118).

**Comment by blowmage** [comment]
Vision has ERB templates in a [`synth` directory](https://github.com/googleapis/google-cloud-ruby/tree/3b39b01a222da92dbca9faac9b1e2b96d9369db4/google-cloud-vision/synth).
