### ISSUE TITLE
Debugger breakpoints on the first line of a method fail on Ruby 2.6

### ISSUE THREAD

**Issue by blowmage** [googleapis/google-cloud-ruby#3022]
We get the four following failures when running debugger unit tests on Ruby 2.6.1

```
$ cd google-cloud-debugger
$ bundle exec rake test
install -c tmp/x86_64-darwin18/google/cloud/debugger/debugger_c/2.6.1/google/cloud/debugger/debugger_c.bundle lib/google/cloud/debugger/debugger_c.bundle
cp tmp/x86_64-darwin18/google/cloud/debugger/debugger_c/2.6.1/google/cloud/debugger/debugger_c.bundle tmp/x86_64-darwin18/stage/lib/google/cloud/debugger/debugger_c.bundle
/Users/blowmage/.gem/repos/gcloud-ruby/gems/activesupport-4.2.11/lib/active_support/core_ext/object/duplicable.rb:111: warning: BigDecimal.new is deprecated; use BigDecimal() method instead.
Run options: --seed 30522

# Running:

.......................................................................................F....FF.....................................................................................................................................................................F...............................................................................................................

Finished in 2.012205s, 184.3749 runs/s, 615.7424 assertions/s.

  1) Failure:
Google::Cloud::Debugger::Tracer::mock_debugger#test_0001_catches breakpoint from function call [/Users/blowmage/google/codez/gcloud-ruby/google-cloud-debugger/test/google/cloud/debugger/tracer/tracer_scenarios_test.rb:72]:
Expected: true
  Actual: false

  2) Failure:
Google::Cloud::Debugger::Tracer::mock_debugger#test_0002_catches breakpoint called from a child thread [/Users/blowmage/google/codez/gcloud-ruby/google-cloud-debugger/test/google/cloud/debugger/tracer/tracer_scenarios_test.rb:94]:
Expected: true
  Actual: false

  3) Failure:
Google::Cloud::Debugger::Tracer::mock_debugger#test_0004_catches breakpoint when function interleave files [/Users/blowmage/google/codez/gcloud-ruby/google-cloud-debugger/test/google/cloud/debugger/tracer/tracer_scenarios_test.rb:132]:
Expected: true
  Actual: false

  4) Failure:
Google::Cloud::Debugger::Breakpoint::Evaluator::.readonly_eval_expression#test_0016_doesn't allow return operation in expression [/Users/blowmage/google/codez/gcloud-ruby/google-cloud-debugger/test/google/cloud/debugger/breakpoint/evaluator_test.rb:115]:
Expected /Prohibited\ operation\ detected/ to match # encoding: ASCII-8BIT
"unexpected return".

371 runs, 1239 assertions, 4 failures, 0 errors, 0 skips
```

**Comment by blowmage** [comment]
This is the issue holding up #2851.

**Comment by blowmage** [comment]
I suspect this is specific to 2.6. I don't see any release notes for changes to the threading implementation in 2.6, but there was the [#15499](https://bugs.ruby-lang.org/issues/15499) bug filed by the grpc team. Hope that helps.

**Comment by dazuma** [comment]
I have a patch for these that should unblock the tests. However, the underlying issue is unsolved. I'll try to describe it as I understand it so far:

Ruby 2.6 changed the behavior of TracePoint with regard to line tracing at the beginning of a method. The Debugger code sometimes responds to a `call` tracepoint by enabling a `line` tracepoint. In Ruby < 2.6, this works and allows the first line in the method to trigger the line tracepoint. However, in Ruby >= 2.6, the first line in the method does not trigger the new tracepoint. (This happens only if the line tracepoint was only activated inside the call tracepoint's callback. If the line tracepoint was active previously, then it properly triggers on the method's first line.)

**Comment by dazuma** [comment]
It sounds like it's possible this has been fixed upstream in Ruby 2.6.4 (https://github.com/deivid-rodriguez/byebug/issues/550#issuecomment-525921168). Will check.

**Comment by dazuma** [comment]
Nope, the upstream fix was for something different. This issue is still present.
I'm going to deprioritize this because we're not getting requests for a fix, and honestly we're severely limited in what we can do anyway.

**Comment by dazuma** [comment]
Closing as obsolete, given that debugger is being turned down.
