### ISSUE TITLE
Incompatibility with Bundler Standalone Mode

### ISSUE THREAD

**Issue by drcapulet** [googleapis/google-cloud-ruby#3058]
Bundler has a standalone installation mode that alleviates the need to use Bundler or Rubygems at runtime by generating a file that adds each gem to the load path like so:

```ruby
require 'rbconfig'
# ruby 1.8.7 doesn't define RUBY_ENGINE
ruby_engine = defined?(RUBY_ENGINE) ? RUBY_ENGINE : 'ruby'
ruby_version = RbConfig::CONFIG["ruby_version"]
path = File.expand_path('..', __FILE__)
$:.unshift "#{path}/../#{ruby_engine}/#{ruby_version}/gems/rake-12.3.2/lib"
...
$:.unshift "#{path}/../#{ruby_engine}/#{ruby_version}/gems/google-cloud-pubsub-0.33.2/lib"
...
```

Unfortunately there are numerous usages of `Gem.loaded_specs['google-cloud-foo'].version.version` which subsequently causes errors (```NoMethodError: undefined method `version' for nil:NilClass```). Can y'all instead use the version constants defined?

**Comment by blowmage** [comment]
@dazuma @TheRoyalTnetennba is this something we can replace using `symth.py` in the gems that have a version file? The GAPIC-only gems set the version in the `gemspec` file and don't have a version file.

**Comment by quartzmo** [comment]
[Example of `Gem.loaded_specs['google-cloud-asset'].version.version`](https://github.com/googleapis/google-cloud-ruby/blob/master/google-cloud-asset/lib/google/cloud/asset/v1/asset_service_client.rb#L154) in `google-cloud-asset`.

**Comment by blowmage** [comment]
@dazuma @TheRoyalTnetennba Ping.

**Comment by blowmage** [comment]
Version files have been added to all the gems now. @drcapulet has this resolved the runtime errors in your use-case?

**Comment by blowmage** [comment]
Haven't heard back. We think this is resolved. If it is not, please open a new issue and reference this one. Thanks!

**Comment by drcapulet** [comment]
Thanks for the updates! I've been waiting to hear back from the team that hit the issue, but I'll assume it's resolved!
