### ISSUE TITLE
Cloud storage documentation issue of File class

### ISSUE THREAD

**Issue by shouichi** [googleapis/google-cloud-ruby#3113]
Hello,

In the cloud storage documentation, there are few examples that calls `rewind` just after calling `File#download`.

- https://github.com/googleapis/google-cloud-ruby/blob/95c99917824f06bc142625a728eacfdb4ea68348/google-cloud-storage/lib/google/cloud/storage/file.rb#L63
- https://github.com/googleapis/google-cloud-ruby/blob/2dacea929edb834345047959035f989c1341edb0/google-cloud-storage/OVERVIEW.md#L291

However, if I understand it correctly, `File#download` returns `StringIO` which is not read at all, thus we don't need to call `rewind`. Do I miss something?

Thanks you,
Shouichi

**Comment by blowmage** [comment]
Hi @shouichi, thanks for the question. Even with `StringIO`, the position will be at the end after writing the contents. So calling `#rewind` will reset the position to the beginning.

```ruby
require "stringio"

io = StringIO.new
io.write "hello"
io.write " "
io.write "world"
io.write "!"

# When we read from this object we don't see the contents
io.read #=> ""
# This is because the IO position is at the end
io.pos #=> 12

# So, if we rewind we can read the contents
io.rewind #=> 0 # This is the new position
io.read #=> "hello world!"
```

**Comment by shouichi** [comment]
Hi @blowmage, thanks for the quick response!

I want to clarify my question by excerpting code from the document.

```
file = bucket.file "path/to/public-file.ext", skip_lookup: true
downloaded = file.download
downloaded.rewind
downloaded.read #=> "Hello world!"
```

From the user perspective, `downloaded` is a newly allocated `StringIO` which is not read at all, thus `downloaded` is expected to be readable without calling `rewind`. Internally library may write to the `downloaded` object but I personally think returning it without `rewind` (or not making ready to read) is not really user friendly. Whether library should `rewind` or not is a design choice but the behavior should be documented clearly at least.

I also tried `downloaded.read` without `rewind` and it returned the content of file, I may miss something though.

Thanks!

**Comment by blowmage** [comment]
I understand what you are saying, however, there are reasons we treat the IO object this way. First, by not providing a file path string or an IO object, we treat the download as if you did provide an empty StringIO object. It is the same as this:

```ruby
downloaded = StringIO.new

file = bucket.file "path/to/public-file.ext", skip_lookup: true
file.download downloaded

downloaded.rewind
downloaded.read #=> "Hello world!"
```

We don't rewind the IO object because not every IO object can be rewound. For example, if users are piping downloaded content to some other process then calling `IO#rewind` will raise an error:

```ruby
read_io, write_io = IO.pipe

Thread.new do
  # Processes content as its being downloaded
  process_io read_io
end

# Download content to piped IO
file = bucket.file "path/to/public-file.ext", skip_lookup: true
file.download write_io
```

Lastly, I understand that rewinding and reading is a pain. I usually call [`StringIO#string`](https://ruby-doc.org/stdlib-2.6.2/libdoc/stringio/rdoc/StringIO.html#method-i-string) to get the underlying string, without care for where the IO's position is.

**Comment by shouichi** [comment]
Mmm, when user passes an object (whether `StringIO` or `IO`) to `File#download`, user is responsible for calling (or not calling) `rewind`. However, when not passing an object, I usually expect the returned object is ready to read as http response body is. Anyway, I got the point, just wanted to clarify.

Thank you!
