### ISSUE TITLE
Renaming File::Signer to File::SignerV2 is not backwards compatible

### ISSUE THREAD

**Issue by wlipa** [googleapis/google-cloud-ruby#3114]
The change in https://github.com/googleapis/google-cloud-ruby/pull/3057/commits/86daaa6ff5728f0ad92d17fe5d010f387b8b1b1e is a breaking API change for users of File::Signer (class is not found any more), so shouldn't it wait for a major version change?

This is in google-cloud-storage 1.18.0 compared to 1.17.0.

**Comment by blowmage** [comment]
Hi @wilpa, thanks for the question. You are correct, Signer has been renamed. However, this does not break API compatibility. Signer is an internal class, marked `@private`, and not part of the public API. The public API is `Project#signed_url`, `Bucket#signed_url`, and `File#signed_url`, all of which remain backwards compatible.

As we have discussed the signing implementation we have always stressed that users that choose to use this internal class run the risk of things changing because it is not part of the public API.

Does that help?

**Comment by wlipa** [comment]
Yes, thanks.  I'm using it like this, so I'll try to figure if I can change to using the public API. (I think this may have been an optimization to avoid a network request for the file object.)

    signer = Google::Cloud::Storage::File::Signer.from_bucket(gcp_view_bucket, gcp_view_path(suffix))
    signer.signed_url issuer: gcp_view_issuer, signing_key: gcp_view_signing_key, expires: 3600

**Comment by wlipa** [comment]
Yes, thanks.  I'm using it like this, so I'll try to figure if I can change to using the public API. (I think this may have been an optimization to avoid a network request for the file object.)

    signer = Google::Cloud::Storage::File::Signer.from_bucket(gcp_view_bucket, gcp_view_path(suffix))
    signer.signed_url issuer: gcp_view_issuer, signing_key: gcp_view_signing_key, expires: 3600

**Comment by blowmage** [comment]
There are a few ways to avoid pulling down a resource. First, you could use [`Project#signed_url`](http://googleapis.github.io/google-cloud-ruby/docs/google-cloud-storage/latest/Google/Cloud/Storage/Project.html#signed_url-instance_method) and pass the bucket name and the file path. Or, you could use the `skip_lookup` optional argument to get a [`Bucket`](http://googleapis.github.io/google-cloud-ruby/docs/google-cloud-storage/latest/Google/Cloud/Storage/Project.html#bucket-instance_method) or [`File`](http://googleapis.github.io/google-cloud-ruby/docs/google-cloud-storage/latest/Google/Cloud/Storage/Bucket.html#file-instance_method) object without making the associated `get` API call and call their `#signed_url` method.

**Comment by wlipa** [comment]
Great, thanks for the pointer!

**Comment by quartzmo** [comment]
@wlipa Were you able to successfully change to the public API? If not, might be able to get a fix in for you.

**Comment by wlipa** [comment]
I just reverted the gem for now, but I'm planning to switch to the public API.  If I run into problems with that (hopefully unlikely) I'll open a separate ticket.  Thanks for the help.
