### ISSUE TITLE
Error: "cannot load such file -- google/cloud/storage" when running in a Dangerfile

### ISSUE THREAD

**Issue by jywarren** [googleapis/google-cloud-ruby#3117]
In https://github.com/publiclab/plots2/pull/5320, we're getting an error `cannot load such file -- google/cloud/storage` when running `require "google/cloud/storage"` from within a Dangerfile. It's in our Gemfile and we run this in the Dangerfile:

```ruby
system("gem install google-cloud-storage")
require "google/cloud/storage"
```

Any idea why we wouldn't be able to require this? Thank you!

**Comment by blowmage** [comment]
I am not familiar with Danger. Is it Bundler-aware? If so, do you have a different version specified in the Gemfile.lock file than what is being downloaded?

Perhaps switch the system call before the require to `system(“bundle install”)`?

**Comment by jywarren** [comment]
Thank you, i will try that! https://github.com/publiclab/plots2/pull/5320/commits/faa039a3453438b2e7d227608075e1c84b780752

**Comment by jywarren** [comment]
Ah, i believe we've figured this out! We needed to run danger from within our docker container, as we're not in a standard TravisCI setup. Thank you!
