### ISSUE TITLE
Downgrade dependency on addressable

### ISSUE THREAD

**Issue by prapicault** [googleapis/google-cloud-ruby#3122]
The google-cloud-storage 1.18 gem includes a dependency on `addressable`. This dependency is configured to point to addressable 2.6 or greater (https://github.com/googleapis/google-cloud-ruby/blob/master/google-cloud-storage/google-cloud-storage.gemspec#L25).

Unfortunately this creates conflicts with other libraries that have not yet adopted the recent 2.6 version (released in Jan 2019) and thus make adopting google-cloud-storage (and esp the fix for #4997) hard to consume in an environment with many dependencies at play (in our case https://rubygems.org/gems/webmock and https://rubygems.org/gems/sawyer)

#### Environment details

  - OS: MacOS
  - Ruby version: 2.4.4
  - Gem name and version: google-cloud-storage 1.18.0

**Comment by quartzmo** [comment]
@prapicault Thanks for reporting this issue. We will look into it immediately, and hopefully resolve it if possible.

**Comment by prapicault** [comment]
I've opened https://github.com/googleapis/google-cloud-ruby/pull/3123 and I even have the CLA :-)
