### ISSUE TITLE
Support Storage::Bucket#location_type

### ISSUE THREAD

**Issue by quartzmo** [googleapis/google-cloud-ruby#3302]
Location type will be a new field added for Bucket resource. It will be populated on-the-fly for output path, and is a read-only field so patch/update/create will not have any effect on bucket resource.

**Comment by JesseLovelace** [comment]
"MULTI_REGION", "REGION", and" DUAL_REGION" were supposed to be "multi-region", "region", and "dual-region". This will be changed in the API after a rollout on June 26 and should also be reflected here.
