### ISSUE TITLE
Firestore: Return user-defined result from Transaction function

### ISSUE THREAD

**Issue by schmidt-sebastian** [googleapis/google-cloud-ruby#3388]
Note: This is a dupe of https://github.com/googleapis/google-cloud-ruby/issues/2103

I would like to ask if we could re-consider the API for `runTransaction` and return a user-provided result. On other platforms, the SDK returns the return value of the last successful run.

You can see a couple of implementations here:
https://github.com/googleapis/nodejs-firestore/blob/master/types/firestore.d.ts#L206
https://github.com/googleapis/google-cloud-java/blob/master/google-cloud-clients/google-cloud-firestore/src/main/java/com/google/cloud/firestore/Firestore.java#L84,https://github.com/googleapis/google-cloud-php-firestore/blob/master/src/FirestoreClient.php#L394

Is it possible to update the Ruby client to match?

**Comment by blowmage** [comment]
Would it be possible to allow the current behavior if the user opts in for it? For example, the default behavior could be to return the value from the closure:

```ruby
require "google/cloud/firestore"

firestore = Google::Cloud::Firestore.new

response = firestore.transaction do |tx|
  # Set the data for NYC
  tx.set("cities/NYC", { name: "New York City" })

  # Update the population for SF
  tx.update("cities/SF", { population: 1000000 })

  # Delete LA
  tx.delete("cities/LA")

  :hello
end

response #=> :hello
```

But if the user sets a configuration a [`CommitResponse`](http://googleapis.github.io/google-cloud-ruby/docs/google-cloud-firestore/latest/Google/Cloud/Firestore/CommitResponse.html) could be returned instead?

```ruby
require "google/cloud/firestore"

firestore = Google::Cloud::Firestore.new

response = firestore.transaction commit_response: true do |tx|
  # Set the data for NYC
  tx.set("cities/NYC", { name: "New York City" })

  # Update the population for SF
  tx.update("cities/SF", { population: 1000000 })

  # Delete LA
  tx.delete("cities/LA")

  :hello
end

response #=> #<Google::Cloud::Firestore::CommitResponse ...>
```

**Comment by schmidt-sebastian** [comment]
That sounds good to me!
