### ISSUE TITLE
Bigtable Ruby Client Max Row size is 4mb

### ISSUE THREAD

**Issue by lightbulb151** [googleapis/google-cloud-ruby#3394]
This is the ruby version of this issue https://github.com/googleapis/google-cloud-python/issues/2880

error message:
GRPC::ResourceExhausted: 8:Received message larger than max (10000078 vs. 4194304)

in summary, google bigtable can store 100mb for any given cell, but the underlying grpc message can only hold 4 mb by default. Does anyone know how to resolve this issue?

for more context: i am using the "read_rows" call in the ruby client, and fetching one row that has around 100mb in one cell.
https://github.com/googleapis/google-cloud-ruby/blob/76966fe01357444256c307a05f44ac0e5f5587cc/google-cloud-bigtable/lib/google/cloud/bigtable/read_operations.rb

**Comment by blowmage** [comment]
The grpc client needs to be created with `grpc.max_send_message_length` and `grpc.max_receive_message_length` headers set to -1.

**Comment by lightbulb151** [comment]
is there any documentation on how this setup can be achieved? 

my existing setup is

require "google/cloud"
require "google/cloud/bigtable"

project_id = "project_name"
bigtable = Google::Cloud.bigtable(project_id: project_id)
table = bigtable.table("cluster", "table_name")

its not clear where grpc setup comes into play here

**Comment by blowmage** [comment]
Can you set your project to use [my branch](https://github.com/blowmage/google-cloud-ruby/pull/new/bigtable/grpc-headers) and see if this helps your situation? Update your Gemfile with the following:

```ruby
gem "google-cloud-bigtable", github: "blowmage/google-cloud-ruby", branch: "bigtable/grpc-headers"

**Comment by lightbulb151** [comment]
i gave it a try, but did not seem to do it.

my setup doesn't initialize Google::Cloud::Bigtable::Service anywhere so the logic wasnt touched.

**Comment by blowmage** [comment]
It does, Service is a private class.

**Comment by lightbulb151** [comment]
i see. i believe that that should do it then. i just need to figure out my gemfile setup. given that its correct, what would be the next steps, would we consider merging this change to master?

**Comment by lightbulb151** [comment]
yup confirmed that it works.

**Comment by lightbulb151** [comment]
@blowmage  Thank you for doing this! Looking forward to the merged change :D
