### ISSUE TITLE
[Documentation Issue]  Broken link: "Preparing Data for BigQuery"

### ISSUE THREAD

**Issue by derencius** [googleapis/google-cloud-ruby#3419]
The link "[Preparing Data for BigQuery](https://cloud.google.com/bigquery/preparing-data-for-bigquery)" in https://googleapis.github.io/google-cloud-ruby/docs/google-cloud-bigquery/latest/Google/Cloud/Bigquery/Table.html is broken

**Comment by blowmage** [comment]
Thanks for the issue. How is it broken?

**Comment by derencius** [comment]
I got a 404 when I clicked on the link "Preparing Data for BigQuery" in https://googleapis.github.io/google-cloud-ruby/docs/google-cloud-bigquery/latest/Google/Cloud/Bigquery/Table.html

it points to https://cloud.google.com/bigquery/preparing-data-for-bigquery  that returns a 404.

**Comment by quartzmo** [comment]
This link is used in the following locations:

```sh
Targets
    Occurrences of '/preparing-data-for-bigquery' in Directory /Users/quartzmo/code/google/codez/google-cloud-ruby/google-cloud-bigquery with mask '*.rb'
Found Occurrences  (7 usages found)
    google-cloud-ruby  (7 usages found)
        google-cloud-bigquery/lib/google/cloud/bigquery  (5 usages found)
            load_job.rb  (1 usage found)
                (843: 48) # ](https://cloud.google.com/bigquery/preparing-data-for-bigquery).
            schema.rb  (2 usages found)
                (29: 47) # @see https://cloud.google.com/bigquery/preparing-data-for-bigquery
                (430: 46) # ](https://cloud.google.com/bigquery/preparing-data-for-bigquery).
            table.rb  (2 usages found)
                (47: 47) # @see https://cloud.google.com/bigquery/preparing-data-for-bigquery
                (2903: 48) # ](https://cloud.google.com/bigquery/preparing-data-for-bigquery).
        google-cloud-bigquery/lib/google/cloud/bigquery/schema  (2 usages found)
            field.rb  (2 usages found)
                (25: 49) # @see https://cloud.google.com/bigquery/preparing-data-for-bigquery
                (511: 60) # for BigQuery](https://cloud.google.com/bigquery/preparing-data-for-bigquery).
```

**Comment by quartzmo** [comment]
The correct replacement for almost all usages is `https://cloud.google.com/bigquery/docs/loading-data#loading_denormalized_nested_and_repeated_data`. The link text/title should be changed to `Loading denormalized, nested, and repeated data`.
