### ISSUE TITLE
Google::Cloud::PubSub::Project#create_subscription missing?

### ISSUE THREAD

**Issue by msbit** [googleapis/google-cloud-ruby#3420]
### Version:

`google-cloud-pubsub (0.36.0)`

### Description

Just going through the example in the README for PubSub, when I get to:

```
sub = pubsub.subscription "my-topic-sub"
```

this fails, because I don't have a correspondingly named subscription.

However, unlike with topics, which you can create from the client:

```
topic = pubsub.create_topic "my-topic"
```

there doesn't appear to be a way to create the subscription.

### Expected

For symmetry I would have expected something like:

```
sub = pubsub.create_subscription "my-topic-sub"
```

to work. 

### Actual

```
undefined method `create_subscription' for #<Google::Cloud::PubSub::Project:0x00007fd5ea43c160> (NoMethodError)
```

**Comment by blowmage** [comment]
The mechanism to create a subscription is a method on a Topic object: [`Topic#subscribe`](https://googleapis.github.io/google-cloud-ruby/docs/google-cloud-pubsub/latest/Google/Cloud/PubSub/Topic.html#subscribe-instance_method):

```ruby
require "google/cloud/pubsub"

pubsub = Google::Cloud::PubSub.new

topic = pubsub.topic "my-topic"
sub = topic.subscribe "my-topic-sub"
```

The method is also aliased as `create_subscription`, so if you prefer that name you can use it instead:

```ruby
require "google/cloud/pubsub"

pubsub = Google::Cloud::PubSub.new

topic = pubsub.topic "my-topic"
sub = topic.create_subscription "my-topic-sub"
```

**Comment by blowmage** [comment]
Releases prior to 0.27.0 included the [`Project#subscribe`](https://googleapis.github.io/google-cloud-ruby/docs/google-cloud-pubsub/v0.26.0/Google/Cloud/Pubsub/Project.html#subscribe-instance_method) method (also aliased as `create_subscription`), but it (and others) were removed in 0.27.0 at the request of the Google Pub/Sub team. See the [0.27.0 release notes](https://github.com/googleapis/google-cloud-ruby/releases/tag/google-cloud-pubsub/v0.27.0).

**Comment by msbit** [comment]
Thanks @blowmage, moving to `topic.{find,create}_subscription` works perfectly for this case.

Ignore the commit I started on to change the docs to `topic.subscription`, I realised after the fact that it wasn't necessary.
