### ISSUE TITLE
Generated AUTHENTICATION.md references nonexistent config interface for generated libraries

### ISSUE THREAD

**Issue by dazuma** [googleapis/google-cloud-ruby#3494]
The generated `AUTHENTICATION.md` file discusses using the configuration interface (`Google::Cloud::LibraryModule.configure`) even for generated libraries that do not support this interface.

**Comment by meredithslota** [comment]
The `AUTHENTICATION` files were updated in https://github.com/googleapis/google-cloud-ruby/pull/4277 and I cannot repro this issue anymore. Is this still relevant?
