### ISSUE TITLE
Spanner: Ensure client backoff is implemented to respect client configuration.

### ISSUE THREAD

**Issue by crwilcox** [googleapis/google-cloud-ruby#3523]
There was an issue in the client library for python where requests to retry could occur without a proper retry object. In this case, rather than defaulting to an exponential backoff, we defaulted to immediate retry. Ensure that for this client library we respect the min, max, and multiplier as specified in the gapic configuration. 

Original Bug: https://github.com/googleapis/google-cloud-python/issues/7303

**Comment by quartzmo** [comment]
If no `retryDelay` is present in `err.metadata` (included any nested `cause` errors), the Ruby client [defaults to an incremental backoff](https://github.com/googleapis/google-cloud-ruby/blob/master/google-cloud-spanner/lib/google/cloud/spanner/client.rb#L1009) that starts at `1.0` seconds. The backoff value is multiplied by `1.3` for subsequent attempts until the total time spent exceeds a `deadline`, which can be user-specified but defaults to `120` seconds. If this behavior looks good please close the issue, thanks!

**Comment by crwilcox** [comment]
The others (Java, Node, Python) are doing exponential, but I am not sure this is worth changing? The biggest concern of this is that we have a delay and don't immediately retry.

**Comment by quartzmo** [comment]
@crwilcox Do you know what the `retryDelay` values are like in practice? Can we/should we try to copy that behavior?

**Comment by crwilcox** [comment]
@quartzmo we tend to do 1.3 as you have done here. This matches the spirit of this request and as I was mostly wanting to make sure the defect of immediately retrying wasn't also in ruby, I am closing this.
