### ISSUE TITLE
Create a ruby file with the gem name for generated libraries

### ISSUE THREAD

**Issue by dazuma** [googleapis/google-cloud-ruby#3541]
For example, the `google-cloud-asset` library should have a file `lib/google-cloud-asset.rb`. This is currently missing from most generated libraries.

**Comment by quartzmo** [comment]
@dazuma This should just be done manually?

**Comment by dazuma** [comment]
Yeah, let's just do this manually. The file isn't going to change once it gets created (or at least not in an automateable way) so I don't think adding it to the monolithic generator or to synth will buy us much.

**Comment by dazuma** [comment]
This was completed in the microgenerator.
