### ISSUE TITLE
Critical information missing in App Engine documentation

### ISSUE THREAD

**Issue by dosco** [googleapis/google-cloud-ruby#3601]
One of the most common tasks for apps on GAE is to talk to GCS and that almost always that happens using signed urls. The appengine documentation does not mention that the default app engine service account and it's related key provided in `GOOGLE_APPLICATION_CREDENTIALS` does not work for signing (Don't know why) you need to create another service account with the right GCS roles and include that key with your app.

For example for rails app ActiveStorage CloudStorage adapter will need to be provided this new credential file in the config and not the default GAE credentials.

This also does introduce the added complexity of dealing with KMS to decrypt this other credential at build or runtime.

**Comment by blowmage** [comment]
> does not work for signing (Don't know why)

The Oauth token provided by the GAE environment is just a token, and is not a full service account.

The documentation for [`signed_url`](https://googleapis.github.io/google-cloud-ruby/docs/google-cloud-storage/latest/Google/Cloud/Storage/Project.html#signed_url-instance_method) states:

> Generating a URL requires service account credentials, either by connecting with a service account when calling `Google::Cloud.storage`, or by passing in the service account `issuer` and `signing_key` values.

**Comment by quartzmo** [comment]
@dosco Thank you for opening this issue!

**Comment by frankyn** [comment]
@quartzmo this can be fixed by supporting GCE credentials with IAM Credentials API. Was there any large blockers with supporting this signing path for Ruby? I can't remember if we ended up supporting it or not.

**Comment by aman29april** [comment]
I am getting Google::Cloud::Storage::SignedUrlUnavailable error and my Rails application is on GCP. As per documentation, no key or authentication is needed. So want to confirm if the key is required during the download?

**Comment by parubets** [comment]
I'm also trying to generate download url for file that was uploaded in kubernetes environment using automatic credential discovery. My rails app successfully upload file to google bucket, but then throwing Google::Cloud::Storage::SignedUrlUnavailable on download

**Comment by giovannibonetti** [comment]
As you probably realized by now, even though part of the documentation suggests you won't need a service account for using Cloud Storage in your Rails app you will actually need one. Most of the tutorials I found online for integrating Rails Active Storage with Cloud Storage mentioned that.

If you like to put your credentials in an environment variable you can do it like we did in my company. We put the JSON keyfile in STORAGE_KEYFILE_JSON since [the `google-cloud-storage` gem picks it up automatically](https://github.com/googleapis/google-cloud-ruby/blob/e0bcff9509519d0e96b39c0fae54c3f942cf30c9/google-cloud-storage/lib/google/cloud/storage/credentials.rb#L49).

**Comment by frankyn** [comment]
@quartzmo is there an update on this issue?

**Comment by macropin** [comment]
Requiring a key file is not good for security. We originally provisioned bucket access using workload identity for GKE, but this didn't work because the library requires a static key. Please consider fixing this.

**Comment by kam1kaze** [comment]
Is there any update? We could not use workload identity for GKE due to google-cloud-storage gem limitation.

**Comment by frankyn** [comment]
Closing as this should now be addressed by: 
https://cloud.google.com/ruby/docs/reference/google-cloud-storage/latest/Google-Cloud-Storage-File

![image](https://github.com/googleapis/google-cloud-ruby/assets/1907648/a355abb0-49b3-4060-bc40-4863c086ed7a)
