### ISSUE TITLE
Deprecation Dialogflow v1 in September but Ruby client still in alpha 

### ISSUE THREAD

**Issue by muhammadn** [googleapis/google-cloud-ruby#3604]
Dialogflow will be deprecated in September this year and we are now in July, yet the Ruby client is missing most of the methods (even though it is "documented" in the API).

We can't switch over from v1 to v2 overnight while the Ruby client is in Alpha. Is it possible for google to at least extend the deprecation date or at least make this library work with TextInput or QueryInput?

**Comment by blowmage** [comment]
I wouldn’t let the “alpha” designation stop you from switching. The Google Cloud Dialog gem is generated from the protobuf files and uses the same process as gems that are designated “ga”.

**Comment by muhammadn** [comment]
@blowmage If the ruby gem is generated with the same protobuf files as the python library, then why is most of the methods still missing in this new dialogflow gem but documented in google's rubydocs?

**Comment by blowmage** [comment]
Can you give us some examples of missing methods?

**Comment by muhammadn** [comment]
@blowmage Sorry about this. i think i read the docs wrongly.

I wanted to use QueryInput module and i realised i needed to use TextInput module with new method and text argument. Which was confusing at first.

So i had figured it is:
```
Google::Cloud::Dialogflow::V2::QueryInput.new(text: Google::Cloud::Dialogflow::V2::TextInput.new(text: 'data', language_code: 'en-US'))
```
