### ISSUE TITLE
Coverage task erring on loading Bigtable conformance files

### ISSUE THREAD

**Issue by blowmage** [googleapis/google-cloud-ruby#3654]
The coverage task errors while trying to load the Bigtable conformance JSON files.

```
Errno::ENOENT: No such file or directory @ rb_sysopen - conformance/v2/readrows.json
~/gcloud-ruby/google-cloud-bigtable/test/google/cloud/bigtable/conformance_test.rb:99:in `read'
~/gcloud-ruby/google-cloud-bigtable/test/google/cloud/bigtable/conformance_test.rb:99:in `<top (required)>'
```

This is likely due to `LOAD_PATH` being different when running the conformance task.

**Comment by quartzmo** [comment]
This is in bigtable, but make sure that all conformance test files are loaded correctly.

**Comment by quartzmo** [comment]
[recent build with error](https://source.cloud.google.com/results/invocations/580500ce-d30d-402c-b49a-f81cc9d67cea/targets/cloud-devrel%2Fclient-libraries%2Fgoogle-cloud-ruby%2Fcontinuous%2Flinux%2Fpost/log)
