### ISSUE TITLE
Cloud Bigtable setCell timestamp field does not set timestamp on cell.

### ISSUE THREAD

**Issue by billyjacobson** [googleapis/google-cloud-ruby#3676]
When setting the timestamp on a cell value, the timestamp is ignored. You can test this with the [hello world](https://github.com/GoogleCloudPlatform/ruby-docs-samples/blob/master/bigtable/hello_world.rb) 

```
  entry = table.new_mutation_entry "greeting#{i}"
  entry.set_cell(
    column_family,
    column_qualifier,
    value,
    timestamp: Time.now.to_i * 1000
  )

  table.mutate_row entry
```
When I read the results, this is what I see: 
```
greeting0
  cf:greeting                              @ 1970/01/18-21:16:13.999000
    "Hello World!"
----------------------------------------
greeting1
  cf:greeting                              @ 1970/01/18-21:16:14.000000
    "Hello Bigtable!"
----------------------------------------
greeting2
  cf:greeting                              @ 1970/01/18-21:16:14.000000
    "Hello Ruby!"
```

**Comment by quartzmo** [comment]
@billyjacobson Thank you for opening this issue. I'll try to reproduce it myself today.

**Comment by quartzmo** [comment]
@billyjacobson I can't reproduce this. I edited [mutate_row_test.rb#L46-L75](https://github.com/googleapis/google-cloud-ruby/blob/master/google-cloud-bigtable/acceptance/bigtable/table/mutate_row_test.rb#L46-L75) to use a hardcoded `timestamp` argument and print the returned cell value, it looks OK to me.

```rb
  focus
  it "set cell with timestamp and delete cells with timestamp range" do
    postfix = random_str
    row_key = "setcell-#{postfix}"
    qualifier = "mutate-row-#{postfix}"
    timestamp = 1563398765000

    # Set cell
    entry = table.new_mutation_entry(row_key)
    entry.set_cell(
      family, qualifier, "mutatetest value #{postfix}", timestamp: timestamp
    ).set_cell(
      family, qualifier, "mutatetest value #{postfix}", timestamp: timestamp + 1000
    ).set_cell(
      family, qualifier, "mutatetest value #{postfix}", timestamp: timestamp + 2000
    )

    table.mutate_row(entry).must_equal true
    row = table.read_row(row_key)
    puts "timestamp argument: #{timestamp}"
    puts "read_row cell: #{row.cells[family].last.inspect}"
    row.cells[family].select{|v| v.qualifier == qualifier}.length.must_equal 3

    # Delete cell
    entry = table.new_mutation_entry(row_key)
    entry.delete_cells(
      family, qualifier, timestamp_from: timestamp, timestamp_to: timestamp + 2000
    )

    table.mutate_row(entry)
    row = table.read_row(row_key)
    row.cells[family].select{|v| v.qualifier == qualifier}.length.must_equal 1
  end
```

Output:

```
Chriss-iMac:google-cloud-bigtable quartzmo$ bundle exec rake acceptance
"=> 'google-cloud-ruby-tests' instance is ready."
Run options: "-n=/^(DataClient\\ Mutate\\ Row::bigtable\\#test_0002_set\\ cell\\ with\\ timestamp\\ and\\ delete\\ cells\\ with\\ timestamp\\ range)$/" --seed 13183

# Running:

timestamp argument: 1563398765000
read_row cell: #<Google::Cloud::Bigtable::Row::Cell:0x00007ff8e93c09d0 @family="cf", @qualifier="mutate-row-5799b26d", @timestamp=1563398765000, @value="mutatetest value 5799b26d", @labels=[]>
.

Finished in 1.395108s, 0.7168 runs/s, 2.8672 assertions/s.

1 runs, 4 assertions, 0 failures, 0 errors, 0 skips
"=> Deleting acceptance test tables from instance google-cloud-ruby-tests."
```

**Comment by quartzmo** [comment]
I also copied the hello world example into our acceptance test suite, and got the same results:

```rb
    timestamp = 1563398765000


    column_family = "cf"
    column_qualifier = "greeting"
    puts "Write some greetings to the table #{table}"
    greetings = ["Hello World!", "Hello Bigtable!", "Hello Ruby!"]

    # Insert rows one by one
    # Note: To perform multiple mutation on multiple rows use `mutate_rows`.
    greetings.each_with_index do |value, i|
      puts " Writing,  Row key: greeting#{i}, Value: #{value}"

      entry = table.new_mutation_entry "greeting#{i}"
      entry.set_cell(
        column_family,
        column_qualifier,
        value,
        timestamp: timestamp
      )

      table.mutate_row entry
      row = table.read_row("greeting#{i}")
      puts "timestamp argument: #{timestamp}"
      puts "greeting cell: #{row.cells[family].last.inspect}"
    end
```

Output:

```
Write some greetings to the table #<Google::Cloud::Bigtable::Table:0x00007fa0a1145660>
 Writing,  Row key: greeting0, Value: Hello World!
timestamp argument: 1563398765000
greeting cell: #<Google::Cloud::Bigtable::Row::Cell:0x00007fa0a112eeb0 @family="cf", @qualifier="greeting", @timestamp=1563398765000, @value="Hello World!", @labels=[]>
 Writing,  Row key: greeting1, Value: Hello Bigtable!
timestamp argument: 1563398765000
greeting cell: #<Google::Cloud::Bigtable::Row::Cell:0x00007fa0a111c0d0 @family="cf", @qualifier="greeting", @timestamp=1563398765000, @value="Hello Bigtable!", @labels=[]>
 Writing,  Row key: greeting2, Value: Hello Ruby!
timestamp argument: 1563398765000
greeting cell: #<Google::Cloud::Bigtable::Row::Cell:0x00007fa09fa8a240 @family="cf", @qualifier="greeting", @timestamp=1563398765000, @value="Hello Ruby!", @labels=[]>
```

**Comment by blowmage** [comment]
I think the problem is that the example code is using milliseconds, but the table is likely configured for microseconds. The API's [`Mutation.SetCell` documentation](https://cloud.google.com/bigtable/docs/reference/data/rpc/google.bigtable.v2#google.bigtable.v2.Mutation.SetCell) states:

> Values must match the granularity of the table (e.g. micros, millis).

So there seems to me to be a mismatch here. The example code is clearly using milliseconds, but the "granularity of the table" that the user is using is likely set to microseconds.

If you don't want to change the table granularity, I would replace `Time.now.to_i * 1000` with `Time.now.to_i * 1000000`, or the more accurate `(t = Time.now; t.to_i * 1000000 + t.usec)`:

```ruby
  entry.set_cell(
    column_family,
    column_qualifier,
    value,
    timestamp: (t = Time.now; t.to_i * 1000000 + t.usec)
  )
```

**Comment by quartzmo** [comment]
@blowmage @billyjacobson By default (according to the [#create_table docs](https://github.com/googleapis/google-cloud-ruby/blob/e97f655514eac49d7bf86c39e2ef70b830ad392d/google-cloud-bigtable/lib/google/cloud/bigtable/instance.rb#L524-L528)) the timestamp granularity should be milliseconds:

```
        # @param granularity [Symbol]
        #   The granularity at which timestamps are stored in this table.
        #   Timestamps not matching the granularity will be rejected.
        #   Valid value is `:MILLIS`.
        #   If unspecified, the value will be set to `:MILLIS`.
```

(Thanks @Kolea2 for helping us find this.)

**Comment by billyjacobson** [comment]
By default Bigtable tables should use milliseconds not microseconds. 

As I'm looking at my results when I check using the Cloud Bigtable tool, it does appear to be changing the times, it just doesn't use the correct values, so when I just ran it I get 1970/01/18-21:16:26.945000 then when I run it again a few minutes after, I get 1970/01/18-21:17:43.077000

**Comment by billyjacobson** [comment]
I also found another Bigtable bug that I created https://github.com/googleapis/google-cloud-ruby/issues/3680 for, so you might want to check that out if you're still playing in the Bigtable codebase

**Comment by blowmage** [comment]
The [protobuf field](https://googleapis.github.io/google-cloud-ruby/docs/google-cloud-bigtable/v0.4.3/Google/Bigtable/V2/Mutation/SetCell.html#timestamp_micros-instance_method) is named `timestamp_micros`, so by the name alone I would assume that the API will always return microseconds. Is it possible what the table granularity is doing is controlling millisecond precision vs. microsecond precision? (1563468813059000 vs. 1563468813059359) @kolea2 do you have any insight here?

To make matters worse, the [`MutationEntry#set_cell` method](https://googleapis.github.io/google-cloud-ruby/docs/google-cloud-bigtable/v0.4.3/Google/Cloud/Bigtable/MutationEntry.html#set_cell-instance_method) documents the `timestamp` argument type as `Time, Integer`, but the implementation looks to only support `Integer`. I suspect if a `Time` object is passed, it will be converted to _seconds_, not the milliseconds or microseconds.

**Comment by quartzmo** [comment]
I'll improve the acceptance test and see if there is any unexpected rounding.

**Comment by billyjacobson** [comment]
So is the solution for this to just use t.to_i * 1000000 instead of t.to_i * 1000 ?

**Comment by blowmage** [comment]
I would love to know if changing your code to `t.to_i * 1000000` (or even `t.to_f * 1000000`) fixes the behavior you are seeing. If it does, then we should update the documentation and code examples to match.

**Comment by quartzmo** [comment]
@blowmage I did some testing on this today (and will open a small PR adding a couple of new acceptance tests).

Most interestingly, the **only** timestamp granularity setting supported when creating a table is milliseconds, as [documented here](https://cloud.google.com/bigtable/docs/reference/admin/rpc/google.bigtable.admin.v2#timestampgranularity). I tried passing `:MICROS` when creating a new table and got:

```
Unknown symbol value for enum field 'granularity'. (RangeError)
	from /Users/quartzmo/code/google/codez/google-cloud-ruby/google-cloud-bigtable/lib/google/cloud/bigtable/table.rb:408:in `new'
	from /Users/quartzmo/code/google/codez/google-cloud-ruby/google-cloud-bigtable/lib/google/cloud/bigtable/table.rb:408:in `create'
	from /Users/quartzmo/code/google/codez/google-cloud-ruby/google-cloud-bigtable/lib/google/cloud/bigtable/project.rb:480:in `create_table'
```

My attempts to pass an unrounded timestamp to `setCell` with microsecond granularity (`(t = Time.now; t.to_i * 1000000 + t.usec)`) get:

```
Error in field 'Mutation list' : Error in element #0 : Timestamp granularity mismatch. Expected a multiple of 1000 (millisecond granularity), but got 1564250195985925.
```

**Comment by quartzmo** [comment]
@billyjacobson You wrote:

> When I read the results, this is what I see:
```
greeting0
  cf:greeting                              @ 1970/01/18-21:16:13.999000
    "Hello World!"
```

How are you reading these values? Using only this client library to read the row and cells, I am unable to reproduce your bug. Using `Table#read_row`, I get back the timestamp values that I set with `Entry#set_cell`, as [demonstrated above](https://github.com/googleapis/google-cloud-ruby/issues/3676#issuecomment-512384861).

**Comment by quartzmo** [comment]
I think the correct argument for `setCell` `timestamp_micros` should be a microsecond value rounded to the nearest `1000`. For example:

`1564257960168000`

NOT the equivalent 13-digit millisecond value `1564257960168`.

To get the correct value, use: `(Time.now.to_f * 1000).to_i * 1000`

**Comment by quartzmo** [comment]
@blowmage 

> To make matters worse, the MutationEntry#set_cell method documents the timestamp argument type as Time, Integer, but the implementation looks to only support Integer. I suspect if a Time object is passed, it will be converted to seconds, not the milliseconds or microseconds.

In fact, the protobuf object rejects the `Time` argument with `Google::Protobuf::TypeError`:

```
DataClient Mutate Row::bigtable#test_0006_set_cell with incorrect Time timestamp:
Google::Protobuf::TypeError: Expected number type for integral field 'timestamp_micros' (given Time).
    /Users/quartzmo/code/google/codez/google-cloud-ruby/google-cloud-bigtable/lib/google/cloud/bigtable/mutation_entry.rb:119:in `initialize'
    /Users/quartzmo/code/google/codez/google-cloud-ruby/google-cloud-bigtable/lib/google/cloud/bigtable/mutation_entry.rb:119:in `initialize'
    /Users/quartzmo/code/google/codez/google-cloud-ruby/google-cloud-bigtable/lib/google/cloud/bigtable/mutation_entry.rb:119:in `new'
    /Users/quartzmo/code/google/codez/google-cloud-ruby/google-cloud-bigtable/lib/google/cloud/bigtable/mutation_entry.rb:119:in `set_cell'
    /Users/quartzmo/code/google/codez/google-cloud-ruby/google-cloud-bigtable/acceptance/bigtable/table/mutate_row_test.rb:152:in `block (2 levels) in <top (required)>'
```

**Comment by blowmage** [comment]
> In fact, the protobuf object rejects the Time argument

Correct, the documentation I was referring to is the veneer documentation. I'm saying that if we were the ones designing the veneer API we would probably have coerced the `timestamp_micros` value into a `Time` object when exposing the value. And only accepted a `Time` object instead of the underlying `Integer` value when setting the value.

**Comment by quartzmo** [comment]
Yes, probably so. Although I think that in this case the service's requirements for the value are so fiddly that we better stick with integer.

**Comment by quartzmo** [comment]
@billyjacobson It looks to us like the values you read are probably the same as the ones you set, but because they are quite small as microsecond values the returned dates are very near to the start of the epoch (1 January 1970). The reason your values are so small is that your code example sets millisecond values in a microseconds field.

```
greeting0
  cf:greeting                              @ 1970/01/18-21:16:13.999000
    "Hello World!"
----------------------------------------
greeting1
  cf:greeting                              @ 1970/01/18-21:16:14.000000
    "Hello Bigtable!"
----------------------------------------
greeting2
  cf:greeting                              @ 1970/01/18-21:16:14.000000
    "Hello Ruby!"
```

See #3709 for documentation fixes in the client library and [this comment](https://github.com/GoogleCloudPlatform/ruby-docs-samples/pull/437#discussion_r308404096) for recommended fixes in your ruby-docs-samples PR.
