### ISSUE TITLE
Cloud Bigtable: Unable to create column family without a garbage collection policy

### ISSUE THREAD

**Issue by billyjacobson** [googleapis/google-cloud-ruby#3680]
I tried creating a table with a column family that had no garbage collection policy (which would be default,) but I receive an error when it runs.

```
    table = bigtable.create_table @instance_id, table_id
    table.column_family("stats_summary").create()
```

```
  table = bigtable.create_table instance_id, table_id do |column_families|
    column_families.add(column_family)
  end

```
These both fail.

**Comment by quartzmo** [comment]
@billyjacobson Can you please post the backtrace outputs for each of these if you still have them handy? Thanks!

**Comment by billyjacobson** [comment]
Here you go 
`    column_families.add(column_family)`

Traceback (most recent call last):
	4: from hello_world.rb:25:in `<main>'
	3: from /Users/thebilly/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/google-cloud-bigtable-0.3.1/lib/google/cloud/bigtable/project.rb:480:in `create_table'
	2: from /Users/thebilly/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/google-cloud-bigtable-0.3.1/lib/google/cloud/bigtable/table.rb:406:in `create'
	1: from hello_world.rb:26:in `block in <main>'
/Users/thebilly/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/google-cloud-bigtable-0.3.1/lib/google/cloud/bigtable/table/column_family_map.rb:50:in `add': wrong number of arguments (given 1, expected 2) (ArgumentError)

`    table.column_family("stats_summary").create()`

Traceback (most recent call last):
	4: from hello_world.rb:25:in `<main>'
	3: from /Users/thebilly/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/google-cloud-bigtable-0.3.1/lib/google/cloud/bigtable/project.rb:480:in `create_table'
	2: from /Users/thebilly/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/google-cloud-bigtable-0.3.1/lib/google/cloud/bigtable/table.rb:406:in `create'
	1: from hello_world.rb:26:in `block in <main>'
/Users/thebilly/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/google-cloud-bigtable-0.3.1/lib/google/cloud/bigtable/table/column_family_map.rb:50:in `add': wrong number of arguments (given 1, expected 2) (ArgumentError)
(reverse-i-search)`rbe': cd /Users/thebilly/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/google-cloud-bigtable-0.3.0/lib/google/cloud/bigtable/mutation_entry.rb
bigtable[write-samples]$ bundle exec rspec --tag focus
Run options: include {:focus=>true}
"central-instance instance is ready."
F

Failures:

  1) Google Cloud Bigtable instance Samples create table, perform several writes then, delete table
     Failure/Error: table.column_family("stats_summary").create()

     NoMethodError:
       undefined method `to_grpc' for nil:NilClass
     # ./spec/write_samples_spec.rb:12:in `block (2 levels) in <top (required)>'

**Comment by quartzmo** [comment]
In your first example, you call [`Table#column_family`](https://github.com/googleapis/google-cloud-ruby/blob/master/google-cloud-bigtable/lib/google/cloud/bigtable/table.rb#L282) without the `gc_rule` argument. This argument defaults to `nil`, however the documentation states that it is ["Required for create and update operations."](https://github.com/googleapis/google-cloud-ruby/blob/master/google-cloud-bigtable/lib/google/cloud/bigtable/table.rb#L242).

In your second example, you call [`ColumnFamilyMap#add`](https://github.com/googleapis/google-cloud-ruby/blob/master/google-cloud-bigtable/lib/google/cloud/bigtable/table/column_family_map.rb#L50) without the required `gc_rule` argument, so of course you get a `wrong number of arguments` error.

Are you saying that the API surface is incorrect, and needs to be changed to support adding a column family without a GC Rule?

**Comment by billyjacobson** [comment]
Yes, you should be able to add a column family without a GC Rule, or support it adding a GC Rule of "None"

**Comment by quartzmo** [comment]
Sounds good, I'll change this issue to a feature request. Can you link to any official docs or requirements stating that you should be able to add a column family without a GC Rule, or support it adding a GC Rule of "None"?

**Comment by billyjacobson** [comment]
Here you go: https://cloud.google.com/bigtable/docs/garbage-collection#defaults

**Comment by quartzmo** [comment]
Sorry, where does it say (API docs would be best) that the `gc_rule` is optional or has a default in the service if not provided?

**Comment by billyjacobson** [comment]
I actually can't find where it says this, we might need to update some of those docs...

**Comment by quartzmo** [comment]
Sorry for the trouble, but the client (which I didn't write) very explicitly states that `gc_rule` is "Required for create and update operations." I have tested creating a column family with a `nil` `gc_rule` and it works. I'm happy to make the change, but it would be very good to provide as much documentation for it in this issue as possible.

**Comment by billyjacobson** [comment]
No problem at all and thanks for all the help this week. I totally understand, I'm confused myself why that information isn't included in the docs.
