### ISSUE TITLE
Cloud Bigtable API docs duplicated return information

### ISSUE THREAD

**Issue by billyjacobson** [googleapis/google-cloud-ruby#3681]
The APIs docs for Cloud Bigtable have duplicated return messages displayed 
![see here](https://user-images.githubusercontent.com/5743695/61483691-60ac2500-a96b-11e9-9ead-ea267ed1b226.png)

Is this a configuration issue with generation or does something need to be updated somewhere?

**Comment by quartzmo** [comment]
Thanks for pointing this out. Unfortunately, there isn't much that we can do about this generated documentation and the way that YARD handles it.
