### ISSUE TITLE
Missing links in api docs

### ISSUE THREAD

**Issue by TheRoyalTnetennba** [googleapis/google-cloud-ruby#3695]
e.g. [Google::Cloud::PubSub](https://googleapis.dev/ruby/google-cloud-pubsub/latest/Google/Cloud/PubSub.html#configure-class_method) doesn't link to `Google::Cloud::Config` in the return value of the `configure` method.

Reference: https://github.com/googleapis/docuploader/issues/18 for more details

**Comment by blowmage** [comment]
`Google::Cloud::Config` is defined in google-cloud-core. It can't link to it because it only knows about google-cloud-pubsub.

**Comment by quartzmo** [comment]
@TheRoyalTnetennba Would a hardcoded link to the following URL be acceptable?

https://googleapis.dev/ruby/google-cloud-core/latest/Google/Cloud/Config.html

**Comment by fhinkel** [comment]
Greetings, we're closing this. Looks like the issue got resolved. Please let us know if the issue needs to be reopened.
