### ISSUE TITLE
Clarify token authentication isn't limited to GCE

### ISSUE THREAD

**Issue by ahmetb** [googleapis/google-cloud-ruby#3696]
https://github.com/googleapis/google-cloud-ruby/tree/aea767c02299e507dd1e0f3c4889604f7e031198/google-cloud-storage#authentication says:

> When running on Compute Engine the credentials will be discovered automatically.

This is not limited to GCE, but also GKE, GAE, GCF, and Cloud Run.

https://stackoverflow.com/questions/57191989/using-gcloud-storage-on-cloud-run-with-ruby this stackoverflow question highlights someone was confused by the statement and they thought they can't do the same on Cloud Run.

**Comment by quartzmo** [comment]
Somewhat related to #3601.

**Comment by frankyn** [comment]
This could be updated without #3601 being fixed.
