### ISSUE TITLE
[spanner] Support overriding of endpoint host

### ISSUE THREAD

**Issue by dazuma** [googleapis/google-cloud-ruby#3760]
Support overriding the endpoint host in the veneer layer, by setting either constructor argument or config field.

See #3752 for an example from bigtable.

**Comment by quartzmo** [comment]
@blowmage @dazuma I ran into some trouble with our plan to use `service_address` and `service_port` in the Spanner gapic clients. Although the `SpannerClient` initializer accepts these args, the [`InstanceAdminClient`](https://github.com/googleapis/google-cloud-ruby/blob/master/google-cloud-spanner/lib/google/cloud/spanner/admin/instance/v1/instance_admin_client.rb#L184-L191) and [`DatabaseAdminClient`](https://github.com/googleapis/google-cloud-ruby/blob/master/google-cloud-spanner/lib/google/cloud/spanner/admin/database/v1/database_admin_client.rb#L151-L158) do not. Should they have been updated to expose these params?

```
/Users/quartzmo/code/google/codez/google-cloud-ruby/google-cloud-spanner/lib/google/cloud/spanner/admin/instance/v1/instance_admin_client.rb:185:in `initialize': unknown keywords: service_address, service_port (ArgumentError)
	from /Users/quartzmo/code/google/codez/google-cloud-ruby/google-cloud-spanner/lib/google/cloud/spanner/service.rb:62:in `new'
	from /Users/quartzmo/code/google/codez/google-cloud-ruby/google-cloud-spanner/lib/google/cloud/spanner/service.rb:62:in `instances'
	from /Users/quartzmo/code/google/codez/google-cloud-ruby/google-cloud-spanner/lib/google/cloud/spanner/service.rb:104:in `block in get_instance'
	from /Users/quartzmo/code/google/codez/google-cloud-ruby/google-cloud-spanner/lib/google/cloud/spanner/service.rb:478:in `execute'
	from /Users/quartzmo/code/google/codez/google-cloud-ruby/google-cloud-spanner/lib/google/cloud/spanner/service.rb:103:in `get_instance'
	from /Users/quartzmo/code/google/codez/google-cloud-ruby/google-cloud-spanner/lib/google/cloud/spanner/project.rb:156:in `instance'
```

**Comment by dazuma** [comment]
Crap, sorry. #3786
