### ISSUE TITLE
BucketPolicyOnly: fix broken requests to update BPO enabled field.

### ISSUE THREAD

**Issue by frankyn** [googleapis/google-cloud-ruby#3781]
Hi @quartzmo,

Last week, a system test was skipped due to a backend bug (#3772) . The backend bug will take another 3 weeks based on my last conversation with the GCS team.

In the mean time a workaround should be put in place to reduce impact on users.
When performing an update on the BPO field (enable or disable), the UniformBucketLevelAccess field must be set to the same value as the BPO field during an Update or Patch request.

Here's an example patch:
PATCH uri
Body:
```
{
"iamConfiguration":
  {
     "bucketPolicyOnly": {"enabled": true},
     "uniformBucketLevelAccess": {"enabled": true}
  }
}
```
Related issue in Python: https://github.com/googleapis/google-cloud-python/issues/8552

**Comment by quartzmo** [comment]
Thanks @frankyn, will do!

**Comment by quartzmo** [comment]
@frankyn When `BucketPolicyOnly#locked_time` is set, should it be set to the same value in `UniformBucketLevelAccess`?

**Comment by frankyn** [comment]
locked_time is defined by the service and is not a user mutable.

**Comment by quartzmo** [comment]
Ah sorry to bother you, I just realized that too.

**Comment by frankyn** [comment]
Not a problem, thanks for asking. Thanks for taking a look at this @quartzmo.
