### ISSUE TITLE
Encoding on SpeechToText API

### ISSUE THREAD

**Issue by Hamdan85** [googleapis/google-cloud-ruby#3864]
Why encoding is necessary since web showcase doesnt require it?
Im using the google Speech To Text api and it seems to always return empty results, no matter what...

The same audio file works fine on google speech to text showcase page.

Is anything wrong with the gem or I'm missing something?

gem version: 
google-cloud-speech (0.36.0)
ruby 2.6.3
rails 5.2.3

**Comment by blowmage** [comment]
Hi @Hsmdan85, thanks for the question. What type of file are you using? Specifying the encoding is only optional for FLAC and WAV files.

Can you post the code that you are using that is not working?

**Comment by Hamdan85** [comment]
Im so sorry for that @blowmage ... the problem was encoding... I needed to use an wave encoder.
Seems strange for me that chrome doesn't support audio formats compatible with google cloud... it seems odd, but the fault was mine definitely. 

Thanks for your support.
