### ISSUE TITLE
Bigquery not working through Oj

### ISSUE THREAD

**Issue by brauliobo** [googleapis/google-cloud-ruby#3866]
The following code
```ruby
b=Google::Cloud::Bigquery.new
b.query 'select * from analytics.monitoring limit 10'
```

Returns `[]` with the following monkey patch to replace JSON with Oj https://github.com/ohler55/oj/wiki/Flexible-usage-with-MRI-and-JRuby
It returns data without this patch.

Any clue why?

**Comment by blowmage** [comment]
It looks like Oj does not support the [`symbolize_names` option](https://ruby-doc.org/stdlib-2.6.3/libdoc/json/rdoc/JSON.html#method-i-parse):

```ruby
json = '{ "key": "value" }'

require "json"
JSON.parse json, symbolize_names: true #=> {:key=>"value"}

require "oj"
Oj.load json, symbolize_names: true #=> {"key"=>"value"}
```

BigQuery uses `symbolize_names` to keep reduce the number of short lived strings and lower the pressure on GC while pulling data from the API.

**Comment by blowmage** [comment]
The [Oj docs state that the Oj option for this is `symbol_keys`](https://github.com/ohler55/oj/blob/4c5f8ac3ad47b0782e27f8a230318f774925f033/pages/Options.md#symbol_keys-boolean), but also that `symbolize_names` is supported as an alias. But this doesn't look to be the case using the monkey-patch you linked to.

You might consider leveraging the `Oj.mimic_JSON` call, which looks to support `symbolize_names` correctly, and only load it when running on MRI.

```ruby
if RUBY_ENGINE == "ruby"
  require "oj"
  Oj.mimic_JSON
end
```

```ruby
json = '{ "key": "value" }'

require "json"

JSON.parse json, symbolize_names: true #=> {:key=>"value"}

# The method's location is in the json ruby file
JSON.method(:parse).source_location
#=> ["~/.rubies/ruby-2.6.3/lib/ruby/2.6.0/json/common.rb", 155]

require "oj"
Oj.mimic_JSON

# We have the correct value again!
JSON.parse json, symbolize_names: true #=> {:key=>"value"}

# The method's location is nil, because it is C code
JSON.method(:parse).source_location #=> nil
```

**Comment by brauliobo** [comment]
thank you, it worked @blowmage :D
