### ISSUE TITLE
Dialog Flow streaming detect intent enable_word_info

### ISSUE THREAD

**Issue by Ammet** [googleapis/google-cloud-ruby#3991]
Hey, the parameter `enable_word_info` is missing in audio config. So gem raises an error once I'm trying to add it. Can you please update it? 

Taken the parameter from here: https://cloud.google.com/dialogflow/docs/reference/rpc/google.cloud.dialogflow.v2beta1#google.cloud.dialogflow.v2beta1.InputAudioConfig

**Comment by blowmage** [comment]
Hi @Ammet, thanks for the issue. The API version you linked to is v2beta1, but currently the gem is only supporting v2 which does not have that field defined.

I am asking for verification on which API versions are intended to be exposed by the gem.

**Comment by blowmage** [comment]
Hi @Ammet, apologies for the delay. The good news is that we've just been given approval to add v2beta1 to the gem.

**Comment by Ammet** [comment]
Sounds good! Excited to see it in gem!

**Comment by Ammet** [comment]
@blowmage Will that cover CCAI?
