### ISSUE TITLE
Update MultiRegional and Regional to Standard

### ISSUE THREAD

**Issue by JesseLovelace** [googleapis/google-cloud-ruby#4006]
(I don't have assign privileges in this repository but this should be assigned to @quartzmo )

Previously, we implemented the concept of "Location Type" to move the concept of bucket location away from storage class. It is no longer considered correct to use "MultiRegional" or "Regional" as a storage class, instead those should be location types.

As such, we need to update every instance of the "MultiRegional" and "Regional" storage in samples, library documentation, and tests to use "Standard" instead--Standard is a correct storage class.

Note that "MultiRegional" and "Regional" should only be replaced with "Standard" in cases where they are used a storage class. If they're used as a location type, that's fine and doesn't need to be replaced.

https://github.com/googleapis/google-cloud-ruby/blob/e55655699b66b765b49f4f40d6ecc7f2ab0d4c07/google-cloud-storage/lib/google/cloud/storage/bucket/lifecycle.rb#L55
https://github.com/googleapis/google-cloud-ruby/blob/01b8f514813cac2fd784a840010306d96607f797/google-cloud-storage/test/google/cloud/storage/bucket_update_test.rb
https://github.com/googleapis/google-cloud-ruby/blob/e55655699b66b765b49f4f40d6ecc7f2ab0d4c07/google-cloud-storage/test/google/cloud/storage/lazy/bucket_update_test.rb
https://github.com/googleapis/google-cloud-ruby/blob/01b8f514813cac2fd784a840010306d96607f797/google-cloud-storage/acceptance/storage/bucket_test.rb
https://github.com/googleapis/google-cloud-ruby/blob/6a889c312037ebcabe5555bac6a7288e718b944a/google-cloud-storage/support/doctest_helper.rb#L1182
https://github.com/googleapis/google-cloud-ruby/blob/01b8f514813cac2fd784a840010306d96607f797/google-cloud-storage/lib/google/cloud/storage/bucket.rb#L237

**Comment by quartzmo** [comment]
@JesseLovelace Should [this line](https://github.com/googleapis/google-cloud-ruby/blob/master/google-cloud-storage/lib/google/cloud/storage/bucket.rb#L375-L376) still appear in the documentation? 

```
        # `:multi_regional`, `:regional`, and  `durable_reduced_availability`
        # are accepted as legacy storage classes.
```

**Comment by quartzmo** [comment]
@JesseLovelace If the legacy class mention in my question above is OK, should [this line](https://github.com/googleapis/google-cloud-ruby/blob/master/google-cloud-storage/lib/google/cloud/storage/bucket/lifecycle.rb#L113-L115) (and similar lines) in `Lifecycle` be changed to list legacy storage classes separately?

**Comment by JesseLovelace** [comment]
Specifying that they are accepted as legacy storage classes is OK. Liens such as that one should be changed to specify that they are legacy

**Comment by quartzmo** [comment]
> Liens such as that one should be changed to specify that they are legacy

Done.
