### ISSUE TITLE
Fix pubsub `subscriber.stop` and `subscriber.wait!` documentation. 

### ISSUE THREAD

**Issue by josedonizetti** [googleapis/google-cloud-ruby#4011]
Since the PR https://github.com/googleapis/google-cloud-ruby/pull/2278 the documentation for the methods `stop`, and `wait!` are incorrect. Both mention the behavior is to wait until all pending messages are processed, which is not the case anymore, pending messages are now purged: 

https://github.com/googleapis/google-cloud-ruby/blob/master/google-cloud-pubsub/lib/google/cloud/pubsub/subscriber.rb#L126 

https://github.com/googleapis/google-cloud-ruby/blob/master/google-cloud-pubsub/lib/google/cloud/pubsub/subscriber.rb#L149

https://github.com/googleapis/google-cloud-ruby/blob/master/google-cloud-pubsub/lib/google/cloud/pubsub/subscriber/stream.rb#L90

Notice that not only pending messages are purged, based on tests I have been doing, in-progress messages are also stopped, which I'm not sure if is a feature, or a bug.

I'm willing to open a pull request to fix the documentation, but I'd like to first understand what is actually expected now from the stop/wait methods. It won't process any pending messages, but how about not finish processing in-progress messages?

**Comment by blowmage** [comment]
Yes, we should correct the documentation. The behavior is now that received but unprocessed messages will purged when the subscriber is stopped, and will be reclaimed by the API. But messages that have been processed (by invoking the subscriber's callback) but not yet updated to the API when stopped will update the API.

**Comment by pjohnmeyer** [comment]
@blowmage: Which of the two behaviors above is supposed to apply to a message that is still _being_ processed? Specifically, this scenario:

- Subscriber callback is called on thread A.
- Before callback completes, stop-wait is called from thread B

It seems in my experimentation that the callback in thread A is being interrupted.

**Comment by blowmage** [comment]
I believe that if the Subscriber is stopped before the callback is completed, the message is purged.

Or, more accurately, if the Subscriber is stopped before the message is acked or mod acked then the message is purged. If is possible to ack or mod ack the message, and then perform other work in the callback. So if the Subscriber is stopped during that post ack/mod ack work then the message should still be updated to the API.

**Comment by blowmage** [comment]
This is fixed in https://github.com/googleapis/google-cloud-ruby/releases/tag/google-cloud-pubsub/v0.39.2
