### ISSUE TITLE
Bigtable::Table#column_families should return frozen hash

### ISSUE THREAD

**Issue by quartzmo** [googleapis/google-cloud-ruby#4133]
`Bigtable::Table#column_families` currently returns an ordinary array of `ColumnFamily` instances. While this data representation is complete (`Bigtable::ColumnFamily` includes a `name` attr), it is inconsistent with [the `column_families` param type in `Project#create_table` and `Instance#create_table`:

```
        # @param column_families [Hash{String => Google::Cloud::Bigtable::ColumnFamily}]
        #   (See {Google::Cloud::Bigtable::Table::ColumnFamilyMap})
        #   If unspecified, you may use a code block to add column families.
```
In this structure, the hash keys are the same as the `ColumnFamily#name`. An alternative solution would be to change the `column_families` param to an array of `ColumnFamily`, but this would have to be checked for duplicate `name` values.

**Comment by blowmage** [comment]
I would expect that it would return a frozen hash, but yield a non-frozen ColumnFamilyMap with all the modification helper methods. The return value should be the same as the method argument IMO.

**Comment by quartzmo** [comment]
Updated description to change to frozen hash. See #4134 for the yield.

**Comment by quartzmo** [comment]
Per offline discussion with @dazuma, the return type should be a frozen `ColumnFamilyMap`, not a frozen hash.
