### ISSUE TITLE
Bigtable public methods expose lower-level API types

### ISSUE THREAD

**Issue by quartzmo** [googleapis/google-cloud-ruby#4146]
The published class methods [`Bigtable::ColumnFamily.create_modification`](https://github.com/googleapis/google-cloud-ruby/blob/master/google-cloud-bigtable/lib/google/cloud/bigtable/column_family.rb#L158), `Bigtable::ColumnFamily.update_modification` and `Bigtable::ColumnFamily.drop_modification` all return `Google::Bigtable::Admin::V2::ModifyColumnFamiliesRequest::Modification`, a lower-level type that should not be exposed in the veneer API.

A thorough audit of Bigtable should be performed to verify that no other lower-level types are exposed.

**Comment by blowmage** [comment]
Google::Cloud::Bigtable::MutationEntry

* [`#mutations ⇒ Array<Google::Bigtable::V2::Mutation>`](https://googleapis.dev/ruby/google-cloud-bigtable/v0.6.2/Google/Cloud/Bigtable/MutationEntry.html#mutations-instance_method)

Google::Cloud::Bigtable::MutationOperations

* [`#mutate_rows(entries) ⇒ Array<Google::Bigtable::V2::MutateRowsResponse::Entry>`](https://googleapis.dev/ruby/google-cloud-bigtable/v0.6.2/Google/Cloud/Bigtable/MutationOperations.html#mutate_rows-instance_method)

Google::Cloud::Bigtable::RowFilter::ChainFilter

* [`#filters ⇒ Array<Google::Bigtable::V2::RowFilter>`](https://googleapis.dev/ruby/google-cloud-bigtable/v0.6.2/Google/Cloud/Bigtable/RowFilter/ChainFilter.html#filters-instance_method)

Google::Cloud::Bigtable::RowFilter::InterleaveFilter

* [`#filters ⇒ Array<Google::Bigtable::V2::RowFilter>`](https://googleapis.dev/ruby/google-cloud-bigtable/v0.6.2/Google/Cloud/Bigtable/RowFilter/InterleaveFilter.html#filters-instance_method)

Google::Cloud::Bigtable::Table

* [`#mutate_rows(entries) ⇒ Array<Google::Bigtable::V2::MutateRowsResponse::Entry>`](https://googleapis.dev/ruby/google-cloud-bigtable/v0.6.2/Google/Cloud/Bigtable/Table.html#mutate_rows-instance_method)

Google::Cloud::Bigtable::AppProfile

* .multi_cluster_routing ⇒ Google::Bigtable::Admin::V2::AppProfile::MultiClusterRoutingUseAny
* .single_cluster_routing(cluster_id, allow_transactional_writes: false) ⇒ Google::Bigtable::Admin::V2::AppProfile::SingleClusterRouting
* #multi_cluster_routing ⇒ Google::Bigtable::Admin::V2::AppProfile::MultiClusterRoutingUseAny
* #single_cluster_routing(cluster_id, allow_transactional_writes: false) ⇒ Google::Bigtable::Admin::V2::AppProfile::SingleClusterRouting
* #routing_policy ⇒ Google::Bigtable::Admin::V2::AppProfile::SingleClusterRouting, Google::Bigtable::Admin::V2::AppProfile::MultiClusterRoutingUseAny
* #routing_policy=(policy)
  * policy (Google::Bigtable::Admin::V2::AppProfile::SingleClusterRouting | Google::Bigtable::Admin::V2::AppProfile::MultiClusterRoutingUseAny)

Google::Cloud::Bigtable::ColumnFamily

* .create_modification(name, gc_rule) ⇒ Google::Bigtable::Admin::V2::ModifyColumnFamiliesRequest::Modification
* .drop_modification(name) ⇒ Google::Bigtable::Admin::V2::ModifyColumnFamiliesRequest::Modification
* .update_modification(name, gc_rule) ⇒ Google::Bigtable::Admin::V2::ModifyColumnFamiliesRequest::Modification

Google::Cloud::Bigtable::GcRule

* .intersection(*rules) ⇒ Google::Bigtable::Admin::V2::GcRule
* .max_age(age) ⇒ Google::Bigtable::Admin::V2::GcRule
* .max_versions(versions) ⇒ Google::Bigtable::Admin::V2::GcRule
* .union(*rules) ⇒ Google::Bigtable::Admin::V2::GcRule
* #intersection ⇒ Google::Bigtable::Admin::V2::GcRule::Intersection
* #intersection=(rules)
  * rules (Array<Google::Cloud::Bigtable::GcRule>) (Is this right?)
* #union ⇒ Google::Bigtable::Admin::V2::GcRule::Union
* #union=(rules) ⇒ Object
  * rules (Array<Google::Cloud::Bigtable::GcRule>) (Is this right?)

**Comment by quartzmo** [comment]
Thanks for this comprehensive list @blowmage !
