### ISSUE TITLE
rake test:coverage reports 0.0% coverage at the gem level

### ISSUE THREAD

**Issue by quartzmo** [googleapis/google-cloud-ruby#4167]
Running `rake test:coverage` at the gem level generates reports with "0.0%" coverage. (I tested in bigquery and bigtable). The top-level `rake test:coverage` task appears to work correctly.

@blowmage commented:

> it looks like things have changed over time. originally the test task was defined like this:
```rb
task :test do
  $LOAD_PATH.unshift "lib", "test"
  Dir.glob("test/**/*_test.rb")
    .each { |file| require_relative file }
end
```

> but now the test task is defined like this:

```rb
Rake::TestTask.new do |t|
  t.libs << "test"
  t.test_files = FileList["test/**/*_test.rb"]
  t.warning = false
end
```

> that change is the reason why the coverage report generates with no coverage

**Comment by dazuma** [comment]
We're not using test:coverage for now.
