### ISSUE TITLE
Authentication.MD references non existing method

### ISSUE THREAD

**Issue by adityasrini** [googleapis/google-cloud-ruby#4188]
#### Environment details

  - OS: macOS 10.15
  - Ruby version: 2.6.3
  - Gem name and version: google-cloud-dialogflow 0.7.0

#### Steps to reproduce

  1. Initialize a client with the code provided in AUTHENTICATION.MD: `client = Google::Cloud::Dialogflow.new`

#### Full backtrace

```ruby
NoMethodError (undefined method `new' for Google::Cloud::Dialogflow:Module)
	from (irb):7
```

#### Notes

This method doesn't seem to exist in the source code. I can get a new Agent by calling the `Agents.new` method in the `Dialogflow` module. Perhaps this is what was meant?

**Comment by blowmage** [comment]
Thanks for letting us know. Dialogflow has several clients, which is why those `.new` methods are a level lower than `Google::Cloud::Dialogflow`. I'll get these documents updated.
