### ISSUE TITLE
Add support for uniform bucket level access

### ISSUE THREAD

**Issue by JesseLovelace** [googleapis/google-cloud-ruby#4202]
(I don't have assign permission in this repo, but this should be assigned to @quartzmo)

Bucket Policy Only is being replaced with Uniform Bucket Level Access. Please add support and mark BPO as deprecated. A reference implementation is available here: https://github.com/googleapis/google-cloud-java/pull/5899

Get in touch with me if you have trouble accessing the one pager

**Comment by quartzmo** [comment]
@JesseLovelace Thanks, I have access to "GCS - Uniform bucket-level access GA".

**Comment by JesseLovelace** [comment]
Great! Let me know if you need anything else. We are targeting end of month for release

**Comment by quartzmo** [comment]
See #3794 for previous workaround involving Uniform Bucket Level Access.

**Comment by quartzmo** [comment]
@JesseLovelace When should we change from this URL? https://cloud.google.com/storage/docs/bucket-policy-only

**Comment by quartzmo** [comment]
@JesseLovelace This issue is a request for "Phase 2 Update BPO to use the UBLA fields instead.", correct?

**Comment by JesseLovelace** [comment]
Yes, the workaround should be removed and we should actually use UBLA. BPO should still be supported but marked as deprecated, and if possible calls to set BPO should set UBLA instead. You can change the doc links in this PR, and we won't merge until the new docs are ready
