### ISSUE TITLE
storage: content-type is not copied when providing a block in copy

### ISSUE THREAD

**Issue by renchap** [googleapis/google-cloud-ruby#4254]
#### Environment details

  - OS: macOS 10.15
  - Ruby version: 2.6.4
  - Gem name and version: google-cloud-storage 1.21.1

#### Steps to reproduce

Call `File#copy` on an existing file with a `content-type`, and provide a block to set, for example, `cache_control`. The returned file wont have the correct `content-type.`

#### Code example

```ruby
require "google/cloud/storage"

gcs = Google::Cloud::Storage.new(project: '##project')
bucket_name = "##bucket_name"

bucket = gcs.bucket(b, skip_lookup: true)

original_file = bucket.file("test.png")

original_file.content_type
# => "image/png"

test1 = original_file.copy(bucket_name, "test_1.png")
test1.content_type
# => "image/png"

test2 = original_file.copy(bucket_name, "test_2.png") { |f| f.cache_control = "public, max-age: 7200" }
test2.cache_control
# => "public, max-age: 7200"
test2.content_type
# => nil
```

This has been first reported here: https://github.com/renchap/shrine-google_cloud_storage/issues/36
I suspect it comes from https://github.com/googleapis/google-cloud-ruby/blob/2ad4e22280dc8a2e61613251461e8049129deb4b/google-cloud-storage/lib/google/cloud/storage/file.rb#L1201-L1208
and the code overrides the attributes copied from the original file with `nil`, but I did not debug this further.

**Comment by quartzmo** [comment]
@renchap Thank you for this detailed issue. I'll look into it promptly!

**Comment by quartzmo** [comment]
Updated from bug to feature request since the existing behavior is considered consistent with the GCS service API.
