### ISSUE TITLE
Investigate build failure

### ISSUE THREAD

**Issue by blowmage** [googleapis/google-cloud-ruby#4280]
Seen this in two different build failures:

```
  1) Error:
Google::Cloud::PubSub::Topic::publish_async::ordered_messages::mock_pubsub#test_0002_publishes messages with ordering_key and callback:
NoMethodError: undefined method `lock' for nil:NilClass
    /root/.rbenv/versions/2.5.7/lib/ruby/2.5.0/monitor.rb:192:in `mon_enter'
    /root/.rbenv/versions/2.5.7/lib/ruby/2.5.0/monitor.rb:233:in `block in mon_synchronize'
    /root/.rbenv/versions/2.5.7/lib/ruby/2.5.0/monitor.rb:233:in `handle_interrupt'
    /root/.rbenv/versions/2.5.7/lib/ruby/2.5.0/monitor.rb:233:in `mon_synchronize'
    /tmpfs/src/github/google-cloud-ruby/google-cloud-pubsub/lib/google/cloud/pubsub/async_publisher.rb:279:in `run_background'
    /tmpfs/src/github/google-cloud-ruby/google-cloud-pubsub/lib/google/cloud/pubsub/async_publisher.rb:87:in `block in initialize'
```

**Comment by blowmage** [comment]
https://source.cloud.google.com/results/invocations/ec0836df-89c4-497d-9c23-00fa994b0894/log
https://source.cloud.google.com/results/invocations/6e41b213-4622-4619-8593-f5f4bc92c418/log

**Comment by quartzmo** [comment]
This is the [error line](https://github.com/googleapis/google-cloud-ruby/blob/26b6ee9a39af7097e3109b4a964892bd44114fe9/google-cloud-pubsub/lib/google/cloud/pubsub/async_publisher.rb#L282) for the links above (more recent commits have shifted the code).

**Comment by quartzmo** [comment]
Should the initialization of `@cond` be moved higher in the initializer? Above [this line](https://github.com/googleapis/google-cloud-ruby/blob/26b6ee9a39af7097e3109b4a964892bd44114fe9/google-cloud-pubsub/lib/google/cloud/pubsub/async_publisher.rb#L90)?

**Comment by blowmage** [comment]
> Should the initialization of @cond be moved higher in the initializer? Above this line?

Ugh, probably... Good, catch.
