### ISSUE TITLE
Storage: Add support for archive storage class

### ISSUE THREAD

**Issue by tritone** [googleapis/google-cloud-ruby#4285]
GCS is adding a storage class called "archive" to the existing options for object storage (coldline, standard, etc). Support for this should be added to this client library. This has already been implemented in the C++ client library and there is a PR in python; reference PR [here](https://github.com/googleapis/google-cloud-python/issues/9532)

This should be straightforward as ARCHIVE should just mirror existing valid storage classes. I see the following places where changes are required in order to accomplish this:

* https://github.com/googleapis/google-cloud-ruby/blob/master/google-cloud-storage/lib/google/cloud/storage/convert.rb (add new constant).
* https://github.com/googleapis/google-cloud-ruby/blob/master/google-cloud-storage/lib/google/cloud/storage/bucket.rb (update documentation).
* https://github.com/googleapis/google-cloud-ruby/blob/master/google-cloud-storage/lib/google/cloud/storage/project.rb (update documentation).
* https://github.com/googleapis/google-cloud-ruby/blob/master/google-cloud-storage/lib/google/cloud/storage/file.rb (update documentation).
* Consider adding or modifying at least 1 test to exercise the archive storage class.

**Comment by frankyn** [comment]
For the record: this request should come after UBLA is completed/ready.
