### ISSUE TITLE
Cloud DataFlow

### ISSUE THREAD

**Issue by amedeiros** [googleapis/google-cloud-ruby#4290]
**Is your feature request related to a problem? Please describe.**
Missing Cloud DataFlow.

 **Describe the solution you'd like**
Client for Cloud DataFlow

 **Additional context**
https://cloud.google.com/dataflow/docs/reference/rest/

I looked at the GO SDK and I do not see it there either is there a reason for no API support of Cloud DataFlow in the SDK's or am I just missing something thanks!

**Comment by blowmage** [comment]
The generated Ruby client for the Dataflow API is found in the google-api-client gem.

https://googleapis.dev/ruby/google-api-client/latest/Google/Apis/DataflowV1b3.html

Does this answer your question?

**Comment by amedeiros** [comment]
There is a generated on in a different gem and is useable with the DataFlow API? Why is there no client in this project ?
