### ISSUE TITLE
Request to release google-cloud-storage

### ISSUE THREAD

**Issue by frankyn** [googleapis/google-cloud-ruby#4376]
Hi @quartzmo, could you cut a release for the google-cloud-storage gem?

cc: @JesseLovelace

**Comment by dazuma** [comment]
A release happened this morning about 8am, with support for `Bucket#uniform_bucket_level_access`. Is that what you're looking for?
https://rubygems.org/gems/google-cloud-storage/versions/1.23.0
https://googleapis.dev/ruby/google-cloud-storage/latest/file.CHANGELOG.html

**Comment by frankyn** [comment]
+1, thanks @dazuma! Closing request. Apologies for the confusion.
