### ISSUE TITLE
Passing additional information in error reports, such as request ID

### ISSUE THREAD

**Issue by jensljungblad** [googleapis/google-cloud-ruby#4381]
I can't seem to find information on if it's possible to include additional context when reporting errors. For instance, it would be useful to attach the request ID (or background job ID or similar) to errors, so you can find all the relevant log entries for the request that failed when looking at the error.

Currently it seems you can only attach an HTTP request and a "user" to the context?

**Comment by blowmage** [comment]
Hi, thanks for your question. Unfortunately, the Error Reporting API does not have any fields for user-defined metadata about the error. And the Ruby client can't add support for this until the API supports it.

If this is something you would like to request the API to support, you can use the [Stackdriver Support guide](https://cloud.google.com/stackdriver/docs/getting-support#feature-request) to make a feature request, or you can upvote the existing [Metadata on reported error events](https://issuetracker.google.com/issues/122450670) issue.
