### ISSUE TITLE
rails with spring gem and google/cloud/firestore thread fault

### ISSUE THREAD

**Issue by davingee** [googleapis/google-cloud-ruby#4387]
If i add spring to the gemfile i get this error, when i remove spring it works as expected.

## Environment details
  - OS: Mac OS Catalina 10.15
  - Ruby version: ruby-2.4.5
  - Gem name and version: google-cloud-firestore (1.1.0)

#### Steps to reproduce
  1.  install rails (5.2.3)
  2. install spring (2.1.0)
  3. rails c
#### Code example

```ruby
  require "google/cloud/firestore"
  
  firestore = Google::Cloud::Firestore.new(
    project_id: 'project_id',
    credentials: "/path.json"
  )

  city_ref = firestore.doc "cities/LA"

  data = {
    name:    "Los Angeles",
    state:   "CA",
    country: "USA"
  }

  city_ref.set data
```

#### Full backtrace

```sh
2.4.5 :019 >     city_ref.set data
objc[17615]: +[__NSCFConstantString initialize] may have been in progress in another thread when fork() was called.
objc[17615]: +[__NSCFConstantString initialize] may have been in progress in another thread when fork() was called. We cannot safely call it or ignore it in the fork() child process. Crashing instead. Set a breakpoint on objc_initializeAfterForkError to debug.
```

**Comment by blowmage** [comment]
Firestore depends on GRPC, and the GRPC gem is unable to survive a fork. For this reason, we suggest app developers defer all calls and connections until after the the web app is fully initialized and forked, so each forked process establishes its own local connection.

This means that any initialization your application is doing should be performed using `Spring.after_fork` or Puma's `after_worker_fork`.

**Comment by iDuuck** [comment]
I am seeing the same thing when using the custom service I built using the `rails console`.

Here is my worker:

```ruby
# frozen_string_literal: true

require 'google/cloud/language'

class TextClassificationService
  include Callable

  # Error classes
  class NoTextSetException < RuntimeError; end

  # Class definition
  def initialize(text: nil)
    raise NoTextSetException, 'No text was set to translate' if text.nil?

    @client = Google::Cloud::Language.new
    @text = text
    @working_copy = text
    @categories = []
  end

  def call
    translate
    classify

    {
      source: @text,
      translated_text: @working_copy,
      categories: @categories
    }
  end

  protected

  def translate
    response = DeepL.translate @text, nil, 'EN'
    @working_copy = response.text
  end

  def classify
    document = {
      content: @working_copy,
      language: :en,
      type: :PLAIN_TEXT
    }
    response = @client.classify_text document

    @categories = response.categories
  end
end
```

**Comment by blowmage** [comment]
@iDuuck Are you creating a `TextClassificationService` instance object at app boot? Or are you creating this object in the `Spring.after_fork` callback?

**Comment by iDuuck** [comment]
No, on the server this is working. FWIW this is only not working in console.

**Comment by quartzmo** [comment]
Closing as explained by comment in #4455 

> Spring starts a process of your app, and then forks the process whenever you open a console or run a task against it. Each action is run on a forked process of the original process.

**Comment by Bontgoy** [comment]
For folks using `Active Job` running `rails jobs:work` and placing your firestore services in jobs for workers to process the actions allows for use of the firestore api in the console.

`SomeFirestoreServiceJob.perform_later(args*)`
