### ISSUE TITLE
Performance issue with AsyncWriter

### ISSUE THREAD

**Issue by alanhala** [googleapis/google-cloud-ruby#4428]
I have an api which receives logs from Heroku Logplex and then sends those to GCP. Heroku sends batch of logs (sometimes up to 70 entries) and we send them all together using the async writer (one shared async writer per puma worker).
After a while running the api, I started to timeout some requests. In order to figure out what was happening, I added Google Trace and I found out that the Google Cloud Logging gem was taking sometimes 2 seconds to run `write_entries`.
I also tried using an async writer per thread instead, but we still get high response times.

Is this AsyncWriter supposed to support that amount of logs in one batch? Is there something that I can configure from the async writer that would help me with this?

#### Environment details

  - Environment: Heroku Standard-2x Dyno
  - Ruby version: 2.4.4
  - Gem name and version: google-cloud-logging (1.8.0)

**Comment by quartzmo** [comment]
Hi @alanhala,

Thanks for reporting this issue. We'll try to reproduce what you're seeing and get an answer to you as quickly as we can. Meanwhile, if you can think of any more information that might help us replicate it, please post it here.
