### ISSUE TITLE
Usage of config is inconsistent between logging and error reporting

### ISSUE THREAD

**Issue by jensljungblad** [googleapis/google-cloud-ruby#4434]
There are two config options: `use_error_reporting` and `use_logging`. The `use_error_reporting` option is used both to enable sending error reports at all, and to enable the railtie middleware. The `use_logging` option, however, is only used to enable the railtie middleware. You can still manually send log entries without enabling that option.

Which one is doing the correct thing? What are the options indented to do?

**Comment by quartzmo** [comment]
Hi @jensljungblad,

The [google-cloud-error_reporting](https://rubygems.org/gems/google-cloud-error_reporting) gem, which provides the `use_error_reporting` config option and corresponding [`Google::Cloud::ErrorReporting::Railtie`](https://github.com/googleapis/google-cloud-ruby/blob/master/google-cloud-error_reporting/lib/google/cloud/error_reporting/rails.rb) Railtie and [`Google::Cloud::ErrorReporting::Middleware`](https://github.com/googleapis/google-cloud-ruby/blob/master/google-cloud-error_reporting/lib/google/cloud/error_reporting/middleware.rb) middleware, is a client for the [Stackdriver Error Reporting](https://cloud.google.com/error-reporting/) service.

Similarly, the [google-cloud-logging](https://rubygems.org/gems/google-cloud-logging) gem, which provides the `use_logging` config option and corresponding [`Google::Cloud::Logging::Railtie`](https://github.com/googleapis/google-cloud-ruby/blob/master/google-cloud-logging/lib/google/cloud/logging/rails.rb) Railtie and [`Google::Cloud::Logging::Middleware`](https://github.com/googleapis/google-cloud-ruby/blob/master/google-cloud-logging/lib/google/cloud/logging/middleware.rb) middleware, is a client for the [Stackdriver Logging](https://cloud.google.com/logging/) service.

They are both bundled in the [stackdriver](https://rubygems.org/gems/stackdriver) gem and can both be configured in the same block with `Google::Cloud.configure`, but they are actually separate clients for separate services.

The guide [Stackdriver Instrumentation Configuration](https://googleapis.dev/ruby/stackdriver/latest/file.INSTRUMENTATION_CONFIGURATION.html) covers all of the configuration options.

**Comment by jensljungblad** [comment]
Hi @quartzmo! Thanks for getting back. Yes indeed, I was just pointing out that the usage is inconsistent. From the error reporting gem, it seems like the `use_` configuration option should also control if the error logging occurs or not. For logging, it only controls if the middleware gets added or not. You can still log even though `use_logging = false`.

Seems one of them is incorrect? :)

**Comment by quartzmo** [comment]
If that is true, then given the description `use_logging: [Boolean] Explicitly enable or disable Logging features.` in the docs, it seems that `use_logging = false` is not behaving correctly. Can you provide any more details on how to reproduce?

**Comment by quartzmo** [comment]
Are you using `Rails.application.configure` or `Google::Cloud.configure`? If you are using `Rails.application.configure`, then it seems that [this gate](https://github.com/googleapis/google-cloud-ruby/blob/master/google-cloud-logging/lib/google/cloud/logging/rails.rb#L144) should prevent logging. However, I do not see any similar logic if you are using ``Google::Cloud.configure`.

By contrast, `google-cloud-error_reporting` has a very clear gate in [`Google::Cloud::ErrorReporting.report`](https://github.com/googleapis/google-cloud-ruby/blob/master/google-cloud-error_reporting/lib/google/cloud/error_reporting.rb#L214).

**Comment by jensljungblad** [comment]
We are using `Google::Cloud.configure`. 

```ruby
Google::Cloud.configure do |config|
  config.use_logging = false # Makes no difference, logging still possible
end
```

> By contrast, google-cloud-error_reporting has a very clear gate in Google::Cloud::ErrorReporting.report.

Exactly. I would assume something similar in logging's `write_entry` or something :)

**Comment by quartzmo** [comment]
Great, thank you. I'm going to try to get input from the original author on this, it may take a little bit.

**Comment by dazuma** [comment]
I can speak to the original intent. It was to have a switch to turn on/off reporting of {errors,logs} in different environments. For example, in local development, you normally don't want to report these to a remote service, but you'll have code in your app that does so, so there should be a way to disable it—as well as a way to re-enable it in case you decide you do want it (for testing or whatever other purpose).

With that in mind, the original intent was for "high level" calls to honor the switch. Those are the calls we expect most applications to use, and they should be regulated. However, there are also "raw" API calls, and those were intended not to be regulated—for consistency with all other "raw" API interfaces in `google-cloud-*` gems (which are not regulated). The thought process is: we should allow switching "logging entries" on and off, but not "calling APIs".

You're right, of course, that logging's `write_entries` falls under both categories, and so is ambiguous. (And indeed, this whole distinction we were trying to make is also quite ambiguous.) Our assumption was that people would not be using `write_entries` by itself, but it's becoming clear that was an incorrect assumption.

**Comment by jensljungblad** [comment]
Thanks, that helps me understand the intention!
