### ISSUE TITLE
Stackdriver not logging SQL requests by ActiveRecord

### ISSUE THREAD

**Issue by farnoy** [googleapis/google-cloud-ruby#4501]
I have successfully configured logging and am seeing access logs from Rails in my Stackdriver console. What I'm not seeing are timing summaries that rails outputs (time spent in views, DB, etc.) or the detailed ActiveRecord diagnostics for every query executed.

My `config/environments/production.rb` has these lines:

```rb
  config.log_level = :debug

  if enable_stackdriver
    project_id = ...
    log_name = ...
    keyfile = ...
    puts "Logging to stackdriver project #{project_id}/#{log_name}"
    config.google_cloud.use_logging = true
    config.google_cloud.logging.project_id = project_id
    config.google_cloud.logging.log_name = log_name
    config.google_cloud.logging.keyfile = keyfile
  end
```

Does the ruby library filter rails logs in any way? I'm fairly sure that replacing `Rails.logger` with `STDOUT` would not only output access logs, but SQL queries & timings too. While digging through `google-cloud-logging`, I've found a configuration value `set_default_logger_on_rails_init`, is it needed or useful?

**Comment by dazuma** [comment]
Just checking a few things.
* Is the `google-cloud-logging` gem in your bundle?
* Is the `stackdriver` gem in your bundle? If not, do you have the following in your `application.rb` or someplace similar: `require "google/cloud/logging/rails"` (See [this doc](https://github.com/googleapis/google-cloud-ruby/blob/master/google-cloud-logging/INSTRUMENTATION.md) for more info on setting up instrumentation.)
* What is your logging level set to? Make sure it's set appropriately to catch the level of the ActiveRecord logs you're looking for.

**Comment by farnoy** [comment]
@dazuma 

I have the gem, I defined `stackdriver` with:

```rb
group :production do
  gem "stackdriver"
end
```

My logging level is `:debug` as in my original snippet above. I also see the print I've put in `config/environments/production.rb` in my server logs. And finally, I see it correctly logging to my given stackdriver label, but there mostly just access logs there, and definitely no ActiveRecord logs.

`Rails.logger` seems to work correctly if used by my application or another library. For example, my app uses `google-cloud-storage (1.13.0)` to upload files to GCS, and I see logs made from here, for example:

```
/data/rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/google-api-client-0.19.8/lib/google/apis/core/upload.rb
161:          logger.debug { sprintf('Upload status %s', upload_status) }
```

And I can also confirm that I'm seeing custom messages defined in my app's codebase too. So it seems to be working overall, but filtering certain types of output (at least ActiveRecord)? I'm not sure what's happening here.

**Comment by farnoy** [comment]
Looks like it was a problem with my web server. Passenger seems to replace some of the loggers in the "smart spawning" mode. This was the fix I went with:

```ruby
if defined?(PhusionPassenger)
  PhusionPassenger.on_event(:starting_worker_process) do |forked|
    if forked
      ActiveRecord::Base.logger = Rails.logger
      ActionController::Base.logger = Rails.logger
    end
  end
end
```

**Comment by farnoy** [comment]
I'd love to get your feedback on this. Is it safe to reuse the logger after forking? I noticed the `set_default_logger!` method with comments about forking, but I didn't know how to trigger it.

**Comment by fhinkel** [comment]
Greetings, we're closing this. Looks like the issue got resolved. Please let us know if the issue needs to be reopened.
