### ISSUE TITLE
Alpine 3.9

### ISSUE THREAD

**Issue by CarlosUvaSilva** [googleapis/google-cloud-ruby#4515]
Trying to build my docker image using `ruby:2.6.4-alpine3.9`

my Gemfile.lock has these dependencies:

google-cloud-translate (2.1.0)
grpc (1.25.0)
google-protobuf (3.10.1)

I'm getting error: 
```
 Error relocating /usr/local/bundle/gems/google-protobuf-3.11.2/lib/google/protobuf_c.so: __va_copy: symbol not found - /usr/local/bundle/gems/google-protobuf-3.11.2/lib/google/protobuf_c.so
```

I know this has been reported in other issues but none of the solutions provided there solved my problem

**Comment by blowmage** [comment]
Have you tried setting the `BUNDLE_FORCE_RUBY_PLATFORM=1` environment variable? That will force the gem to not use the pre-compiled version and install/compile the gem on Alpine.

**Comment by blowmage** [comment]
Where does your ``/usr/local/bundle` directory come from? Are you installing the gems in the docker image? Or are you copying those files from your host machine?

**Comment by CarlosUvaSilva** [comment]
hello @blowmage 

i've tried `RUN BUNDLE_FORCE_RUBY_PLATFORM=1 bundle install` on my Dockerfile.
About your second question. I'm installing the gems in my dockerfile yes, copying both Gemfile and Gemfile.lock and using the previous command. I tried to force the `platform [ruby]` (spelling) thing but it didn't work

**Comment by quartzmo** [comment]
@CarlosUvaSilva Any success yet with your install?

**Comment by blowmage** [comment]
> copying both Gemfile and Gemfile.lock 

I'd be curious what gem your Gemfile.lock file is specifying. Have you tried not copying that file to your docker container?

**Comment by CarlosUvaSilva** [comment]
@quartzmo i had some urgency on deploying my project so I gave up and went with an ubuntu image

@blowmage If I only copy Gemfile I get the latest gem versions which could break stuff

**Comment by quartzmo** [comment]
I'm going to close this for now. Please re-open if/when more information is available.
