### ISSUE TITLE
Cannot access any of the documents linked to googleapis.dev

### ISSUE THREAD

**Issue by jeremywadsack** [googleapis/google-cloud-ruby#4553]
All of the API documents seem to link to https://googleapis.dev/ but when I try to access that I get a "refused to connect" error. 

Note that I've tried this on different computers on various networks so I don't think it's a local issue. The only place I've been able to connect is from a shell _with Google Cloud_. 

Is this an internal Google source that's not public? Or is there a firewall rule missing somewhere?

#### From outside Google Cloud network

```
$ curl -i https://googleapis.dev/
curl: (7) Failed to connect to googleapis.dev port 443: Connection refused
```

#### From a shell in GKE

```
$ curl -i https://googleapis.dev/
HTTP/2 200 
x-guploader-uploadid: AEnB2UoHVvaqc_Xj8e-bl2mD0kV9Cy8q7McYxktjhTnlfCw2W_gTAbssljk0adsZRhepEFvFGBtGMxbwO5AVeWps2LPj1L4SdQkko3C7SBShlfUirEE_pZI
expires: Thu, 02 Jan 2020 18:23:13 GMT
date: Thu, 02 Jan 2020 18:23:13 GMT
cache-control: private, max-age=0
last-modified: Mon, 29 Apr 2019 16:28:42 GMT
etag: "708c9af889914929f02a4e854cee0cd0"
x-goog-generation: 1556555322934181
x-goog-metageneration: 1
x-goog-stored-content-encoding: identity
x-goog-stored-content-length: 73
content-type: text/html
x-goog-hash: crc32c=+0bRJw==
x-goog-hash: md5=cIya+ImRSSnwKk6FTO4M0A==
x-goog-storage-class: MULTI_REGIONAL
accept-ranges: bytes
content-length: 73
server: UploadServer
alt-svc: clear

<meta http-equiv="refresh" content="0; url=https://cloud.google.com/" />
```

Could someone else check this and make sure it's not just me?

**Comment by quartzmo** [comment]
Do you need to access the root `https://googleapis.dev/` for some reason?

The documents linked from API docs appear accessible to me. For example:

```
curl https://googleapis.dev/ruby/google-cloud-bigquery/latest/file.AUTHENTICATION.html
```

**Comment by jeremywadsack** [comment]
It's just my computer apparently. I checked other machines (which I should have done first) and all can connect. Oddly I can connect by IPv4 (bypassing the hostname-certificate warning) but can't by hostname. Must be something mucked up in my DNS resolver. 

I'll close this. Sorry for the noise.

**Comment by jeremywadsack** [comment]
In case anyone else runs into this, I had an old, old version of [Pow](Pow.cx) running that mapped `.dev` DNS requests to localhost. Pow now uses `.test` by default [as it should](https://en.wikipedia.org/wiki/.test). :)

[Removing Pow](http://pow.cx/manual.html#section_1.2) resolved this.
