### ISSUE TITLE
Options for using Stackdriver without gRPC until fork is supported

### ISSUE THREAD

**Issue by jeremywadsack** [googleapis/google-cloud-ruby#4554]
As discussed in https://github.com/googleapis/google-cloud-ruby/issues/2917#issuecomment-463008526 and in grpc/grpc#7951, the `grpc` gem currently doesn't work when forked.

I set up Google Cloud (Stackdriver) Monitoring for our system to run in Resque workers. Resque forks the worker before it runs each job. This fails with one of two errors.

In a linux system, I get the following (as expected from grpc/grpc#16332):

> grpc cannot be used before and after forking

On macOS I get this:

> objc[97868]: +[__NSCFConstantString initialize] may have been in progress in another thread when fork() was called.
> objc[97868]: +[__NSCFConstantString initialize] may have been in progress in another thread when fork() was called. We cannot safely call it or ignore it in the fork() child process. Crashing instead. Set a breakpoint on objc_initializeAfterForkError to debug.

(That may be a separate issue and let me know if I should post it somewhere like grpc.)

I see that the other Stackdriver gems were "fixed to work in a forked environment": https://github.com/googleapis/google-cloud-ruby/issues/2888#issuecomment-461476449. Although I can't tell what changes were made to work around this.

In any event, Stackdriver supports a [REST API](https://cloud.google.com/monitoring/api/ref_v3/rest/) as well as the GRPC one. Is it possible to force the gem to use the REST API?

#### Environment details
  - OS: Ubuntu 18.04.3 (container on COS core), macOS 10.13.6
  - Ruby version: 2.5.5
  - Gem name and version: 
    - google-cloud-monitoring-0.34.1
    - grpc-1.25.0-x86_64-linux, grpc-1.25.0-universal-darwin

**Comment by quartzmo** [comment]
Where are you creating your google-cloud-monitoring client(s)? (Please provide some code if possible) 
You should be creating a client instance *after* each process fork, used only within the scope of the fork. Unlike the other Stackdriver gems, which are handwritten, google-cloud-monitoring does not provide any Rails integration.

If you first create a client in the parent process, then create a client in a forked process (as demonstrated below), you will get an error with `grpc cannot be used before and after forking`.

```
Chriss-iMac:google-cloud-monitoring quartzmo$ rbenv gemset create 2.6.5 monitoring-test
created monitoring-test for 2.6.5
Chriss-iMac:google-cloud-monitoring quartzmo$ gem install google-cloud-monitoring
Fetching google-cloud-monitoring-0.34.1.gem
Successfully installed google-cloud-monitoring-0.34.1
Parsing documentation for google-cloud-monitoring-0.34.1
Installing ri documentation for google-cloud-monitoring-0.34.1
Done installing documentation for google-cloud-monitoring after 1 seconds
1 gem installed
Chriss-iMac:google-cloud-monitoring quartzmo$ gem install irb
Successfully installed irb-1.2.1
Parsing documentation for irb-1.2.1
Installing ri documentation for irb-1.2.1
Done installing documentation for irb after 0 seconds
1 gem installed
Chriss-iMac:google-cloud-monitoring quartzmo$ irb
irb(main):001:0> require "google/cloud/monitoring"
=> true
irb(main):003:0> fork { puts Google::Cloud::Monitoring::ServiceMonitoring.new.class }
=> 70201
irb(main):004:0> Google::Cloud::Monitoring::V3::ServiceMonitoringServiceClient
irb(main):004:0> 
irb(main):005:0> puts Google::Cloud::Monitoring::ServiceMonitoring.new.class
Google::Cloud::Monitoring::V3::ServiceMonitoringServiceClient
=> nil
irb(main):006:0> fork { puts Google::Cloud::Monitoring::ServiceMonitoring.new.class }
=> 70202
irb(main):007:0> Traceback (most recent call last):
                                                   	32: from /Users/quartzmo/.rbenv/versions/2.6.5/gemsets/quartzmo/bin/irb:23:in `<main>'
                                                                                                                                              	31: from /Users/quartzmo/.rbenv/versions/2.6.5/gemsets/quartzmo/bin/irb:23:in `load'
        	30: from /Users/quartzmo/.rbenv/versions/2.6.5/gemsets/quartzmo/gems/irb-1.2.1/exe/irb:11:in `<top (required)>'
                                                                                                                               	29: from /Users/quartzmo/.rbenv/versions/2.6.5/gemsets/quartzmo/gems/irb-1.2.1/lib/irb.rb:398:in `start'
            	28: from /Users/quartzmo/.rbenv/versions/2.6.5/gemsets/quartzmo/gems/irb-1.2.1/lib/irb.rb:469:in `run'
                                                                                                                      	27: from /Users/quartzmo/.rbenv/versions/2.6.5/gemsets/quartzmo/gems/irb-1.2.1/lib/irb.rb:469:in `catch'
    	26: from /Users/quartzmo/.rbenv/versions/2.6.5/gemsets/quartzmo/gems/irb-1.2.1/lib/irb.rb:470:in `block in run'
                                                                                                                       	25: from /Users/quartzmo/.rbenv/versions/2.6.5/gemsets/quartzmo/gems/irb-1.2.1/lib/irb.rb:535:in `eval_input'
         	24: from /Users/quartzmo/.rbenv/versions/2.6.5/gemsets/quartzmo/gems/irb-1.2.1/lib/irb/ruby-lex.rb:134:in `each_top_level_statement'
                                                                                                                                                    	23: from /Users/quartzmo/.rbenv/versions/2.6.5/gemsets/quartzmo/gems/irb-1.2.1/lib/irb/ruby-lex.rb:134:in `catch'
                                             	22: from /Users/quartzmo/.rbenv/versions/2.6.5/gemsets/quartzmo/gems/irb-1.2.1/lib/irb/ruby-lex.rb:135:in `block in each_top_level_statement'
                                                                                                                                                                                             	21: from /Users/quartzmo/.rbenv/versions/2.6.5/gemsets/quartzmo/gems/irb-1.2.1/lib/irb/ruby-lex.rb:135:in `loop'
                                                                                    	20: from /Users/quartzmo/.rbenv/versions/2.6.5/gemsets/quartzmo/gems/irb-1.2.1/lib/irb/ruby-lex.rb:150:in `block (2 levels) in each_top_level_statement'
                    	19: from /Users/quartzmo/.rbenv/versions/2.6.5/gemsets/quartzmo/gems/irb-1.2.1/lib/irb.rb:536:in `block in eval_input'
                                                                                                                                              	18: from /Users/quartzmo/.rbenv/versions/2.6.5/gemsets/quartzmo/gems/irb-1.2.1/lib/irb.rb:693:in `signal_status'
                                    	17: from /Users/quartzmo/.rbenv/versions/2.6.5/gemsets/quartzmo/gems/irb-1.2.1/lib/irb.rb:539:in `block (2 levels) in eval_input'
                                                                                                                                                                         	16: from /Users/quartzmo/.rbenv/versions/2.6.5/gemsets/quartzmo/gems/irb-1.2.1/lib/irb/context.rb:419:in `evaluate'
                                                                       	15: from /Users/quartzmo/.rbenv/versions/2.6.5/gemsets/quartzmo/gems/irb-1.2.1/lib/irb/workspace.rb:114:in `evaluate'
                                                                                                                                                                                             	14: from /Users/quartzmo/.rbenv/versions/2.6.5/gemsets/quartzmo/gems/irb-1.2.1/lib/irb/workspace.rb:114:in `eval'
                                                                                     	13: from (irb):6:in `irb_binding'
                                                                                                                         	12: from (irb):6:in `fork'
                                                                                                                                                          	11: from (irb):6:in `block in irb_binding'
                                                                                                                                                                                                          	10: from /Users/quartzmo/.rbenv/versions/2.6.5/gemsets/quartzmo/gems/google-cloud-monitoring-0.34.1/lib/google/cloud/monitoring.rb:416:in `new'
                                                                                                                                   	 9: from /Users/quartzmo/.rbenv/versions/2.6.5/gemsets/quartzmo/gems/google-cloud-monitoring-0.34.1/lib/google/cloud/monitoring/v3.rb:455:in `new'
                                                              	 8: from /Users/quartzmo/.rbenv/versions/2.6.5/gemsets/quartzmo/gems/google-cloud-monitoring-0.34.1/lib/google/cloud/monitoring/v3.rb:455:in `new'
                                                                                                                                                                                                                  	 7: from /Users/quartzmo/.rbenv/versions/2.6.5/gemsets/quartzmo/gems/google-cloud-monitoring-0.34.1/lib/google/cloud/monitoring/v3/service_monitoring_service_client.rb:230:in `initialize'
                                                                                                                                                                                       	 6: from /Users/quartzmo/.rbenv/versions/2.6.5/gemsets/quartzmo/gems/google-gax-1.8.1/lib/google/gax/grpc.rb:139:in `create_stub'
                                                                                             	 5: from /Users/quartzmo/.rbenv/versions/2.6.5/gemsets/quartzmo/gems/google-gax-1.8.1/lib/google/gax/grpc.rb:139:in `new'
                                                                                                                                                                                                                         	 4: from /Users/quartzmo/.rbenv/versions/2.6.5/gemsets/quartzmo/gems/grpc-1.26.0-universal-darwin/src/ruby/lib/grpc/generic/service.rb:157:in `initialize'
                                                                                                                                                         	 3: from /Users/quartzmo/.rbenv/versions/2.6.5/gemsets/quartzmo/gems/grpc-1.26.0-universal-darwin/src/ruby/lib/grpc/generic/client_stub.rb:102:in `initialize'
                                                                                                  	 2: from /Users/quartzmo/.rbenv/versions/2.6.5/gemsets/quartzmo/gems/grpc-1.26.0-universal-darwin/src/ruby/lib/grpc/generic/client_stub.rb:47:in `setup_channel'
                                            	 1: from /Users/quartzmo/.rbenv/versions/2.6.5/gemsets/quartzmo/gems/grpc-1.26.0-universal-darwin/src/ruby/lib/grpc/generic/client_stub.rb:47:in `new'
                                                                                                                                                                                                      /Users/quartzmo/.rbenv/versions/2.6.5/gemsets/quartzmo/gems/grpc-1.26.0-universal-darwin/src/ruby/lib/grpc/generic/client_stub.rb:47:in `initialize': grpc cannot be used before and after forking (RuntimeError)
```

**Comment by blowmage** [comment]
> I see that the other Stackdriver gems were "fixed to work in a forked environment": #2888 (comment). Although I can't tell what changes were made to work around this.

The other Stackdriver gems all have a hand-written layer that calls the generated GRPC client code. The Monitoring gem is only the generated GRPC client code, without any hand-written layer in front of it. The other Stackdriver gems all had changes made in the hand-written code to delay the creation of a GRPC client object until it is needed, which is usually post-fork.

The behavior this issue describes is consistent with creating a Monitoring client object in the parent process before the fork. If you can delay creating the Monitoring client object until after the fork then this behavior should go away.

**Comment by quartzmo** [comment]
@jeremywadsack Can you let us know some more about how you are creating your google-cloud-monitoring client(s)? See above, thanks!

**Comment by jeremywadsack** [comment]
@quartzmo Thanks for the ping. 

And thank you both for the in-depth response. This helps me better understand how the gRPC connection is being used and what the challenges are in addressing this.

This helped me dig into the issue. We do not initialize `Google::Cloud::Monitoring::V3::MetricServiceClient` (in this container) except in a Resque job.  My understanding of how Resque works is that it launches the worker process idle, picks a job from the queue, and then [forks before each job and runs the job in the fork](https://github.com/resque/resque/blob/v2.0.0/lib/resque/worker.rb#L264). It should not be running any of our code in the parent process and my tracing didn't detect any of that. So this is not an issue with our code or with Resque.

Using your test code above in our production environment (this didn't exhibit any problems in development), that this is failing because we initialize a Google Cloud PubSub connection on start-up of Rails.

```
$ bin/rails c
*** GRPC setup_channel(#<GRPC::Core::Channel:0x000055ffff837ac0>, pubsub.googleapis.com:443, {})
*** GRPC setup_channel(#<GRPC::Core::Channel:0x000055ffff837ac0>, pubsub.googleapis.com:443, {})
*** GRPC setup_channel(#<GRPC::Core::Channel:0x00005600004938f0>, pubsub.googleapis.com:443, {})
*** GRPC setup_channel(#<GRPC::Core::Channel:0x00005600004938f0>, pubsub.googleapis.com:443, {})
Loading production environment (Rails 5.2.3)
irb(main):001:0> fork { puts Google::Cloud::Monitoring::ServiceMonitoring.new.class }
=> 217
*** GRPC setup_channel(, monitoring.googleapis.com:443, {"grpc.service_config_disable_resolution"=>1})
Traceback (most recent call last):
	40: from bin/rails:6:in `<main>'
	39: from bin/rails:6:in `require'
        ...
.../vendor/bundle/ruby/2.5.0/gems/grpc-1.25.0-x86_64-linux/src/ruby/lib/grpc/generic/client_stub.rb:48:in `initialize': grpc cannot be used before and after forking (RuntimeError)
```

So while we aren't initializing the Monitoring client in the parent process we are initializing gRPC because we have a PubSub call.

I can disable or delay or move the PubSub calls in this case (these Resque workers don't need them). That's probably the best course of action for our case (and a clean up for our code).

This would have been a lot easier if the error message had given me details about when gRPC was first used. I looked into `grcp` to see about a PR but I don't trust my C to make that safe. I can open an issue there with that as a suggestion, though, if you think that's a good idea.

**Comment by blowmage** [comment]
> we initialize a Google Cloud PubSub connection on start-up of Rails

Yes, that would cause this behavior. Are you only creating the Pub/Sub client or are you also using it in the parent process? If you can delay the creation of the Pub/Sub client until it is first needed you might be able to avoid this unfortunate behavior.

**Comment by jeremywadsack** [comment]
@blowmage Yeah,  exactly. 

This code runs in a Rails initializer and makes a connection to PubSub. Unfortunately, the workers need the Rails environment and that runs the initializers in the parent process. I'd like to run the PubSub code _only_ in the server (and not other Rake or Console instances) but it turns out that's trickier than it should be.

Ideally we improve encapsulation and segregate our code better.

I have what I need to resolve this on our end. Thanks for the confirmation.

**Comment by quartzmo** [comment]
@jeremywadsack  Whew, what a pain, right? Thank you for digging in and identifying the PubSub initialization.

And please never hesitate to post these issues, even when you have already solved them yourself, since it is doubtless of great benefit to other users to have this discussion in the public record.
