### ISSUE TITLE
Feature request: Admin Auth API

### ISSUE THREAD

**Issue by josh-m-sharpe** [googleapis/google-cloud-ruby#4696]
As of this writing the admin SDK seems to support node/java/go/c#/python.

https://firebase.google.com/docs/auth/admin/manage-users

Will ruby be supported in the future?

**Comment by quartzmo** [comment]
Hi @josh-m-sharpe,

Thanks for your question. Unfortunately I have no idea. The [firebase](https://github.com/firebase) org in GitHub is the place to ask. But given that the matrix in [Add the Firebase Admin SDK to Your Server](https://firebase.google.com/docs/admin/setup) does not include a column for Ruby, I suppose I wouldn't expect it very soon. I wonder if maybe [oscardelben/firebase-ruby](https://github.com/oscardelben/firebase-ruby) supports managing users or if it could be extended to do so? Good luck!

**Comment by rttll** [comment]
Custom tokens can be created using a third-party jwt library. 
There's a ruby example in the docs:

https://firebase.google.com/docs/auth/admin/create-custom-tokens#create_custom_tokens_using_a_third-party_jwt_library

```
require "jwt"

# Get your service account's email address and private key from the JSON key file
$service_account_email = "service-account@my-project-abc123.iam.gserviceaccount.com"
$private_key = OpenSSL::PKey::RSA.new "-----BEGIN PRIVATE KEY-----\n..."

def create_custom_token(uid, is_premium_account)
  now_seconds = Time.now.to_i
  payload = {:iss => $service_account_email,
             :sub => $service_account_email,
             :aud => "https://identitytoolkit.googleapis.com/google.identity.identitytoolkit.v1.IdentityToolkit",
             :iat => now_seconds,
             :exp => now_seconds+(60*60), # Maximum expiration time is one hour
             :uid => uid,
             :claims => {:premium_account => is_premium_account}}
  JWT.encode payload, $private_key, "RS256"
end
```
