### ISSUE TITLE
Unlinked references in documentation

### ISSUE THREAD

**Issue by busunkim96** [googleapis/google-cloud-ruby#4708]
Originally filed in https://github.com/googleapis/docuploader/issues/18 by @broady.

**What I did:**

Navigate to:

(Ruby) https://googleapis.dev/ruby/google-cloud-pubsub/latest/Google/Cloud/PubSub.html

**What I saw**

(Ruby) Unlinked references to `Google::Cloud::Config`
![image](https://user-images.githubusercontent.com/24982/61830535-3b625f80-ae20-11e9-959a-36e622893408.png)

**What I expect**

Able to click through to the docs for Cloud::Config, and any other docs for a dependency or transitive dependency.

**Comment by dazuma** [comment]
The referenced class is in a different library (`google-cloud-core`). While it may be technically possible to reproduce cross-library links here, it is not really practical. Closing this as infeasible.
