### ISSUE TITLE
AUTHENTICATION guide incorrect for generated packages

### ISSUE THREAD

**Issue by quartzmo** [googleapis/google-cloud-ruby#4742]
As reported by @arslanmurtaza in #4741 for monitoring, this documentation issue appears to be true for all generated packages. The source of the guide is in synthtool and should be fixed there.

#### Steps to reproduce

  1. Not able to configure as stated in documentation: https://googleapis.dev/ruby/google-cloud-monitoring/latest/file.AUTHENTICATION.html

#### Code example
```
Google::Cloud::Monitoring.configure do |config|
  config.project_id  = project_id
  config.credentials = keyfile
end
```
#### Full backtrace

```
/initializers/google_cloud.rb:34:in `<top (required)>': undefined method `configure' for Google::Cloud::Monitoring:Module (NoMethodError)
```
I'm using the Stackdriver logging, Bigquery and error reporting too.
Those are working correctly with the following configuration
```
Google::Cloud.configure do |config|
  config.error_reporting.project_id = project_id
  config.error_reporting.keyfile = keyfile

  config.logging.project_id = project_id
  config.logging.keyfile = keyfile

  config.bigquery.project_id = project_id
  config.bigquery.keyfile  = keyfile
end
```
I tried with 
```
config.monitoring.project_id = project_id
```
too but that also gives the error like:
```
/config/initializers/google_cloud.rb:21:in `block in <top (required)>': undefined method `project_id=' for nil:NilClass (NoMethodError)
```

**Comment by ishields** [comment]
I ran into this same issue with 

```
Google::Cloud::Language.configure
=> undefined method `configure' for Google::Cloud::Language:Module
```

The docs (https://googleapis.dev/ruby/google-cloud-language/latest/file.AUTHENTICATION.html) state the gem can be configured as 
![image](https://user-images.githubusercontent.com/3834864/77440598-df8d1380-6dbe-11ea-97a9-f121815356f3.png)
but this does not work.  

I'd like to configure within ruby rather than using the default env variables.  Is there a work around for this?

**Comment by ehundt** [comment]
Also at https://github.com/googleapis/google-cloud-ruby/tree/google-cloud-logging/v2.3.2/google-cloud-logging

it suggests under Authentication:
```
Rails.application.configure do |config|
  config.google_cloud.project_id = "your-project-id"
  ...
end
```
This didn't work for me in my Rails application whereas 
```
Google::Cloud.configure do |config|
  config.project_id = 'your-project-id'
  config.keyfile = "/path/to/key.json"
end
```
worked.

**Comment by aandreassa** [comment]
Closing this issue as I believe this was fixed long ago -- for reference an implementation of `configure` [here](https://github.com/googleapis/google-cloud-ruby/blob/main/google-cloud-language/lib/google/cloud/language.rb#L111).
