### ISSUE TITLE
Can't view logs in the log viewer..

### ISSUE THREAD

**Issue by Sudarshan013** [googleapis/google-cloud-ruby#4748]
Followed the [guide](https://cloud.google.com/logging/docs/setup/ruby) (GCE)  to set up the Rails application to get the logs.
But I could only able to view  the syslogs in the Logging viewer.
And while running the following command in Rails console, 
`Rails.logger` 
The google cloud instance object is returning positively.
Followed the steps to interact with the Google Cloud Library
`
## Imports the Google Cloud client library
require "google/cloud/logging"

## Your Google Cloud Platform project ID
project_id = "test-rails"

## Instantiates a client
logging = Google::Cloud::Logging.new project: my_proid_56678

## Prepares a log entry
entry = logging.entry
## The data to log
entry.payload = "Hello, world!"
## The name of the log to write to
entry.log_name = "Dashboard log"
## The resource associated with the data
entry.resource.type = "global"

## Writes the log entry
logging.write_entries entry

puts "Logged #{entry.payload}" `

**Comment by quartzmo** [comment]
@Sudarshan013 Thanks for opening this issue. I can't see anything wrong with your usage in the lines you have provided. Did you manage to find the solution since posting this?

**Comment by Sudarshan013** [comment]
Hi @quartzmo , not yet able to figure out the issue

**Comment by Sudarshan013** [comment]
How

**Comment by quartzmo** [comment]
Just curious, is there a reason your project ID does not match in these lines?

```
project_id = "test-rails"
```
and
```
logging = Google::Cloud::Logging.new project: my_proid_56678
```

Could you provide your initialization code again but in a more complete form?

**Comment by quartzmo** [comment]
@Sudarshan013 Can you please provide more details about your environment (Gemfile.lock, etc) as well as continuous, complete example code? Thanks!

**Comment by quartzmo** [comment]
Closing for lack of response. 
@Sudarshan013 Please re-open if you can provide more details, thank you!
