### ISSUE TITLE
spanner: allow user-agent to be passed in and not a hardcoded version

### ISSUE THREAD

**Issue by odeke-em** [googleapis/google-cloud-ruby#4761]
We'd like to be able to pass in a user-agent from applications that build atop spanner-ruby (we are currently building an ORM plugin),
where ideally the final user-agent when set by us would be
```shell
x-goog-api-client': \
'spanner-activerecord/0.0.1 gl-ruby/<VERSION> grpc/<gRPC_VERSION> gax/<GAX_VERSION>' 
```

Coming here from a report by @jiren on January 19th 2020, which I shall quote verbatim:

@odeke-em In ruby spanner this is not possible as per current implementation. Ruby spanner lib has hardcoded values.

lib_name: "gccl",
lib_version: Google::Cloud::Spanner::VERSION

Here is the file link,
https://github.com/googleapis/google-cloud-ruby/blob/fe8f239bd97c2bdadb4da5a3012cc4cd738a7efa/google-cloud-spanner/lib/google/cloud/spanner/service.rb#L54-L55

I think need to create an issue on spanner ruby.

This issue is to follow up with @jiren's report. /cc @skuruppu

**Comment by quartzmo** [comment]
@odeke-em Thanks for this request. @jiren Do you want to take this?

**Comment by jiren** [comment]
> @odeke-em Thanks for this request. @jiren Do you want to take this?

Yes @quartzmo , I have created pull request against this.

**Comment by skuruppu** [comment]
Thanks to @quartzmo, #4762 is now in [google-cloud-spanner 1.14.0](https://github.com/googleapis/google-cloud-ruby/releases/tag/google-cloud-spanner%2Fv1.14.0). Closing this issue.
