### ISSUE TITLE
pubsub: expose an max_duration_per_lease_extension setting for subscribers

### ISSUE THREAD

**Issue by hongalex** [googleapis/google-cloud-ruby#4850]
For languages that support lease management, we have bound the percentile distribution to 10s - 10m. It would be useful if the upper bound were configurable.

A user might process messages very slowly (8m to ack)
If the application fails 5s after receiving a message (whose ack deadline was set to 8m, because that's the deadline the percentile distribution gave), the user has to wait 7m55s for the message to be redelivered
Users should be able to set `max_duration_per_lease_extension` = 20s, which caps an individual modAck RPC to 20s. This would have the downside of causing more modack RPCs to be sent, but the upside that the redelivery time would only be 15s
This setting differs from [`inventory_extension`](https://github.com/googleapis/google-cloud-ruby/blob/848bcf4c0acb75358ef9cdac0277730538ca0aa7/google-cloud-pubsub/lib/google/cloud/pubsub/subscriber.rb#L301), which defines the total amount of time we'll hold a message.

In addition, `max_duration_per_lease_extension` should be disabled if set to be 0 (or less), and should default to 0.

In addition, please add an alias for `inventory_extension` with the more descriptive name `max_total_lease_duration`.

For an idea of how this is implemented, please refer to the [Go implementation for MaxExtensionPeriod](https://code-review.googlesource.com/c/gocloud/+/48570), [Github PR](https://github.com/googleapis/google-cloud-go/commit/257fe64ad194f18ac7b12f237574882d2a78293f).

**Comment by quartzmo** [comment]
Similar [Python issue](https://github.com/googleapis/python-pubsub/issues/35)

**Comment by quartzmo** [comment]
Released package:

https://rubygems.org/gems/google-cloud-pubsub/versions/1.5.0

Documentation:

https://googleapis.dev/ruby/google-cloud-pubsub/v1.5.0/Google/Cloud/PubSub/Subscription.html#listen-instance_method
