### ISSUE TITLE
document 'set'  with merge: 'true' destroy field if value is nil (instead set Null type)

### ISSUE THREAD

**Issue by GuillaumeM59** [googleapis/google-cloud-ruby#4882]
Why deleting field if value is nil when merge:true ( on document.set method ) ?

REPORT:
#### Environment details

  - OS: Ubuntu 19.04
  - Ruby version: 2.6.5
  - Gem name and version:  google-cloud-firestore (1.2.4), google-protobuf (3.11.4), google-cloud-core (1.5.0)

#### Steps to reproduce

  1. create new document with field_name 'foo' and value 'bar' in a collection ( in exemple, here: 'lines' )
  #### Code example
   @fire = Google::Cloud::Firestore.new
   doc = @fire.col('lines').doc('test')
   doc.create( { foo: 'bar'})

  #### Result:
![Screenshot from 2020-02-26 17-23-06](https://user-images.githubusercontent.com/15214746/75365245-3507fa80-58bd-11ea-9ad8-d29a9009ea42.png)

  2. update test document with field_name 'foo' and value nil through 'set' method and merging allowed.
  #### Code example
   @fire = Google::Cloud::Firestore.new
   doc = @fire.col('lines').doc('test')
   doc.set( { foo: nil }, merge: true)

  #### Result:
![Screenshot from 2020-02-26 17-28-52](https://user-images.githubusercontent.com/15214746/75365457-7e584a00-58bd-11ea-9932-91d51f58ad45.png)

  #### Expected:
![Screenshot from 2020-02-26 17-29-56](https://user-images.githubusercontent.com/15214746/75365584-b069ac00-58bd-11ea-8dbf-bcbe19e7ee7a.png)

Am I bad?
Thanks !

**Comment by GuillaumeM59** [comment]
I don't know if it's not a "GCP Firestore console" bug ...

because reading the doc:

=> #<Google::Cloud::Firestore::DocumentSnapshot:0x000055d914675ac8 @grpc=<Google::Firestore::V1::Document: name: "projects/****/databases/(default)/documents/lines/test", fields: {"foo"=><Google::Firestore::V1::Value: boolean_value: false, integer_value: 0, double_value: 0.0, reference_value: "", map_value: nil, geo_point_value: nil, array_value: nil, timestamp_value: nil, null_value: :NULL_VALUE, string_value: "", bytes_value: "">}, create_time: <Google::Protobuf::Timestamp: seconds: 1582734178, nanos: 467015000>, update_time: <Google::Protobuf::Timestamp: seconds: 1582734592, nanos: 655230000>>, @ref=#<Google::Cloud::Firestore::DocumentReference:0x000055d914675c30 @client=#<Google::Cloud::Firestore::Client:0x000055d916040480 @service=Google::Cloud::Firestore::Service(***)>, @path="projects/****/databases/(default)/documents/lines/test">, @read_at=2020-02-26 17:36:30 +0100>

The 'foo' field still here ...

**Comment by quartzmo** [comment]
@GuillaumeM59 Thank you for reporting this issue, I'll try to reproduce it.

**Comment by quartzmo** [comment]
@GuillaumeM59 I could not reproduce what you saw. Could you please try repeating my steps?

```
irb(main):011:0> doc = @fire.col('lines').doc('test2')
=> #<Google::Cloud::Firestore::DocumentReference:0x00007f90d82c83a8 @client=#<Google::Cloud::Firestore::Client:0x00007f90d88c1f70 @service=Google::Cloud::Firestore::Service(buoyant-ability-182823)>, @path="projects/buoyant-ability-182823/databases/(default)/documents/lines/test2">
irb(main):012:0> doc.create( { foo: 'bar'})
=> #<Google::Cloud::Firestore::CommitResponse::WriteResult:0x00007f90da1e7b30 @update_time=2020-03-01 18:03:41 -0700>
irb(main):013:0> snap_1 = doc.get
=> #<Google::Cloud::Firestore::DocumentSnapshot:0x00007f90d9211f58 @grpc=<Google::Firestore::V1::Document: name: "projects/buoyant-ability-182823/databases/(default)/documents/lines/test2", fields: {"foo"=><Google::Firestore::V1::Value: boolean_value: false, integer_value: 0, double_value: 0.0, reference_value: "", map_value: nil, geo_point_value: nil, array_value: nil, timestamp_value: nil, null_value: :NULL_VALUE, string_value: "bar", bytes_value: "">}, create_time: <Google::Protobuf::Timestamp: seconds: 1583111021, nanos: 219151000>, update_time: <Google::Protobuf::Timestamp: seconds: 1583111021, nanos: 219151000>>, @ref=#<Google::Cloud::Firestore::DocumentReference:0x00007f90d9211fd0 @client=#<Google::Cloud::Firestore::Client:0x00007f90d88c1f70 @service=Google::Cloud::Firestore::Service(buoyant-ability-182823)>, @path="projects/buoyant-ability-182823/databases/(default)/documents/lines/test2">, @read_at=2020-03-01 18:03:57 -0700>
irb(main):014:0> doc.set( { foo: nil }, merge: true)
=> #<Google::Cloud::Firestore::CommitResponse::WriteResult:0x00007f90d8252900 @update_time=2020-03-01 18:04:26 -0700>
irb(main):015:0> snap_2 = doc.get
=> #<Google::Cloud::Firestore::DocumentSnapshot:0x00007f90da14cf40 @grpc=<Google::Firestore::V1::Document: name: "projects/buoyant-ability-182823/databases/(default)/documents/lines/test2", fields: {}, create_time: <Google::Protobuf::Timestamp: seconds: 1583111021, nanos: 219151000>, update_time: <Google::Protobuf::Timestamp: seconds: 1583111066, nanos: 207186000>>, @ref=#<Google::Cloud::Firestore::DocumentReference:0x00007f90da14c4f0 @client=#<Google::Cloud::Firestore::Client:0x00007f90d88c1f70 @service=Google::Cloud::Firestore::Service(buoyant-ability-182823)>, @path="projects/buoyant-ability-182823/databases/(default)/documents/lines/test2">, @read_at=2020-03-01 18:04:31 -0700>
```

**Comment by GuillaumeM59** [comment]
@quartzmo thanks for answer.
Here we are:

irb(main):018:0> doc = @fire.col('lines').doc('test2')
=> #<Google::Cloud::Firestore::DocumentReference:0x00005569bb176450 @client=#=> #<Google::Cloud::Firestore::DocumentReference:0x00005569bcb6c5a8 @client=#<Google::Cloud::Firestore::Client:0x00005569bccd3f90 @service=Google::Cloud::Firestore::Service(***********)>, @path="projects/**********/databases/(default)/documents/apps/tests-web/lines/test2">

result: 
![Screenshot from 2020-03-02 15-54-50](https://user-images.githubusercontent.com/15214746/75687523-3874fa80-5c9e-11ea-979d-10908246f4ce.png)


irb(main):022:0> snap_1 = doc.get
=> #<Google::Cloud::Firestore::DocumentSnapshot:0x00005569ba8fd170 @grpc=<Google::Firestore::V1::Document: name: "projects/********/databases/(default)/documents/apps/tests-web/lines/test2", fields: {"foo"=><Google::Firestore::V1::Value: boolean_value: false, integer_value: 0, double_value: 0.0, reference_value: "", map_value: nil, geo_point_value: nil, array_value: nil, timestamp_value: nil, null_value: :NULL_VALUE, string_value: "bar", bytes_value: "">}, create_time: <Google::Protobuf::Timestamp: seconds: 1583160852, nanos: 62352000>, update_time: <Google::Protobuf::Timestamp: seconds: 1583160852, nanos: 62352000>>, @ref=#<Google::Cloud::Firestore::DocumentReference:0x00005569ba8fd800 @client=#<Google::Cloud::Firestore::Client:0x00005569bccd3f90 @service=Google::Cloud::Firestore::Service(********)>, @path="projects/********/databases/(default)/documents/apps/tests-web/lines/test2">, @read_at=2020-03-02 15:58:32 +0100>

irb(main):023:0> doc.set( { foo:nil}, merge: true)
=> #<Google::Cloud::Firestore::CommitResponse::WriteResult:0x00005569bc515c90 @update_time=2020-03-02 16:01:21 +0100>
irb(main):024:0> snap_2 = doc.get
=> #<Google::Cloud::Firestore::DocumentSnapshot:0x00005569bcd522a0 @grpc=<Google::Firestore::V1::Document: name: "projects/********/databases/(default)/documents/apps/tests-web/lines/test2", fields: {}, create_time: <Google::Protobuf::Timestamp: seconds: 1583160852, nanos: 62352000>, update_time: <Google::Protobuf::Timestamp: seconds: 1583161281, nanos: 852661000>>, @ref=#<Google::Cloud::Firestore::DocumentReference:0x00005569bcd52340 @client=#<Google::Cloud::Firestore::Client:0x00005569bccd3f90 @service=Google::Cloud::Firestore::Service(********)>, @path="projects/********/databases/(default)/documents/apps/tests-web/lines/test2">, @read_at=2020-03-02 16:03:49 +0100>

result:
![Screenshot from 2020-03-02 16-05-21](https://user-images.githubusercontent.com/15214746/75688358-a53cc480-5c9f-11ea-891e-90bb38eca3db.png)

expected:
![Screenshot from 2020-03-02 16-05-54](https://user-images.githubusercontent.com/15214746/75688394-b71e6780-5c9f-11ea-9244-07e5737edd4b.png)

In my ruby console I have no troubles all is fine...
But when my fellows look at google firebase web console, attribute vanished ...
This error is not happening with the android firestore librairy.

**Comment by quartzmo** [comment]
@GuillaumeM59 Did you resolve this issue?

**Comment by quartzmo** [comment]
@GuillaumeM59 Any updates for this issue?

**Comment by quartzmo** [comment]
Closing due to lack of response. Please re-open if help is needed!
