### ISSUE TITLE
Can not use async_writer inside rake task

### ISSUE THREAD

**Issue by vascoosx** [googleapis/google-cloud-ruby#4896]
#### Environment details

  - OS: ubuntu
  - Ruby version: 2.6.3
  - Gem name and version: google-cloud-logging

#### Steps to reproduce

1. write code that logs to stackdriver in a rake task
2. run rake task
3. check log

write code to log inside any rake task

#### Code example

```ruby
logging = Google::Cloud::Logging.new project: 'my-project'
async = logging.async_writer
resource = logging.resource 'global'
entry = logging.entry severity: severity, payload: 'log'
async.write_entries(entry, log_name: 'log-test', resource: resource
```

#### Full backtrace

no backtrace available

#### Note
if instead of `async.write_entries` I use `logging.write_entries` it works. Also `async.write_entries` works when ran inside the console.

**Comment by quartzmo** [comment]
@vascoosx Thank you for opening this issue. Please try this solution:

```ruby
task :async do
  require "google/cloud/logging"
  logging = Google::Cloud::Logging.new # project id and credential from env
  async = logging.async_writer
  async.on_error do |error|
    puts error.inspect
  end
  resource = logging.resource 'global'
  entry = logging.entry payload: 'entry from rake'
  async.write_entries entry, log_name: 'log-test', resource: resource
  async.stop!
end
```

If you do not call [`stop!`](https://googleapis.dev/ruby/google-cloud-logging/latest/Google/Cloud/Logging/AsyncWriter.html#stop!-instance_method) on  the `AsyncWriter`, the rake process will exit before writing the logs and the error handler will print:

```
#<Google::Cloud::Logging::AsyncWriterError: Error writing entries: Concurrent::RejectedExecutionError>
```

Let us know if this solves your problem, thank you.

**Comment by vascoosx** [comment]
Thank you very much! That solved my problem.
