### ISSUE TITLE
spanner: add support to create session using spanner project instance.

### ISSUE THREAD

**Issue by jiren** [googleapis/google-cloud-ruby#4915]
Required api at project level object to create a session. This will help to create sessions while integrating with ORM(ActiveRecord) because ActiveRecord handles connection pool(session pool for spanner) 

Current implementation session is created and handled by `client.rb` and does not provide any direct  api to create a session 

ActiveRecord [code reference](https://github.com/rails/rails/blob/3269e4e7b04c06855464d48ed4f862a127abb5ba/activerecord/lib/active_record/connection_adapters/abstract/connection_pool.rb#L101)

Example use-case:

```ruby
spanner = Google::Cloud::Spanner.new
spanner.create_session "instance_id", "database_id", labels: ["pid_1234_rails"]
```
 
cc @skuruppu

**Comment by skuruppu** [comment]
@jiren asking a few questions since we're in the process of trying to triage all the spanner issues.

In this case, I'm a bit uncertain about exposing sessions outside of the client library because ultimately, we don't want our users to have to worry about sessions.

Why does it make it easier for ActiveRecord to have access to a session directly? if you can explain with an example, that'd be great.

**Comment by jiren** [comment]
@skuruppu User will not directly be going to use Session. ActiveRecord Spanner connector will user Session API to manage transactions. In the current `google-cloud-spanner` implementation transaction execution is implemented as a block, so ActiveRecord connector can not create a transaction and manage transaction out of code block. If we expose session creation API then the ActiveRecord connector can create, commit, and rollback transactions.

Transaction [interface](https://github.com/rails/rails/blob/12bfc8d9a6164329aa66244da82c381b56349802/activerecord/lib/active_record/connection_adapters/abstract/transaction.rb) in Rails.

`google-cloud-spanner` cloud transaction handling.
https://github.com/googleapis/google-cloud-ruby/blob/bfb4ac7296cdebe457a7bcb093b7ec4755a616e0/google-cloud-spanner/lib/google/cloud/spanner/client.rb#L1018-L1073

**Comment by skuruppu** [comment]
Ah ok thanks for the explanation. I understand that this makes sense for ActiveRecord. My worry is that by exposing a way to create sessions, users are bound to try to create sessions on their own. I suppose there's no way to just expose it to ActiveRecord.

I need to think a bit more about how to do this in a way that doesn't allow users to mistakenly try to create their own sessions.

**Comment by skuruppu** [comment]
One possibility is to move the driver layer of the ORM implementation to this repo and then that code can depend on an implementation that allows them to get a hold of a session from the pool. But make it so that it's not exposed as part of the standard client API.

@jiren, do you think this is possible?

**Comment by jiren** [comment]
I am not sure about it, because any fixes and future changes in ActiveRecord ORM abstract connection interface will create an issue, in this case, need to release a new version of Google Spanner ruby gem if moves driver layer of ORM in this repo.

In my view one possible way to extend or reopening [class Project](https://github.com/googleapis/google-cloud-ruby/blob/master/google-cloud-spanner/lib/google/cloud/spanner/project.rb) in ORM connector code with session api.

**Comment by quartzmo** [comment]
@jiren Can the ORM implementation use the [generated client's `#create_session`](https://github.com/googleapis/google-cloud-ruby/blob/master/google-cloud-spanner/lib/google/cloud/spanner/v1/spanner_client.rb#L392) directly, rather than making changes to `Project` in the veneer layer?

**Comment by jiren** [comment]
> @jiren Can the ORM implementation use the [generated client's `#create_session`](https://github.com/googleapis/google-cloud-ruby/blob/master/google-cloud-spanner/lib/google/cloud/spanner/v1/spanner_client.rb#L392) directly, rather than making changes to `Project` in the veneer layer?

Currently I reopened Project class in ORM connection layer to add create_session.
Yes, I can use underling client object to create a connection.
