### ISSUE TITLE
spanner: allow commit transaction with optional yield block

### ISSUE THREAD

**Issue by jiren** [googleapis/google-cloud-ruby#4916]
Allow commit transection in session class with optional code block.

Current code ref:

https://github.com/googleapis/google-cloud-ruby/blob/a3c20c20393fbd8d3d501a769ff655713f1ba86e/google-cloud-spanner/lib/google/cloud/spanner/session.rb#L403-L411

Expected 

```ruby
def commit transaction_id: nil
  ensure_service!
  commit = Commit.new
  yield commit if block_given?
  commit_resp = service.commit path, commit.mutations,
                             transaction_id: transaction_id
  @last_updated_at = Time.now
  Convert.timestamp_to_time commit_resp.commit_timestamp
end
```

cc @skuruppu

**Comment by skuruppu** [comment]
@jiren, can I ask what the use case for this is?

**Comment by jiren** [comment]
Currently, code block compulsory to commit a transaction.

To commit a transaction without any statement not possible. i.e
```
session.commit(transaction_id) 
```

The above use-case is only possible using a passing empty code block.
```ruby
commit(transaction_id) do |c|
end
```

**Comment by jiren** [comment]
No changes required in gem. This is going to handle by an ORM adapter.
