### ISSUE TITLE
bigquery: intermittent parse errors with list_tabledata

### ISSUE THREAD

**Issue by shollyman** [googleapis/google-cloud-ruby#5180]
This issue came in via an internal channel.  Corresponding internal issue is b/151771755 but this looks like one from the bag of hard-to-repro transient issues.  Will see about connecting the reporter to this issue directly.

From the internal report (user id info elided):
```
Issue summary: It appears that the #list_tabledata function in the official Ruby library for BigQuery does not handle exceptions properly. This appears to happen when there is a transient error on the BigQuery API side.

JSON::ParserError 434: unexpected token at '{

"v": null '

/usr/lib/ruby/gems/2.6.0/gems/json-2.3.0/lib/json/common.rb:156:in `parse'

/usr/lib/ruby/gems/2.6.0/gems/json-2.3.0/lib/json/common.rb:156:in `parse'

/usr/lib/ruby/gems/2.6.0/gems/google-cloud-bigquery-1.20.0/lib/google/cloud/bigquery/service.rb:200:in `block in list_tabledata'

/usr/lib/ruby/gems/2.6.0/gems/google-cloud-bigquery-1.20.0/lib/google/cloud/bigquery/service.rb:518:in `block in execute'

/usr/lib/ruby/gems/2.6.0/gems/google-cloud-bigquery-1.20.0/lib/google/cloud/bigquery/service.rb:553:in `block in execute'

/usr/lib/ruby/gems/2.6.0/gems/google-cloud-bigquery-1.20.0/lib/google/cloud/bigquery/service.rb:551:in `loop'

/usr/lib/ruby/gems/2.6.0/gems/google-cloud-bigquery-1.20.0/lib/google/cloud/bigquery/service.rb:551:in `execute'

/usr/lib/ruby/gems/2.6.0/gems/google-cloud-bigquery-1.20.0/lib/google/cloud/bigquery/service.rb:518:in `execute'

/usr/lib/ruby/gems/2.6.0/gems/google-cloud-bigquery-1.20.0/lib/google/cloud/bigquery/service.rb:193:in `list_tabledata'

/usr/lib/ruby/gems/2.6.0/gems/google-cloud-bigquery-1.20.0/lib/google/cloud/bigquery/data.rb:413:in `next'

/usr/lib/ruby/gems/2.6.0/gems/google-cloud-bigquery-1.20.0/lib/google/cloud/bigquery/data.rb:486:in `block in all'

Sample code:

Note that they don't call #list_tabledata directly. Instead they call

table.data.all do |row|

[do something with row]

end

and that calls #list_tabledata for them.

Which version of this CLI / Library / API is called: latest version google-cloud-bigquery 1.20.0

Where is this called from (More detail, the better):

Temporary table is created and then table.data.all is called on it.

Link where this API / library is documented:

https://www.rubydoc.info/gems/google-cloud-bigquery/Google/Cloud/Bigquery/Table#data-instance_method

and

https://www.rubydoc.info/gems/google-cloud-bigquery/Google/Cloud/Bigquery/Data#all-instance_method

Link where this API / library is obtained:

https://rubygems.org/gems/google-cloud-bigquery

https://github.com/googleapis/google-cloud-ruby/blob/master/google-cloud-bigquery/lib/google/cloud/bigquery/service.rb

Reproduction steps:

Hard to reproduce unless you have a very active account hitting BigQuery hard.
```

**Comment by quartzmo** [comment]
@shollyman Thank you for passing this along. Do you have any idea why and what kind of data the RPC is returning that contains the apparently invalid JSON shown in the backtrace?

```
'{

"v": null '
```

**Comment by shollyman** [comment]
I suspect this was a partial fragment  It looks like part of the key/value portion of the tabledata.list/getQueryResults row data format (the f,v stuff), where we've got a null value in a field.  

Any chance we have a reasonably clean way to log the full response from the backend when we encounter this kind of parse error?  May help the reporter get more info, I suspect reproducing this one without more info is challenging.

**Comment by quartzmo** [comment]
I think the best way would be to catch the `JSON::ParserError` and raise a `Google::Cloud::Error` with the response data in the error message. How does that sound?

**Comment by shollyman** [comment]
That seems reasonable, but I worry about the size of a message (e.g. we could expect up to a 10MB response).

**Comment by quartzmo** [comment]
Wow, good point. With that in mind, the implementation looks very simple for such a large response. Is there any chance the value of `json_text` is only a fragment of the entire JSON response [when `parse` is called on line 200](https://github.com/googleapis/google-cloud-ruby/blob/master/google-cloud-bigquery/lib/google/cloud/bigquery/service.rb#L194-L200)?

There is currently no special facility for logging in this library. But I am perfectly fine with adding a call to print the response data to `$stderr` in the catch block.

**Comment by quartzmo** [comment]
It might be possible to correlate debug logging output from the underlying Apiary client ([instructions here](https://github.com/googleapis/google-cloud-ruby/blob/master/google-cloud-bigquery/LOGGING.md)) with the error in the veneer client, but it's probably a pain given how much debug output there might be.

**Comment by shollyman** [comment]
From the wire perspective, it's possible there's some kind of chunking/buffering of the message in transit but I'd expect the ruby http client to wait for the end of response before passing this off.

If there's a good verbosity level concept in the library, we perhaps that gets used to determine whether to dump the full response?  Generally that's a property of the logging facility not the exception mechanism so it feels a bit wonky.

**Comment by quartzmo** [comment]
> From the wire perspective, it's possible there's some kind of chunking/buffering of the message in transit but I'd expect the ruby http client to wait for the end of response before passing this off.

So would I. Anything else I would consider a bug. @dazuma Ever seen anything like this with the Apiary client?

> Generally that's a property of the logging facility not the exception mechanism so it feels a bit wonky.

Agreed. But I'm open to a short-term, one-off change that helps debug this.

> If there's a good verbosity level concept in the library

There's no logging at all in the google-cloud-bigquery veneer (hand-written layer). My experience with the Apiary client is that its logging levels are kind of all or nothing.

**Comment by seamusabshere** [comment]
This is still happening, here's a new example:

```
JSON::ParserError 434: unexpected token at '{
          "v": "{\"type\":\"Point\",\"coordinates\":[-8644748.47893912'
/var/lib/gems/2.6.0/gems/json-2.3.0/lib/json/common.rb:156:in `parse'
/var/lib/gems/2.6.0/gems/json-2.3.0/lib/json/common.rb:156:in `parse'
/var/lib/gems/2.6.0/gems/google-cloud-bigquery-1.20.0/lib/google/cloud/bigquery/service.rb:200:in `block in list_tabledata'
/var/lib/gems/2.6.0/gems/google-cloud-bigquery-1.20.0/lib/google/cloud/bigquery/service.rb:518:in `block in execute'
/var/lib/gems/2.6.0/gems/google-cloud-bigquery-1.20.0/lib/google/cloud/bigquery/service.rb:553:in `block in execute'
/var/lib/gems/2.6.0/gems/google-cloud-bigquery-1.20.0/lib/google/cloud/bigquery/service.rb:551:in `loop'
/var/lib/gems/2.6.0/gems/google-cloud-bigquery-1.20.0/lib/google/cloud/bigquery/service.rb:551:in `execute'
/var/lib/gems/2.6.0/gems/google-cloud-bigquery-1.20.0/lib/google/cloud/bigquery/service.rb:518:in `execute'
/var/lib/gems/2.6.0/gems/google-cloud-bigquery-1.20.0/lib/google/cloud/bigquery/service.rb:193:in `list_tabledata'
/var/lib/gems/2.6.0/gems/google-cloud-bigquery-1.20.0/lib/google/cloud/bigquery/data.rb:413:in `next'
/var/lib/gems/2.6.0/gems/google-cloud-bigquery-1.20.0/lib/google/cloud/bigquery/data.rb:486:in `block in all'
```

@quartzmo I was hoping the bigquery client would rescue and retry this...

**Comment by quartzmo** [comment]
@seamusabshere @shollyman I'll start work on a PR to update [`Service#retry_error_reason?`](https://github.com/googleapis/google-cloud-ruby/blob/master/google-cloud-bigquery/lib/google/cloud/bigquery/service.rb#L574-L584) in order that this local `JSON::ParserError` results in a retry. I will also add opt-in logging of the error in the retry mechanism.

**Comment by dazuma** [comment]
My thoughts here (sorry I missed this issue)

* I'm not 100% sure the underlying http client is configured to handle chunked transfer encoding. However, if this were a case of chunked transfer not being processed, we would have seen the chunk headers (i.e. chunk lengths) in the content, which we apparently aren't. It looks like we're actually getting truncated json from the server.
* @quartzmo and I discussed offline and agreed that it makes sense to retry in this case, so he will be doing that, as well as providing a mechanism to log retry-able errors.

**Comment by quartzmo** [comment]
From #5552 

> @quartzmo this problem has disappeared. i unfortunately don't have an example of where it retried, but it was deployed with logging disabled for a couple weeks.

> i will update this thread if i see a retry in the logs.

Closing for now. Please re-open if this error is seen again. Thanks!

**Comment by seamusabshere** [comment]
A different error but one that I believe is related to the code changes has been posted to https://github.com/googleapis/google-cloud-ruby/pull/5552#issuecomment-624714024

**Comment by seamusabshere** [comment]
https://github.com/googleapis/google-cloud-ruby/issues/5919
