### ISSUE TITLE
broken links in AUTHENTICATION guides on googleapis.dev

### ISSUE THREAD

**Issue by TheRoyalTnetennba** [googleapis/google-cloud-ruby#5185]
Synthtool generates an authentication guide for each library, [AUTHENTICATION.md](https://github.com/googleapis/synthtool/blob/master/synthtool/gcp/templates/ruby_library/AUTHENTICATION.md). These authentication guides reference a TROUBLESHOOTING.md that is not generated by synthtool. There are a lot of libraries that don't have a TROUBLESHOOTING.md, which is causing broken links on both the repo's markdown, and on googleapis.dev.

Examples: 
1) [google-cloud-monitoring's authentication guide](https://googleapis.dev/ruby/google-cloud-monitoring/latest/file.AUTHENTICATION.html), which at the very bottom references a troubleshooting doc which 404s
1) The [authentication guide for google-cloud-datastore](https://googleapis.dev/ruby/google-cloud-datastore/latest/file.AUTHENTICATION.html) has a 200 link for troubleshooting.

**Comment by dazuma** [comment]
We should just remove the troubleshooting link from the template for now.

**Comment by quartzmo** [comment]
I re-ran the kokoro job for #5215 and still get the same error:

```
http://localhost:5249/file.AUTHENTICATION.html
  [404] http://localhost:5249/file.TROUBLESHOOTING.html
...
ERROR: Detected 1 broken links. Scanned 141 links in 2.134 seconds.
doc contains the following broken links:
  [404] http://localhost:5249/file.TROUBLESHOOTING.html
    [404] http://localhost:5249/file.TROUBLESHOOTING.html

google-cloud-bigquery-data_transfer tests took 16 seconds


[ID: 4502577] Build finished after 261 secs, exit value: 1


Warning: Permanently added 'localhost' (ECDSA) to the list of known hosts.
[12:33:26] Collecting build artifacts from build VM
Build script failed with exit code: 1
```

Do we need to close it and similar PRs for regen?

**Comment by dazuma** [comment]
Oh, we need to rerun synth on the affected libraries for this to take effect and remove the broken links.

**Comment by dazuma** [comment]
Reran synth. These should be fixed now. (There are other issues, but will open separate issues for them.)
