### ISSUE TITLE
parentheses not closed for link

### ISSUE THREAD

**Issue by TheRoyalTnetennba** [googleapis/google-cloud-ruby#5188]
https://github.com/googleapis/google-cloud-ruby/blob/cdc3c9d70bc47b1762533bc8970d9e68ba7dc727/google-cloud-secret_manager-v1/proto_docs/google/protobuf/timestamp.rb#L93

**Comment by dazuma** [comment]
Wow. This is happening because the api-common-protos image includes protos from an old (pre-3.7) version of protobuf before this was fixed upstream.

**Comment by dazuma** [comment]
I just pushed a new microgenerator image with the updated core protos, so the next microgenerator synth runs should generate fixed docs.
