### ISSUE TITLE
Vision-Client: Error not being thrown

### ISSUE THREAD

**Issue by james-prodigy** [googleapis/google-cloud-ruby#5650]
A rather esoteric one, 
I've been implementing the vision client on a ruby app. As always, everything is working fine on my local but deployment seems to be a bit of a pain.

When trying to connect to the vision client deployed on the sever, I am getting a 502 error response with no error information. 

Unfortunately I don't have access to a console on the server. and can only see logs that have been tagged.

Using the ol log on each line of code to find where the issue is, It appears I am coming into an error when connecting to the vision-api. 
I am 99% sure its not an authentication issue as I am using the same credentials to successfully connect to gcs and upload a pdf for ocr. 

In order to see what the issue was, I wrote the following block:
```ruby
  def create_vision_client
    Google::Cloud::Vision::ImageAnnotator.new
  rescue Exception => err
    Rails.logger.info("vision client cannot connect #{err}")
    raise err
  end
```
Expecting any error to be caught by that rescue block, however, nothing is showing up in the logs when I get the 502 error. 

#### Code example

```ruby
    Rails.logger.info('BEGIN VISION CLIENT')
    image_annotator = create_vision_client
    Rails.logger.info('Client created, calling...')
```

#### Full backtrace

```sh
> BEGIN VISION CLIENT
> 502 error
```

Raising this as  an error is occurring when trying to instantiate a vision client without being raised as an exception and Im pretty sure its not an auth error.

**Comment by quartzmo** [comment]
It looks like the error is not an `Exception`. Do you want to try rescuing `StandardError` instead. ([Some background](https://thoughtbot.com/blog/rescue-standarderror-not-exception) on the difference.) As long as your logs are secure, I would also log `err.inspect` in case the body has anything useful.

I don't know why you're getting the `502` in that environment. Anything you can safely tell us about the environment might be helpful.

**Comment by dazuma** [comment]
One thing that comes to mind is that the Cloud Storage client uses REST (HTTP/1.1) as its transport layer, whereas the Vision client uses gRPC (HTTP/2) as its transport. So if your server environment has some interesting restrictions that interfere with HTTP/2, that might explain the error. (Although why it is being reported in that fashion rather than as an exception, is puzzling to me.)

**Comment by quartzmo** [comment]
@james-prodigy Do you have any updates regarding this issue?

**Comment by james-prodigy** [comment]
Still facing the issue and fighting hard to get console access to the bug.

From devops on my side:
There’s nothing that would stop an outbound HTTP/2 connection as the NAT gateway is HTTP/2 native. I’m 99% sure that a response from a client (Google in this case) would reply back to the NAT GW’s IP using the same protocol.

Will update when I have more information.

**Comment by james-prodigy** [comment]
Couldn't manage to get console access to the server.
Any tips on how I can patch this lib to show more logs?

**Comment by quartzmo** [comment]
Did you try configuring a `DEBUG` level logger as [described here in google-cloud-vision/README.md](https://github.com/googleapis/google-cloud-ruby/blob/master/google-cloud-vision/README.md#enabling-logging)?

**Comment by james-prodigy** [comment]
I have it set to WARN as in the readme. lets see what `DEBUG` produces.

**Comment by quartzmo** [comment]
> lets see what DEBUG produces.

You should now see every network request.

**Comment by james-prodigy** [comment]
Doesn't seem to be helping, those debug logs are only showing up after the client is established so not seeing any connection logs.

I've managed to extract some logs about the error:


```
5759 /app/vendor/bundle/ruby/2.5.0/gems/google-cloud-vision-0.38.0/lib/google/cloud/vision/v1/geometry_pb.rb
5762 /app/vendor/bundle/ruby/2.5.0/gems/google-cloud-vision-0.38.0/lib/google/cloud/vision/v1/product_search_pb.rb
5769 /app/vendor/bundle/ruby/2.5.0/gems/google-cloud-vision-0.38.0/lib/google/cloud/vision/v1/credentials.rb
5770 /app/vendor/bundle/ruby/2.5.0/gems/google-cloud-vision-0.38.0/lib/google/cloud/vision/version.rb
5774 /app/vendor/bundle/ruby/2.5.0/gems/google-cloud-vision-0.38.0/lib/google/cloud/vision/v1.rb
5764 /app/vendor/bundle/ruby/2.5.0/gems/google-cloud-vision-0.38.0/lib/google/cloud/vision/v1/web_detection_pb.rb 
5495 /app/vendor/bundle/ruby/2.5.0/gems/google-cloud-vision-0.38.0/lib/google/cloud/vision.rb 
5772 /app/vendor/bundle/ruby/2.5.0/gems/google-cloud-vision-0.38.0/lib/google/cloud/vision/v1/helpers.rb
5761 /app/vendor/bundle/ruby/2.5.0/gems/google-cloud-vision-0.38.0/lib/google/cloud/vision/v1/product_search_service_pb.rb 
5763 /app/vendor/bundle/ruby/2.5.0/gems/google-cloud-vision-0.38.0/lib/google/cloud/vision/v1/text_annotation_pb.rb 
5768 /app/vendor/bundle/ruby/2.5.0/gems/google-cloud-vision-0.38.0/lib/google/cloud/vision/v1/image_annotator_pb.rb 
5771 /app/vendor/bundle/ruby/2.5.0/gems/google-cloud-vision-0.38.0/lib/google/cloud/vision/v1/image_annotator_client.rb 
5773 /app/vendor/bundle/ruby/2.5.0/gems/google-cloud-vision-0.38.0/lib/google/cloud/vision/v1/product_search_client.rb
5775 /app/vendor/bundle/ruby/2.5.0/gems/google-cloud-vision-0.38.0/lib/google/cloud/vision/v1/image_annotator_services_pb.rb

/app/vendor/bundle/ruby/2.5.0/gems/google-cloud-vision-0.38.0/lib/google/cloud/vision.rb:169:in `new'
/app/vendor/bundle/ruby/2.5.0/gems/google-cloud-vision-0.38.0/lib/google/cloud/vision/v1.rb:166:in `new'
/app/vendor/bundle/ruby/2.5.0/gems/google-cloud-vision-0.38.0/lib/google/cloud/vision/v1/image_annotator_client.rb:124:in `initialize'
/app/vendor/bundle/ruby/2.5.0/gems/google-cloud-vision-0.38.0/lib/google/cloud/vision/v1.rb:166:in `new'
/app/vendor/bundle/ruby/2.5.0/gems/google-cloud-vision-0.38.0/lib/google/cloud/vision/v1/image_annotator_client.rb:124:in `new'

c:0075 p:0169 s:0579 e:000578 METHOD /app/vendor/bundle/ruby/2.5.0/gems/google-cloud-vision-0.38.0/lib/google/cloud/vision.rb:169
c:0076 p:0077 s:0595 e:000594 METHOD /app/vendor/bundle/ruby/2.5.0/gems/google-cloud-vision-0.38.0/lib/google/cloud/vision/v1.rb:166
c:0078 p:0116 s:0626 e:000625 METHOD /app/vendor/bundle/ruby/2.5.0/gems/google-cloud-vision-0.38.0/lib/google/cloud/vision/v1/image_annotator_client.rb:124 [FINISH]
```
Hopefully this means something to you.

**Comment by quartzmo** [comment]
So it appears to be stopping here? [/image_annotator_client.rb#L124](https://github.com/googleapis/google-cloud-ruby/blob/google-cloud-vision/v0.38.0/google-cloud-vision/lib/google/cloud/vision/v1/image_annotator_client.rb#L124)

**Comment by dazuma** [comment]
Just seems to confirm that the issue happens on gRPC connect. That's the first point in the code when a gRPC connection is made.

Another option that might get us more info is to activate logging for the low-level C layer of gRPC (which is controlled differently than the Ruby logging layer). You can do this by setting the following environment variables:
* `GRPC_VERBOSITY=INFO` (or maybe even `GRPC_VERBOSITY=DEBUG`)
* `GRPC_TRACE=api,call_error,http` (You can experiment with various settings; see [this link](https://github.com/grpc/grpc/blob/master/doc/environment_variables.md) for more info.)

See https://github.com/grpc/grpc/blob/master/TROUBLESHOOTING.md and https://github.com/grpc/grpc/blob/master/doc/environment_variables.md for more info on these debugging options.

**Comment by james-prodigy** [comment]
Been trying a few things to see more logs.
None of your suggestions seemed to produce anything on the server logs. 

Am taking the option of just implementing the calls the the api.

Thanks for the help, sorry I couldn't find anything in my logs to help debug the issue.
