### ISSUE TITLE
Segmentation fault on Ruby 2.7.0 and GAE Flex

### ISSUE THREAD

**Issue by isabanin** [googleapis/google-cloud-ruby#5721]
#### Environment details

  - OS: App Engine Ruby Flexible Environment.
  - Ruby version: 2.7.0
  - Gem name and version: stackdriver 0.16.1

#### Steps to reproduce

  1. Try to use Cloud Debugger, the app segfaults right away.

#### Full backtrace

https://gist.github.com/isabanin/8062b6d5f640d3da40e083dd4597dc5d

**Comment by dazuma** [comment]
The `google-protobuf` gem (which Debugger, and indeed most of the other client libraries depends on) doesn't yet have a build for Ruby 2.7. Until that gets resolved, we're a bit stuck. You can follow https://github.com/protocolbuffers/protobuf/issues/7070.

**Comment by isabanin** [comment]
Got it, thanks for the reply. We'll downgrade to 2.6 for now.

**Comment by dazuma** [comment]
Sorry we forgot to update this issue. This should have been resolved some months ago with google-protobuf 3.12 or later, and google-cloud-debugger 0.36.3 or later.
