### ISSUE TITLE
Default cache_control for Active Storage images

### ISSUE THREAD

**Issue by muhammedtufekyapan** [googleapis/google-cloud-ruby#5929]
Hi everyone,

I want to set cache_control: public, max-age=31536000 but I can't find solution for ActiveStorage objects. (I can set cache_control when I upload files with my custom method but couldn't find solution for ActiveStorage images)

Is there a way to do that?

Thanks a lot.

**Comment by quartzmo** [comment]
Hi @muhammedtufekyapan,

Are you asking about how to do this for the library in this repo, [google-cloud-storage](https://github.com/googleapis/google-cloud-ruby/tree/master/google-cloud-storage), or for [Ruby on Rails Active Storage](https://github.com/rails/rails/tree/master/activestorage)?

If you are asking about Ruby on Rails Active Storage, please open the issue there if possible. I can still try to help, but the issue should be in the correct repo. Thanks!

**Comment by muhammedtufekyapan** [comment]
Hi @quartzmo 

I was asking how to set cache-control header for Active Storage objects so I guess you're right. I should open the issue in there.

Thanks for reply ;)

**Comment by quartzmo** [comment]
@muhammedtufekyapan I'd still like to try to help. After you create the new issue, please link to it from here (or link to this one from new one, a reverse link will be generated.)
