### ISSUE TITLE
Text to speech returning an error

### ISSUE THREAD

**Issue by darkogj** [googleapis/google-cloud-ruby#5972]
Using Ruby 2.7 on Ubuntu 18.04

I've tried the code from the readme:

`require "google/cloud/text_to_speech"

text_to_speech_client = Google::Cloud::TextToSpeech.new`

but I get:

`generate_speech_from_text.rb:12:in <main>: undefined method "new" for Google::Cloud::TextToSpeech:Module (NoMethodError)`

I was using this exact code a few months ago and all went smoothly. Seems there is a breaking change not mentioned in the readme.

UPDATE:
Found that the readme contains an outdated sample, you guys prob need to update it to reflect this: https://github.com/googleapis/google-cloud-ruby/blob/master/google-cloud-text_to_speech/samples/quickstart.rb

**Comment by quartzmo** [comment]
@darkogj Thank you for letting us know about this outdated example. We will update it. Much appreciated!
