### ISSUE TITLE
Remove EXPERIMENTAL label from RetryPolicy docs

### ISSUE THREAD

**Issue by quartzmo** [googleapis/google-cloud-ruby#6303]
The label was removed from the lower-level client in #6299.

**Comment by quartzmo** [comment]
This should wait until GA for this feature.

**Comment by meredithslota** [comment]
Added the "Blocked" label until GA. :)

**Comment by meredithslota** [comment]
@hongalex Is this still blocked?

**Comment by meredithslota** [comment]
(I think it's not.)

**Comment by hongalex** [comment]
Yeah, Retry Policy is now GA so these should be removed now.

**Comment by quartzmo** [comment]
Great, I'll remove the labels, thanks!
