### ISSUE TITLE
Helper method to confirm an object name meets guidelines

### ISSUE THREAD

**Issue by jpaulgs** [googleapis/google-cloud-ruby#6406]
The Google Cloud Documentation provide [Object naming guidelines](https://cloud.google.com/storage/docs/naming-objects)

It would be super nice if these guidelines were formalised into a helper method.  Perhaps something like:

```
Google::Cloud::Storage::File.valid_object_name?()
```

**Comment by jpaulgs** [comment]
> My first concern about a feature like this is that the solution might fall out of sync with the rules in the service.

That is definitely a risk, I'd argue that external integrations to GCS will find it just as hard to update their validations and I suspect most clients will keep their gems up-to-date so I would expect changes to roll through over time.

This sort of feature is a nice to have.  That said forcing implementation of this sort of validation onto your external integrators is really not differentiating work.

**Comment by quartzmo** [comment]
@crwilcox Any opinion on this feature?

**Comment by crwilcox** [comment]
@quartzmo, @frankyn and I had a chat and are reaching out to some other folks about how to approach this.

**Comment by frankyn** [comment]
Hi @quartzmo  and @jpaulgs,

I'm following up with the Cloud Storage API team to get more input. Pending a response, thank you for your patience.

internal_bug: 159327733

**Comment by quartzmo** [comment]
@frankyn Any follow up on this? Should we close this issue at this point?

**Comment by frankyn** [comment]
Didn't hear back, but will ping the request again. I think it will be largely up to us. I'll raise it in a weekly meeting tomorrow and will get back to you.

**Comment by frankyn** [comment]
Hi folks,

Apologies for the wait. We decided not to move forward with this request.

Rationale:

1. We don't want to mimic server side validation client side.
2. Validation requirements can change in the future and this helper would become brittle.

Thank you for the request and your patience.
