### ISSUE TITLE
Service account authentication requires serviceusage.services.use access, even if only Storage is used

### ISSUE THREAD

**Issue by viditganpi** [googleapis/google-cloud-ruby#6456]
#### Environment details

  - OS:
  - Ruby version: 2.5.3
  - Gem name and version: 1.26.1

#### Steps to reproduce

  1. Initialize a client like:-
`Google::Cloud::Storage.new(project_id: project_id, credentials: credentials, scope: scope, retries: retries, timeout: timeout_seconds)`
2. Try to upload a file to a bucket like
` bucket = @storage.bucket bucket_name, user_project: true, skip_lookup: true
      gcs_file_name = <file-name-on-bucket>
      file = bucket.create_file local_path, gcs_file_name`

#### Full backtrace

```sh
Starting Upload of <local-file> as <gcs_file_name> to bucket <bucket-name>
Sending upload start command to https://storage.googleapis.com/upload/storage/v1/b/<bucket-name>/o?name=<gcs_file_name>&userProject=<project_id>
Upload status final
Error - #<Google::Apis::ClientError: forbidden: <service-account-name>@<project-id>.iam.gserviceaccount.com does not have serviceusage.services.use access to the Google Cloud project. status_code: 403 header: #<HTTP::Message::Headers:0x00007f8a3dab2038 @http_version="1.1", @body_size=0, @chunked=false, @request_method="POST", @request_uri=#<Addressable::URI:0x3fc523c38598 URI:https://storage.googleapis.com/upload/storage/v1/b/<bucket-name>/o?name=<gcs_file_name>&userProject=<project-id>, @request_query=nil, @request_absolute_uri=nil, @status_code=403, @reason_phrase="Forbidden", @body_type=nil, @body_charset=nil, @body_date=nil, @body_encoding=#<Encoding:UTF-8>, @is_request=false, @header_item=[["X-GUploader-UploadID", "AAANsUmwQmisIquoz97MdhFQuWA5BMVaHOD68JCQreH2bGoJ7V2-FQopFlD9_f7BGkqDcEpnYpIoPiyRzEZIxNq0k205mB8Akw"], ["X-Goog-Upload-Status", "final"], ["Content-Type", "application/json; charset=UTF-8"], ["Date", "Thu, 04 Jun 2020 11:54:59 GMT"], ["Vary", "Origin"], ["Vary", "X-Origin"], ["Cache-Control", "no-cache, no-store, max-age=0, must-revalidate"], ["Expires", "Mon, 01 Jan 1990 00:00:00 GMT"], ["Pragma", "no-cache"], ["Content-Length", "428"], ["Server", "UploadServer"],  @dumped=false> body: "{\n  \"error\": {\n    \"code\": 403,\n    \"message\": \"<service-account-name>@<project-id>.iam.gserviceaccount.com does not have serviceusage.services.use access to the Google Cloud project.\",\n    \"errors\": [\n      {\n        \"message\": \"<service-account-name>@<project-id>.iam.gserviceaccount.com does not have serviceusage.services.use access to the Google Cloud project.\",\n        \"domain\": \"global\",\n        \"reason\": \"forbidden\"\n      }\n    ]\n  }\n}\n">
```
The service account has `Storage Object Admin` access

**Comment by quartzmo** [comment]
@viditganpi I believe this is happening because you are setting `user_project: true` when retrieving the bucket. Per the [docs](https://googleapis.dev/ruby/google-cloud-storage/v1.26.1/Google/Cloud/Storage/Project.html#bucket-instance_method) for the `user_project` parameter:

> If this parameter is set to true, transit costs for operations on the requested bucket or a file it contains will be billed to the current project for this client... This parameter is required with requester pays-enabled buckets.

The guide [Cloud IAM permissions for the Google Cloud Console](https://cloud.google.com/storage/docs/access-control/iam-console) states:

> All actions that include a billing project in the request require serviceusage.services.use permission for the project that's specified.

Do you need to set `user_project: true` for a requester pays-enabled bucket?
> This permission ensures you are authorized to bill the project you specify. Including a billing project is used, for example, when accessing a bucket with Requester Pays enabled.

**Comment by quartzmo** [comment]
Closing for lack of response from original poster.
