### ISSUE TITLE
Migrate google-cloud-spanner to the microgenerator

### ISSUE THREAD

**Issue by dazuma** [googleapis/google-cloud-ruby#6490]
Migrate google-cloud-spanner to the microgenerator. This involves the following steps:

* [x] Update the upstream protos to use the Ruby namespaces `Google::Cloud::Spanner::DatabaseAdmin::V1` and `Google::Cloud::Spanner::InstanceAdmin::V1` for the admin services.
* [x] Update synth for the current `google-cloud-spanner` to alias the new admin service namespaces to the old namespace for compatibility, and release a spanner update. Do this before migrating, to ensure that the legacy code base remains viable.
* [x] Write synth file and generate `google-cloud-spanner-v1`
* [x] Write synth file and generate `google-cloud-spanner-database_admin-v1`
* [x] Write synth file and generate `google-cloud-spanner-instance_admin-v1`
* [x] Make sure the new libraries are configured in kokoro
* [x] Release `google-cloud-spanner-v1`
* [x] Release `google-cloud-spanner-database_admin-v1`
* [x] Release `google-cloud-spanner-instance_admin-v1`
* [ ] Switch `google-cloud-spanner` backend to the versioned gems. That is:
    * Rip out synth and all the generated code
    * Add the three versioned gems as dependencies
    * Update the veneer code to the microgenerator usage
* [ ] Release `google-cloud-spanner` update

I do not believe samples need to be updated, unless they invoke the low-level interface directly.

**Comment by hengfengli** [comment]
Hi @jiren, I just want to follow up with this task. Is there any update?

**Comment by jiren** [comment]
> Hi @jiren, I just want to follow up with this task. Is there any update?

@hengfengli Work in progress. In 1 or 2 day will be completed.
