### ISSUE TITLE
Support for Cloud Build

### ISSUE THREAD

**Issue by spearl** [googleapis/google-cloud-ruby#6492]
I am currently submitting builds for processing to Cloud Build from a ruby backend. To accomplish this I am shelling out to the gcloud CLI and submitting the builds that way.

The Cloud Build V1 api is supported in the google-api-ruby-client and I am migrating to using this for my needs. However, this is a low level client in maintenance mode that does not support automatic credential discovery when run inside of GCP infrastructure.

It would be great to have a top level `Google::Cloud::Build` object to interact with Cloud Build programmatically!

**Comment by quartzmo** [comment]
@spearl Thanks for this request! We'll try to find out if a Cloud Build client is something we can offer.

**Comment by dazuma** [comment]
It looks like Java/Go/Node/Python already have cloud build clients, so the external API definitions should be stable. We'll need to make sure the Ruby namespaces are configured properly, but otherwise we should be able to generate a client for Cloud Build.

**Comment by dazuma** [comment]
https://rubygems.org/gems/google-cloud-build

**Comment by spearl** [comment]
Thanks @dazuma !
