### ISSUE TITLE
BigQuery query example is deceptively simple

### ISSUE THREAD

**Issue by coffenbacher** [googleapis/google-cloud-ruby#6499]
The example at https://github.com/googleapis/google-cloud-ruby/tree/master/google-cloud-bigquery makes it look like you can loop over the results of a query very easily.

Unfortunately, the example only loops over an arbitrary page of results, which means anyone expecting this to loop over all results has a serious bug. I can't think of why anyone would ever want to only loop the first page in practice.

What do you think about changing it to `data.all.each`? Other options would be including a comment mentioning this only processes one page , or including the necessary paging code to loop over the entire result set.

```
# Run a query
data = dataset.query "SELECT first_name FROM my_table"

data.each do |row|
  puts row[:first_name]
end
```

**Comment by quartzmo** [comment]
I'm leaning toward demonstrating page iteration with `#next?` and `#next` as the best practice. (I don't think `#all` is a good idea for large result sets.)

**Comment by coffenbacher** [comment]
Sounds good to me :+1:
