### ISSUE TITLE
[Vision samples] Concurrent tests runs conflict (import product images)

### ISSUE THREAD

**Issue by dazuma** [googleapis/google-cloud-ruby#6634]
Concurrent tests runs of `product_search_import_product_images_test` appear to be conflicting.

**Comment by TheRoyalTnetennba** [comment]
Example: https://source.cloud.google.com/results/invocations/215ed2af-7a61-47a8-9820-7985c747767d/targets/cloud-devrel%2Fclient-libraries%2Fgoogle-cloud-ruby%2Fsamples_presubmit%2Flinux%2Fruby_2.6.6/log
