### ISSUE TITLE
[Storage samples] Tests failing due to several types of quota errors

### ISSUE THREAD

**Issue by dazuma** [googleapis/google-cloud-ruby#6715]
We're seeing at least two types of quota errors during CI runs:

1. Buckets created/deleted too quickly. Example:
    ```
    Buckets Snippets::create_bucket#test_0001_creates a storage bucket:
    Google::Cloud::ResourceExhaustedError: rateLimitExceeded: The project exceeded the rate limit for creating and deleting buckets.
    /tmpfs/src/github/google-cloud-ruby/google-cloud-storage/lib/google/cloud/storage/service.rb:633:in `rescue in execute'
    /tmpfs/src/github/google-cloud-ruby/google-cloud-storage/lib/google/cloud/storage/service.rb:630:in `execute'
    /tmpfs/src/github/google-cloud-ruby/google-cloud-storage/lib/google/cloud/storage/service.rb:97:in `insert_bucket'
    /tmpfs/src/github/google-cloud-ruby/google-cloud-storage/lib/google/cloud/storage/project.rb:379:in `create_bucket'
    /tmpfs/src/github/google-cloud-ruby/google-cloud-storage/samples/buckets.rb:182:in `create_bucket'
    /tmpfs/src/github/google-cloud-ruby/google-cloud-storage/samples/acceptance/buckets_test.rb:167:in `block (5 levels) in <top (required)>'
    ```

    This also causes secondary test failures because the following warning can be printed, and interferes with tests that check output text.
    ```
    rateLimitExceeded: The project exceeded the rate limit for creating and deleting buckets. Gonna try again
    ```

2. Service account HMAC key limit reached. Example:
    ```
    HMAC Snippets::delete_hmac_key#test_0001_deletes an hmac key from an access_id:
    Google::Cloud::PermissionDeniedError: quotaExceeded: Service account HMAC key limit reached
    /tmpfs/src/github/google-cloud-ruby/google-cloud-storage/lib/google/cloud/storage/service.rb:633:in `rescue in execute'
    /tmpfs/src/github/google-cloud-ruby/google-cloud-storage/lib/google/cloud/storage/service.rb:630:in `execute'
    /tmpfs/src/github/google-cloud-ruby/google-cloud-storage/lib/google/cloud/storage/service.rb:458:in `create_hmac_key'
    /tmpfs/src/github/google-cloud-ruby/google-cloud-storage/lib/google/cloud/storage/project.rb:403:in `create_hmac_key'
    /tmpfs/src/github/google-cloud-ruby/google-cloud-storage/samples/acceptance/hmac_test.rb:26:in `block (2 levels) in <top (required)>'
    ```

    Not sure if this is a rate limiting issue or a hard limit on the cumulative number of keys that have been created.

**Comment by quartzmo** [comment]
I've been working on the HMAC key tests, but the situation is difficult because of the hard limit on keys (I believe it's 5 keys max). What do you think about using mocks for the HMAC keys tests?

**Comment by dazuma** [comment]
If there's a hard limit, then I'm okay with mocking.

**Comment by quartzmo** [comment]
@dazuma @TheRoyalTnetennba The HMAC keys tests in this issue are a kind of extreme example of the resource constraints we are running up against as we bring the samples acceptance tests into google-cloud-ruby. One solution (which I am currently working on here) is to change problematic acceptance tests to mocked unit tests. But it occurred to me that another possible solution would be to [serially test the entire sequence of CRUD operations](https://github.com/googleapis/google-cloud-ruby/blob/master/google-cloud-storage/acceptance/storage/project_test.rb#L26-L87) using just one or maybe two resources in a single test. This is an old tactic for efficient acceptance testing that is common in this project. With four concurrent test runs we might still run into trouble with HMAC keys (it's tight, 5 is the limit), but it might reduce quota issues with many other resources. Do you see any problem with this approach? How does it fit with our preference for "test file per sample file"?

**Comment by quartzmo** [comment]
This sequential testing within a single test is basically the same as specs running in a predefined order. So, adopting it would unblock me in converting a couple of problematic samples test suites from ordered rspec to unordered minitest.

**Comment by TheRoyalTnetennba** [comment]
I think I'd favor mocking, unless the time period for 5 HMAC keys limit is really short. If it's a guaranteed failure at 5+ simultaneous VMs between PRs and continuous tests I imagine failure should happen pretty frequently.

That or a robust, willing-to-take-its-time retry setup.

**Comment by quartzmo** [comment]
I'll go ahead with mocking the HMAC tests, thanks!
