### ISSUE TITLE
Storage: support customTime metadata and custom timestamp based OLM

### ISSUE THREAD

**Issue by jkwlui** [googleapis/google-cloud-ruby#6918]
Request to support a new customTime metadata and associated custom timestamp based OLM conditions:

```ruby
bucket.lifecycle do |l|
  l.add_delete_rule days_since_custom_time: 30
  l.add_delete_rule custom_time_before: Datetime.now + 10
end

# New metadata field:
file.update do |f|
  f.custom_time = "2020-01-01T00:00:00Z"
end
```

**Comment by quartzmo** [comment]
What about `matches_pattern`?

**Comment by quartzmo** [comment]
See my previous question about these missing fields in #6718.

**Comment by jkwlui** [comment]
Hi @quartzmo, only `days_since_custom_time` and `custom_time_before` is relevant for this feature. I'm not sure what feature `matches_pattern` is associated with, but I'll find out and report back. Thanks!

**Comment by quartzmo** [comment]
I added support for these fields to existing PR #6649.
