### ISSUE TITLE
spanner: add support for custom timeout and retry options - Google::Gax::CallOptions

### ISSUE THREAD

**Issue by hengfengli** [googleapis/google-cloud-ruby#7011]
Currently, the client lib does not allow users to provide custom timeout and retry options that overrides the gapic default settings. 

`Google::Gax::CallOptions` is supported by the methods in spanner_client: 

https://github.com/googleapis/google-cloud-ruby/blob/1b0545aef072289a5d88a42054f9bed582423067/google-cloud-spanner/lib/google/cloud/spanner/v1/spanner_client.rb#L829

However, the methods in `service.rb` do not accept `Google::Gax::CallOptions`: 

https://github.com/googleapis/google-cloud-ruby/blob/1b0545aef072289a5d88a42054f9bed582423067/google-cloud-spanner/lib/google/cloud/spanner/service.rb#L304-L307

We can implement the following two features to allow overrides: 

- Method-level: update the methods in `service.rb` to support CallOptions. 
- Client-level: accept a hash/map (mapping a method name to a CallOptions) when initializing the service and update `default_options_from_session` to merge the custom CallOptions of a method. 

The precedence of order: 

gapic defaults < client-level < method-level

@jiren Do you have any thoughts on this? Thanks.

**Comment by dazuma** [comment]
Note: the new generated code drops `Google::Gax::CallOptions` entirely, and provides a different mechanism for customizing timeout and retry. I would recommend holding off on this work until the spanner client has been migrated to the new generated code. (#6490)

**Comment by hengfengli** [comment]
Got it. No problem. 👍
