### ISSUE TITLE
Missing documentation for google translate library v3

### ISSUE THREAD

**Issue by inspire22** [googleapis/google-cloud-ruby#7066]
The prior documentation (v2) is here: 
https://googleapis.github.io/google-cloud-dotnet/docs/Google.Cloud.Translation.V2/

The latest documentation is in two places, neither of which is finished
https://googleapis.dev/ruby/google-cloud-translate-v3/latest/index.html
https://googleapis.dev/ruby/google-cloud-translate/latest/index.html

There's no "getting started" or "sample code" sections

One page does have a short section, but it contains a reference to an undefined method & no way to create the actual request.
https://googleapis.dev/ruby/google-cloud-translate-v3/latest/index.html

The link to the API details just leads to the same page.

**Comment by fhinkel** [comment]
👋 @inspire22 Thanks for opening an issue. We're working on a larger effort to consolidate our documentation. 

The quickstart and more samples can be found [here](https://cloud.google.com/translate/docs/advanced/translating-text-v3#translating_text) .
