### ISSUE TITLE
GCP Pubsub Streamer stops processing messages

### ISSUE THREAD

**Issue by ce07c3** [googleapis/google-cloud-ruby#7068]
#### Environment details

  - OS: Debian Heroku Flavor (Cedar Stack)
  - Ruby version: 2.6.6
  - Gem name and version: `google-cloud-pubsub`, `1.9.0`

#### Steps to reproduce

  1. Run the subscriber under heavy load
  2. Eventually, the status of the streams will look like this:

```
inventory   status  thread_status
200         paused   sleep
200         paused   sleep
200         paused   sleep
200         paused   sleep
200         paused   sleep

inventory   status   thread_status
335         paused   sleep
335         paused   sleep
336         paused   sleep

inventory   status   thread_status
334         paused   sleep
334         paused   sleep
334         paused   sleep

inventory   status   thread_status
334         paused   sleep
338         paused   sleep
5           running  sleep
```

#### Code

We're wondering if there can be a "deadlock".

The only part of the code where it would pause is in `background_run`.

```ruby
# def background_run
# ...
          synchronize { pause_streaming! }
```

Which checks if the inventory is full. Perhaps we satisfy the condition for being full.

```rb
          def pause_streaming!
            return unless pause_streaming?

            @paused = true
          end

          def pause_streaming?
            return if @stopped
            return if @paused

            @inventory.full?
          end
```

Once the `background_run` loop is retried, it goes into a waiting state.

```rb
            loop do
              synchronize do
                if @paused && !@stopped
                  @pause_cond.wait
                  next
                end
              end
```

This waiting state, in this scenario, probably (we don't see how the other signals could be triggered) can only be resolved by the inventory calling `renew_lease!`, which then unpauses streaming.

```rb
          def background_run
            delay_target = nil

            until stopped?
              if empty?
                delay_target = nil

                synchronize { @wait_cond.wait } # wait until broadcast
                next
              end

              delay_target ||= calc_target
              delay_gap = delay_target - Time.now

              unless delay_gap.positive?
                delay_target = calc_target
                stream.renew_lease!
                next
              end

              synchronize { @wait_cond.wait delay_gap }
            end
          end
```

and

```rb
          def unpause_streaming!
            return unless unpause_streaming?

            @paused = nil
            # signal to the background thread that we are unpaused
            @pause_cond.broadcast
          end
```

Question: can it happen that the delay gap is always positive in some scenarios?

**Comment by quartzmo** [comment]
> can it happen that the delay gap is always positive in some scenarios?

Just from looking at the code, I can't see a bug if there is one. Are you able to test changes?

**Comment by ce07c3** [comment]
We're able to deploy changes, but it's hard for us to reproduce. We had to purge our backlog eventually. Then issues stopped. 🤷 I wish I knew how to debug this.

**Comment by quartzmo** [comment]
Possibly helpful: https://github.com/GoogleCloudPlatform/pubsub/tree/master/load-test-framework

**Comment by quartzmo** [comment]
Closing, as three months have passed without new reports of the problem.
