### ISSUE TITLE
spanner: verify why google-cloud-resource-prefix header may not be set

### ISSUE THREAD

**Issue by skuruppu** [googleapis/google-cloud-ruby#7084]
The google-cloud-resource-prefix header is expected to be set for the RPCs sent by the data client and optionally for RPCs sent by the two admin clients of Cloud Spanner.

Some header analysis showed that it's not set for any methods in Ruby. So filing this issue to debug.

**Comment by hengfengli** [comment]
Confirmed from the backend traffic. This has been fixed by the latest version (2.0.0) of client library. It always has the correct header.
