### ISSUE TITLE
google-cloud-trace (0.40.0) have invalid scope?

### ISSUE THREAD

**Issue by le0pard** [googleapis/google-cloud-ruby#7248]
#### Environment details

  - OS: linux
  - Ruby version: 2.6.6
  - Gem name and version: google-cloud-trace (0.40.0)

#### Steps to reproduce

  1. Add to rails project google-cloud-trace (0.40.0) gem
  2. After rails load you get message:

```
Note: Google::Cloud::Trace is disabled because it failed to authorize with the service. (Authorization failed.  Server message:
{"error":"invalid_scope","error_description":"Invalid OAuth scope or ID token audience provided."})
```

#### How to fix:

Back to google-cloud-trace (0.39.0) fix the issue.

Thanks!

**Comment by alexebird** [comment]
While trying to use Cloud Trace for the first time and following the setup instructions, I came across this. Tried with version `0.41.3`.

Downgrading to `0.39.0` seems to have fixed it.
