### ISSUE TITLE
"8:received initial metadata size exceeds limit." error in KMS

### ISSUE THREAD

**Issue by apa512** [googleapis/google-cloud-ruby#7449]
#### Environment details

  - OS: Ubuntu 18.04.1 LTS
  - Ruby version: 2.7.1
  - Gem name and version: google-cloud-kms 2.0.0

#### Steps to reproduce

Try to decrypt a string that was encrypted using google-cloud-kms 1.0.0.

#### Code example

```ruby
client = Google::Cloud::Kms.key_management_service do |config|
  config.credentials = "config/xxx.json"
end

client.decrypt(name: "my-crypto-key", ciphertext: "string-that-was-encrypted-using-a-previous-version-of-google-kms").plaintext.chomp
```

#### Full backtrace

```sh
gems/google-cloud-kms-v1-0.2.2/lib/google/cloud/kms/v1/key_management_service/client.rb:1722:in `rescue in decrypt': 8:received initial metadata size exceeds limit. debug_error_string:{"created":"@1596542308.004444653","description":"Error received from peer ipv4:172.217.218.95:443","file":"src/core/lib/surface/call.cc","file_line":1055,"grpc_message":"received initial metadata size exceeds limit","grpc_status":8} (Google::Cloud::ResourceExhaustedError)
    from gems/google-cloud-kms-v1-0.2.2/lib/google/cloud/kms/v1/key_management_service/client.rb:1688:in `decrypt'
    from lib/kms.rb:6:in `decrypt'
```

Note that this only happens intermittently even if `decrypt` is given the same input. So far I haven't had it happened on my local development machine, but it happens frequently on the server.

**Comment by dazuma** [comment]
We've gotten a few similar reports that seem to be related to an underlying issue in the grpc library. One workaround that seems to be working for some people is, reuse client objects if you can. If you create too many new client objects, each one will trigger a new grpc connection, and the issue seems to manifest after some large number of new grpc connections have been created.

**Comment by dazuma** [comment]
This looks like the same issue as #7447. I'm going to close it as a duplicate if that's okay.

**Comment by dazuma** [comment]
A fix has been released. Please upgrade to grpc 1.31.1 or later.
