### ISSUE TITLE
Create GCE instances using Ruby

### ISSUE THREAD

**Issue by sekhar-searce** [googleapis/google-cloud-ruby#7598]
We want to automate the GCE instance creation using Ruby, but I am not able to find any Ruby libraries to do so. Is it possible from Ruby or am I missing something.

**Comment by dazuma** [comment]
The [google-api-client](https://rubygems.org/gems/google-api-client) gem includes a client for the GCE API. We don't currently have a modernized client, though. (In a pinch, you can also install the [gcloud command line](https://cloud.google.com/sdk) and shell out to it.)

**Comment by fhinkel** [comment]
Greetings, we're closing this. Looks like the issue got resolved. Please let us know if the issue needs to be reopened.
