### ISSUE TITLE
Releasetool fails to update release PRs

### ISSUE THREAD

**Issue by dazuma** [googleapis/google-cloud-ruby#7612]
Currently the release process does not update release PRs (i.e. does not add comments indicating release progress or update the labels). See #7611. This is because the magic proxy is failing. Apparently Ben Coe has a solution involving a GitHub app that we should migrate to.

**Comment by chingor13** [comment]
Fix from Java: https://github.com/googleapis/synthtool/commit/019c7168faa0e56619f792693a8acdb30d6de19b: loads the app credentials from secret manager (assuming you have the [script to populate secrets in trampoline available](https://github.com/googleapis/synthtool/blob/master/synthtool/gcp/templates/java_library/.kokoro/populate-secrets.sh)).

**Comment by dazuma** [comment]
Thanks @chingor13 ! Yeah I'm piloting this in googleapis/ruby-cloud-env at the moment (based on Ben's version of the populate_secrets script), and will update google-cloud-ruby once I've ironed out the details.

**Comment by dazuma** [comment]
This work has been completed.
