### ISSUE TITLE
execution expired while uploading a single file

### ISSUE THREAD

**Issue by snirbenyosef** [googleapis/google-cloud-ruby#7626]
i׳m tryring to use the api in order to upload a 500MB file.
but i get an error after 15 min:
```sh
Got error: Google::Cloud::Error with message: execution expired while uploading a single file: myfile.csv
```

when i׳m trying to upload 50mb file it works. but more then that it just fail.

where is the problem? in my api? in google cloud settings of my bucket ?

#### Environment details

  - OS:mac os catlina
  - Ruby version: ruby 2.6.3p62 (2019-04-16 revision 67580) [x86_64-darwin19]
  - Gem name and version: cnvrg-1.10.8

#### Steps to reproduce

  1. cnvrg data put mydata "myfile"

#### Code example

```ruby
 @storage = Google::Cloud::Storage.new(project_id: @project_id, credentials: @credentials, retries: 20, timeout: 999)
```

#### Full backtrace

```sh
Got error: Google::Cloud::Error with message: execution expired while uploading a single file: myfile.csv
```

**Comment by quartzmo** [comment]
Hi @snirbenyosef,

Can you please provide more information about your environment, including the version of the `google-cloud-storage` gem, and also a **full** backtrace of the error? Also, can you show what happens when you do **not** set `retries` or `timeout`? Thank you!

**Comment by quartzmo** [comment]
And full code example including the file creation, thanks!

**Comment by snirbenyosef** [comment]
i have set a higher timeout. and its solved.
but where in google its configured to stop after 15 min? what is default if i'm not using timeout ?

**Comment by quartzmo** [comment]
> where in google its configured to stop after 15 min?

I'm not where there is a default configuration for 15 min.

> what is default if i'm not using timeout ?

I believe the default timeout is `120` seconds, [defined here in nahi/httpclient/lib/httpclient/session.rb](https://github.com/nahi/httpclient/blob/master/lib/httpclient/session.rb#L147).
