### ISSUE TITLE
Google::Cloud::InternalError: 13:Received RST_STREAM with error code 2

### ISSUE THREAD

**Issue by kaprakash90** [googleapis/google-cloud-ruby#7675]
#### Environment details

  - OS: Mac OS Catalina v10.15.6
  - Ruby version: ruby 2.6.5p114
  - Gem name and version: google-cloud-language

#### Steps to reproduce

  1. We have the google-cloud-language API call in the model after_create_commit and the model is being loaded by sidekiq on 10 threads max. The API works fine for a day or two the I start receive this "Google::Cloud::InternalError: 13:Received RST_STREAM with error code 2" and after 1 hour I'm receiving the "
Google::Cloud::DeadlineExceededError: 4:Deadline Exceeded.". Restarting the sidekiq and rails app resolves the issue for another day or two. But these two errors keeps popping out. 

#### Code example
Exact code given in the google documents
```ruby
  def google_nlp_request(txt)
    language = Google::Cloud::Language.language_service

    document = { content: txt, type: :PLAIN_TEXT }
    response = language.analyze_entities document: document
    response.entities
  end
```

#### Full backtrace

```sh
Google::Cloud::DeadlineExceededError: 4:Deadline Exceeded. debug_error_string:{"created":"@1600225880.930641284","description":"Deadline Exceeded","file":"src/core/ext/filters/deadline/deadline_filter.cc","file_line":69,"grpc_status":4}
[PROJECT_ROOT]/app/services/google_nlp.rb:49 :in `google_nlp_request`
47 
48     document = { content: news_txt, type: :PLAIN_TEXT }
49     response = language.analyze_entities document: document
50     response.entities
51   end

Google::Cloud::InternalError: 13:Received RST_STREAM with error code 2. debug_error_string:{"created":"@1600192878.676138009","description":"Error received from peer ipv4:172.217.167.170:443","file":"src/core/lib/surface/call.cc","file_line":1055,"grpc_message":"Received RST_STREAM with error code 2","grpc_status":13}
[PROJECT_ROOT]/app/services/google_nlp.rb:49 :in `google_nlp_request`
47 
48     document = { content: news_txt, type: :PLAIN_TEXT }
49     response = language.analyze_entities document: document
50     response.entities
51   end
```

Thanks!

**Comment by stefanondisponibile** [comment]
we've experienced the same, but are unlikely hitting quota limits.
