### ISSUE TITLE
BigQuery: audit use of dense response encoding

### ISSUE THREAD

**Issue by shollyman** [googleapis/google-cloud-ruby#7806]
# Request
Review this library to ensure dense encoding (e.g. `prettyPrint=false`) is specified when possible when communicating with the BigQuery API methods.

# Additional Context
Pretty printed JSON responses from server can have significant response size inflation for complex objects.  BigQuery data APIs tend to exacerbate this.  Library can improve performance by using dense encoding, particular for underlying methods like jobs.getQueryResults and tabledata.list that may supply large, complex JSON responses.

Info about `prettyPrint` system API parameter:
https://cloud.google.com/apis/docs/system-parameters

# Internal (for Googlers)
See issue 168725137

**Comment by quartzmo** [comment]
Thanks @shollyman!

**Comment by quartzmo** [comment]
@shollyman has checked the Ruby user-agent requests from the backend and verified that this query param is not being set.

**Comment by quartzmo** [comment]
@shollyman This value can't be sent as a header can it? There is nothing listed in the HTTP/gRPC Header column in the [System Parameters table](https://cloud.google.com/apis/docs/system-parameters), but I just wanted to double-check.

**Comment by shollyman** [comment]
I am unaware of other mechanisms beyond url query params to alter this behavior.
