### ISSUE TITLE
BigQuery: Support Time Unit Partitioning

### ISSUE THREAD

**Issue by d-torres** [googleapis/google-cloud-ruby#7848]
BigQuery has introduced additional types of time unit partitioning for partitioned tables.  Supported values are "HOUR", "DAY", "MONTH", and "YEAR".  May we extend support for the new values in the library?  

Reference implementations:
Go - https://github.com/googleapis/google-cloud-go/pull/2858
Java - https://github.com/googleapis/java-bigquery/pull/737

**Comment by shollyman** [comment]
Language in [REST reference](https://cloud.google.com/bigquery/docs/reference/rest/v2/tables#TimePartitioning):

The supported types are DAY, HOUR, MONTH, and YEAR, which will generate one partition per day, hour, month, and year, respectively.
