### ISSUE TITLE
Cloud Debugger Does Not Work with Ruby application on GCE or GAE

### ISSUE THREAD

**Issue by Louis-Ye** [googleapis/google-cloud-ruby#7850]
#### Environment details

  - OS: Debian Linux on GCE Instance
  - Ruby version: 2.7.1
  - Gem name and version: stackdriver

#### Steps to reproduce

For GAE:
Follow the steps to [set up the quickstart application](https://cloud.google.com/appengine/docs/flexible/ruby/quickstart) in GCE with [enabling Cloud Debugger GAE Flex](https://cloud.google.com/debugger/docs/setup/ruby#gae-flex).

For GCE:
Follow the steps to set up the same application but running on a GCE instance with [instructions to enable Cloud Debugger](https://cloud.google.com/debugger/docs/setup/ruby#gce).

#### Expected Result

For both GAE and GCE, the debugged application is available in the GCP Debugger console
For GAE, the application's source code is available to view in the Debugger console.

#### Actual Result

Two issues
1) For application on GAE and GCE, the application is not available for debugging in the debugger Console..
2) For application on GAE, the source code of the application is not available.

**Comment by dazuma** [comment]
Debugger is being turned down (see https://cloud.google.com/debugger/docs). Closing out related issues.
