### ISSUE TITLE
Feature Request: add support for querying field where "!=" nil 

### ISSUE THREAD

**Issue by dcts** [googleapis/google-cloud-ruby#8088]
The javascript firestore SDK supports `.where(fieldname, "!=", null)` ([since version 7.21.0](https://firebase.google.com/support/release-notes/js#version_7210_-_september_17_2020)), which is great and a really usefull query. For the ruby sdk I did notice this method is not supported yet. [See docs](https://googleapis.dev/ruby/google-cloud-firestore/latest/Google/Cloud/Firestore/Query.html#where-instance_method).

 **Describe the solution you'd like**
- add support for `db.col.where(fieldname, "!=", nil)`

 **Describe alternatives you've considered**
- using the javascript SDK and deploying an API solely for this specific query (time-consuming)
- fetching all documents and filtering them on my server with ruby (costly)

**Comment by quartzmo** [comment]
@dcts Thank you for opening this issue. I will add the following operators:

* `!=` - a query operator to find documents where a field’s value is set and does not equal the specified value.
* `NOT_IN` - a query operator to find documents where a field’s value is `!=` any of the values in the specified array.

**Comment by quartzmo** [comment]
Existing implementations:

* [Java PR](https://github.com/googleapis/java-firestore/pull/350)
* [Node PR](https://github.com/googleapis/nodejs-firestore/pull/1292)

**Comment by quartzmo** [comment]
This feature was released in [google-cloud-firestore v2.4.0](https://rubygems.org/gems/google-cloud-firestore/versions/2.4.0).
