### ISSUE TITLE
Ignore bundler-related directories properly

### ISSUE THREAD

**Issue by aeroastro** [googleapis/google-cloud-ruby#8132]
**Is your feature request related to a problem? Please describe.**

I'm beginning to contribute to this repository, and I've found out that `.gitignore` is not properly defined regarding `bundler`.

This annoys gem development since it is regarded as an untracked files by git.

Following are the result of `git status` after I ran `(cd google-cloud-spanner && bundle install --path=vendor/bundle)`

```
$ git status
On branch feature/gitignore-for-bundler
Untracked files:
  (use "git add <file>..." to include in what will be committed)
	google-cloud-spanner/.bundle/
	google-cloud-spanner/vendor/

nothing added to commit but untracked files present (use "git add" to track)
```

In my opinion, this is pretty common development style and `.gitignore` repository also has the definitions for this.
https://github.com/github/gitignore/blob/218a941be92679ce67d0484547e3e142b2f5f6f0/Ruby.gitignore#L41-L44

 **Describe the solution you'd like**

Following code will fix this, and I am just before sending the Pull Request.

https://github.com/googleapis/google-cloud-ruby/compare/master...aeroastro:feature/gitignore-for-bundler?expand=1

 **Describe alternatives you've considered**

Not to use `--path=vendor/bundle` option. (but I would like to use it to separate environments)

 **Additional context**

no

**Comment by quartzmo** [comment]
@aeroastro Thank you for this issue! The proposed PR looks good to me, please open it, thank you!

**Comment by aeroastro** [comment]
Thank you for reviewing this ⭐ 
I've just opened the Pull Request.
