### ISSUE TITLE
storage: add support for PublicAccessPrevention

### ISSUE THREAD

**Issue by shaffeeullah** [googleapis/google-cloud-ruby#8135]
We need to add support for a new field `publicAccessPrevention` in the bucket IAM configuration for storage. Full details are available in [this doc](https://docs.google.com/document/d/1o_ElQg4c8enEx8OYa3irrUYFKADmHFbRn7dC9g287sI/). This should include ability to create buckets with this field set, get the field, and set the field. We'd also like an integration test that verifies that the feature works as expected.

Please wait for approval from myself or @tritone before merging or releasing this change so we can coordinate around release dates.

Based on looking at the code, I _think_ the field should go here:
https://github.com/googleapis/google-cloud-ruby/blob/77a53b96027a391177a22e8cf3f3a7d722f85494/google-cloud-storage/test/helper.rb#L198

**Comment by quartzmo** [comment]
The `publicAccessPrevention` field is now in the discovery document [here](https://github.com/googleapis/discovery-artifact-manager/blob/master/discoveries/storage.v1.json#L214-L217).

**Comment by quartzmo** [comment]
@shaffeeullah I've requested access to the design document referenced above.

**Comment by tritone** [comment]
Shared it with the email address I have for you @quartzmo , let me know if you run into issues.
