### ISSUE TITLE
[synth] Some types of synth failures cause a PR that deletes all code

### ISSUE THREAD

**Issue by dazuma** [googleapis/google-cloud-ruby#8150]
Examples: #8148 and #8149. These were synth failures (due to a missing proto file). However, the synth job did not signal failure. Instead, it just failed to generate anything, which in turn caused autosynth to delete all tracked files. We need to make sure this kind of synth failure actually fails the job rather than opening a bogus PR.

**Comment by danoscarmike** [comment]
@dazuma should we open this on [synthtool](https://github.com/googleapis/synthtool)?

**Comment by dazuma** [comment]
@danoscarmike No not at this time. It was unclear whether the issue was in synthtool, the synth scripts in this repo, or the Ruby microgenerator. I'll downgrade this to P3 since we haven't seen it in a while, and it may go away anyway with our bazel changes or with owlbot.

**Comment by danoscarmike** [comment]
SGTM

**Comment by dazuma** [comment]
I haven't seen this in a while, and we're rapidly moving off synthtool so I'm going to close this.
