### ISSUE TITLE
storage: add samples for PublicAccessPrevention

### ISSUE THREAD

**Issue by quartzmo** [googleapis/google-cloud-ruby#8159]
Add samples with the following region tags for the `PublicAccessPrevention` feature (#8135). A PR adding these samples should wait for/be based on the change to file-per-sample in #7823. These samples should not be included in #8154 unless it has been rebased on master after the merge of #7823.

- [ ] `storage_get_public_access_prevention`
- [ ] `storage_enforce_public_access_prevention`
- [ ] `storage_unspecify_public_access_prevention`

Existing implementation: See the samples in googleapis/nodejs-storage#1310.

/cc @shaffeeullah

**Comment by shaffeeullah** [comment]
Note the samples have been renamed to be: 
- [ ]   `storage_get_public_access_prevention`
- [ ]   `storage_set_public_access_prevention_enforced`
- [ ]   `storage_set_public_access_prevention_unspecified`

This change is already reflected in the linked nodejs PR
