### ISSUE TITLE
implement support for Hive partitioning options in BigQuery

### ISSUE THREAD

**Issue by shollyman** [googleapis/google-cloud-ruby#8164]
This feature request is to track client implementation of `HivePartitioningOptions` in BigQuery APi, which augments load and external query capabilities by allowing use of the GCS object path to infer additional partitioning columns.

Additional documentation has already been shared out of band with maintainers.

Internal tracking issue: 142409248

**Comment by quartzmo** [comment]
As part of this issue, the `ORC` source format needs to be added to the existing support for [external data sources](https://cloud.google.com/bigquery/external-data-sources). (It is already supported for Load Jobs.)
