### ISSUE TITLE
Does this support Google Cloud Run?

### ISSUE THREAD

**Issue by ukazap** [googleapis/google-cloud-ruby#8236]
I couldn't see any mention of Cloud Run in the docs, the closest thing I found is the Kubernetes API, however, I want to use a higher level API.

**Comment by dazuma** [comment]
This repo doesn't have a client for the Cloud Run API yet. It is likely that one will come at some point, but we don't have a timeline yet.

Some alternatives for now:
* There is a Cloud Run client class in the REST client, [google-api-client](https://rubygems.org/gems/google-api-client). Use the `Google::Apis::RunV1::CloudRunService` class.
* Shell out to the [gcloud command line](https://cloud.google.com/sdk)

(Of course, any of the client libraries will run just fine in an app deployed to Cloud Run.)

**Comment by ukazap** [comment]
Thanks for pointing me to google-api-client, I can work with that for now.
