### ISSUE TITLE
`bundle exec rake ci` fails under `google-cloud-spanner`

### ISSUE THREAD

**Issue by aeroastro** [googleapis/google-cloud-ruby#8417]
#### Environment details

  - OS: Mac OS X
  - Ruby version: 2.6.2
  - Gem name and version: `google-cloud-spanner`

#### Steps to reproduce

Run the following command.

```bash
cd google-cloud-spanner
bundle exec rake ci
```

#### Code example

This is the same as above.

#### Full backtrace

```sh

#####################################
### BUILDING google-cloud-spanner ###
#####################################


************************************
*** google-cloud-spanner rubocop ***
************************************

Running RuboCop...
vendor/bundle/ruby/2.6.0/gems/simplecov-html-0.12.3/.rubocop.yml: Layout/LineLength has the wrong namespace - should be Metrics
Error: RuboCop found unsupported Ruby version 2.1 in `TargetRubyVersion` parameter (in vendor/bundle/ruby/2.6.0/gems/rainbow-3.0.0/.rubocop.yml). 2.1-compatible analysis was dropped after version 0.58.
Supported versions: 2.3, 2.4, 2.5, 2.6, 2.7
RuboCop failed!
```

This seems to be due to an incorrect setting in the `.rubocop.yml`.
I am going to send a patch to fix this afterwards.

**Comment by aeroastro** [comment]
I think we can fix this issue by ignoring files under `vendor` directories just like `.gitignore` as follows.

https://github.com/googleapis/google-cloud-ruby/compare/master...aeroastro:feature/fix-rubocop-issue-on-spanner?expand=1

We have discussed the background for this directories at #8132

**Comment by jiren** [comment]
@aeroastro If you have patch with `vendor` folder ignore for rubocop is ready than please create a pull request.

**Comment by aeroastro** [comment]
Sorry for the late reply.
Actually I had the same patch at the previous comment 1 month ago.
https://github.com/googleapis/google-cloud-ruby/issues/8417#issuecomment-748982396
https://github.com/googleapis/google-cloud-ruby/compare/master...aeroastro:feature/fix-rubocop-issue-on-spanner?expand=1

I'm wondering if it is O.K. to create a Pull Request after creating an issue, in order to make the development more smoothly, next time.
Probably we have the same opinion toward this kind of trivial issues.

**Comment by jiren** [comment]
> Sorry for the late reply.
> Actually I had the same patch at the previous comment 1 month ago.
> [#8417 (comment)](https://github.com/googleapis/google-cloud-ruby/issues/8417#issuecomment-748982396)
> https://github.com/googleapis/google-cloud-ruby/compare/master...aeroastro:feature/fix-rubocop-issue-on-spanner?expand=1
> 
> I'm wondering if it is O.K. to create a Pull Request after creating an issue, in order to make the development more smoothly, next time.
> Probably we have the same opinion toward this kind of trivial issues.

Yes, you can create a pull request after creating issue.
