### ISSUE TITLE
Authentincation link in readmes is rendering as a text

### ISSUE THREAD

**Issue by mslinn** [googleapis/google-cloud-ruby#8578]
The [README.md for google-cloud-translate](https://github.com/googleapis/google-cloud-ruby/blob/master/google-cloud-translate/README.md) has a placeholder instead of useful information:

{file:AUTHENTICATION.md Set up authentication.}

Consequently, I still do not know how to set up authentication.

**Comment by quartzmo** [comment]
That link markup is not resolved in the GitHub rendering of the README, but it is resolved in the same README presented in the [API documentation](https://googleapis.dev/ruby/google-cloud-translate/latest/index.html). In either case, `AUTHENTICATION.md` can be found in the same location as the README. In GitHub, it's here: https://github.com/googleapis/google-cloud-ruby/blob/master/google-cloud-translate/AUTHENTICATION.md

**Comment by mslinn** [comment]
Perhaps the file should have a note to this effect, so others will know where to look? As a newcomer to this project, my first attempt to work with this project resulted in hitting this issue. For me the result was I could not make any progress.

**Comment by quartzmo** [comment]
As far as I know there is no elegant solution to this problem, but I made an attempt to present both links on the same line in a way that is hopefully not too confusing. What do you think?

### Source code

```
1. Set up authentication. See {file:AUTHENTICATION.md AUTHENTICATION.md} (API docs) or [AUTHENTICATION.md](AUTHENTICATION.md) (GitHub).
```

### Output

#### API docs (YARD)

Note: Second link to `AUTHENTICATION.md (GitHub)` is rendered, but is broken.

<img width="736" alt="Screen Shot 2021-01-11 at 2 18 57 PM" src="https://user-images.githubusercontent.com/205445/104239867-6f688080-5418-11eb-8d2e-5df571808684.png">

#### GitHub

<img width="957" alt="Screen Shot 2021-01-11 at 2 18 49 PM" src="https://user-images.githubusercontent.com/205445/104239826-5e1f7400-5418-11eb-8656-b687aa09148c.png">

**Comment by dazuma** [comment]
Another possible solution is to introduce a build process. Use GitHub-style links in the source file as is, but in the release script we run a transform on `.md` files that looks for GitHub links and rerenders them as YARD links in place before building the gem.

**Comment by quartzmo** [comment]
@dazuma Sorry, I forgot to comment after reading this earlier: I really like your suggestion.

**Comment by dazuma** [comment]
Assigning to @trambui09 .

Let's implement this first in translate-v2 (a handwritten library) and then we can move on to update it in the generator.
