### ISSUE TITLE
PubSub Lite Support? Existing? Intended?

### ISSUE THREAD

**Issue by GLStephen** [googleapis/google-cloud-ruby#8930]
Is PubSub lite supported in the current library? Is supported planned?

**Comment by quartzmo** [comment]
@GLStephen Thanks for this question. Did you see the [Simple REST client for Pub/Sub Lite](https://github.com/googleapis/google-api-ruby-client/blob/master/generated/google-apis-pubsublite_v1/OVERVIEW.md) in the [googleapis/google-api-ruby-client](https://github.com/googleapis/google-api-ruby-client) repo?

**Comment by quartzmo** [comment]
If you're specifically asking about Pub/Sub Lite support in a gRPC client in this repo, I can try to find out if/when that might happen.

**Comment by GLStephen** [comment]
@quartzmo thanks for the heads up on that REST repo, that might be a good stopgap. I would love some info on the GRPC support here. We're publishing lots of messages out of Fluentd and GRPC usually performs much better.

**Comment by quartzmo** [comment]
OK, great. I'll try to get you an answer on Thursday 2021/01/21.

**Comment by GLStephen** [comment]
@quartzmo thanks, appreciate that. It looks like the REST API only handles managing pubsub-list, but doesn't have the ability to publish messages to a TOPIC. Unless I'm missing something.

**Comment by quartzmo** [comment]
I'll take a look at the simple Ruby REST client.

Just for reference, here's a generated Python client: https://github.com/googleapis/google-cloud-python

**Comment by GLStephen** [comment]
@quartzmo that's good to see, but need Ruby to publish to pubsub via fluentd. Thanks for the help!

**Comment by quartzmo** [comment]
@GLStephen It appears that the reason the Ruby simple REST client doesn't have a `publish` method is likely because that RPC appears to be specified as streaming, which is not supported.

The guide [Publishing messages to Lite topics](https://cloud.google.com/pubsub/lite/docs/publishing#publishing_messages) states:

> To publish messages, request a streaming connection to the Lite topic and then send messages over the streaming connection.

I don't believe streaming RPCs are supported by the REST clients.

**Comment by GLStephen** [comment]
@quartzmo That makes sense and is what I expected from my reading too. Will the GRPC client here support it? Any idea when that might be available?

**Comment by quartzmo** [comment]
I don't know.

@kamalaboulhosn Can you comment on how a Ruby gRPC client for Pub/Sub Lite might currently be prioritized?

**Comment by kamalaboulhosn** [comment]
At this time, we are evaluating demand for Lite client libraries in different languages but have not committed to a timeline for creating them. One can generate the gRPC library from the public proto file, though the subscribe side would require quite a bit of wrapper code to, for example, resume reading from the last offset a your stream dies. That is why we haven't just released the raw gRPC libraries without the hand-written layer above it. We'll keep this request in mind as we consider what language libraries to add for Lite.

**Comment by quartzmo** [comment]
Thanks @kamalaboulhosn

**Comment by kunalv89** [comment]
@quartzmo @kamalaboulhosn , Team, are we have gem/plugin for publish data to PubSub lite. i'am working on fluentd and need to sends streaming data on pubsub lite, as this is a very niche tool and technology, yet unable to find a way.

**Comment by plantfansam** [comment]
> At this time, we are evaluating demand for Lite client libraries in different languages but have not committed to a timeline for creating them. One can generate the gRPC library from the public proto file, though the subscribe side would require quite a bit of wrapper code to, for example, resume reading from the last offset a your stream dies. That is why we haven't just released the raw gRPC libraries without the hand-written layer above it. We'll keep this request in mind as we consider what language libraries to add for Lite.

Any updates on whether or not this is on the roadmap?
