### ISSUE TITLE
BigQuery Ruby Client Library #query sql doesn't work on Ruby 3.0.0

### ISSUE THREAD

**Issue by joshdemoss** [googleapis/google-cloud-ruby#9128]
#### Environment details

  - OS: macOS Catalina, 10.15.7
  - Ruby version: 3.0.0
  - Gem name and version: google-cloud-bigquery 1.26.0

#### Steps to reproduce

  1. Use google-cloud-bigquery with ruby version 3.0.0, with rvm and bundler
  2. Query using the following code

#### Code example

```ruby
# Authentication set up and works
bigquery = Google::Cloud::Bigquery.new
# The table exists -- I can use other methods like #datasets and #tables to verify that it is connected to the right table
sql = "SELECT * FROM `EXISTING_TABLE_IN_BIGQUERY` LIMIT 1000"
results = bigquery.query sql
```

#### Full backtrace

```sh
/Users/****/.rvm/gems/ruby-3.0.0/gems/google-cloud-bigquery-1.26.0/lib/google/cloud/bigquery/service.rb:222:in `list_tabledata': wrong number of arguments (given 3, expected 2) (ArgumentError)
        from /Users/****/.rvm/gems/ruby-3.0.0/gems/google-cloud-bigquery-1.26.0/lib/google/cloud/bigquery/query_job.rb:696:in `data'
        from /Users/****/.rvm/gems/ruby-3.0.0/gems/google-cloud-bigquery-1.26.0/lib/google/cloud/bigquery/project.rb:881:in `query'
        from app.rb:12:in `query'
        from app.rb:32:in `<main>'
```

#### Easiest solution
- rvm use 2.7.2
- bundle
- #run code

**Comment by quartzmo** [comment]
@joshdemoss Thanks for this request! Ruby 3 support is on the way, and will address the specific issue you demonstrate here. I'll try to get more detail on the status and report back here.

**Comment by quartzmo** [comment]
Similar to #8580.

**Comment by quartzmo** [comment]
The google-cloud-ruby gems have a couple of important dependencies that must first be updated to support Ruby 3:

* grpc - [PR #25070](https://github.com/grpc/grpc/pull/25070)
* protobuf - [PR #8134](https://github.com/protocolbuffers/protobuf/pull/8134)

Both of these PRs have now been merged, but we're waiting for the next scheduled google-protobuf release, which should be in the next few weeks.

**Comment by avondalepark** [comment]
@quartzmo Great news about support for 3, in the meantime what is the most recent supported version of Ruby?

**Comment by quartzmo** [comment]
These are [the Ruby versions that we are currently testing](https://github.com/googleapis/google-cloud-ruby/tree/master/.kokoro/samples_presubmit/linux) in CI. Hopefully there will soon be some changes to the contents of this directory!

**Comment by dazuma** [comment]
Fixed in the master branch. Will release updated gems shortly.
