### ISSUE TITLE
Ruby 3 Argument error

### ISSUE THREAD

**Issue by lafeber** [googleapis/google-cloud-ruby#9635]
#### Environment details

  - OS: OSX
  - Ruby version: 3.0.0
  - Gem name and version: google-cloud-pubsub 2.3.2

#### Steps to reproduce

1. pubsub = Google::Cloud::PubSub.new(project_id: ENV["PROJECT_ID"])
2. subscription = pubsub.subscription(ENV["SUBSCRIPTION_NAME"])
3. subscriber = subscription.listen(threads: { callback: 1, push: 1 }) do ... end

This will eventually call the code below:

#### Code example

```ruby
Inventory.new self, @subscriber.stream_inventory
```

The last argument being a Hash, this breaks in ruby 3. See inventory.rb:36.

#### Full backtrace

```sh
`google-cloud-pubsub-2.3.2/lib/google/cloud/pubsub/subscriber/inventory.rb:36:in `initialize': wrong number of arguments (given 2, expected 1; required keywords: limit, bytesize, extension, max_duration_per_lease_extension, use_legacy_flow_control) (ArgumentError)
```

**Comment by quartzmo** [comment]
@lafeber Thanks for reporting this issue! Ruby 3 support is coming soon. These are [the supported Ruby versions that we are currently testing](https://github.com/googleapis/google-cloud-ruby/tree/master/.kokoro/samples_presubmit/linux) in CI.

Related to #9128 and #8580.

**Comment by dazuma** [comment]
Fixed in the master branch. Will release an updated library shortly.
